---
permalink: install-ip/concept_mediator_requirements.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency
summary: Beginning with ONTAP 9.7, the ONTAP Mediator service can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= Prepare to install the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]
Your environment must meet the following requirements.


[NOTE]
====
* If you plan on updating your Linux version, do so before you install the most current ONTAP Mediator service.
* The ONTAP Mediator service and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.
* The ONTAP Mediator must be installed on a LINUX host at a separate location from the MetroCluster sites.
* The ONTAP Mediator service can support up to five MetroCluster configurations simultaneously.
* Automatic unplanned switchover is supported in ONTAP 9.7 and later.
====

== Network requirements for using Mediator in a MetroCluster configuration

To install the ONTAP Mediator service in a MetroCluster configuration, you must ensure that the configuration meets several network requirements.

* Latency
+
Round trip latency must be no more than 75 ms.
+
Jitter must be no more than 25 ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
Packet loss must be less than or equal to 0.01%.

* Bandwidth
+
The link between the Mediator service and the MetroCluster configuration must have at least 20 Gbps of bandwidth.

== Firewall requirements for ONTAP Mediator

ONTAP Mediator uses a number of ports to communicate with specific services.

If you are using a third-party firewall:

* HTTPS access must be enabled.
* It must be configured to allow access on ports 31784 and 3260.
+
When using the default Red Hat or CentOS firewall, the firewall is automatically configured during Mediator installation.

The following table lists the ports that you must allow in your firewall:

|===

h| Port/services h| Source h| Destination h| Purpose

a|
31784/tcp
a|
ONTAP cluster management interfaces
//ontap-metrocluster/issues/34
a|
ONTAP Mediator web server
a|
REST API (HTTPS)
a|
3260/tcp
a|
ONTAP cluster
a|
ONTAP Mediator iSCSI targets
a|
iSCSI data connection for mailboxes
|===

== Guidelines for upgrading the ONTAP Mediator in a MetroCluster configuration

If you are upgrading the ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* The Mediator service can be upgraded from version from an immediately prior version to the current version.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service^]

== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the `storage iscsi-initiator show` command to confirm that the Mediator connections are up.
