---
permalink: install-ip/concept_considerations_drive_assignment.html
sidebar: sidebar
keywords: drive auto-assignment, adp, advanced disk partitioning, root disk, unmirrored root, data partition, root partition, shelf-by-shelf, AFF A320, AFF A220, AFF A250, AFF A300, AFF A400, AFF A700, AFF A800, FAS2750, FAS8200, FAS500f, FAS9000
summary: Starting with ONTAP 9.4, MetroCluster IP configurations support new installations with AFF systems using ADP (Advanced Drive Partitioning).
---
= Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later
:icons: font
:imagesdir: ../media/

[.lead]
Starting with ONTAP 9.4, MetroCluster IP configurations support new installations with AFF systems using ADP (Advanced Drive Partitioning). In most configurations, partitioning and disk assignment are performed automatically during the initial configuration of the MetroCluster sites.

ONTAP 9.4 and later releases include the following changes for ADP support:

* Pool 0 disk assignments are done at the factory.
* The unmirrored root is created at the factory.
* Data partition assignment is done at the customer site during the setup procedure.
* In most cases, drive assignment and partitioning is done automatically during the setup procedures.

NOTE: When upgrading from ONTAP 9.4 to 9.5, the system recognizes the existing disk assignments.

== Automatic partitioning

ADP is performed automatically during initial configuration of the platform.

NOTE: Starting with ONTAP 9.5, `disk auto=assignment` must be enabled for automatic partitioning for ADP to occur.

== How shelf-by-shelf automatic assignment works

If there are four external shelves per site, each shelf is assigned to a different node and different pool, as shown in the following example:

* All of the disks on site_A-shelf_1 are automatically assigned to pool 0 of node_A_1
* All of the disks on site_A-shelf_3 are automatically assigned to pool 0 of node_A_2
* All of the disks on site_B-shelf_1 are automatically assigned to pool 0 of node_B_1
* All of the disks on site_B-shelf_3 are automatically assigned to pool 0 of node_B_2
* All of the disks on site_B-shelf_2 are automatically assigned to pool 1 of node_A_1
* All of the disks on site_B-shelf_4 are automatically assigned to pool 1 of node_A_2
* All of the disks on site_A-shelf_2 are automatically assigned to pool 1 of node_B_1
* All of the disks on site_A-shelf_4 are automatically assigned to pool 1 of node_B_2

== How to populate partially-full shelves

If your configuration is using shelves that are not fully populated (have empty drive bays) you must distribute the drives evenly throughout the shelf, depending on the disk assignment policy. The disk assignment policy depends on how many shelves are at each MetroCluster site.

If you are using a single shelf at each site (or just the internal shelf on an AFF A800 system), disks are assigned using a quarter-shelf policy. If the shelf is not fully populated,  install the drives equally on all quarters.

The following table shows an example of how to place 24 disks in a 48 drive internal shelf. The ownership for the drives is also shown.

[cols=2*,options="header"]
|===
| The 48 drive bays are divided into four quarters:| Install six drives in the first six bays in each quarter...
a|
Quarter 1: Bays 0 -11
a|
Bays 0-5
a|
Quarter 2: Bays 12-23
a|
Bays 12-17
a|
Quarter 3: Bays 24-35
a|
Bays 24-29
a|
Quarter 4: Bays 36-48
a|
Bays 36-41
|===
If you are using two shelves at each site, disks are assigned using a half-shelf policy. If the shelves are not fully populated, install the drives equally from either end of the shelf.

For example, if you are installing 12 drives in a 24 drive shelf, install drives in bays 0-5 and 18-23.

== Manual drive assignment (ONTAP 9.5)

In ONTAP 9.5, manual drive assignment is required on systems with the following shelf configurations:

* Three external shelves per site.
+
Two shelves are assigned automatically using a half-shelf assignment policy, but the third shelf must be assigned manually.

* More than four shelves per site and the total number of external shelves is not a multiple of four.
+
Extra shelves above the nearest multiple of four are left unassigned and the drives must be assigned manually. For example, if there are five external shelves at the site, shelf five must be assigned manually.

You only need to manually assign a single drive on each unassigned shelf. The rest of the drives on the shelf are then automatically assigned.

== Manual drive assignment (ONTAP 9.4)

In ONTAP 9.4, manual drive assignment is required on systems with the following shelf configurations:

* Fewer than four external shelves per site.
+
The drives must be assigned manually to ensure symmetrical assignment of the drives, with each pool having an equal number of drives.

* More than four external shelves per site and the total number of external shelves is not a multiple of four.
+
Extra shelves above the nearest multiple of four are left unassigned and the drives must be assigned manually.

When manually assigning drives, you should assign disks symmetrically, with an equal number of drives assigned to each pool. For example, if the configuration has two storage shelves at each site, you would one shelf to the local HA pair and one shelf to the remote HA pair:

* Assign half of the disks on site_A-shelf_1 to pool 0 of node_A_1.
* Assign half of the disks on site_A-shelf_1 to pool 0 of node_A_2.
* Assign half of the disks on site_A-shelf_2 to pool 1 of node_B_1.
* Assign half of the disks on site_A-shelf_2 to pool 1 of node_B_2.
* Assign half of the disks on site_B-shelf_1 to pool 0 of node_B_1.
* Assign half of the disks on site_B-shelf_1 to pool 0 of node_B_2.
* Assign half of the disks on site_B-shelf_2 to pool 1 of node_A_1.
* Assign half of the disks on site_B-shelf_2 to pool 1 of node_A_2.

== Adding shelves to an existing configuration.

Automatic drive assignment supports the symmetrical addition of shelves to an existing configuration.

When new shelves are added, the system applies the same assignment policy to newly added shelves. For example, with a single shelf per site, if an additional shelf is added, the systems applies the quarter-shelf assignment rules to the new shelf.

*Related information*

xref:concept_required_mcc_ip_components_and_naming_guidelines_mcc_ip.adoc[Required MetroCluster IP components and naming conventions]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[Disk and aggregate management]

== ADP and disk assignment differences by system in MetroCluster IP configurations

[.lead]
The operation of Advanced Drive Partitioning (ADP) and automatic disk assignment in MetroCluster IP configurations varies depending on the system model.

NOTE: In systems using ADP, aggregates are created using partitions in which each drive is partitioned in to P1, P2 and P3 partitions. The root aggregate is created using P3 partitions.

You must meet the MetroCluster limits for the maximum number of supported drives and other guidelines.

https://hwu.netapp.com[NetApp Hardware Universe]

=== ADP and disk assignment on AFF A320 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Two shelves
a|
The drives on each external shelf are divided into two equal groups (halves). Each half-shelf  is automatically assigned to a separate pool.
a|
One shelf is used by the local HA pair. The second shelf is used by the remote HA pair.

Partitions on each shelf are used to create the root aggregate. Each of the two plexes in the root aggregate includes the following partitions::

* Eight partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
One shelf
a|
The drives are divided into four equal groups. Each quarter-shelf is automatically assigned to a separate pool.
a|
Each of the two plexes in the root aggregate includes the following partitions:

* Three partitions for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A220 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Internal drives only
a|
The internal drives are divided into four equal groups. Each group is automatically assigned to a separate pool and each pool is assigned to a separate controller in the configuration.

NOTE: Half of the internal drives remain unassigned before MetroCluster is configured.

a|
Two quarters are used by the local HA pair. The other two quarters are used by the remote HA pair.

The root aggregate includes the following partitions in each plex:

* Three partitions for data
* Two parity partitions
* One spare partition

a|
Minimum supported shelves (per site)
a|
16 internal drives
a|
The drives are divided into four equal groups. Each quarter-shelf is automatically assigned to a separate pool.

Two quarters on a shelf can have the same pool. The pool is chosen based on the node that owns the quarter:

* If owned by the local node, pool0 is used.
* If owned by the remote node, pool1 is used.

For example: a shelf with quarters Q1 through Q4 can have following assignments:

* Q1: node_A_1 pool0
* Q2: node_A_2 pool0
* Q3: node_B_1 pool1
* Q4:node_B_2 pool1

NOTE: Half of the internal drives remain unassigned before MetroCluster is configured.

a|
Each of the two plexes in the root aggregate includes the following partitions:

* One partition for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A250 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Two shelves
a|
The drives on each external shelf are divided into two equal groups (halves). Each half-shelf  is automatically assigned to a separate pool.
a|
One shelf is used by the local HA pair. The second shelf is used by the remote HA pair.

Partitions on each shelf are used to create the root aggregate. The root aggregate includes the following partitions in each plex:

* Eight partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
24 internal drives only
a|
The drives are divided into four equal groups. Each quarter-shelf is automatically assigned to a separate pool.
a|
Each of the two plexes in the root aggregate includes the following partitions:

* Three partitions for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A300 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Two shelves
a|
The drives on each external shelf are divided into two equal groups (halves). Each half-shelf  is automatically assigned to a separate pool.
a|
One shelf is used by the local HA pair. The second shelf is used by the remote HA pair.

Partitions on each shelf are used to create the root aggregate. The root aggregate includes the following partitions in each plex:

* Eight partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
One shelf
a|
The drives are divided into four equal groups. Each quarter-shelf is automatically assigned to a separate pool.
a|
Each of the two plexes in the root aggregate includes the following partitions:

* Three partitions for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A400 systems
// BURT 1384407
[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Four shelves
a|
Drives are automatically assigned on a shelf-by-shelf basis.
a|
Each of the two plexes in the root aggregate includes:

* 20 partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
One shelf
a|
The drives are divided into four equal groups (quarters). Each quarter-shelf is automatically assigned to a separate pool.
a|
Each of the two plexes in the root aggregate includes:

* Three partitions for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A700 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Four shelves
a|
Drives are automatically assigned on a shelf-by-shelf basis.
a|
Each of the two plexes in the root aggregate includes:

* 20 partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
One shelf
a|
The drives are divided into four equal groups (quarters). Each quarter-shelf is automatically assigned to a separate pool.
a|
Each of the two plexes in the root aggregate includes:

* Three partitions for data
* Two parity partitions
* One spare partition

|===

=== ADP and disk assignment on AFF A800 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root aggregate
a|
Minimum recommended shelves (per site)
a|
Internal drives and four external shelves
a|
The internal partitions are divided into four equal groups (quarters). Each quarter is automatically assigned to a separate pool.The drives on the external shelves are automatically assigned on a shelf-by-shelf basis, with all of the drives on each shelf assigned to  one of the four nodes in the MetroCluster configuration.

a|
The root aggregate is created with 12 root partitions on the internal shelf.

Each of the two plexes in the root aggregate includes:

* Eight partitions for data
* Two parity partitions
* Two spare partitions

a|
Minimum supported shelves (per site)
a|
24 internal drives only
a|
The internal partitions are divided into four equal groups (quarters). Each quarter is automatically assigned to a separate pool.
a|
The root aggregate is created with 12 root partitions on the internal shelf.

Each of the two plexes in the root aggregate includes:

* Three partitions for data
* Two parity partitions
* One spare partitions

|===

=== Disk assignment on FAS2750 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
One internal and one external shelf
a|
The internal and external shelves are divided into two equal halves. Each half is automatically assigned to different pool
a|
Not applicable.
a|
Minimum supported shelves (per site) (active/passive HA configuration)
a|
Internal drives only
a|
Manual assignment required.
|===

=== Disk assignment on FAS8200 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum supported shelves (per site)
a|
Two shelves
a|
The drives on the external shelves are divided into two equal groups (halves). Each half-shelf  is automatically assigned to a separate pool.
a|
Not applicable.
a|
Minimum supported shelves (per site) (active/passive HA configuration)
a|
One shelf
a|
Manual assignment required.
|===

=== Disk assignment on FAS500f systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Four shelves
a|
Drives are automatically assigned on a shelf-by-shelf basis.
a|
Not applicable.
a|
Minimum supported shelves (per site)
a|
One shelf
a|
The drives are divided into four equal groups. Each quarter-shelf is automatically assigned to a separate pool.
|===

=== Disk assignment on FAS9000 systems

[cols=4*,options="header"]
|===
| Guideline| Shelves per site| Drive assignment rules| ADP layout for root partition
a|
Minimum recommended shelves (per site)
a|
Four shelves
a|
Drives are automatically assigned on a shelf-by-shelf basis.
a|
Not applicable.
a|
Minimum supported shelves (per site)
a|
Two shelves
a|
The drives on the shelves are divided into two equal groups (halves). Each half-shelf is automatically assigned to a separate pool.
a|
Minimum supported shelves (per site) (active/passive HA configuration)
a|
One shelf
a|
Manual assignment required.
|===
