---
permalink: install-ip/concept_network_speeds_and_switchport_modes.html
sidebar: sidebar
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed
summary: MetroCluster IP switches that are listed as supported switches in the link:https://hwu.netapp.com/[NetApp HardWare Universe^] and provided by NetApp are NetApp-validated. Beginning with ONTAP 9.7, MetroCluster IP configurations can use MetroCluster-compliant switches. These are switches that are not NetApp-validated but are compliant with NetApp specifications. However, NetApp does not provide support services, troubleshooting and/or configuration for any non-validated switch.
---

= Platform-specific network speeds and switch port modes for MetroCluster-compliant switches
:icons: font
:imagesdir: ../media/

[.lead]
The following table provides platform-specific network speeds and switch port modes for MetroCluster-compliant switches. You should configure the switch port mode as outlined in the table.

NOTE: Missing values indicate that the platform cannot be used with a MetroCluster-compliant switch.

|===

h| Platform h| Network Speed (Gbps) h| Switch port mode

a|
AFF A900
a|
100
a|
trunk mode
a|
AFF A800
a|
40 or 100
a| access mode
a|
AFF A700
a|
40
a|
access mode
a|
AFF A400
a|
40 or 100
a|
trunk mode
a|
AFF A320
a|
100
a|
access mode
a|
AFF A300
a|
25
a|
access mode
a|
AFF A250
a|
-
a|
-
a|
AFF A220
a|
-
a|
-
a|
AFF A150
a|
-
a|
-
a|
C800
a|
40 or 100
a|
access mode
a|
C400
a|
40 or 100
a|
trunk mode
a|
C250
a|
-
a|
-
a|
FAS9000
a|
40
a|
access mode
a|
FAS9500
a|
100 (not supported for FAS9000 to FAS9500 upgrades) 
40
a|
trunk mode
a|
FAS8700
a|
100
a|
trunk mode
a|
FAS8300
a|
40 or 100
a|
trunk mode
a|
FAS8200
a|
25
a|
access mode
a|
FAS2750
a|
-
a|
-
a|
FAS500f
a|
-
a|
-
|===

// 2023-07-18, burt 1451528/ONTAPDOC-928