---
permalink: install-ip/concept_mediator_requirements.html
sidebar: sidebar
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency
summary: Beginning with ONTAP 9.7, ONTAP Mediator can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= ONTAP Mediator installation requirements for MetroCluster IP configurations
:icons: font
:imagesdir: ../media/

[.lead]
Your environment must meet certain requirements. 

The following requirements apply to one disaster recovery group (DR group). Learn more about link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups[DR groups].

* If you plan on updating your Linux version, do so before you install the most current version of ONTAP Mediator.

* The ONTAP Mediator and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.

* ONTAP Mediator must be installed on a Linux host at a separate location from the MetroCluster sites.
+
The connectivity between the ONTAP Mediator and each site must be two separate failure domains.

* Automatic unplanned switchover is supported in ONTAP 9.7 and later.

* Beginning with ONTAP 9.19.1 and ONTAP Mediator 1.12, you can configure an ONTAP Mediator that uses HTTPS for communication instead of iSCSI.  For more information, see <<Select a communication protocol for ONTAP Mediator>>.

* Beginning with ONTAP 9.18.1 and ONTAP Mediator 1.11, a single ONTAP Mediator instance configured with iSCSI can manage up to ten MetroCluster configurations simultaneously. In ONTAP 9.17.1 and ONTAP Mediator 1.10 and earlier, an ONTAP Mediator configured with iSCSI can support up to five MetroCluster configurations simultaneously.

* Beginning with ONTAP 9.18.1, IPv6 is supported for ONTAP Mediator 1.11 or later in a MetroCluster IP configuration.

== Network requirements for using ONTAP Mediator in a MetroCluster configuration

To install ONTAP Mediator in a MetroCluster configuration, you must make sure that the configuration meets several network requirements.

* Latency
+
Maximum latency of less than 75ms (RTT).
+
Jitter must be no more than 5ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
For both Internet Control Message Protocol (ICMP) and TCP traffic, packet loss must be less than 0.01%.

* Bandwidth
+
The link between ONTAP Mediator and one DR group must have at least 20Mbps of bandwidth.

* Independent connectivity
+
Independent connectivity between each site and the ONTAP Mediator is required. A failure in one site must not interrupt the IP connectivity between the other two unaffected sites.

== Host requirements for ONTAP Mediator in a MetroCluster configuration

You must ensure that the configuration meets several host requirements.

* ONTAP Mediator must be installed at an external site that is physically separated from the two ONTAP clusters.

* ONTAP Mediator does not require more than the host operating system's minimum requirements for CPU and memory (RAM).

* In addition to the host operating system's minimum requirements, at least 30GB of additional usable disk space must be available.
+
**  Each DR group requires up to 200MB of disk space.

== Select a communication protocol for ONTAP Mediator

By default, MetroCluster IP nodes access ONTAP Mediator mailbox LUNs using iSCSI sessions. ONTAP Mediator relies on the SCST package to provide iSCSI. iSCSI sessions are authenticated using the Challenge Handshake Authentication Protocol (CHAP) with an obfuscated, machine-generated pre-shared key, but are not fully encrypted.

Beginning with ONTAP 9.19.1 and ONTAP Mediator 1.12, you can configure an ONTAP Mediator instance that uses HTTPS for communication instead of iSCSI. HTTPS is a secure protocol for communication that encrypts entire sessions using SSL/TLS, providing increased security when compared with iSCSI.

You can install ONTAP Mediator with support for both iSCSI and HTTPS, or HTTPS only. For more information, see link:https://docs.netapp.com/us-en/ontap/mediator/index.html#https-iscsi-installation[HTTPS and iSCSI installation options for ONTAP Mediator^].

You can configure ONTAP Mediator with iSCSI or HTTPS, not both. Using a mix of protocols in your deployment is not supported.  

You can only configure an ONTAP Mediator that uses HTTPS using the CLI. System Manager is not supported. 

Support for monitoring multiple MetroCluster IP configurations depends on whether you are configuring ONTAP Mediator for iSCSI or HTTPS. For more information see <<Use ONTAP Mediator to monitor multiple MetroCluster IP configurations>>.

// 2026 Feb 12, GH 504

[[mediator-multiple-mccip]]
== Use ONTAP Mediator to monitor multiple MetroCluster IP configurations

ONTAP Mediator can be used to monitor multiple MetroCluster IP configurations simultaneously, the support depends on whether you configure ONTAP Mediator with iSCSI or HTTPS.

=== ONTAP Mediator configured with iSCSI

* Beginning with ONTAP 9.18.1 and ONTAP Mediator 1.11, a single ONTAP Mediator instance configured with iSCSI can manage up to ten MetroCluster configurations simultaneously. 

* In ONTAP 9.17.1 and ONTAP Mediator 1.10 and earlier, an ONTAP Mediator configured with iSCSI can support up to five MetroCluster configurations simultaneously.

=== ONTAP Mediator configured with HTTPS

Beginning with ONTAP 9.19.1 and ONTAP Mediator 1.12, you can configure an ONTAP Mediator instance that uses HTTPS for communication instead of iSCSI.

.Monitoring multiple MetroCluster IP configurations

ONTAP Mediator configured with HTTPS has the following support for monitoring multiple MetroCluster IP configurations. Support depends on the ONTAP Mediator version, host OS specifications, and whether the MetroCluster IP configuration is four-node or eight-node.

[cols="1,2,1,1",options="header"]
|===
| ONTAP Mediator version
| Host OS requirements
| Four-node MetroCluster IP configurations 
| Eight-node MetroCluster IP configurations 
| 1.12
| N/A
| 1
| 1
.2+| 1.12.1 and later
| Hosts with fewer than 8 CPU cores and at least 8GB of RAM
| 1
| 1
| Hosts with at least 8 CPU cores and at least 16GB of RAM
| 10
| 5
|===

.Monitoring MetroCluster IP and SnapMirror active sync configurations

Beginning with ONTAP Mediator 1.12.1 and ONTAP 9.19.1, you can use the same ONTAP Mediator instance to monitor a four-node MetroCluster IP configuration and a SnapMirror active sync cluster peer relationship simultaneously. Your configuration must meet the following requirements:

* ONTAP Mediator 1.12.1 or later is installed on a host OS running 2-core CPU
* The ONTAP Mediator instance is configured with the HTTPS protocol

NOTE: You can only monitor one four-node MetroCluster IP configuration and one SnapMirror active sync peer relationship using the same ONTAP Mediator instance.



== Guidelines for upgrading ONTAP Mediator in a MetroCluster configuration

If you are upgrading ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* ONTAP Mediator can be upgraded from version from an immediately prior version to the current version.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade ONTAP Mediator^]

== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the `storage iscsi-initiator show` command to confirm that the Mediator connections are up.

// 2025 Mar 13, ONTAPDOC-2115, ONTAPDOC-2874
// 2022-06-02, BURT 1439085
// 2022-JAN-05, BURT 1505168