---
permalink: install-ip/concept_considerations_mcc_compliant_switches.html
sidebar: sidebar
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, requirements, compliant
summary: MetroCluster IP switches that are listed as supported switches in the link:https://hwu.netapp.com/[NetApp HardWare Universe^] and provided by NetApp are NetApp-validated. Beginning with ONTAP 9.7, MetroCluster IP configurations can use MetroCluster-compliant switches. These are switches that are not NetApp-validated but are compliant with NetApp specifications. 
---

= Considerations for using MetroCluster-compliant switches
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.7, MetroCluster IP configurations can use MetroCluster-compliant switches. These are switches that are not NetApp-validated but are compliant with NetApp specifications. However, NetApp does not provide support services, troubleshooting and/or configuration for any non-validated switch.

== NetApp-validated switches

A switch is NetApp-validated if it meets the following requirements:

* The switch is provided by NetApp as part of the MetroCluster IP configuration
* The switch is listed in link:https://hwu.netapp.com/[NetApp HardWare Universe^] as a supported switch under _MetroCluster-over-IP-connections_
* The switch is only used to connect MetroCluster IP controllers and, in some configurations, NS224 drive shelves
* The switch is configured using the Reference Configuration File (RCF) provided by NetApp 

Any switch that does not meet these requirements is *not* a NetApp-validated switch. 

== MetroCluster-compliant switches
A MetroCluster-compliant switch is not NetApp-validated but can be used in a MetroCluster IP configuration if it meets certain requirements and configuration guidelines.

NOTE: NetApp does not provide support services, troubleshooting or configuration for any non-validated MetroCluster-compliant switch.



// 2023-07-03, ONTAPDOC-928