---
permalink: install-ip/concept_considerations_mediator.html
sidebar: sidebar
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker
summary: The various MetroCluster configurations have key differences in the required components.
---
= Differences between ONTAP Mediator and MetroCluster Tiebreaker
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.7, you can use either the ONTAP Mediator-assisted automatic unplanned switchover (MAUSO) in the MetroCluster IP configuration or you can use the MetroCluster Tiebreaker software. Only one of the two services can be used with the MetroCluster IP configuration.

The different MetroCluster configurations perform automatic switchover under different circumstances:

* *MetroCluster FC configurations using the AUSO capability (not present in MetroCluster IP configurations)*
+
In these configurations, AUSO is initiated if controllers fail but the storage (and bridges, if present) remain operational.

* *MetroCluster IP configurations using the ONTAP Mediator service (ONTAP 9.7 and later)*
+
In these configurations, MAUSO is initiated in the same circumstances as AUSO, as described above, and also after a complete site failure (controllers, storage, and switches).
+
NOTE: MAUSO is initiated only if nonvolatile cache mirroring (_DR mirroring_) and SyncMirror plex mirroring is in sync at the time of the failure.

* *MetroCluster IP or FC configurations using the Tiebreaker software in active mode*
+
In these configurations, the Tiebreaker initiates unplanned switchover after a complete site failure.
+
Before using the Tiebreaker software, review the link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html[MetroCluster Tiebreaker Software installation and configuration]

== Interoperability of ONTAP Mediator with other applications and appliances

You cannot use any third-party applications or appliances that can trigger a switchover in combination with ONTAP Mediator. In addition, monitoring a MetroCluster configuration with MetroCluster Tiebreaker software is not supported when using ONTAP Mediator.

== How the ONTAP Mediator supports automatic unplanned switchover

The ONTAP Mediator stores state information about the MetroCluster nodes in mailboxes located on the Mediator host. The MetroCluster nodes can use this information to monitor the state of their DR partners and implement a Mediator-assisted automatic unplanned switchover (MAUSO) in the case of a disaster.

When a node detects a site failure requiring a switchover, it takes steps to confirm that the switchover is appropriate and, if so, performs the switchover.

A MAUSO is only initiated in the following scenarios:

* Both SyncMirror mirroring and DR mirroring of each node's nonvolatile cache is operating and the caches and mirrors are synchronized at the time of the failure.
* None of the nodes at the surviving site are in takeover state.

IMPORTANT: A MAUSO is only initiated if a site disaster occurs.
A site disaster is a failure of *all* nodes at the same site; however, there are some exceptions.

A MAUSO is *not* initiated in the following shutdown scenarios:

 * You initiate a shutdown. For example, when you:
 ** halt the nodes
 ** reboot the nodes

 * A fan or component failure initiates a shutdown (environmental shutdown)

// BURT 1442346 24/01/2022
// BURT 1456187 11/02/2022
