---
permalink: install-ip/concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure
summary: Starting with ONTAP 9.7, the ONTAP Mediator service can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= Configuring the ONTAP Mediator service for unplanned automatic switchover
:icons: font
:imagesdir: ../media/

[.lead]
Starting with ONTAP 9.7, the ONTAP Mediator service can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.

NOTE:

* The ONTAP Mediator service and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.
* The ONTAP Mediator service can support up to five MetroCluster configurations simultaneously.

== Installing and configuring the ONTAP Mediator service

[.lead]
The ONTAP Mediator must be installed on the Linux host and then configured in ONTAP from the MetroCluster nodes.

=== Network requirements for using Mediator in a MetroCluster configuration

[.lead]
To install the ONTAP Mediator service in a MetroCluster configuration, you must ensure that the configuration meets several network requirements.

* Round trip latency
+
Round trip latency must be no more than 25 ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
Packet loss must be less than or equal to 0.01%.

* Bandwidth
+
The link between the Mediator service and the MetroCluster configuration must have at least 1 Gbps of bandwidth.

=== Firewall requirements for ONTAP Mediator

[.lead]
ONTAP Mediator uses a number of ports to communicate with specific services.

* If you are using a third-party firewall:
 ** HTTPS access must be enabled
 ** It must be configured to allow access on ports 31784 and 3260
When using the default Red Hat or CentOS firewall, the firewall is automatically configured during Mediator installation.

The following table lists the ports that you must allow in your firewall:

[options="header"]
|===
| Port/services| Source| Destination| Purpose
a|
31784/tcp
a|
ONTAP cluster
a|
ONTAP Mediator web server
a|
REST API (HTTPS)
a|
3260/tcp
a|
ONTAP cluster
a|
ONTAP Mediator iSCSI targets
a|
iSCSI data connection for mailboxes
|===

=== Guidelines for upgrading the ONTAP Mediator in a MetroCluster configuration

[.lead]
If you are upgrading the ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* The Mediator service can be upgraded from version 1.0 to 1.1.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

==== Upgrading the host operating system and Mediator together

The following table provides the upgrade guidelines if you are upgrading from RHEL/CentOS 7.6 to a later RHEL/CentOS release in addition upgrading the Mediator version.

[options="header"]
|===
| Target Linux version| Target Mediator version| Upgrade notes
a|
RHEL/CentOS 7.7
a|
1.1
a|

* The upgrade must be performed in the following order:
 .. Upgrade the operating system from RHEL/CentOS version 7.6 to 7.7.
+
NOTE: The ONTAP Mediator and Mediator-assisted automatic unplanned switchover is not available during the operating system upgrade. The Mediator is offline until the Mediator version 1.0 to 1.1 upgrade process is complete..

 .. Reboot the host to apply the kernel module changes.
 .. Upgrade the Mediator from version 1.0 to 1.1.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#installing-or-upgrading-the-ontap-mediator-service[Installing or upgrading the ONTAP Mediator service]
* The storage iscsi-initiator show command will report that the connection to the Mediator service is down during the upgrade.
* The ONTAP operating system will generate cf.mccip.med.auso.stDisabled EMS events during the upgrade.
* The ONTAP operating system will generate a cf.mccip.med.auso.stEnabled EMS event when automatic unplanned switchover is re-enabled.

a|
RHEL/CentOS 8.0 or 8.1
a|
1.1
a|
There is no direct upgrade path. You must remove the 1.0 version and install the 1.1 version after the operating system upgrade:

. Delete the Mediator service from the ONTAP configuration: metrocluster configuration-settings mediator remove
. Uninstall the 1.0 version of the Mediator service.
+
<<Uninstalling the ONTAP Mediator service>>

. Upgrade the Linux operating system to version 8.0 or 8.1.
. Install the 1.1 version of the Mediator service.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#installing-or-upgrading-the-ontap-mediator-service[Installing or upgrading the ONTAP Mediator service]

. Add the Mediator service to the ONTAP configuration: metrocluster configuration-settings add -addressmediator-1.1-ip-address

|===

==== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the storage iscsi-initiator show command to confirm that the Mediator connections are up.

==== Reverting from a Mediator 1.1 installation

A direct revert from Mediator version 1.1 to 1.0 is not supported. You must remove the 1.1 version and reinstall the 1.0 version.

. Delete the Mediator service from the ONTAP configuration: metrocluster configuration-settings mediator remove
. Uninstall the 1.1 version of the Mediator service.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.adoc[Uninstalling the ONTAP Mediator service]

. Install the 1.0 version of the Mediator service.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#installing-or-upgrading-the-ontap-mediator-service[Installing or upgrading the ONTAP Mediator service]

. Add the Mediator service to the ONTAP configuration: metrocluster configuration-settings add -addressmediator-1.0-ip-address

==== Recovering from Linux kernel upgrades

The ONTAP Mediator requires the SCST kernel module. If the Linux kernel is updated, this dependency may lead to a loss of service. It is highly recommended that you rebuild the SCST kernel module when any kernel package changes are made.

NOTE:

* Upgrading from ONTAP Mediator version 1.0 to 1.1 rebuilds the SCST module.
* Kernel module changes are applied after the Linux kernel is rebooted.

You can use either of the following procedures to recover from a kernel upgrade that has resulted in loss of service for the Mediator.

[options="header"]
|===
| Procedure| Steps
a|
Remove and reinstall the SCST kernel module
a|
You must have the SCST tar bundle used by your version of Mediator:

* ONTAP Mediator 1.0 requires scst-3.3.0.tar.bz2
* ONTAP Mediator 1.1 requires scst-3.4.0.tar.bz2

. Uninstall the SCST module:
 .. Download and untar the SCST tar bundle required by your version of Mediator.
 .. Run the following commands inside of the scst directory:
+
----
systemctl stop mediator-scst
make scstadm_uninstall
make iscsi_uninstall
make usr_uninstall
make scst_uninstall
depmod
----
. Reinstall the SCST module for your version of Mediator by issuing the following commands inside of the scst directory:
+
----
make scst_install
make usr_install
make iscsi_install
make scstadm_install
depmod
patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch
reboot
----

a|
Remove and reinstall ONTAP Mediator**Note:** This requires a reconfiguration of the Mediator in ONTAP.

a|

. Delete the Mediator service from the ONTAP configuration: metrocluster configuration-settings mediator remove
. Uninstall the Mediator service.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.adoc[Uninstalling the ONTAP Mediator service]

. Reinstall the Mediator service.
+
xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#installing-or-upgrading-the-ontap-mediator-service[Installing or upgrading the ONTAP Mediator service]

. Add the Mediator service to the ONTAP configuration: metrocluster configuration-settings add -addressmediator-ip-address

|===

=== Installing or upgrading the ONTAP Mediator service

[.lead]
To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.

[options="header"]
|===
| Mediator version| Supported Linux versions
a|
1.2
a|
Red Hat Enterprise Linux or CentOS 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
|===

* 64-bit physical installation or virtual machine
 ** 8 GB RAM
 ** User: Root access
The best practices for installing Red Hat Enterprise Linux or CentOS and the associated repositories on your system are listed below. Systems installed or configured differently might require additional steps.
 ** You must install Red Hat Enterprise Linux or CentOS according to Red Hat best practices.
 ** While installing the ONTAP Mediator service on Red Hat Enterprise Linux or CentOS, the system must have access to the appropriate repository so that the installation program can access and install all the required software dependencies.
 ** For the yum installer to find dependent software in the Red Hat Enterprise Linux repositories, you must have registered the system during the Red Hat Enterprise Linux installation or afterwards by using a valid Red Hat subscription.
+
See the Red Hat documentation for information about the Red Hat Subscription Manager.
* The following ports must be unused and available for the Mediator:
 ** 31784
 ** 3260
* If using a third-party firewall: refer to xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#firewall-requirements-for-ontap-mediator[Firewall requirements for ONTAP Mediator]
* If the Linux host is in a location without access to the internet, you can either install the packages manually or you must ensure that the required packages are available in a local repository.
+
You can use the following link for information about setting up a repository.
+
If you are using Link Aggregation Control Protocol (LACP) in a Linux environment, you must correctly configure the kernel and make sure the sysctl net.ipv4.conf.all.arp_ignore is set to `2`.
+
The following packages are required by the ONTAP Mediator service version 1.2:
+
[options="header"]
|===
| All RHEL/CentOS versions| Additional packages for RHEL/CentOS 7.x| Additional packages for RHEL/CentOS 8.x
a|

 ** openssl
 ** openssl-devel
 ** kernel-devel
 ** gcc
 ** libselinux-utils
 ** make
 ** redhat-lsb-core
 ** patch
 ** bzip2
 ** python36
 ** python36-devel
 ** perl-Data-Dumper
 ** perl-ExtUtils-MakeMaker
 ** python3-pip

a|

 ** policycoreutils-python
 ** python36-pip

a|

 ** elfutils-libelf-devel
 ** policycoreutils-python-utils

+
|===

* If signature verification is configured, it must be disabled. This can be done in one of two ways:
 ** If the UEFI SecureBoot mechanism is configured, disable it.
 ** Disable the signature verification mechanism by updating and regenerating the grub.cfg file:
  ... Open the /etc/default/grub file.
  ... Add the string module.sig_enforce=0 to the end of the GRUB_CMDLINE_LINUX statement.
  ... Regenerate the grub.cfg file to implement the change: `update-bootloader || update-grub || grub2-mkconfig -o /boot/grub2/grub.cfg`
  ... Reboot the host.

The Mediator installation package is a self-extracting compressed tar file that includes:

* An RPM file containing all dependencies that cannot be obtained from the supported release's repository.
* An install script.

A valid SSL certification is recommended, as documented in this procedure.

This procedure is used for an installation or an upgrade of an existing installation.

xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#guidelines-for-upgrading-the-ontap-mediator-in-a-metrocluster-configuration[Guidelines for upgrading the ONTAP Mediator in a MetroCluster configuration]

. Enable access to the repositories listed above so Mediator can access the required packages during the installation process.
+
[options="header"]
|===
| If your operating system is...| You must provide access to these repositories...
a|
RHEL 7.x
a|
rhel-7-server-optional-rpms
a|
CentOS 7.x
a|
C7.6.1810 - Base repository
a|
RHEL 8.x
a|

 ** rhel-8-for-x86_64-baseos-rpms
 ** rhel-8-for-x86_64-appstream-rpms

a|
CentOS 8.0
a|
kernel-devel
|===
[options="header"]
|===
| If your operating system is... | Use these steps...

a| *RHEL 7.x*
a|
. Subscribe to the required repository: `subscription-manager repos --enable rhel-7-server-optional-rpms`
+
The following example shows the execution of this command:
+
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. Run the yum repolist command.
+
The following example shows the execution of this command. The rhel-7-server-optional-rpms repository should appear in the list.
+
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----

a|*RHEL 8.x*
a|. Subscribe to the required repository: `subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms``subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms`
+
The following example shows the execution of this command:
+
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----

. Run the yum repolist command.
+
The newly subscribed repositories should appear in the list.

a| *CentOS 7.x*
a|
. Add the C7.6.1810 - Base repository. The C7.6.1810 - Base vault repository contains the kernel-devel package needed for ONTAP Mediator.

. Add the following lines to /etc/yum.repos.d/CentOS-Vault.repo.
+
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$
basearch/gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----

. Run the yum repolist command.
+
The following example shows the execution of this command. The CentOS-7.6.1810 - Base repository should appear in the list.
+
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----

a| *CentOS 8.0.1905 or later builds*
a| Because the latest version of the 8.0 (CentOS 8.0.1905) core resides in the CentOS Vault, you must provide access to the matching kernel-devel package to compile the needed kernel module.      Issue the following command to directly install the kernel-devel package: rpm -i http://vault.centos.org/8.0.1905/BaseOS/x86_64/os/Packages/kernel-devel-$(uname -r).rpm
+
If the system displays an error indicating that the package is already installed, remove the package and try again:

 .. Remove the kernel-devel package: `yum remove kernel-devel`
 .. Repeat the rpm command shown above.

+
|===

. Download the Mediator installation package from the ONTAP Mediator page.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab[ONTAP Mediator download page]

. Confirm that the Mediator installation package is in the target directory: `ls`
+
----
[root@mediator-host ~]#ls
./ontap-mediator_1.2
----
+
If you are at a location without access to the internet, you must ensure that the installer has access to the required packages.

. If necessary, move the Mediator installation package from the download directory to the installation directory on the Linux Mediator host.
. Install the Mediator installation package and respond to the prompts as required: `./ontap-mediator_1.2`
+
The installation process proceeds to create the required accounts and install required packages. If you have a previous version of Mediator installed on the host, you will be prompted to confirm that you want to upgrade.
+
The following example shows a fresh installation of the Mediator service:
+
----
[root@red-hat-enterprise-linux ~]# ./ontap-mediator_1.2
ONTAP Mediator: Self Extracting Installer


ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).

Would you like to use the default account names: netapp + mediatoradmin? (Y(es)/n(o)): y



Enter ONTAP Mediator system service account (mediatoradmin) password:

Re-Enter ONTAP Mediator system service account (mediatoradmin) password:


Checking for default Linux firewall

Linux firewall is running. Open ports 31784 and 3260? y(es)/n(o): y
success
success

###############################################################

Preparing for installation of ONTAP Mediator packages.

Do you wish to continue? y(es)/n(o): y

+ Installing required packages.

Loaded plugins: product-id, search-disabled-repos, subscription-manager
epel/x86_64/metalink                                                                                                                                                              |  17 kB  00:00:00
epel-extra                                                                                                                                                                        | 4.9 kB  00:00:00
ius                                                                                                                                                                               | 1.3 kB  00:00:00
rhel-7-server-rpms                                                                                                                                                                | 3.5 kB  00:00:00
(1/3): ius/x86_64/primary                                                                                                                                                         | 129 kB  00:00:00
(2/3): epel-extra/group_gz                                                                                                                                                        |  88 kB  00:00:01
(3/3): epel-extra/primary_db                                                                                                                                                      | 6.7 MB  00:00:06
ius                                                                                                                                                                                              538/538
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
                            .
                            .
                            .
                            .

=========================================================================================================================================================================================================
