---
permalink: install-ip/mcc-compliant-netapp-validated-switches.html
sidebar: sidebar
keywords: isls, ip, layer 2, layer 3, shared switch
summary: "This section provides the information required to verify that your MetroCluster configuration and the network is meeting all requirements."
---
= NetApp-validated and MetroCluster-compliant switches

[lead]
All of the switches used in your configuration, including backend switches, must either be NetApp-validated or MetroCluster-compliant. 

== NetApp-validated switches

A switch is NetApp-validated if it meets the following requirements:

* The switch is provided by NetApp as part of the MetroCluster IP configuration
* The switch is listed in link:https://hwu.netapp.com/[NetApp Hardware Universe^] as a supported switch under _MetroCluster-over-IP-connections_
* The switch is only used to connect MetroCluster IP controllers and, in some configurations, NS224 drive shelves
* The switch is configured using the Reference Configuration File (RCF) provided by NetApp 

Any switch that does not meet these requirements is *not* a NetApp-validated switch. 

== MetroCluster-compliant switches
A MetroCluster-compliant switch is not NetApp-validated but can be used in a MetroCluster IP configuration if it meets certain requirements and configuration guidelines.

NOTE: NetApp does not provide support services, troubleshooting or configuration for any non-validated MetroCluster-compliant switch.