---
permalink: install-ip/concept-network-speeds-and-switchport-modes.html
sidebar: sidebar
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, compliant, network speed, switch port mode
summary: If you are using MetroCluster compliant switches, you should be aware of the platform-specific network speeds and switch port mode requirements.
---
= ONTAP platform-specific network speeds and switch port modes for MetroCluster-compliant switches
:icons: font
:imagesdir: ../media/

[.lead]
If you are using MetroCluster compliant switches, you should be aware of the platform-specific network speeds and switch port mode requirements.

The following table provides platform-specific network speeds and switch port modes for MetroCluster-compliant switches. You should configure the switch port mode according to the table.

[NOTE]
====
* Missing values indicate that the platform cannot be used with a MetroCluster-compliant switch.
* AFF A30, AFF C30, AFF C60, and FAS50 systems require a QSFP-to-SFP adapter in the card on the controller to support a 25Gbps network speed.
====

[cols="1,2,2" options="header"]
|===
| Platform | Network speed (Gbps) | Switch port mode

a| FAS9500 

AFF A900 

ASA A900
a| 100Gbps 

40Gbps when upgrading PCM from FAS9000 or AFF A700
a| Trunk mode

a| AFF C800 

ASA C800 

AFF A800 

ASA A800
a| 40Gbps or 100Gbps
a| Access mode

a| FAS9000 

AFF A700
a| 40Gbps
a| Access mode

a| FAS8300 

AFF C400 

ASA C400

AFF A400 

ASA A400
a| 40Gbps or 100Gbps
a| Trunk mode

a| AFF A320
a| 40Gbps or 100Gbps
a| Access mode

a| FAS8200 

AFF A300
a| 25Gbps
a| Access mode

a| FAS500f 

AFF C250 

ASA C250 

AFF A250 

ASA A250
a| -
a| -

a| FAS2750

AFF A220
a| -
a| -

a| AFF A150 

ASA A150
a| -
a| -

a| AFF A20
a| 25Gbps
a| Trunk mode

a| AFF A30
a| 25Gbps or 100Gbps
a| Trunk mode

a| AFF C30
a| 25Gbps or 100Gbps
a| Trunk mode

a| AFF C60
a| 25Gbps or 100Gbps
a| Trunk mode

a| FAS50
a| 25Gbps or 100Gbps
a| Trunk mode

a| AFF A50
a| 100Gbps
a| Trunk mode

a| AFF A70
a| 100Gbps
a| Trunk mode

a| AFF A90
a| 100Gbps
a| Trunk mode

a| AFF A1K
a| 100Gbps
a| Trunk mode

a| AFF C80
a| 100Gbps
a| Trunk mode

a| FAS70
a| 100Gbps
a| Trunk mode

a| FAS90
a| 100Gbps
a| Trunk mode
|===

// 2026 May 21, ONTAPDOC-3888
// 2024 Dec 09, ONTAPDOC-2349
// 2024 Jul 11, ONTAPDOC-2117
// 2023-07-18, burt 1451528/ONTAPDOC-928