---
permalink: install-ip/concept_considerations_mediator.html
sidebar: sidebar
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker
summary: The various MetroCluster configurations have key differences in the required components.
---
= Differences between ONTAP Mediator and MetroCluster Tiebreaker
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.7, you can use either the ONTAP Mediator-assisted automatic unplanned switchover (MAUSO) in the MetroCluster IP configuration or you can use the MetroCluster Tiebreaker software. It is not required to use the MAUSO or Tiebreaker software; however, if you choose to not use either of these services, you must link:../disaster-recovery/concept_dr_workflow.html[perform a manual recovery] if a disaster occurs.

The different MetroCluster configurations perform automatic switchover under different circumstances:

* *MetroCluster FC configurations using the AUSO capability (not present in MetroCluster IP configurations)*
+
In these configurations, AUSO is initiated if controllers fail but the storage (and bridges, if present) remain operational.

* *MetroCluster IP configurations using the ONTAP Mediator service (ONTAP 9.7 and later)*
+
In these configurations, MAUSO is initiated in the same circumstances as AUSO, as described above, and also after a complete site failure (controllers, storage, and switches).
+
link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html[Learn about how the ONTAP Mediator supports automatic unplanned switchover].

* *MetroCluster IP or FC configurations using the Tiebreaker software in active mode*
+
In these configurations, the Tiebreaker initiates unplanned switchover after a complete site failure.
+
Before using the Tiebreaker software, review the link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html[MetroCluster Tiebreaker Software installation and configuration]

== Interoperability of ONTAP Mediator with other applications and appliances

You cannot use any third-party applications or appliances that can trigger a switchover in combination with ONTAP Mediator. In addition, monitoring a MetroCluster configuration with MetroCluster Tiebreaker software is not supported when using ONTAP Mediator.



// 2024 FEB 21, ontap-metrocluster-issue-365
// 2024 FEB 20, ONTAPDOC-1168
// 2023 APR 19, BURT 1532596
// 2022 JAN 24, BURT 1442346 
// 2022 FEB 11, BURT 1456187 
