---
permalink: install-ip/concept-risks-limitations-automatic-switchover.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, forced
summary:
---

= Risks and limitations of using MetroCluster automatic forced switchover
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1, you can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover (MAUSO)
feature. 

Switchover upon detection of a site failure happens automatically when you enable the MetroCluster automatic forced switchover feature. You can use this feature to supplement the MetroCluster IP automatic switchover capability.

When you allow a MetroCluster IP configuration to operate in automatic forced switchover mode, the following known issues might lead to data loss:

* The nonvolatile memory (NVRAM or NVMEM, depending on the platform model) in the storage controllers is not mirrored to the remote disaster recovery (DR) partner on the partner site.

CAUTION: You might encounter scenarios that are not mentioned. NetApp is not responsible for any data corruption, data loss, or other damage that may arise from enabling the MetroCluster automatic Forced Switchover feature. Do not use the MetroCluster automatic forced switchover feature if the risks and limitations are not acceptable to you.
