---
permalink: install-ip/concept_mediator_requirements.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency
summary: Beginning with ONTAP 9.7, the ONTAP Mediator service can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= Preparing to install the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.7, the ONTAP Mediator service can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information. Your environment must meet the following requirements. You may need to update your Linux version.

[NOTE]
====
* The ONTAP Mediator service and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.
* The ONTAP Mediator must be installed on a LINUX host at a separate location from the MetroCluster sites.
* The ONTAP Mediator service can support up to five MetroCluster configurations simultaneously.
* Automatic unplanned switchover is supported in ONTAP 9.7 and later.
====

== Network requirements for using Mediator in a MetroCluster configuration

To install the ONTAP Mediator service in a MetroCluster configuration, you must ensure that the configuration meets several network requirements.

* Latency
+
Round trip latency must be no more than 75 ms.
+
Jitter must be no more than 25 ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
Packet loss must be less than or equal to 0.01%.

* Bandwidth
+
The link between the Mediator service and the MetroCluster configuration must have at least 20 Gbps of bandwidth.

== Firewall requirements for ONTAP Mediator

ONTAP Mediator uses a number of ports to communicate with specific services.

* If you are using a third-party firewall:
** HTTPS access must be enabled.
** It must be configured to allow access on ports 31784 and 3260.
+
When using the default Red Hat or CentOS firewall, the firewall is automatically configured during Mediator installation.

The following table lists the ports that you must allow in your firewall:

|===

h| Port/services h| Source h| Destination h| Purpose

a|
31784/tcp
a|
ONTAP cluster management interfaces
//ontap-metrocluster/issues/34
a|
ONTAP Mediator web server
a|
REST API (HTTPS)
a|
3260/tcp
a|
ONTAP cluster
a|
ONTAP Mediator iSCSI targets
a|
iSCSI data connection for mailboxes
|===

== Guidelines for upgrading the ONTAP Mediator in a MetroCluster configuration

If you are upgrading the ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* The Mediator service can be upgraded from version 1.0 to 1.1.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

== Upgrading the host operating system and Mediator together

The following table provides the upgrade guidelines if you are upgrading from RHEL/CentOS 7.6 to a later RHEL/CentOS release in addition upgrading the Mediator version.

[cols="20,20,60"]
|===

h| Target Linux version h| Target Mediator version h| Upgrade notes

a|
RHEL/CentOS 7.7
a|
1.1
a|

* The upgrade must be performed in the following order:
 .. Upgrade the operating system from RHEL/CentOS version 7.6 to 7.7.
+
*Note*: The ONTAP Mediator and Mediator-assisted automatic unplanned switchover is not available during the operating system upgrade. The Mediator is offline until the Mediator version 1.0 to 1.1 upgrade process is complete..

 .. Reboot the host to apply the kernel module changes.
 .. Upgrade the Mediator from version 1.0 to 1.1.
+
link:task_install_configure_mediator.html[Installing or upgrading the ONTAP Mediator service]

* The storage iscsi-initiator show command will report that the connection to the Mediator service is down during the upgrade.
* The ONTAP operating system will generate cf.mccip.med.auso.stDisabled EMS events during the upgrade.
* The ONTAP operating system will generate a cf.mccip.med.auso.stEnabled EMS event when automatic unplanned switchover is re-enabled.

a|
RHEL/CentOS 8.0 or 8.1
a|
1.1
a|
There is no direct upgrade path. You must remove the 1.0 version and install the 1.1 version after the operating system upgrade:

. Delete the Mediator service from the ONTAP configuration:
+
`metrocluster configuration-settings mediator remove`
. Uninstall the 1.0 version of the Mediator service.
+
link:../install-ip/task_uninstall_mediator.html[Uninstalling the ONTAP Mediator service]

. Upgrade the Linux operating system to version 8.0 or 8.1.
. Install the 1.1 version of the Mediator service.
+
link:task_uninstall_mediator.html[Installing or upgrading the ONTAP Mediator service]

. Add the Mediator service to the ONTAP configuration:
+
`metrocluster configuration-settings add -mediator-address-1.1-ip-address`

|===

== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the `storage iscsi-initiator show` command to confirm that the Mediator connections are up.

== Reverting from a Mediator 1.1 installation

A direct revert from Mediator version 1.1 to 1.0 is not supported. You must remove the 1.1 version and reinstall the 1.0 version.

. Delete the Mediator service from the ONTAP configuration:
+
`metrocluster configuration-settings mediator remove`
. Uninstall the 1.1 version of the Mediator service.
+
link:../install-ip/task_uninstall_mediator.html[Uninstalling the ONTAP Mediator service]

. Install the 1.0 version of the Mediator service.
+
link:task_install_configure_mediator.html[Installing or upgrading the ONTAP Mediator service]

. Add the Mediator service to the ONTAP configuration:
+
`metrocluster configuration-settings add -mediator-address-1.0-ip-address`

== Recovering from Linux kernel upgrades

The ONTAP Mediator requires the SCST kernel module. If the Linux kernel is updated, this dependency may lead to a loss of service. It is highly recommended that you rebuild the SCST kernel module when any kernel package changes are made.

[NOTE]
====
* Upgrading from ONTAP Mediator version 1.0 to 1.1 rebuilds the SCST module.
* Kernel module changes are applied after the Linux kernel is rebooted.
====

You can use either of the following procedures to recover from a kernel upgrade that has resulted in loss of service for the Mediator.

[cols="30,70"]
|===

h| Procedure h| Steps

a|
Remove and reinstall the SCST kernel module
a|
You must have the SCST tar bundle used by your version of Mediator:

* ONTAP Mediator 1.0 requires scst-3.3.0.tar.bz2
* ONTAP Mediator 1.1 requires scst-3.4.0.tar.bz2

. Uninstall the SCST module:
 .. Download and untar the SCST tar bundle required by your version of Mediator.
 .. Run the following commands inside of the scst directory:
+
----
systemctl stop mediator-scst
make scstadm_uninstall
make iscsi_uninstall
make usr_uninstall
make scst_uninstall
depmod
----
. Reinstall the SCST module for your version of Mediator by issuing the following commands inside of the scst directory:
+
----
make scst_install
make usr_install
make iscsi_install
make scstadm_install
depmod
patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch
reboot
----

a|
Remove and reinstall ONTAP Mediator

**Note:** This requires a reconfiguration of the Mediator in ONTAP.

a|

. Delete the Mediator service from the ONTAP configuration:
+
`metrocluster configuration-settings mediator remove`

. link:../install-ip/task_uninstall_mediator.html[Uninstall the ONTAP Mediator service].
. link:../install-ip/task_install__configure_mediator.html[Reinstall the Mediator service].
. Add the Mediator service to the ONTAP configuration:
+
`metrocluster configuration-settings add -mediator-address-ip-address`

|===

// 2022-07-01, Issue 119
