---
permalink: install-ip/concept_considerations_mcc_compliant_switches.html
sidebar: sidebar
keywords: metrocluster ip, metrocluster-compliant switches, metrocluster-compliant, requirements, compliant
summary: MetroCluster IP switches that are listed as supported switches in the link:https://hwu.netapp.com/[NetApp HardWare Universe^] and provided by NetApp are NetApp-validated. Beginning with ONTAP 9.7, MetroCluster IP configurations can use MetroCluster-compliant switches. These are switches that are not NetApp-validated but are compliant with NetApp specifications. However, NetApp does not provide support services, troubleshooting and/or configuration for any non-validated switch.

---
= Considerations for using MetroCluster-compliant switches
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.7, MetroCluster IP configurations can use MetroCluster-compliant switches. These are switches that are not NetApp-validated but are compliant with NetApp specifications. However, NetApp does not provide support services, troubleshooting and/or configuration for any non-validated switch.

== NetApp-validated switches

A switch is NetApp validated if it meets all the following:

* The switch is provided by NetApp as part of the MetroCluster IP configuration
* The switch is listed in link:https://hwu.netapp.com/[NetApp HardWare Universe^] as a supported switch under “MetroCluster-over-IP-connections”
* The switch is only used to connect MetroCluster IP controllers and, in some configurations, NS224 drive shelves
* The switch is configured using the NetApp provided RCF (Reference Configuration File)

Any switch not meeting these criteria is *not* a NetApp-validated switch. 

== MetroCluster-compliant switches
A MetroCluster-compliant switch is not NetApp-validated but can be used in a MetroCluster IP configuration if it meets the below requirements and configuration guidelines.

NOTE: NetApp does not provide support services, troubleshooting and/or configuration for any non-validated MetroCluster-compliant switch.

== General requirements for MetroCluster-compliant switches

The switch connecting the MetroCluster IP interfaces must meet the following:

* The switches must support quality of service (QoS) and traffic classification.
* The switches must support explicit congestion notification (ECN).
* The switches must support L4 port-vlan load-balancing policies to preserve order along the path.
* The switches must support L2 Flow Control (L2FC).
* The cables connecting the nodes to the switches must be provided by NetApp. These cables must be supported by the switch vendor.
* The switches connecting the MetroCluster nodes can carry non-MetroCluster traffic.
* Only platforms that provide dedicated ports for switchless cluster interconnects can be used with a MetroCluster-compliant switch. Platforms such as the FAS2750 and AFF A220 cannot be used because MetroCluster traffic and MetroCluster interconnect traffic share the same network ports.
* The MetroCluster-compliant switch must not be used for local cluster connections.
* The MetroCluster IP interface can be connected to any switch port that can be configured to meet the requirements.
* Four IP switches are required, two for each switch fabric. If you use directors, then you can use a single director at each side, but the MetroCluster IP interfaces must connect to two different blades in two different failure domains on that director.
* The MetroCluster interfaces from one node must connect to two network switches or blades. The MetroCluster interfaces from one node cannot be connected to the same network or switch or blade.
* The network must meet the following requirements as outlined in the sections:
** Considerations for Inter-Switch Links (ISLs)
** Considerations when deploying MetroCluster in a shared layer 2 or layer 3 network
* The maximum transmission unit (MTU) of 9216 must be configured on all switches that carry MetroCluster IP traffic.
* Reverting to ONTAP 9.6 or earlier is not supported.

If you use any more intermediate switches between the switches connecting the MetroCluster IP interfaces at both sites, then these intermediate switches must meet the requirements and must be configured as outlined in section “Considerations when deploying MetroCluster in a shared layer 2 or layer 3 network”.

== Limitations to MetroCluster-compliant switches

Any configuration or feature that requires that the local cluster connections are connected to a switch cannot be used. For example, the following configurations and procedures cannot be used with a MetroCluster-compliant switch:

* Eight-node MetroCluster configurations
* Transitioning from MetroCluster FC to MetroCluster IP configurations
* Refreshing a four-node MetroCluster IP configuration
* Platforms sharing a physical interface for local cluster and MetroCluster traffic. Refer to the table below for support speed.

== Platform-specific network speeds and switch port modes for MetroCluster-compliant switches

The following table provides platform-specific network speeds and switch port modes for MetroCluster-compliant switches. You should configure the switch port mode as outlined in the table.

NOTE: Missing values indicate that the platform cannot be used with a MetroCluster-compliant switch.

|===

h| Platform h| Network Speed (Gbps) h| Switch port mode

a|
AFF A900
a|
100
a|
trunk mode
a|
AFF A800
a|
40 or 100
a| access mode
a|
AFF A700
a|
40
a|
access mode
a|
AFF A400
a|
40 or 100
a|
trunk mode
a|
AFF A320
a|
100
a|
access mode
a|
AFF A300
a|
25
a|
access mode
a|
AFF A250
a|
-
a|
-
a|
AFF A220
a|
-
a|
-
a|
AFF A150
a|
-
a|
-
a|
C800
a|
40 or 100
a|
access mode
a|
C400
a|
40 or 100
a|
trunk mode
a|
C250
a|
-
a|
-
a|
FAS9000
a|
40
a|
access mode
a|
FAS9500
a|
100 (not supported for FAS9000 to FAS9500 upgrades) 
40
a|
trunk mode
a|
FAS8700
a|
100
a|
trunk mode
a|
FAS8300
a|
40 or 100
a|
trunk mode
a|
FAS8200
a|
25
a|
access mode
a|
FAS2750
a|
-
a|
-
a|
FAS500f
a|
-
a|
-
|===

== Configuration overview

The following is an overview of how the various switch ports need to be configured.

Depending on the switch vendor you might require different values for DSCP. The following examples are using decimal values and follow the table that applies to Cisco switches. Refer to the corresponding table of your switch vendor to derive the correct value:

|===

h| DSCP value h| Decimal h| Hex h| Meaning

a|
101 000
a|
16
a|
0x10
a|
CS2
a|
011 000
a|
24
a|
0x18
a|
CS3
a|
100 000
a|
32
a|
0x20
a|
CS4
a|
101 000
a|
40
a|
0x28
a|
CS5

|===

.Switchport connecting a MetroCluster interface

* Classification, remote direct memory access (RDMA) traffic: 
** Match : TCP port 10006, source and/or destination
** Optional match: COS 5
** Optional match: DSCP 40
** Set DSCP 40
** Set COS 5
** Optional : rate shaping to 20Gbps
* Classification, iSCSI traffic: 
** Match : TCP port 62500, source and/or destination
** Optional match: COS 4
** Optional match: DSCP 32
** Set DSCP 32
** Set COS 4
* L2FlowControl (pause), RX and TX

.ISL ports

* Classification:
** Match cos 5 or DSCP 40
*** Set DSCP 40
*** Set COS 5
** Match cos 4 or DSCP 32
*** Set DSCP 32
*** Set COS 4
* Egress queuing
** We are currently configuring thresholds (min/max) of 2000/3000 for COS 4 and 3500/6500 for COS 5
+
NOTE: The above configurations should be evaluated due to only stating what NetApp configure and as a result, they might or might not fit your environment.
+
** ECN enabled for Q4 and Q5
** RED enabled for Q4 and Q5

.Bandwidth allocation (switch ports connecting MetroCluster interfaces and ISL ports)
* RDMA, COS5 / DSCP 40: 60%
* iSCSI, COS4 / DSCP 32: 40%
* Minimum capacity requirement per MetroCluster and network: 10Gbps

NOTE: If you use rate limits, then the traffic should be *shaped* without introducing loss.

== Examples for configuring switch ports connecting the MetroCluster controller

The examples provided are valid for Cisco NX3232 or Cisco NX9336 switches. If other switches are used, these commands can be used as guidance, but the commands might be different. If a feature or its equivalent shown in the examples is not available on the switch, this means that the switch does not meet the minimum requirements and cannot be used to deploy a MetroCluster configuration. This is true for any switch that is connecting a MetroCluster configuration and for all switches on the path between those switches.

Examples might show the configuration for one network only.

.Basic configuration
A virtual LAN (VLAN) in each network must be configured. The example shows how to configure a VLAN in network 10.

*Example:*

----
# vlan 10
The load balancing policy should be set so that order is preserved.
----

*Example:*
----
# port-channel load-balance src-dst ip-l4port-vlan
----

== Configuring classification

You must configure the access and class maps which map the RDMA and iSCSI traffic to the appropriate classes.

All TCP traffic to and from the port 65200 is mapped to the storage (iSCSI) class. All TCP traffic to and from the port 10006 is mapped to the RDMA class. These policy-maps are used on switch ports connecting the MetroCluster interfaces.

*Example:*
----
ip access-list storage
  10 permit tcp any eq 65200 any
  20 permit tcp any any eq 65200
ip access-list rdma
  10 permit tcp any eq 10006 any
  20 permit tcp any any eq 10006

class-map type qos match-all storage
  match access-group name storage
class-map type qos match-all rdma
match access-group name rdma
----

You must configure the ingress policy. The ingress policy maps the traffic as classified to the different COS groups. In this example, the RDMA traffic is mapped to COS group 5 and iSCSI traffic is mapped to COS group 4. The ingress policy is used on switch ports connecting the MetroCluster interfaces and on the ISL ports carrying MetroCluster traffic.

*Example:*
----
policy-map type qos MetroClusterIP_Ingress
class rdma
  set dscp 40
  set cos 5
  set qos-group 5
class storage
  set dscp 32
  set cos 4
  set qos-group 4
----

It is recommended that you shape traffic on switch ports connecting a MetroCluster interface if the switch ports operational speed is greater than 10-Gbps.

*Example:*
----
policy-map type qos MetroClusterIP_Ingress
class rdma
  set dscp 40
  set cos 5
  set qos-group 5
class storage
  set dscp 32
  set cos 4
  set qos-group 4
----

It is recommended that you shape traffic on switch ports connecting a MetroCluster interface if the switch ports operational speed is greater than 10-Gbps.

*Example:*
----
policy-map type queuing MetroClusterIP_Node_Egress
class type queuing c-out-8q-q7
  priority level 1
class type queuing c-out-8q-q6
  priority level 2
class type queuing c-out-8q-q5
  priority level 3
  shape min 0 gbps max 20 gbpsclass type queuing c-out-8q-q4
  priority level 4
class type queuing c-out-8q-q3
  priority level 5
class type queuing c-out-8q-q2
  priority level 6
class type queuing c-out-8q-q1
  priority level 7
class type queuing c-out-8q-q-default
  bandwidth remaining percent 100
  random-detect threshold burst-optimized ecn
----

== Configuring the node ports 

You might need to configure the node port in breakout mode. In this example, ports 25 and 26 are configured in 4 x 25 Gbps breakout mode.

*Example:*
----
interface breakout module 1 port 25-26 map 25g-4x
----

You might need to configure the MetroCluster interface port speed. The example shows how to configure the speed to *auto* or into 40-Gbps mode

*Example:*
----
	speed auto

	speed 40000
----

The following example shows a switch port configured to connect a MetroCluster interface. It is an access mode port in VLAN 10, with MTU of 9216 and is operating in native speed. It has symmetric (send and receive) flow control (pause) enabled and the MetroCluster ingress and egress policies assigned.

*Example:*
----
interface eth1/9
description MetroCluster-IP Node Port
speed auto
switchport access vlan 10
spanning-tree port type edge
spanning-tree bpduguard enable
mtu 9216
flowcontrol receive on
flowcontrol send on
service-policy type qos input MetroClusterIP_Ingress
service-policy type queuing output MetroClusterIP_Node_Egress
no shutdown
----

On 25-Gbps ports, the Forward Error Correction (FEC) setting might need to be set to "off" as shown in the example.

*Example:*
----
fec off
----

==  Configuration of the ISL ports throughout the network

A MetroCluster-compliant switch is regarded as intermediate switch, even it directly connects the MetroCluster interfaces. The ISL ports carrying MetroCluster traffic on the MetroCluster-compliant switch need to be configured the same way as the ISL ports on an intermediate switch. Please refer to the section “Required settings on intermediate switches” for guidance and examples. Note that some policy-maps are the same for switch ports connecting MetroCluster interfaces and ISLs carrying MetroCluster traffic. You can leverage the same policy-map for both port usages.

== Examples of MetroCluster network topologies

Beginning with ONTAP 9.6, some additional network configurations are supported for MetroCluster IP configurations. This section provides some examples of those. Not all the supported topologies are listed.

In either of these topologies, it is assumed that the ISL and/or intermediate network is meeting and is configured as per the prior outlined requirements.

NOTE: If sharing an ISL with non-MetroCluster traffic, ensure that the MetroCluster has at least the minimum required bandwidth available at all times.

.Shared network configuration with direct links

In this topology, two distinct sites are connected by direct links. These links can be between xWDM and TDM devices or switches. The capacity of the ISLs is not dedicated to the MetroCluster traffic but is shared with other non-MetroCluster traffic.

// IMAGE 1 HERE

.Shared infrastructure with intermediate networks

In this topology, the MetroCluster sites are not directly connected but MetroCluster and the host traffic travel through a network. 
The network can consist of a series of xWDM and TDM and/or switches, but unlike the shared configuration with direct ISLs, the links are not direct between the sites. Depending on the infrastructure between the sites, any combination of network configurations is possible. 

// IMAGE 2 HERE

.Multiple MetroCluster configurations sharing an intermediate network

In this topology, two separate MetroCluster configurations are sharing the same intermediate network. In the example, MetroCluster one switch_A_1 and MetroCluster two switch_A_1 both connect to the same intermediate switch. 

NOTE: “MetroCluster one” or “MetroCluster two” can both be one 8-node MetroCluster or two 4-node MetroClusters.

// IMAGE 3 HERE

.Combination of one MetroCluster using NetApp validated switches and one using MetroCluster-compliant switches

Two separate MetroCluster configurations share the same intermediate switch, where one MetroCluster is configured using NetApp validated switches in a shared L2 configuration (MetroCluster one), and the other MetroCluster is configured using MetroCluster-compliant switches connecting directly to the intermediate switches (MetroCluster two).

// IMAGE 4 HERE



// 2023-07-03, ONTAPDOC-928