---
permalink: install-ip/concept_mediator_requirements.html
sidebar: sidebar
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency
summary: Beginning with ONTAP 9.7, ONTAP Mediator can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= ONTAP Mediator installation requirements for MetroCluster IP configurations
:icons: font
:imagesdir: ../media/

[.lead]
Your environment must meet certain requirements. 

The following requirements apply to one disaster recovery group (DR group). Learn more about link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups[DR groups].

* If you plan on updating your Linux version, do so before you install the most current version of ONTAP Mediator.

* The ONTAP Mediator and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.

* ONTAP Mediator must be installed on a Linux host at a separate location from the MetroCluster sites.
+
The connectivity between the ONTAP Mediator and each site must be two separate failure domains.

* Automatic unplanned switchover is supported in ONTAP 9.7 and later.

* Beginning with ONTAP 9.18.1 and ONTAP Mediator 1.11, a single ONTAP Mediator instance can manage up to ten MetroCluster configurations simultaneously. In earlier releases, ONTAP Mediator can support up to five MetroCluster configurations simultaneously.

* Beginning with ONTAP 9.18.1, IPv6 is supported for ONTAP Mediator 1.11 or later in a MetroCluster IP configuration.

== Network requirements for using ONTAP Mediator in a MetroCluster configuration

To install ONTAP Mediator in a MetroCluster configuration, you must make sure that the configuration meets several network requirements.

* Latency
+
Maximum latency of less than 75ms (RTT).
+
Jitter must be no more than 5ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
For both Internet Control Message Protocol (ICMP) and TCP traffic, packet loss must be less than 0.01%.

* Bandwidth
+
The link between ONTAP Mediator and one DR group must have at least 20Mbps of bandwidth.

* Independent connectivity
+
Independent connectivity between each site and the ONTAP Mediator is required. A failure in one site must not interrupt the IP connectivity between the other two unaffected sites.

== Host requirements for ONTAP Mediator in a MetroCluster configuration

You must ensure that the configuration meets several host requirements.

* ONTAP Mediator must be installed at an external site that is physically separated from the two ONTAP clusters.

* ONTAP Mediator does not require more than the host operating system's minimum requirements for CPU and memory (RAM).

* In addition to the host operating system's minimum requirements, at least 30GB of additional usable disk space must be available.
+
**  Each DR group requires up to 200MB of disk space.

== Learn about the HTTPS and iSCSI protocols

By default, MetroCluster IP nodes access ONTAP Mediator mailbox LUNs using iSCSI sessions. ONTAP Mediator relies on the SCST package to provide iSCSI. iSCSI sessions are authenticated using the Challenge Handshake Authentication Protocol (CHAP) with an obfuscated, machine-generated per-shared key, but are not fully encrypted.

Beginning with ONTAP 9.19.1 and ONTAP Mediator 1.12, you can configure an HTTPS-based Mediator to monitor your MetroCluster IP configuration. HTTPS is a secure protocol for communication. Configuring an HTTPS-based Mediator has the following benefits:
 
* No special kernel packages are required during the ONTAP Mediator installation.
* HTTPS encrypts entire sessions using SSL/TLS making it more secure than using iSCSI. 

NOTE: You can only configure an HTTPS-based ONTAP Mediator using the CLI. System Manager is not supported. 

== Firewall requirements for ONTAP Mediator

ONTAP Mediator uses a number of ports to communicate with specific services. Refer to link:https://review.docs.netapp.com/us-en/ontap_aoife-mediator-https/mediator/index.html#firewall-and-networking-requirements[ONTAP Mediator firewall and networking requirements^] for the the ports that you must allow in your firewall.

// 2026 Feb 12, GH 504

== Guidelines for upgrading ONTAP Mediator in a MetroCluster configuration

If you are upgrading ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* ONTAP Mediator can be upgraded from version from an immediately prior version to the current version.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade ONTAP Mediator^]

== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the `storage iscsi-initiator show` command to confirm that the Mediator connections are up.

// 2025 Mar 13, ONTAPDOC-2115, ONTAPDOC-2874
// 2022-06-02, BURT 1439085
// 2022-JAN-05, BURT 1505168