---
permalink: install-ip/concept-risks-limitations-automatic-switchover.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, forced
summary:
---

= Risks and limitations of using MetroCluster automatic forced switchover
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.12.1, you can enable the MetroCluster Automatic Forced Switchover feature in a MetroCluster IP configuration. When enabled, this feature forces a switchover.

Switchover upon detection of a site failure happens automatically, with the MetroCluster Automatic Forced Switchover feature enabled. This feature can be used to supplement the MetroCluster IP automatic switchover capability

When you allow a MetroCluster IP configuration to operate in Automatic Forced Switchover mode, the following known issues might lead to data loss:

* The nonvolatile memory (NVRAM or NVMEM, depending on the platform model) in the storage controllers is not mirrored to the remote disaster recovery (DR) partner on the partner site.

CAUTION: You might encounter scenarios that are not mentioned. NetApp is not responsible for any data corruption, data loss, or other damage that may arise from enabling the MetroCluster Automatic Forced Switchover feature. Do not use MetroCluster Automatic Forced Switchover feature if the risks and limitations are not acceptable to you.
