---
permalink: install-ip/concept_mediator_requirements.html
sidebar: sidebar
keywords: ontap, mediator, assist, metrocluster, ip, configuration, perform, automatic, unplan, switchover, physical, repository, status, information, configuring, configure, install, configuring, configure, mtu size, packet loss, bandwidth, firewall, rhel, centos, linux, revert, kernal, upgrade, latency
summary: Beginning with ONTAP 9.7, ONTAP Mediator can assist the MetroCluster IP configuration in performing an automatic unplanned switchover by providing a physically separate repository for status information.
---
= Prepare to install ONTAP Mediator in a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
Verify that your environment meets the requirements to install ONTAP Mediator in a MetroCluster IP configuration.

The following requirements apply to one disaster recovery group (DR group). Learn more about link:concept_parts_of_an_ip_mcc_configuration_mcc_ip.html#disaster-recovery-dr-groups[DR groups].

* If you plan on updating your Linux version, do so before you install the most current version of ONTAP Mediator.

* The ONTAP Mediator and MetroCluster Tiebreaker software should not both be used with the same MetroCluster configuration.

* ONTAP Mediator must be installed on a Linux host at a separate location from the MetroCluster sites.
+
The connectivity between the ONTAP Mediator and each site must be two separate failure domains.

* Automatic unplanned switchover is supported in ONTAP 9.7 and later.

* Beginning with ONTAP 9.18.1 and ONTAP Mediator 1.11, a single ONTAP Mediator instance can manage up to ten MetroCluster configurations simultaneously. In earlier releases, ONTAP Mediator can support up to five MetroCluster configurations simultaneously.

* Beginning with ONTAP 9.18.1, IPv6 is supported for ONTAP Mediator 1.11 or later in a MetroCluster IP configuration.

== Requirements to install ONTAP Mediator on an AWS EC2 instance

Beginning with ONTAP 9.18.1GA, you can deploy ONTAP Mediator on an Amazon Web Services (AWS) EC2 instance in a MetroCluster IP configuration. Installing ONTAP Mediator on an AWS EC2 instance is similar to on-premises and SCS deployments, but there are certain requirements for cloud deployments that you must be aware of before you begin the installation. 

* ONTAP Mediator AWS EC2 instance deployments are supported on the following host operating systems:
** RHEL 10.x and later 
** Rocky Linux 10 and later 
* The AWS EC2 instance type must be at least t3.large (2 vCPU and 8GiB Memory)
* The AWS EC2 instance must have at least 5GB of available storage
* AWS EC2 instances use security groups to control inbound and outbound traffic. You need to explicitly allow the required ports (such as 22, 31784, and 3260) to enable secure communication between ONTAP Mediator and your ONTAP clusters.
* During installation, the AWS EC2 instance needs access to either the internet or your organization’s internal package repository to download necessary software dependencies. This can be achieved by configuring outbound rules in the security group or by setting up access to an in-house repository.
* You must place the AWS EC2 instance in a VPC that has network connectivity to your ONTAP clusters.
* You must select a subnet that has routes to ONTAP cluster management and node management LIFs.

== Network requirements for using ONTAP Mediator in a MetroCluster configuration

To install ONTAP Mediator in a MetroCluster configuration, you must make sure that the configuration meets several network requirements.

* Latency
+
Maximum latency of less than 75ms (RTT).
+
Jitter must be no more than 5ms.

* MTU
+
The MTU size must be at least 1400.

* Packet loss
+
For both Internet Control Message Protocol (ICMP) and TCP traffic, packet loss must be less than 0.01%.

* Bandwidth
+
The link between ONTAP Mediator and one DR group must have at least 20Mbps of bandwidth.

* Independent connectivity
+
Independent connectivity between each site and the ONTAP Mediator is required. A failure in one site must not interrupt the IP connectivity between the other two unaffected sites.

== Host requirements for ONTAP Mediator in a MetroCluster configuration

You must ensure that the configuration meets several host requirements.

* ONTAP Mediator must be installed at an external site that is physically separated from the two ONTAP clusters.

* ONTAP Mediator does not require more than the host operating system's minimum requirements for CPU and memory (RAM).

* In addition to the host operating system's minimum requirements, at least 30GB of additional usable disk space must be available.
+
**  Each DR group requires up to 200MB of disk space.


== Firewall requirements for ONTAP Mediator

ONTAP Mediator uses a number of ports to communicate with specific services.

If you are using a third-party firewall:

* HTTPS access must be enabled.
* It must be configured to allow access on ports 31784 and 3260.
+
When using the default Red Hat or CentOS firewall, the firewall is automatically configured during Mediator installation.

The following table lists the ports that you must allow in your firewall:

[NOTE] 
====
* The iSCSI port is only required in a MetroCluster IP configuration.
* The 22/tcp port is not required for normal operation but you can enable it temporarily for maintenance and disable it when the maintenance session has finished.
* The EC2 instance port is only required when you want to install ONTAP Mediator on an AWS EC2 instance. Refer to <<Requirements to install ONTAP Mediator on an AWS EC2 instance>> for more information.
====

|===

h| Port/services h| Source h| Direction h|  Destination h| Purpose 

a| 
22/tcp
a|
Management host
a|
Inbound
a|
ONTAP Mediator
a|
SSH / ONTAP Mediator management
a|
31784/tcp
a|
cluster-mgmt and node-mgmt LIFs
//ontap-metrocluster/issues/34
a|
Inbound
a|
ONTAP Mediator web server
a|
REST API (HTTPS)
a|
3260/tcp
a|
node-mgmt LIFs
a|
Bidirectional
a|
ONTAP Mediator iSCSI targets
a|
iSCSI data connection for mailboxes

a| 
443/https
a|
EC2 instance
a|
Outbound
a|
Linux repositories or internet
a|
Package installation
|===

== Guidelines for upgrading ONTAP Mediator in a MetroCluster configuration

If you are upgrading ONTAP Mediator you must meet the Linux version requirements and follow guidelines for the upgrade.

* ONTAP Mediator can be upgraded from version from an immediately prior version to the current version.
* All Mediator versions are supported on MetroCluster IP configurations running ONTAP 9.7 or later.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade ONTAP Mediator^]

== After the upgrade

After the Mediator and operating system upgrade is complete, you should issue the `storage iscsi-initiator show` command to confirm that the Mediator connections are up.

// 2025 Mar 13, ONTAPDOC-2115, ONTAPDOC-2874
// 2022-06-02, BURT 1439085
// 2022-JAN-05, BURT 1505168
