---
permalink: install-ip/concept_considerations_unmirrored_aggrs.html
sidebar: sidebar
keywords: differences, eight-node, four-node, fabric-attached, stretch, metrocluster ip, storage, bridges, fc-to-sas, atto, fibrebridge, SAS, local HA, auso, automatic unplanned switchover, array luns, mediator, tiebreaker
summary: If your configuration includes unmirrored aggregates, you must be aware of potential access issues after switchover operations.
---
= Learn about unmirrored aggregates in MetroCluster IP configurations
:icons: font
:imagesdir: ../media/

[.lead]
If your configuration includes unmirrored aggregates, you must be aware of potential access issues after switchover operations.

== Unmirrored aggregates and hierarchical namespaces

If you are using hierarchical namespaces, you should configure the junction path so that all of the volumes in that path are either on mirrored aggregates only or on unmirrored aggregates only. Configuring a mix of unmirrored and mirrored aggregates in the junction path might prevent access to the unmirrored aggregates after the switchover operation.

== Unmirrored aggregates and maintenance that requires power shutdown

If you perform a negotiated switchover for maintenance that requires a site-wide power shutdown, you should first manually offline any unmirrored aggregates owned by the disaster site.

If you don't offline the unmirrored aggregates owned by the disaster site, nodes at the surviving site might go down due to multi-disk panics. This might occur if switched-over unmirrored aggregates go offline or are missing because of the loss of connectivity to storage at the disaster site if there's a power shutdown or loss of ISLs.

== Unmirrored aggregates, CRS metadata volumes, and data SVM root volumes

The configuration replication service (CRS) metadata volume and data SVM root volumes must be on a mirrored aggregate. You cannot move these volumes to an unmirrored aggregate. If they are on an unmirrored aggregate, negotiated switchover and switchback operations are vetoed and the `metrocluster check` command returns a warning.

== Unmirrored aggregates and SVMs

You should configure SVMs on mirrored aggregates only or on unmirrored aggregates only. Configuring SVMs on a mix of both unmirrored and mirrored aggregates can result in a switchover operation that exceeds 120 seconds. If the the unmirrored aggregates don't come online, this causes a data outage.

== Unmirrored aggregates and SAN

Before ONTAP 9.9.1, a LUN should not be located on an unmirrored aggregate. Configuring a LUN on an unmirrored aggregate can result in a switchover operation that exceeds 120 seconds and a data outage.
// BURT 1397232

== Add storage shelves for unmirrored aggregates

If you add shelves and want to use them for unmirrored aggregates in a MetroCluster IP configuration, you must do the following:

. Before starting the procedure to add the shelves, issue the following command:
+
`metrocluster modify -enable-unmirrored-aggr-deployment true`
. Verify that automatic disk assignment is off:
+
`disk option show`
. Follow the steps of the procedure to add the shelf.
. Manually assign all disks from new shelf to the node that will own the unmirrored aggregate or aggregates.
. Create the aggregates:  
+
`storage aggregate create`
. After completing the procedure, issue the following command:
+
`metrocluster modify -enable-unmirrored-aggr-deployment false`
. Verify that automatic disk assignment is enabled:
+
`disk option show`

// 2024-03-13, ONTAPDOC-1668