---
permalink: install-ip/overview_isl_requirements.html
sidebar: sidebar
keywords: isls, ip, layer 2, layer 3, shared switch
summary: "The information in this section enables you to make sure that your MetroCluster configuration and the network is meeting all requirements."
---
= Overview

The information in this section enables you to make sure that your MetroCluster configuration and the network is meeting all requirements. Although some information might not apply to your configuration, you should still make sure you are aware of all requirements in this section to gain a better understanding of the overall configuration. 

This section focuses on three high level areas:

[cols=2*,options="header",cols="25,75"]
|===
| Topic
| Description
| Considerations for ISLs | This section applies to all MetroCluster configurations, regardless of network topology and whether you use NetApp-validated switches or MetroCluster-compliant switches.
| Considerations when deploying MetroCluster in a shared layer 2 or layer 3 networks |This section applies to all configurations except for a MetroCluster configuration using NetApp-validated switches and using direct connected ISLs.
| Considerations when using MetroCluster Compliant switches | This section applies to all configurations not using NetApp-validated switches
|===

