---
permalink: install-ip/overview_isl_requirements.html
sidebar: sidebar
keywords: isls, ip, layer 2, layer 3, shared switch
summary: "This section provides the information required to verify that your MetroCluster configuration and the network is meeting all requirements."
---
= Overview

This section contains the information required to verify that your MetroCluster configuration and the network is meeting all requirements. Although some information might not apply to your configuration, you should still be aware of all of the requirements to gain a better understanding of the overall configuration. 

The following table describes the three high-level areas in this section and the configurations they apply to:

[cols=2*,options="header",cols="25,75"]
|===
| Title
| Description
| link:concept_requirements_isls.html[Considerations for ISLs] | Applies to all MetroCluster configurations, regardless of network topology and whether you use NetApp-validated switches or MetroCluster-compliant switches.
| link:concept_considerations_layer_2_layer_3.html[Considerations when deploying MetroCluster in a shared layer 2 or layer 3 networks] |Applies to all configurations except for a MetroCluster configuration using NetApp-validated switches and using direct connected ISLs.
| link:concept_considerations_mcc_compliant_switches.html[Considerations when using MetroCluster Compliant switches] | Applies to all configurations that are not using NetApp-validated switches.
|===

