---
permalink: install-ip/overview_isl_requirements.html
sidebar: sidebar
keywords: isls, ip, layer 2, layer 3, shared switch
summary: "This section provides the information required to verify that your MetroCluster configuration and the network is meeting all requirements."
---
= ISL requirements overview

[lead]
You should verify that your MetroCluster IP configuration and the network is meeting all ISL requirements. Although certain requirements might not apply to your configuration, you should still be aware of all of the ISL requirements to gain a better understanding of the overall configuration. 

The following table describes three high-level areas and the configurations they apply to:

[cols=2*,options="header",cols="25,75"]
|===
| Title
| Description
| link:concept_requirements_isls.html[Considerations for ISLs] | Applies to all MetroCluster configurations, regardless of network topology and whether you use NetApp-validated switches or MetroCluster-compliant switches.
| link:concept_considerations_layer_2_layer_3.html[Considerations when deploying MetroCluster in a shared layer 2 or layer 3 networks] |Applies to all configurations except for a MetroCluster configuration using NetApp-validated switches and using direct connected ISLs.
| link:concept_considerations_mcc_compliant_switches.html[Considerations when using MetroCluster Compliant switches] | Applies to all configurations that are not using NetApp-validated switches.
|===

== MetroCluster switch requirements

All of the switches, including backend switches, used in your configuration must either be NetApp-validated or MetroCluster-compliant. 

=== NetApp-validated switches

A switch is NetApp-validated if it meets the following requirements:

* The switch is provided by NetApp as part of the MetroCluster IP configuration
* The switch is listed in link:https://hwu.netapp.com/[NetApp Hardware Universe^] as a supported switch under _MetroCluster-over-IP-connections_
* The switch is only used to connect MetroCluster IP controllers and, in some configurations, NS224 drive shelves
* The switch is configured using the Reference Configuration File (RCF) provided by NetApp 

Any switch that does not meet these requirements is *not* a NetApp-validated switch. 

=== MetroCluster-compliant switches
A MetroCluster-compliant switch is not NetApp-validated but can be used in a MetroCluster IP configuration if it meets certain requirements and configuration guidelines.

NOTE: NetApp does not provide support services, troubleshooting or configuration for any non-validated MetroCluster-compliant switch.