---
permalink: install-ip/overview-isl-requirements.html
sidebar: sidebar
keywords: isls, ip, layer 2, layer 3, shared switch
summary: "This section provides the information required to verify that your MetroCluster configuration and the network is meeting all requirements."
---
= ISL requirements overview

[lead]
You should verify that your MetroCluster IP configuration and the network is meeting all Inter-Switch Link (ISL) requirements. Although certain requirements might not apply to your configuration, you should still be aware of all of the ISL requirements to gain a better understanding of the overall configuration. 

The following table provides an overview of the topics covered in this section. 

[cols=2*,options="header",cols="25,75"]
|===
| Title
| Description
| link:mcc-compliant-netapp-validated-switches.html[NetApp-validated and MetroCluster-compliant switches] | Describes the switch requirements. 

Applies to all switches used in MetroCluster configurations, including backend switches. 
| link:concept_requirements_isls.html[Considerations for ISLs] | Describes the ISL requirements.

Applies to all MetroCluster configurations, regardless of network topology and whether you use NetApp-validated switches or MetroCluster-compliant switches.
| link:concept_considerations_layer_2_layer_3.html[Considerations when deploying MetroCluster in a shared layer 2 or layer 3 networks] | Describes the requirements for shared layer 2 or layer 3 networks. 

Applies to all configurations except for a MetroCluster configuration using NetApp-validated switches and using direct connected ISLs.
| link:concept_considerations_mcc_compliant_switches.html[Considerations when using MetroCluster Compliant switches] | Describes the requirements for MetroCluster-compliant switches. 

Applies to all configurations that are not using NetApp-validated switches.
| link:concept-example-network-topologies.html[Examples of MetroCluster network topologies] | Provides examples of different MetroCluster network topologies.

Applies to all MetroCluster configurations.
|===

// 2024 Mar 04, ONTAPDOC-928 (ISL rework)