---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html
sidebar: sidebar
keywords: metrocluster, mediator, configure
summary: The ONTAP Mediator service must be configured on the ONTAP node for use in a MetroCluster IP configuration.
---

= Configuring the ONTAP Mediator service from a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP Mediator service must be configured on the ONTAP node for use in a MetroCluster IP configuration.

*Before you begin*

* The ONTAP Mediator must have been successfully installed on a network location that can be reached by both MetroCluster sites.
* You must have the IP address of the host running the ONTAP Mediator service.
* You must have the username and password for the ONTAP Mediator service.
* All nodes of the MetroCluster IP configuration must be online.

*About this task*

* This task enables automatic unplanned switchover by default.
* This task can be performed on the ONTAP interface of any node in the MetroCluster IP configuration.
* A single installation of the ONTAP Mediator service can be configured with up to five MetroCluster IP configurations.

*Procedure*

. Add the ONTAP Mediator service to ONTAP using the following command: metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host
+
Note: You will be prompted for the username and password for the Mediator admin user account.

. Verify that the automatic switchover feature in enabled: metrocluster show
. Verify that the Mediator is now running.

 .. Show the Mediator virtual disks: storage disk show -container-type mediator
+
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1

 .. Set the privilege mode to advanced: set advanced
+
 cluster_A::> set advanced

.. Display the initiators labelled as mediator: storage iscsi-initiator show -label mediator
+
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
