---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html
sidebar: sidebar
keywords: metrocluster, mediator, configure
summary: ONTAP Mediator must be configured on the ONTAP node for use in a MetroCluster IP configuration.
---
= Set up the ONTAP Mediator for a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the ONTAP Mediator on the ONTAP node to use it in a MetroCluster IP configuration.

.Before you begin

* ONTAP Mediator must have been successfully installed on a network location that can be reached by both MetroCluster sites.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade ONTAP Mediator^]
//adding link to new location 2022-03-31
* You must have the IP address of the host running ONTAP Mediator.
* You must have the username and password for ONTAP Mediator.
* All nodes of the MetroCluster IP configuration must be online.

CAUTION: Beginning with ONTAP 9.12.1, you can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover. Before you enable this feature, review the link:concept-ontap-mediator-supports-automatic-unplanned-switchover.html#mauso-9-12-1[Risks and limitations of using MetroCluster automatic forced switchover].

.About this task

* This task enables automatic unplanned switchover by default.
* This task can be performed on the ONTAP interface of any node in the MetroCluster IP configuration.
* Beginning with ONTAP 9.18.1 and ONTAP Mediator 1.11, a single ONTAP Mediator instance can manage up to ten MetroCluster configurations simultaneously. In earlier releases, ONTAP Mediator can support up to five MetroCluster configurations simultaneously.
* If you don't specify the `-type` parameter in the command, the default iSCSI protocol is used. 

[role="tabbed-block"]
=====
.Configure an ONTAP Mediator with HTTPS
--

Beginning with ONTAP 9.19.1 and ONTAP Mediator 1.12, you can configure a HTTPS based Mediator to monitor your MetroCluster configuration. 

.Steps 

. Locate the ONTAP Mediator CA certificates from the ONTAP Mediator Linux VM/host software installation location:
+
`[root@ontap-mediator ~] cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config`
+
You should see output similar to the following example:
+
----
1-ontap-mediator.rules  intermediate.crt   make_self_signed_certs.sh      ontap_mediator_server_chain.crt  ontap_mediator.user_config.yaml  root_ca.crt
config_migration        intermediate.key   netapp_sudoers                 ontap_mediator_server.crt        openssl_ca.cnf                   root_ca.key
config.pyc              intermediate.srl   ontap_mediator.config.yaml     ontap_mediator_server.csr        openssl_intermediate.cnf
__init__.pyc            logging.conf.yaml  ontap_mediator.constants.yaml  ontap_mediator_server.key        openssl_server.cnf
----

. Display the contents of the root CA certificate:
+
`[root@ontap-mediator ~] cat root_ca.crt`
+
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
-----
----

. Display the contents of the intermediate CA certificate:
+
`[root@ontap-mediator ~] cat intermediate.crt`
+
----
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----
-----
----


. Install the root and intermediate CA certificates on site A:
.. Install the root CA certificate:
+
`security certificate install -type server-ca`
+
Enter the `root.crt` when prompted as shown in the following example:
+
----
cluster_A::*> security certificate install -type server-ca

        Enter certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----
. Install the intermediate CA certificate:
+
`security certificate install -type server-ca`
+
Enter the `intermediate.crt` when prompted as shown in the following example:
+
----
cluster_A::*> security certificate install -type server-ca

        Enter certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

You should keep a copy of the CA-signed digital certificate for future
reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: <serial_value>

The certificate's generated name for reference: ONTAPMediatorCA

cluster_A::*>

----

. Repeat the previous step to install the root and intermediate CA certificates on site B.

. Verify the server certificate details and expiration dates:
+
`security certificate show -type server-ca -ca "ONTAP Mediator CA"`
+
You should see output similar to the following example:
+
----
   security certificate show -type server-ca -ca "ONTAP Mediator CA"
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
cluster_A 4011FFF4CC072A0C3DF0D16E36218839031DA04B ONTAPMediatorCA server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

cluster_A ED7F60A4BEE9D3D96AE15EE5819335EC9332C461 ONTAPMediatorCA_ED7F60A4BEE9D3D96AE15EE5819335EC9332C461 server-ca
    Certificate Authority: ONTAP Mediator CA
          Expiration Date: Thu Nov 28 05:26:07 2030

2 entries were displayed.
----

. Add ONTAP Mediator to ONTAP. The steps depend on whether you want to use an IPv4 or IPv6 address.
+
[NOTE]
====
* You must be running ONTAP 9.18.1 or later and ONTAP Mediator 1.11 or later to use IPv6.
* If you enable IPv6 on a cluster, you cannot disable it later. 
====

.. If you want to use IPv6, complete the following steps:
+
If you want to use IPv4, go to <<https_ipv4_step8b, Step 8 (b)>>
+
... Run the following command on both clusters:
+
`network options ipv6 modify -enabled true`

... Configure the node-mgmt IP address with IPv6 addresses on all four nodes.

... Add the ONTAP Mediator:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type https-mediator`
+
NOTE: You are prompted for the username and password for the Mediator admin user account.

.. [[https_ipv4_step8b]]If you want to use IPv4, complete the following step:
+
... Add the ONTAP Mediator:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type https-mediator`
+
NOTE: You are prompted for the username and password for the Mediator admin user account.


. Verify the connection status and the ONTAP Mediator type:
+
`metrocluster configuration-settings mediator show`
+
You should see output similar to the following example:
+
----
cluster_A::*> metrocluster configuration-settings mediator show
        Mediator IP     Port    Type              Node                    Configuration Connection
                                                  Status                  Status
        --------------- ------- ----------------- ----------------------- ------------- -----------
        10.101.101.101
                        31784   https-mediator    cluster1_node_01        true          true
                                                  cluster1_node_02        true          true
                                                  cluster2_node_01        true          true
                                                  cluster2_node_02        true          true
----


.. Verify that the automatic switchover feature is enabled:
+
`metrocluster show`

.. Verify that the Mediator is now running.

... Show the Mediator virtual disks:
+
`storage disk show -container-type mediator`
+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....

... Set the privilege mode to advanced:
+
`set advanced`
+
....
 cluster_A::> set advanced
....

... Show the ONTAP Mediator mailbox disks:
+
`storage failover mailbox-disk show`
+
----
 cluster_A::*> storage failover mailbox-disk show
                  Mailbox
Node             Owner     Disk Name        Disk UUID
---------------- --------- ---------------- ----------------
node_A1
                 local     1.0.6.P3         674A3830:57C03745:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     1.0.7.P3         674A3830:57C03749:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     1.0.8.P3         674A3830:57C03880:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     NET-1.4          34383535:30666163:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000 
                 local     2.0.22.P3        66483030:54A01201:00253845:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     2.0.21.P3        66483030:54A00871:00253845:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     2.0.23.P3        66483030:54B01401:00253841:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   1.0.0.P3         674A3830:57C03879:00253845:00000011:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   1.0.1.P3         674A3830:57C04249:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   1.0.2.P3         674A3830:57C04244:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   2.0.15.P3        674A3830:57C04252:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   2.0.13.P3        674A3830:57C04253:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   2.0.17.P3        674A3830:57C02798:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   NET-1.1          37636232:61373335:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000 
node_A2
                 local     1.0.0.P3         674A3830:57C03879:00253845:00000011:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     1.0.1.P3         674A3830:57C04249:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     1.0.2.P3         674A3830:57C04244:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     2.0.15.P3        674A3830:57C04252:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     2.0.13.P3        674A3830:57C04253:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     2.0.17.P3        674A3830:57C02798:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 local     NET-1.1          37636232:61373335:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000  
                 partner   1.0.6.P3         674A3830:57C03745:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   1.0.7.P3         674A3830:57C03749:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   1.0.8.P3         674A3830:57C03880:00253845:0000000F:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   NET-1.4          34383535:30666163:00000000:00000000:00000000:00000000:00000000:00000000:00000000:00000000  
                 partner   2.0.22.P3        66483030:54A01201:00253845:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   2.0.21.P3        66483030:54A00871:00253845:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
                 partner   2.0.23.P3        66483030:54B01401:00253841:00000002:500A0981:00000003:00000000:00000000:00000000:00000000
28 entries were displayed.

cluster_A::*> 
----

... Verify the state of the automatic unplanned switchover (AUSO) failure domain:
+
`metrocluster show`
+
NOTE: The following example output applies to ONTAP 9.13.1 and later. For ONTAP 9.12.1 and earlier, the AUSO failure domain state should be `auso-on-cluster-disaster`.
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
----

. From the ONTAP Mediator host, verify that disks on the sqlite database are populated with the reservation owner:
+
`[root@ontap-mediator ~]# sqlite3 /opt/netapp/lib/ontap_mediator/db/ontap_mediator.sqlite.db`
+
You should see output similar to the following example:
+
----
[root@ontap-mediator ~]# sqlite3 /opt/netapp/lib/ontap_mediator/db/ontap_mediator.sqlite.db
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> 
sqlite> SELECT DISTINCT disk, reservation_owner FROM mediator_table;  
disk-info-66114f8d-d43a-11f0-|
disk-mb-66114f8d-d43a-11f0--1| 
disk-mb-66114f8d-d43a-11f0--2| 
disk-mb-66114f8d-d43a-11f0--3| 
disk-mb-66114f8d-d43a-11f0--4|
----
-- 
.Configure an ONTAP Medaitor with iSCSI
--

.Steps

. Add ONTAP Mediator to ONTAP. The steps depend on whether you want to use an IPv4 or IPv6 address.
+
[NOTE]
====
* You must be running ONTAP 9.18.1 or later and ONTAP Mediator 1.11 or later to use IPv6.
* If you enable IPv6 on a cluster, you cannot disable it later. 
====

.. If you want to use IPv6, complete the following steps:
+
If you want to use IPv4, go to <<iscsi_ipv4_step8b, Step 8 (b)>>
+
... Run the following command on both clusters:
+
`network options ipv6 modify -enabled true`


... Configure the node-mgmt IP address with IPv6 addresses on all four nodes.

... Add the ONTAP Mediator:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ipv6_ip_address> -type iscsi-mediator`
+
NOTE: You are prompted for the username and password for the Mediator admin user account.

.. [[iscsi_ipv4_step8b]]If you want to use IPv4, complete the following step:

... Add the ONTAP Mediator:
+
`metrocluster configuration-settings mediator add -mediator-address <mediator_host_ip_address> -type iscsi-mediator`
+
NOTE: You are prompted for the username and password for the Mediator admin user account.


.. Verify that the automatic switchover feature is enabled:
+
`metrocluster show`
.. Verify that the Mediator is now running.

... Show the Mediator virtual disks:
+
`storage disk show -container-type mediator`
+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....

... Set the privilege mode to advanced:
+
`set advanced`
+
....
 cluster_A::> set advanced
....

... Display the initiators labelled as mediator:
+
`storage iscsi-initiator show -label mediator`
+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
... Verify the state of the automatic unplanned switchover (AUSO) failure domain:
+
`metrocluster show`
+
NOTE: The following example output applies to ONTAP 9.13.1 and later. For ONTAP 9.12.1 and earlier, the AUSO failure domain state should be `auso-on-cluster-disaster`.
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
----

--
=====

// 2024 FEB 20, ONTAPDOC-1168
// 2023 Sep 11, GH issue 322
// BURT 1448684, 03 FEB 2022
