---
permalink: install-ip/task_sw_config_assign_pool0.html
sidebar: sidebar
keywords: metrocluster, controller, assign drives, pool 0, disk assign
summary: If you did not receive the systems pre-configured from the factory, you might have to manually assign the pool 0 drives. Depending on the platform model and whether the system is using ADP, you must manually assign drives to pool 0 for each node in the MetroCluster IP configuration. The procedure you use depends on the version of ONTAP you are using.
---
= Manually assigning drives to pool 0

[.lead]
If you did not receive the systems pre-configured from the factory, you might have to manually assign the pool 0 drives. Depending on the platform model and whether the system is using ADP, you must manually assign drives to pool 0 for each node in the MetroCluster IP configuration. The procedure you use depends on the version of ONTAP you are using.

== Manually assigning drives for pool 0 (ONTAP 9.4 and later)

If the system has not been pre-configured at the factory and does not meet the requirements for automatic drive assignment, you must manually assign the pool 0 drives.

.About this task

This procedure applies to configurations running ONTAP 9.4 or later.

To determine if your system requires manual disk assignment, you should review link:concept_considerations_drive_assignment.html[Considerations for automatic drive assignment and ADP systems in ONTAP 9.4 and later].

You perform these steps in Maintenance mode. The procedure must be performed on each node in the configuration.

Examples in this section are based on the following assumptions:

* node_A_1 and node_A_2 own drives on:
 ** site_A-shelf_1 (local)
 ** site_B-shelf_2 (remote)
* node_B_1 and node_B_2 own drives on:
 ** site_B-shelf_1 (local)
 ** site_A-shelf_2 (remote)

.Steps

. Display the boot menu:
+
`boot_ontap menu`
. Select option 9a.
+
The following screen shows the boot menu prompt:
+
----

Please choose one of the following:

(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 9a
Pensando Offload Driver, ver 1.4.0-E-78
Pensando Ethernet NIC Driver, ver: 1.4.0-E-96
ionic_rdma ver 1.4.0-E-96 : Pensando RoCE HCA driver

Loaded OSAL module OS2SP configured successfullypnso provider init started.
Notice : pnso card not detected.
hwo: Node is using hardware provider : 1.
cryptomod_fips: Executing Crypto FIPS Self Tests.
cryptomod_fips: Crypto FIPS self-test: 'CPU COMPATIBILITY' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 ECB, AES-256 ECB' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 CBC, AES-256 CBC' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 GCM, AES-256 GCM' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-128 CCM' passed.
cryptomod_fips: Crypto FIPS self-test: 'CTR_DRBG' passed.
cryptomod_fips: Crypto FIPS self-test: 'KDF' passed.
cryptomod_fips: Crypto FIPS self-test: 'SHA1, SHA256, SHA512' passed.
cryptomod_fips: Crypto FIPS self-test: 'HMAC-SHA1, HMAC-SHA256, HMAC-SHA512' passed.
cryptomod_fips: Crypto FIPS self-test: 'PBKDF2' passed.
cryptomod_fips: Crypto FIPS self-test: 'AES-XTS 128, AES-XTS 256' passed.
cryptomod_fips: Crypto FIPS self-test: 'Self-integrity' passed.
9a

########## WARNING: AGGREGATES WILL BE DESTROYED ##########
This is a disruptive operation that applies to all the disks
that are attached and visible to this node.

Before proceeding further, make sure that:

The aggregates visible from this node do not contain
data that needs to be preserved.
This option (9a) has been executed or will be executed
on the HA partner node (and DR/DR-AUX partner nodes if
applicable), prior to reinitializing any system in the
HA-pair or MetroCluster configuration.
The HA partner node (and DR/DR-AUX partner nodes if
applicable) is currently waiting at the boot menu.
Do you want to abort this operation (yes/no)? no
----

. When the node restarts, press Ctrl-C when prompted to display the boot menu and then select the option for *Maintenance mode boot*.
. In Maintenance mode, manually assign drives for the local aggregates on the node:
+
`disk assign _disk-id_ -p 0 -s _local-node-sysid_`
+
The drives should be assigned symmetrically, so each node has an equal number of drives. The following steps are for a configuration with two storage shelves at each site.

 .. When configuring node_A_1, manually assign drives from slot 0 to 11 to pool0 of node A1 from site_A-shelf_1.
 .. When configuring node_A_2, manually assign drives from slot 12 to 23 to pool0 of node A2 from site_A-shelf_1.
 .. When configuring node_B_1, manually assign drives from slot 0 to 11 to pool0 of node B1 from site_B-shelf_1.
 .. When configuring node_B_2, manually assign drives from slot 12 to 23 to pool0 of node B2 from site_B-shelf_1.

. Exit Maintenance mode:
+
`halt`
. Display the boot menu:
+
`boot_ontap menu`
. Repeat these steps on the other nodes in the MetroCluster IP configuration.
. Select Option *4* from the boot menu on both nodes and let the system boot.
. Proceed to link:task_sw_config_setup_ontap.html[Setting up ONTAP].

== Manually assigning drives for pool 0 (ONTAP 9.3)

If you have at least two disk shelves for each node, you use ONTAP's auto-assignment functionality to automatically assign the local (pool 0) disks.

.About this task

While the node is in Maintenance mode, you must first assign a single disk on the appropriate shelves to pool 0. ONTAP then automatically assigns the rest of the disks on the shelf to the same pool. This task is not required on systems received from the factory, which have pool 0 to contain the pre-configured root aggregate.

This procedure applies to configurations running ONTAP 9.3.

This procedure is not required if you received your MetroCluster configuration from the factory. Nodes from the factory are configured with pool 0 disks and root aggregates.

This procedure can be used only if you have at least two disk shelves for each node, which allows shelf-level autoassignment of disks. If you cannot use shelf-level autoassignment, you must manually assign your local disks so that each node has a local pool of disks (pool 0).

These steps must be performed in Maintenance mode.

Examples in this section assume the following disk shelves:

* node_A_1 owns disks on:
 ** site_A-shelf_1 (local)
 ** site_B-shelf_2 (remote)
* node_A_2 is connected to:
 ** site_A-shelf_3 (local)
 ** site_B-shelf_4 (remote)
* node_B_1 is connected to:
 ** site_B-shelf_1 (local)
 ** site_A-shelf_2 (remote)
* node_B_2 is connected to:
 ** site_B-shelf_3 (local)
 ** site_A-shelf_4 (remote)

.Steps

. Manually assign a single disk for root aggregate on each node:
+
`disk assign _disk-id_ -p 0 -s _local-node-sysid_`
+
The manual assignment of these disks allows the ONTAP autoassignment feature to assign the rest of the disks on each shelf.

 .. On node_A_1, manually assign one disk from local site_A-shelf_1 to pool 0.
 .. On node_A_2, manually assign one disk from local site_A-shelf_3 to pool 0.
 .. On node_B_1, manually assign one disk from local site_B-shelf_1 to pool 0.
 .. On node_B_2, manually assign one disk from local site_B-shelf_3 to pool 0.

. Boot each node at site A, using option 4 on the boot menu:
+
You should complete this step on a node before proceeding to the next node.

.. Exit Maintenance mode:
+
`halt`
.. Display the boot menu:
+
`boot_ontap menu`
.. Select option 4 from the boot menu and proceed.

. Boot each node at site B, using option 4 on the boot menu:
+
You should complete this step on a node before proceeding to the next node.

.. Exit Maintenance mode:
+
`halt`
.. Display the boot menu:
+
`boot_ontap menu`
.. Select option 4 from the boot menu and proceed.

// 2022-NOV-22 GitHub issue 228
