---
permalink: install-ip/task_changing_mediator_username.html
sidebar: sidebar
keywords: mediator, username, change
summary: After you have installed ONTAP Mediator service, you might want to change the password. You can change the password in two ways.
---

= Changing the ONTAP Mediator user name
:icons: font
:imagesdir: ../media/

[.lead]
After you have installed ONTAP Mediator service, you might want to change the user name. You can change the password in two ways.

*About this task*

This task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example: /usr/local/bin/mediator_username

*Procedure*

Change the username by choosing one of the following options:

* Run the command mediator_change_user and respond to the prompts as shown in the following example:
+
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#

* Run the following command: MEDIATOR_USERNAME=mediator MEDIATOR_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin mediator_change_user as shown in the following example:
+
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
