---
permalink: install-ip/task_sw_config_gather_info.html
sidebar: sidebar
keywords: metrocluster, configuration, gather information
summary: You need to gather the required IP addresses for the controller modules before you begin the configuration process.
---
= Gathering required information

[.lead]
You need to gather the required IP addresses for the controller modules before you begin the configuration process.

link:../media/metrocluster_ip_setup_worksheet_site-a.csv[MetroCluster IP setup worksheet, site_A]

== IP network information worksheet for site A

[.lead]
You must obtain IP addresses and other network information for the first MetroCluster site (site A) from your network administrator before you configure the system.

=== Site A switch information

When you cable the system, you need a host name and management IP address for each cluster switch.

[options="header"]
|===
| Cluster switch| Host name| IP address| Network mask| Default gateway
a|
Interconnect 1
a|

a|

a|

a|

a|
Interconnect 2
a|

a|

a|

a|

a|
Management 1
a|

a|

a|

a|

a|
Management 2
a|

a|

a|

a|

|===

=== Site A cluster creation information

When you first create the cluster, you need the following information:

[options="header"]
|===
| Type of information| Your values
a|
Cluster name

Example used in this guide: site_A
a|

a|
DNS domain
a|

a|
DNS name servers
a|

a|
Location
a|

a|
Administrator password
a|

|===

=== Site A node information

For each node in the cluster, you need a management IP address, a network mask, and a default gateway.

[options="header"]
|===
| Node| Port| IP address| Network mask| Default gateway
a|
Node 1 Example used in this guide: controller_A_1

a|

a|

a|

a|

a|
Node 2Example used in this guide: controller_A_2

a|

a|

a|

a|

|===

=== Site A LIFs and ports for MetroCluster IP back-end connectivity

For each node in the cluster, you need the IP addresses of two MetroCluster IP LIFs, including a network mask and a default gateway. The MetroCluster IP LIFs are used for MetroCluster IP back-end connectivity.

xref:concept_prepare_for_the_mcc_installation.html#considerations-for-metrocluster-ip-configuration[Considerations for MetroCluster IP configuration]

[options="header"]
|===
| Node| Port| IP address of MetroCluster IP LIF| Network mask| Default gateway
a|
Node 1 MetroCluster IP LIF 1
a|
e5a
a|

a|

a|

a|
Node 1 MetroCluster IP LIF 2
a|
e5b
a|

a|

a|

a|
Node 2 MetroCluster IP LIF 1
a|
e5a
a|

a|

a|

a|
Node 2 MetroCluster IP LIF 2
a|
e5b
a|

a|

a|

|===

=== Site A LIFs and ports for cluster peering

For each node in the cluster, you need the IP addresses of two intercluster LIFs, including a network mask and a default gateway. The intercluster LIFs are used to peer the clusters.

[options="header"]
|===
| Node| Port| IP address of intercluster LIF| Network mask| Default gateway
a|
Node 1 IC LIF 1
a|

a|

a|

a|

a|
Node 1 IC LIF 2
a|

a|

a|

a|

a|
Node 2 IC LIF 1
a|

a|

a|

a|

a|
Node 2 IC LIF 2
a|

a|

a|

a|

|===

=== Site A time server information

You must synchronize the time, which requires one or more NTP time servers.

[options="header"]
|===
| Node| Host name| IP address| Network mask| Default gateway
a|
NTP server 1
a|

a|

a|

a|

a|
NTP server 2
a|

a|

a|

a|

|===

=== Site A AutoSupport information

You must configure AutoSupport on each node, which requires the following information:

[options="header"]
|===
2+| Type of information| Your values
a|
From email address
a|

a|

a|
Mail hosts
a|
IP addresses or names
a|

.2+a|
Transport protocol
a|
HTTP, HTTPS, or SMTP
a|

a|
Proxy server
a|

.3+a|
Recipient email addresses or distribution lists
a|
Full-length messages
a|

a|
Concise messages
a|

a|
Partners
a|

|===

=== Site A SP information

You must enable access to the Service Processor (SP) of each node for troubleshooting and maintenance, which requires the following network information for each node:

[options="header"]
|===
| Node| IP address| Network mask| Default gateway
a|
Node 1
a|

a|

a|

|===

== IP network information worksheet for site B

[.lead]
You must obtain IP addresses and other network information for the second MetroCluster site (site B) from your network administrator before you configure the system.

=== Site B switch information

When you cable the system, you need a host name and management IP address for each cluster switch.

[options="header"]
|===
| Cluster switch| Host name| IP address| Network mask| Default gateway
a|
Interconnect 1
a|

a|

a|

a|

a|
Interconnect 2
a|

a|

a|

a|

a|
Management 1
a|

a|

a|

a|

a|
Management 2
a|

a|

a|

a|

|===

=== Site B cluster creation information

When you first create the cluster, you need the following information:

[options="header"]
|===
| Type of information| Your values
a|
Cluster name

Example used in this guide: site_B
a|

a|
DNS domain
a|

a|
DNS name servers
a|

a|
Location
a|

a|
Administrator password
a|

|===

=== Site B node information

For each node in the cluster, you need a management IP address, a network mask, and a default gateway.

[options="header"]
|===
| Node| Port| IP address| Network mask| Default gateway
a|
Node 1 Example used in this guide: controller_B_1

a|

a|

a|

a|

a|
Node 2Example used in this guide: controller_B_2

a|

a|

a|

a|

|===

=== Site B LIFs and ports for MetroCluster IP back-end connectivity

For each node in the cluster, you need the IP addresses of two MetroCluster IP LIFs, including a network mask and a default gateway. The MetroCluster IP LIFs are used for MetroCluster IP back-end connectivity.

xref:concept_prepare_for_the_mcc_installation.html#considerations-for-metrocluster-ip-configuration[Considerations for MetroCluster IP configuration]

[options="header"]
|===
| Node| Port| IP address of MetroCluster IP LIF| Network mask| Default gateway
a|
Node 1 MetroCluster IP LIF 1
a|
e5a
a|

a|

a|

a|
Node 1 MetroCluster IP LIF 2
a|
e5b
a|

a|

a|

a|
Node 2 MetroCluster IP LIF 1
a|
e5a
a|

a|

a|

a|
Node 2 MetroCluster IP LIF 2
a|
e5b
a|

a|

a|

|===

=== Site B LIFs and ports for cluster peering

For each node in the cluster, you need the IP addresses of two intercluster LIFs, including a network mask and a default gateway. The intercluster LIFs are used to peer the clusters.

[options="header"]
|===
| Node| Port| IP address of intercluster LIF| Network mask| Default gateway
a|
Node 1 IC LIF 1
a|

a|

a|

a|

a|
Node 1 IC LIF 2
a|

a|

a|

a|

a|
Node 2 IC LIF 1
a|

a|

a|

a|

a|
Node 2 IC LIF 2
a|

a|

a|

a|

|===

=== Site B time server information

You must synchronize the time, which requires one or more NTP time servers.

[options="header"]
|===
| Node| Host name| IP address| Network mask| Default gateway
a|
NTP server 1
a|

a|

a|

a|

a|
NTP server 2
a|

a|

a|

a|

|===

=== Site B AutoSupport information

You must configure AutoSupport on each node, which requires the following information:

[options="header"]
|===
2+| Type of information| Your values
a|
From email address
a|

a|

a|
Mail hosts
a|
IP addresses or names
a|

.2+a|
Transport protocol
a|
HTTP, HTTPS, or SMTP
a|

a|
Proxy server
a|

.3+a|
Recipient email addresses or distribution lists
a|
Full-length messages
a|

a|
Concise messages
a|

a|
Partners
a|

|===

=== Site B SP information

You must enable access to the Service Processor (SP) of each node for troubleshooting and maintenance, which requires the following network information for each node:

[options="header"]
|===
| Node| IP address| Network mask| Default gateway
a|
Node 1 (controller_B_1)
a|

a|

a|

|===
