---
permalink: install-ip/task-synchronize-the-system-time-us-ntp.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, synchronize, system, time, ntp
summary: 'Each cluster needs its own Network Time Protocol \(NTP\) server to synchronize the time between the nodes and their clients.'
---
= Synchronize the system time using NTP in a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
Each cluster needs its own Network Time Protocol (NTP) server to synchronize the time between the nodes and their clients.

.About this task

* You cannot modify the time zone settings for a failed node or the partner node after a takeover occurs.
* Each cluster in the MetroCluster IP configuration should have its own separate NTP server or servers used by the nodes and IP switches at that MetroCluster site.
* If you are using the MetroCluster Tiebreaker or ONTAP Mediator, it should also have its own separate NTP server.
* This procedure shows how to configure the NTP after you have already set up the MetroCluster IP clusters. If you used System Manager to configure the clusters, you should already have configured the NTP servers as part of cluster setup. See link:../install-ip/set-up-mcc-site-system-manager.html[Set up a MetroCluster IP site] for details.

include::../_include/steps-edit-system-time.adoc[]

// 2025 Apr 08, ONTAPDOC-1706
// 2025-Feb-5, MCC-1706