---
permalink: install-ip/task_sw_config_configure_mediator.html
sidebar: sidebar
keywords: metrocluster ip, ontap, mediator, tiebreaker
summary: You can download and install on a third site either the MetroCluster Tiebreaker software, or, beginning with ONTAP 9.7, the ONTAP Mediator.
---
= Configuring the MetroCluster Tiebreaker or ONTAP Mediator software

[.lead]
You can download and install on a third site either the MetroCluster Tiebreaker software, or, beginning with ONTAP 9.7, the ONTAP Mediator.

.Before you begin

You must have a Linux host available that has network connectivity to both clusters in the MetroCluster configuration. The specific requirements are in the MetroCluster Tiebreaker or ONTAP Mediator documentation.

If you are connecting to an existing Tiebreaker or ONTAP Mediator instance, you need the username, password, and IP address of the Tiebreaker or Mediator service.

If you must install a new instance of the ONTAP Mediator, follow the directions to install and configure the software.

link:concept_mediator_requirements.html[Configuring the ONTAP Mediator service for unplanned automatic switchover]

If you must install a new instance of the Tiebreaker software, follow the link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html[directions to install and configure the software].

.About this task

You cannot use both the MetroCluster Tiebreaker software and the ONTAP Mediator with the same MetroCluster configuration.

link:../install-ip/concept_considerations_mediator.html[Considerations for using ONTAP Mediator or MetroCluster Tiebreaker]

.Step

. Configure the ONTAP Mediator service or the Tiebreaker software:
** If you are using an existing instance of the ONTAP Mediator, add the ONTAP Mediator service to ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host`
** If you are using the Tiebreaker software, refer to the link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html[Tiebreaker documentation].

// BURT 1448684, 03 FEB 2022
