---
permalink: install-ip/task_remove_unconfigure_mediator.html
sidebar: sidebar
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements
summary: You can remove ONTAP mediator from the MetroCluster IP configuration.
---

= Remove the ONTAP Mediator from a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]

You can unconfigure ONTAP Mediator from the MetroCluster IP configuration.

.Before you begin

You must have successfully installed and configured ONTAP Mediator on a network location that can be reached by both MetroCluster sites.

.Steps

. Unconfigure ONTAP Mediator by using the following command:
+
`metrocluster configuration-settings mediator remove`
+
You are prompted for the user name and password for the ONTAP Mediator admin user account.
+
NOTE: If the ONTAP Mediator is down, the `metrocluster configuration-settings mediator remove` command still prompts you to enter the user name and password for the ONTAP Mediator admin user account and removes ONTAP Mediator from the MetroCluster configuration.

.. Check if there are any broken disks by using the following command:
+
`disk show -broken`
+
*Example*
+
....
There are no entries matching your query.
....

. If you are using an ONTAP Mediator that uses HTTPS for communication, delete the CA certificates after you remove the ONTAP Mediator:

.. Display the installed CA certificates:
+
`security certificate show -common-name ONTAPMediatorCA`
.. Remove the installed root and intermediate certificates:
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <root_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`
+
`security certificate delete -vserver cluster-A -common-name ONTAPMediatorCA -cert-name <intermediate_certificate_name> -type server-ca -ca "ONTAP Mediator CA"`


. Confirm that ONTAP Mediator has been removed from the MetroCluster configuration by running the following command on both clusters:
+
.. `metrocluster configuration-settings mediator show`
+
*Example*
+
----
This table is currently empty.
----



// 2023 Nov 21, ONTAPDOC-1491
// BURT 1389268, 25 Feb 2022
// GH issue 183, 07 Nov 2022
