---
permalink: install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html
sidebar: sidebar
keywords: metrocluster, mediator, configure
summary: The ONTAP Mediator service must be configured on the ONTAP node for use in a MetroCluster IP configuration.
---

= Configure the ONTAP Mediator service from a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP Mediator service must be configured on the ONTAP node for use in a MetroCluster IP configuration.

.Before you begin

* The ONTAP Mediator must have been successfully installed on a network location that can be reached by both MetroCluster sites.
+
link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service^]
//adding link to new location 2022-03-31
* You must have the IP address of the host running the ONTAP Mediator service.
* You must have the username and password for the ONTAP Mediator service.
* All nodes of the MetroCluster IP configuration must be online.

CAUTION: Beginning with ONTAP 9.12.1, you can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover. Before you enable this feature, review link:concept-risks-limitations-automatic-switchover.html[Risks and limitations of using MetroCluster automatic forced switchover].

.About this task

* This task enables automatic unplanned switchover by default.
* This task can be performed on the ONTAP interface of any node in the MetroCluster IP configuration.
* A single installation of the ONTAP Mediator service can be configured with up to five MetroCluster IP configurations.

.Steps

. Add the ONTAP Mediator service to ONTAP:
+
`metrocluster configuration-settings mediator add -mediator-address _ip-address-of-mediator-host_`
+
NOTE: You will be prompted for the username and password for the Mediator admin user account.

. Verify that the automatic switchover feature in enabled:
+
`metrocluster show`
. Verify that the Mediator is now running.

.. Show the Mediator virtual disks:
+
`storage disk show -container-type mediator`
+
....
 cluster_A::> storage disk show -container-type mediator
                        Usable           Disk    Container   Container
 Disk                   Size Shelf Bay Type    Type        Name      Owner
 ---------------- ---------- ----- --- ------- ----------- --------- --------
 NET-1.5                   -     -   - VMDISK  mediator    -         node_A_2
 NET-1.6                   -     -   - VMDISK  mediator    -         node_B_1
 NET-1.7                   -     -   - VMDISK  mediator    -         node_B_2
 NET-1.8                   -     -   - VMDISK  mediator    -         node_A_1
....

.. Set the privilege mode to advanced:
+
`set advanced`
+
....
 cluster_A::> set advanced
....

.. Display the initiators labelled as mediator:
+
`storage iscsi-initiator show -label mediator`
+
....
 cluster_A::*> storage iscsi-initiator show -label mediator
   (storage iscsi-initiator show)
  +                                                                     Status
 Node Type Label    Target Portal      Target Name                      Admin/Op
 ---- ---- -------- ------------------ -------------------------------- --------
 node_A_1
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68- 00a098cbca9e:1 up/up
 node_A_2
      mailbox
           mediator 1.1.1.1       iqn.2012-05.local:mailbox.target.6616cd3f-9ef1-11e9-aada-00a098ccf5d8:a05e1ffb-9ef1-11e9-8f68-00a098cbca9e:1 up/up
....
.. Verify the state of the automatic unplanned switchover (AUSO) failure domain:
+
`metrocluster show`
+
NOTE: The following example output applies to ONTAP 9.13.1 and later. For ONTAP 9.12.1 and earlier, the AUSO failure domain state should be `auso-on-cluster-disaster`.
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-dr-group-disaster 
----

. If you want to configure MetroCluster automatic forced switchover, run the following command: `metrocluster modify -allow-auto-forced-switchover true`
+
Before you enable this feature, review link:concept-risks-limitations-automatic-switchover.html[Risks and limitations of using MetroCluster automatic forced switchover].
+
.Example
....
cluster_A::*> metrocluster modify -allow-auto-forced-switchover true
....

// 2023 Sep 11, GH issue 322
// BURT 1448684, 03 FEB 2022
