---
permalink: install-ip/task_install_and_cable_the_mcc_components.html
sidebar: sidebar
keywords:  ip, switch, configuring
summary: You must configure the IP switches to provide backend MetroCluster IP connectivity.
---
= Learn about configuring the MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the IP switches to provide backend MetroCluster IP connectivity. The procedure you follow depends on your switch vendor and whether you are configuring your switches as part of a fresh install of MetroCluster IP, or as part of another procedure.

== Fresh MetroCluster IP installation

If you are performing a fresh MetroCluster IP installation, you should use the following procedures, depending on your switch vendor:

* link:../install-ip/task_switch_config_broadcom.html[Configure Broadcom IP switches]
* link:../install-ip/task_switch_config_cisco.html[Configure Cisco IP switches]
* link:../install-ip/task_switch_config_nvidia.html[Configure NVIDIA IP switches]

== Switch replacement and RCF or firmware updates

As part of other MetroCluster IP procedures, such as a switch replacement or upgrade, you might need to update the switch firmware, reference configuration file (RCF), or both. In these scenarios, you must move the cluster LIFs before you configure the IP switches. The high-level steps for these scenarios are as follows:

NOTE: You must update the switches in the following order Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.

. link:../install-ip/switch-move-cluster-lifs.html[Move the cluster LIFs]

. After the cluster LIFs have moved to the partner switch, you can follow the standard configuration procedures according to your switch vendor:

* link:../install-ip/task_switch_config_broadcom.html[Configure Broadcom IP switches]
* link:../install-ip/task_switch_config_cisco.html[Configure Cisco IP switches]
* link:../install-ip/task_switch_config_nvidia.html[Configure NVIDIA IP switches]

.  After you have configured the switches in the first fabric (Switch_A_1, Switch_B_1), you must repeat the steps on the second fabric ( Switch_A_2, Switch_B_2), starting from link:../install-ip/switch-move-cluster-lifs.html[Move the cluster LIFs].




// 2024 May 02, ONTAPDOC-1895
// 2026 Aug 20, ONTAPDOC-2880
