---
permalink: install-ip/task_sw_config_verify_haconfig.html
sidebar: sidebar
keywords: metrocluster, ha-config, mccip, haconfig, verify, high-availability
summary: In a MetroCluster IP configuration that is not preconfigured at the factory, you must verify that the ha-config state of the controller and chassis components is set to mccip so that they boot up properly. For systems received from the factory, this value is preconfigured and you do not need to verify it.
---
= Verifying the ha-config state of components

[.lead]
In a MetroCluster IP configuration, you must verify that the ha-config state of the controller and chassis components is set to "`mccip`" so that they boot up properly. Although this value should be preconfigured on systems received from the factory, you should still verify the setting before proceeding.

CAUTION: If the HA state of the controller module and chassis is incorrect, you cannot configure the MetroCluster without reinitializing the node. You must correct the setting and then initialize the system by link:task_sw_config_restore_defaults.html[Restoring system defaults on a controller module]

.Before you begin

The system must be in Maintenance mode.

.Steps

. Display the HA state of the controller module and chassis:
+
`ha-config show`
+
The controller module and chassis should show the value "`mccip`".
+
Use the following table to determine the next steps depending on whether the HA state of the controller module and chassis is correctly set to "`mccip`".
+
[cols=2*,options="header"]
|===
| The settings are correct...
| The settings are incorrect...
| Proceed to link:task_sw_config_setup_ontap.html[Set up ONTAP] | Go to <<step_2_correct_setting, Step 2>> and continue the procedure to correct the settings. 
|===

. [[step_2_correct_setting]]If the displayed system state of the controller is not "`mccip`", set the HA state for the controller:
+
`ha-config modify controller mccip`
. If the displayed system state of the chassis is not "`mccip`", set the HA state for the chassis:
+
`ha-config modify chassis mccip`
. Repeat these steps on each node in the MetroCluster configuration.
. After you have corrected the HA state of the controller module and chassis, proceed to link:task_sw_config_restore_defaults.html[Restore system defaults on a controller module]


// 2024 Aug 20, GH issue 363
// BURT 1180776, 22 APR 2021
// BURT 1380267
// BURT 1381553
// BURT 1448684, 01 FEB 2022
