---
permalink: install-ip/task_rack_hw_components.html
sidebar: sidebar
keywords: metrocluster ip, rack hardware, components, racking
summary: If you have not received the equipment already installed in cabinets, you must rack the components.
---
= Racking the hardware components
:icons: font
:imagesdir: ../media/

[.lead]
If you have not received the equipment already installed in cabinets, you must rack the components.

This task must be performed on both MetroCluster sites.

. Plan out the positioning of the MetroCluster components.
+
The rack space depends on the platform model of the controller modules, the switch types, and the number of disk shelf stacks in your configuration.

. Properly ground yourself.
. Install the controller modules in the rack or cabinet.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html[AFF A320 systems: Installation and setup]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666[AFF A220/FAS2700 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668[AFF A800 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722[AFF A300 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769[FAS8200 Systems Installation and Setup Instructions]

. Install the IP switches in the rack or cabinet.
. Install the disk shelves, power them on, and then set the shelf IDs.
 ** You must power-cycle each disk shelf.
 ** Shelf IDs must be unique for each SAS disk shelf within each MetroCluster DR group (including both sites).
*Note:* Do not cable disk shelves intended to contain unmirrored aggregates at this time. You must wait to deploy shelves intended for unmirrored aggregates until after the MetroCluster configuration is complete and only deploy them after using the `metrocluster modify -enable-unmirrored-aggr-deployment true` command.
