---
permalink: install-ip/task_sw_config_verify_haconfig.html
sidebar: sidebar
keywords: metrocluster, ha-config, mccip, haconfig, verify, high-availability
summary: In a MetroCluster IP configuration that is not preconfigured at the factory, you must verify that the ha-config state of the controller and chassis components is set to mccip so that they boot up properly. For systems received from the factory, this value is preconfigured and you do not need to verify it.
---
= Verifying the ha-config state of components

[.lead]
In a MetroCluster IP configuration that is not preconfigured at the factory, you must verify that the ha-config state of the controller and chassis components is set to "`mccip`" so that they boot up properly. For systems received from the factory, this value is preconfigured and you do not need to verify it.

.Before you begin

The system must be in Maintenance mode.

.Steps

. Display the HA state of the controller module and chassis:
+
`ha-config show`
+
The controller module and chassis should show the value "`mccip`".

. If the displayed system state of the controller is not "`mccip`", set the HA state for the controller:
+
`ha-config modify controller mccip`
. If the displayed system state of the chassis is not "`mccip`", set the HA state for the chassis:
+
`ha-config modify chassis mccip`
. Repeat these steps on each node in the MetroCluster configuration.



// BURT 1180776, 22 APR 2021
// BURT 1380267
// BURT 1381553
// BURT 1448684, 01 FEB 2022
