---
permalink: install-ip/task_remove_unconfigure_mediator.html
sidebar: sidebar
keywords: ontap, mediator, assist, remove, unconfigure, requirements, mediator requirements
summary: You can remove ONTAP mediator from the MetroCluster IP configuration.
---

= Remove the ONTAP Mediator from a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]

You can unconfigure ONTAP Mediator from the MetroCluster IP configuration.

.Before you begin

You must have successfully installed and configured ONTAP Mediator on a network location that can be reached by both MetroCluster sites.

.Steps

. Unconfigure ONTAP Mediator by using the following command:
+
`metrocluster configuration-settings mediator remove`
+
You are prompted for the user name and password for the ONTAP Mediator admin user account.
+
NOTE: If the ONTAP Mediator is down, the `metrocluster configuration-settings mediator remove` command still prompts you to enter the user name and password for the ONTAP Mediator admin user account and removes ONTAP Mediator from the MetroCluster configuration.

.. Check if there are any broken disks by using the following command:
+
`disk show -broken`
+
*Example*
+
....
There are no entries matching your query.
....

. Confirm that ONTAP Mediator has been removed from the MetroCluster configuration by running the following commands on both clusters:
+
.. `metrocluster configuration-settings mediator show`
+
*Example*
+
----
This table is currently empty.
----

.. `storage iscsi-initiator show -label mediator`
+
*Example*
+
----
There are no entries matching your query.
----

// 2023 Nov 21, ONTAPDOC-1491
// BURT 1389268, 25 Feb 2022
// GH issue 183, 07 Nov 2022
