---
permalink: install-ip/task_sw_config_verify_switchover.html
sidebar: sidebar
keywords: metrocluster, switchover, verify
summary: You should verify the switchover, healing, and switchback operations of the MetroCluster configuration.
---
= Verifying switchover, healing, and switchback

[.lead]
You should verify the switchover, healing, and switchback operations of the MetroCluster configuration.

. Use the procedures for negotiated switchover, healing, and switchback that are mentioned in the _MetroCluster Management and Disaster Recovery Guide_.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/home.html[MetroCluster management and disaster recovery]

== Configuring the MetroCluster Tiebreaker or ONTAP Mediator software

[.lead]
You can download and install on a third site either the MetroCluster Tiebreaker software, or, starting with ONTAP 9.7, the ONTAP Mediator.

You must have a Linux host available that has network connectivity to both clusters in the MetroCluster configuration. The specific requirements are in the MetroCluster Tiebreaker or ONTAP Mediator documentation.

If you are connecting to an existing Tiebreaker or ONTAP Mediator instance, you need the username, password, and IP address of the Tiebreaker or Mediator service.

If you must install a new instance of the ONTAP Mediator, follow the directions to install and configure the software.

xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html[Configuring the ONTAP Mediator service for unplanned automatic switchover]

If you must install a new instance of the Tiebreaker software, follow the directions to install and configure the software.

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[MetroCluster Tiebreaker Software Installation and Configuration Guide]

You cannot use both the MetroCluster Tiebreaker software and the ONTAP Mediator with the same MetroCluster configuration.

xref:concept_prepare_for_the_mcc_installation.html#considerations-for-using-ontap-mediator-or-metrocluster-tiebreaker[Considerations for using ONTAP Mediator or MetroCluster Tiebreaker]

. Configure the ONTAP Mediator service or the Tiebreaker software:
 ** If you are using an existing instance of the ONTAP Mediator, add the ONTAP Mediator service to ONTAP using the following command:``metrocluster configuration-settings mediator add -mediator-address ip-address-of-mediator-host``
 ** If you are using the Tiebreaker software, refer to the Tiebreaker documentation.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[MetroCluster Tiebreaker Software Installation and Configuration Guide]

== Protecting configuration backup files

[.lead]
You can provide additional protection for the cluster configuration backup files by specifying a remote URL (either HTTP or FTP) where the configuration backup files will be uploaded in addition to the default locations in the local cluster.

. Set the URL of the remote destination for the configuration backup files: `system configuration backup settings modify URL-of-destination`
+
The System Administration Guide contains additional information under the section _Managing configuration backups_.

*Related information*

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html[System administration]

//BURT 1380267
