---
permalink: install-ip/task_sw_config_verify_haconfig.html
sidebar: sidebar
keywords: metrocluster, ha-config, mccip, haconfig, verify, high-availability
summary: In a MetroCluster IP configuration that is not preconfigured at the factory, you must verify that the ha-config state of the controller and chassis components is set to mccip so that they boot up properly. For systems received from the factory, this value is preconfigured and you do not need to verify it.
---
= Verifying the ha-config state of components

[.lead]
In a MetroCluster IP configuration, you must verify that the ha-config state of the controller and chassis components is set to "`mccip`" so that they boot up properly. Although this value should be preconfigured on systems received from the factory, you should still verify the setting before proceeding.

CAUTION: If the HA state of the controller module and chassis is incorrect, you cannot configure the MetroCluster without reinitializing the node. You must correct the setting using this procedure and then initialize the system by link:task_sw_config_restore_defaults.html[Restoring system defaults on a controller module]

.Before you begin

The system must be in Maintenance mode.

include::../_include/task-verify-haconfig-ip-fc.adoc[]



// 2024 Aug 20, GH issue 363
// BURT 1180776, 22 APR 2021
// BURT 1380267
// BURT 1381553
// BURT 1448684, 01 FEB 2022
