---
permalink: install-ip/task_sw_config_setup_ontap.html
sidebar: sidebar
keywords: metrocluster, ontap, setup
summary: After you boot each node, you are prompted to perform basic node and cluster configuration. After configuring the cluster, you return to the ONTAP CLI to create aggregates and create the MetroCluster configuration.
---
= Setting up ONTAP

[.lead]
After you boot each node, you are prompted to perform basic node and cluster configuration. After configuring the cluster, you return to the ONTAP CLI to create aggregates and create the MetroCluster configuration.

.Before you begin

* You must have cabled the MetroCluster configuration.

If you need to netboot the new controllers, see link:../upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html#netboot-the-new-controllers[Netboot the new controller modules].

.About this task

This task must be performed on both clusters in the MetroCluster configuration.

.Steps

. Power up each node at the local site if you have not already done so and let them all boot completely.
+
If the system is in Maintenance mode, you need to issue the halt command to exit Maintenance mode, and then issue the `boot_ontap` command to boot the system and get to cluster setup.

. On the first node in each cluster, proceed through the prompts to configure the cluster.
.. Enable the AutoSupport tool by following the directions provided by the system.
+
The output should be similar to the following:
+
----
Welcome to the cluster setup wizard.

    You can enter the following commands at any time:
    "help" or "?" - if you want to have a question clarified,
    "back" - if you want to change previously answered questions, and
    "exit" or "quit" - if you want to quit the cluster setup wizard.
    Any changes you made before quitting will be saved.

    You can return to cluster setup at any time by typing "cluster setup".
    To accept a default or omit a question, do not enter a value.

    This system will send event messages and periodic reports to NetApp Technical
    Support. To disable this feature, enter
    autosupport modify -support disable
    within 24 hours.

    Enabling AutoSupport can significantly speed problem determination and
    resolution should a problem occur on your system.
    For further information on AutoSupport, see:
    http://support.netapp.com/autosupport/

    Type yes to confirm and continue {yes}: yes
.
.
.
----

.. Configure the node management interface by responding to the prompts.
+
The prompts are similar to the following:
+
----
Enter the node management interface port [e0M]:
Enter the node management interface IP address: 172.17.8.229
Enter the node management interface netmask: 255.255.254.0
Enter the node management interface default gateway: 172.17.8.1
A node management interface on port e0M with IP address 172.17.8.229 has been created.
----

.. Create the cluster by responding to the prompts.
+
The prompts are similar to the following:
+
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
create


Do you intend for this node to be used as a single node cluster? {yes, no} [no]:
no

Existing cluster interface configuration found:

Port MTU IP Netmask
e0a 1500 169.254.18.124 255.255.0.0
e1a 1500 169.254.184.44 255.255.0.0

Do you want to use this configuration? {yes, no} [yes]: no

System Defaults:
Private cluster network ports [e0a,e1a].
Cluster port MTU values will be set to 9000.
Cluster interface IP addresses will be automatically generated.

Do you want to use these defaults? {yes, no} [yes]: no

Enter the cluster administrator's (username "admin") password:

Retype the password:


Step 1 of 5: Create a Cluster
You can type "back", "exit", or "help" at any question.

List the private cluster network ports [e0a,e1a]:
Enter the cluster ports' MTU size [9000]:
Enter the cluster network netmask [255.255.0.0]: 255.255.254.0
Enter the cluster interface IP address for port e0a: 172.17.10.228
Enter the cluster interface IP address for port e1a: 172.17.10.229
Enter the cluster name: cluster_A

Creating cluster cluster_A

Starting cluster support services ...

Cluster cluster_A has been created.
----

.. Add licenses, set up a Cluster Administration SVM, and enter DNS information by responding to the prompts.
+
The prompts are similar to the following:
+
----
Step 2 of 5: Add Feature License Keys
You can type "back", "exit", or "help" at any question.

Enter an additional license key []:


Step 3 of 5: Set Up a Vserver for Cluster Administration
You can type "back", "exit", or "help" at any question.


Enter the cluster management interface port [e3a]:
Enter the cluster management interface IP address: 172.17.12.153
Enter the cluster management interface netmask: 255.255.252.0
Enter the cluster management interface default gateway: 172.17.12.1

A cluster management interface on port e3a with IP address 172.17.12.153 has been created. You can use this address to connect to and manage the cluster.

Enter the DNS domain names: lab.netapp.com
Enter the name server IP addresses: 172.19.2.30
DNS lookup for the admin Vserver will use the lab.netapp.com domain.

Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: svl
----

.. Enable storage failover and set up the node by responding to the prompts.
+
The prompts are similar to the following:
+
----
Step 4 of 5: Configure Storage Failover (SFO)
You can type "back", "exit", or "help" at any question.


SFO will be enabled when the partner joins the cluster.


Step 5 of 5: Set Up the Node
You can type "back", "exit", or "help" at any question.

Where is the controller located []: site_A
----

.. Complete the configuration of the node, but do not create data aggregates.
+
You can use ONTAP System Manager, pointing your web browser to the cluster management IP address (\https://172.17.12.153).
+
https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/index.html[Cluster management using System Manager (ONTAP 9.7 and earlier)^]
+
https://docs.netapp.com/us-en/ontap/index.html#about-ontap-system-manager[ONTAP System Manager (Version 9.7 and later)]

.. Configure the Service Processor (SP):
+
link:https://docs.netapp.com/us-en/ontap/system-admin/sp-bmc-network-config-concept.html[Configure the SP/BMC network^]
+
link:https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_service_processors.html[Use a Service Processor with System Manager - ONTAP 9.7 and earlier^]

. Boot the next controller and join it to the cluster, following the prompts.
. Confirm that nodes are configured in high-availability mode:
+
`storage failover show -fields mode`
+
If not, you must configure HA mode on each node, and then reboot the nodes:
+
`storage failover modify -mode ha -node localhost`
+
====

NOTE: The expected configuration state of HA and storage failover is as follows:

** HA mode is configured but storage failover is not enabled.
** HA takeover capability is disabled.
** HA  interfaces are offline.
** HA mode, storage failover, and interfaces are configured later in the process.
====

. Confirm that you have four ports configured as cluster interconnects:
+
`network port show`
+
The MetroCluster IP interfaces are not configured at this time and do not appear in the command output.
+
The following example shows two cluster ports on node_A_1:
+
----
cluster_A::*> network port show -role cluster



Node: node_A_1

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


Node: node_A_2

                                                                       Ignore

                                                  Speed(Mbps) Health   Health

Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status

--------- ------------ ---------------- ---- ---- ----------- -------- ------

e4a       Cluster      Cluster          up   9000  auto/40000 healthy  false

e4e       Cluster      Cluster          up   9000  auto/40000 healthy  false


4 entries were displayed.
----

. Repeat these steps on the partner cluster.

.What to do next

Return to the ONTAP command-line interface and complete the MetroCluster configuration by performing the tasks that follow.

// 2024 Mar 28, GH 221
// GitHub issue 138, July 4th 2022
