---
permalink: install-ip/task_uninstall_mediator.html
sidebar: sidebar
keywords: mediator, uninstall
summary: If necessary, you can remove the ONTAP Mediator service.
---
= Changing the ONTAP Mediator user name
:icons: font
:imagesdir: ../media/

[.lead]
If necessary, you can remove the ONTAP Mediator service.

*Before you begin*

The Mediator must be disconnected from ONTAP before you remove the Mediator service.

*About this task*

This task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example:
/usr/local/bin/uninstall_ontap_mediator

*Procedure*

Uninstall the ONTAP Mediator service as shown in the following example using the command: uninstall_ontap_mediator

 [root@mediator-host ~]# uninstall_ontap_mediator

 ONTAP Mediator: Self Extracting Uninstaller

 + Removing ONTAP Mediator. (Log: /tmp/ontap_mediator.GmRGdA/uninstall_ontap_mediator/remove.log)
 + Remove successful.
 [root@mediator-host ~]#
