---
permalink: install-ip/task_cable_other_connections.html
sidebar: sidebar
keywords: cabling, cable, component, peering, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure
summary: You must cable the controller module ports used for cluster peering, management and data connectivity.
---
= Cabling the controller data, management, and peering ports
:icons: font
:imagesdir: ../media/

[[.lead]
You must cable the controller module ports used for cluster peering, management and data connectivity.

This task must be performed on each controller module in the MetroCluster configuration.

At least two ports on each controller module should be used for cluster peering.

The recommended minimum bandwidth for the ports and network connectivity is 1 GbE.

. Identify and cable at least two ports for cluster peering and verify they have network connectivity with the partner cluster.
+
Cluster peering can be done on dedicated ports or on data ports. Using dedicated ports provides higher throughput for the cluster peering traffic.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[Cluster and SVM peering express configuration]

. Cable the controller's management and data ports to the management and data networks at the local site.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html[AFF A320 systems: Installation and setup]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666[AFF A220/FAS2700 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668[AFF A800 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722[AFF A300 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769[FAS8200 Systems Installation and Setup Instructions]
