---
permalink: install-ip/task_cable_other_connections.html
sidebar: sidebar
keywords: cabling, cable, component, peering, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure
summary: You must cable the controller module ports used for cluster peering, management and data connectivity.
---
= Cabling the controller peering, data, and management ports
:icons: font
:imagesdir: ../media/

[.lead]
You must cable the controller module ports used for cluster peering, management and data connectivity.

This task must be performed on each controller module in the MetroCluster configuration.

At least two ports on each controller module should be used for cluster peering.

The recommended minimum bandwidth for the ports and network connectivity is 1 GbE.

. Identify and cable at least two ports for cluster peering and verify they have network connectivity with the partner cluster.
+
Cluster peering can be done on dedicated ports or on data ports. Using dedicated ports provides higher throughput for the cluster peering traffic.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[Cluster and SVM peering express configuration]

. Cable the controller's management and data ports to the management and data networks at the local site.
+
Use the installation instructions for your platform at the https://docs.netapp.com/us-en/ontap-systems/[ONTAP Hardware Systems Documentation^].
+
NOTE: MetroCluster IP systems do not have dedicated shared cluster high-availability (HA) ports. When using _ONTAP Hardware Systems Documentation_ to install your platform, you should not follow the instructions to cable the cluster and HA ports.

// 2024 MAY 25, ONTAPDOC-1754
// 2024 MAR 1, ontap-metrocluster/issues/217
// ontap-metrocluster/issues/75
