---
permalink: install-ip/task_install_configure_mediator.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, install, configure
summary: To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.
---
= Installing or upgrading the ONTAP Mediator service
:icons: font
:imagesdir: ../media/

[.lead]

To install the ONTAP Mediator service, you must ensure all prerequisites are met, get the installation package and run the installer on the host.

== Before you begin

You must meet the following prerequisites.

[options="header"]
|===
| Mediator version| Supported Linux versions
a|
1.3
a|
Red Hat Enterprise Linux or CentOS 7.6, 7.7, 7.8, 8.0, 8.1, 8.2, 8.3

a|
1.2
a|
Red Hat Enterprise Linux or CentOS 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2
|===

* 64-bit physical installation or virtual machine
 ** 8 GB RAM
 ** User: Root access
The best practices for installing Red Hat Enterprise Linux or CentOS and the associated repositories on your system are listed below. Systems installed or configured differently might require additional steps.
 ** You must install Red Hat Enterprise Linux or CentOS according to Red Hat best practices.
 ** While installing the ONTAP Mediator service on Red Hat Enterprise Linux or CentOS, the system must have access to the appropriate repository so that the installation program can access and install all the required software dependencies.
 ** For the yum installer to find dependent software in the Red Hat Enterprise Linux repositories, you must have registered the system during the Red Hat Enterprise Linux installation or afterwards by using a valid Red Hat subscription.
+
See the Red Hat documentation for information about the Red Hat Subscription Manager.
* The following ports must be unused and available for the Mediator:
 ** 31784
 ** 3260
* If using a third-party firewall: refer to xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#firewall-requirements-for-ontap-mediator[Firewall requirements for ONTAP Mediator]
* If the Linux host is in a location without access to the internet, you can either install the packages manually or you must ensure that the required packages are available in a local repository.
+
You can use the following link for information about setting up a repository.
+
If you are using Link Aggregation Control Protocol (LACP) in a Linux environment, you must correctly configure the kernel and make sure the sysctl net.ipv4.conf.all.arp_ignore is set to `2`.
+
The following packages are required by the ONTAP Mediator service:
+
[options="header"]
|===
| All RHEL/CentOS versions| Additional packages for RHEL/CentOS 7.x| Additional packages for RHEL/CentOS 8.x
a|

 ** openssl
 ** openssl-devel
 ** kernel-devel
 ** gcc
 ** libselinux-utils
 ** make
 ** redhat-lsb-core
 ** patch
 ** bzip2
 ** python36
 ** python36-devel
 ** perl-Data-Dumper
 ** perl-ExtUtils-MakeMaker
 ** python3-pip

a|

 ** policycoreutils-python
 ** python36-pip

a|

 ** elfutils-libelf-devel
 ** policycoreutils-python-utils

+
|===

* If signature verification is configured, it must be disabled. This can be done in one of two ways:
 ** If the UEFI SecureBoot mechanism is configured, disable it.
 ** Disable the signature verification mechanism by updating and regenerating the grub.cfg file:
  ... Open the /etc/default/grub file.
  ... Add the string module.sig_enforce=0 to the end of the GRUB_CMDLINE_LINUX statement.
  ... Regenerate the grub.cfg file to implement the change: `update-bootloader || update-grub || grub2-mkconfig -o /boot/grub2/grub.cfg`
  ... Reboot the host.

The Mediator installation package is a self-extracting compressed tar file that includes:

* An RPM file containing all dependencies that cannot be obtained from the supported release's repository.
* An install script.

A valid SSL certification is recommended, as documented in this procedure.

This procedure is used for an installation or an upgrade of an existing installation.

xref:concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html#guidelines-for-upgrading-the-ontap-mediator-in-a-metrocluster-configuration[Guidelines for upgrading the ONTAP Mediator in a MetroCluster configuration]

== Enable access to the repositories

[options="header"]
|===
| If your operating system is...| You must provide access to these repositories...
a|
RHEL 7.x
a|
rhel-7-server-optional-rpms
a|
CentOS 7.x
a|
C7.6.1810 - Base repository
a|
RHEL 8.x
a|

 ** rhel-8-for-x86_64-baseos-rpms
 ** rhel-8-for-x86_64-appstream-rpms

a|
CentOS 8.0
a|
kernel-devel
|===

Enable access to the repositories listed above so Mediator can access the required packages during the installation process. Use the procedure below for your operating system.

If your operating system is *RHEL 7.x*:

. Subscribe to the required repository: `subscription-manager repos --enable rhel-7-server-optional-rpms`
+
The following example shows the execution of this command:
+
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. Run the yum repolist command.
+
The following example shows the execution of this command. The rhel-7-server-optional-rpms repository should appear in the list.
+
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----

If your operating system is *RHEL 8.x*:

. Subscribe to the required repository: `subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms``subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms`
+
The following example shows the execution of this command:
+
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----

. Run the yum repolist command.
+
The newly subscribed repositories should appear in the list.

If your operating system is *CentOS 7.x*:

. Add the C7.6.1810 - Base repository. The C7.6.1810 - Base vault repository contains the kernel-devel package needed for ONTAP Mediator.

. Add the following lines to /etc/yum.repos.d/CentOS-Vault.repo.
+
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$
basearch/gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----

. Run the yum repolist command.
+
The following example shows the execution of this command. The CentOS-7.6.1810 - Base repository should appear in the list.
+
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----

If your operating system is *CentOS 8.0.1905 or later builds*:

Because the latest version of the 8.0 (CentOS 8.0.1905) core resides in the CentOS Vault, you must provide access to the matching kernel-devel package to compile the needed kernel module.      Issue the following command to directly install the kernel-devel package: rpm -i http://vault.centos.org/8.0.1905/BaseOS/x86_64/os/Packages/kernel-devel-$(uname -r).rpm

If the system displays an error indicating that the package is already installed, remove the package and try again:

. Remove the kernel-devel package: `yum remove kernel-devel`
. Repeat the rpm command shown above.


== Download the Mediator installation package

. Download the Mediator installation package from the ONTAP Mediator page.
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab[ONTAP Mediator download page]

. Confirm that the Mediator installation package is in the target directory: `ls`
+
----
[root@mediator-host ~]#ls
./ontap-mediator_1.3
----
+
If you are at a location without access to the internet, you must ensure that the installer has access to the required packages.

. If necessary, move the Mediator installation package from the download directory to the installation directory on the Linux Mediator host.

== Install the ONTAP Mediator installation package

. Install the Mediator installation package and respond to the prompts as required: `./ontap-mediator_1.3`
+
The installation process proceeds to create the required accounts and install required packages. If you have a previous version of Mediator installed on the host, you will be prompted to confirm that you want to upgrade.

=== Example of a fresh ONTAP Mediator installation

The following example shows a fresh installation of the Mediator service:

----
[root@red-hat-enterprise-linux ~]# ./ontap-mediator_1.3
ONTAP Mediator: Self Extracting Installer


ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).

Would you like to use the default account names: netapp + mediatoradmin? (Y(es)/n(o)): y



Enter ONTAP Mediator system service account (mediatoradmin) password:

Re-Enter ONTAP Mediator system service account (mediatoradmin) password:


Checking for default Linux firewall

Linux firewall is running. Open ports 31784 and 3260? y(es)/n(o): y
success
success

###############################################################

Preparing for installation of ONTAP Mediator packages.

Do you wish to continue? y(es)/n(o): y

+ Installing required packages.

Loaded plugins: product-id, search-disabled-repos, subscription-manager
epel/x86_64/metalink                                                                                                                                                              |  17 kB  00:00:00
epel-extra                                                                                                                                                                        | 4.9 kB  00:00:00
ius                                                                                                                                                                               | 1.3 kB  00:00:00
rhel-7-server-rpms                                                                                                                                                                | 3.5 kB  00:00:00
(1/3): ius/x86_64/primary                                                                                                                                                         | 129 kB  00:00:00
(2/3): epel-extra/group_gz                                                                                                                                                        |  88 kB  00:00:01
(3/3): epel-extra/primary_db                                                                                                                                                      | 6.7 MB  00:00:06
ius                                                                                                                                                                                              538/538
Package 1:make-3.82-23.el7.x86_64 already installed and latest version
                            .
                            .
                            .
==============================================================================================================

 Preparing for installation of ONTAP Mediator packages.

 Do you wish to continue? y(es)/n(o): y

 + Installing required packages.

 Loaded plugins: product-id, search-disabled-repos, subscription-manager
 epel/x86_64/metalink                                                                                                                                                              |  17 kB  00:00:00
 epel-extra                                                                                                                                                                        | 4.9 kB  00:00:00
 ius                                                                                                                                                                               | 1.3 kB  00:00:00
 rhel-7-server-rpms                                                                                                                                                                | 3.5 kB  00:00:00
 (1/3): ius/x86_64/primary                                                                                                                                                         | 129 kB  00:00:00
 (2/3): epel-extra/group_gz                                                                                                                                                        |  88 kB  00:00:01
 (3/3): epel-extra/primary_db                                                                                                                                                      | 6.7 MB  00:00:06
 ius                                                                                                                                                                                              538/538
 Package 1:make-3.82-23.el7.x86_64 already installed and latest version
                             .
                             .
                             .
                             .

 =======================================================================
 Package                                                   Arch                                 Version                                             Repository                                       Size
 ============================================================================
 Installing:
  bzip2                                                     x86_64                              1.0.6-13.el7                                        rhel-7-server-rpms                               52 k
  gcc                                                       x86_64                              4.8.5-36.el7_6.2                                    rhel-7-server-rpms                               16 M
  kernel-devel                                              x86_64                              3.10.0-957.el7                                      rhel-7-server-rpms                               17 M
  openssl-devel                                             x86_64                              1:1.0.2k-16.el7_6.1                                 rhel-7-server-rpms                              1.5 M
  patch                                                     x86_64                              2.7.1-10.el7_5                                      rhel-7-server-rpms                              110 k
  perl-Compress-Raw-Zlib                                    x86_64                              1:2.061-4.el7                                       rhel-7-server-rpms                               57 k
  perl-Digest-MD5                                           x86_64                              2.52-3.el7                                          rhel-7-server-rpms                               30 k
  perl-Digest-SHA                                           x86_64                              1:5.85-4.el7                                        rhel-7-server-rpms                               58 k
  perl-ExtUtils-CBuilder                                    noarch                              1:0.28.2.6-294.el7_6                                rhel-7-server-rpms                               68 k
  perl-ExtUtils-MakeMaker                                   noarch                              6.68-3.el7                                          rhel-7-server-rpms                              275 k
  perl-JSON-PP                                              noarch                              2.27202-2.el7                                       rhel-7-server-rpms                               55 k
  python36                                                  x86_64                              3.6.8-2.el7.ius                                     ius                                              60 k
  python36-devel                                            x86_64                              3.6.8-2.el7.ius                                     ius                                             206 k
  python36-pip                                              noarch                              9.0.1-2.el7.ius                                     ius                                             1.7 M
  redhat-lsb-core                                           x86_64                              4.1-27.el7                                          rhel-7-server-rpms                               37 k

 Updating:
  openssl                                                   x86_64                              1:1.0.2k-16.el7_6.1                                 rhel-7-server-rpms                              493 k

 Installing for dependencies:
  at                                                        x86_64                              3.1.13-24.el7                                       rhel-7-server-rpms                               51 k
  avahi-libs                                                x86_64                              0.6.31-19.el7                                       rhel-7-server-rpms                               62 k
  bc                                                        x86_64                              1.06.95-13.el7                                      rhel-7-server-rpms                              115 k
  cpp                                                       x86_64                              4.8.5-36.el7_6.2                                    rhel-7-server-rpms                              6.0 M
  cups-client                                               x86_64                              1:1.6.3-35.el7                                      rhel-7-server-rpms                              151 k
  cups-libs                                                 x86_64                              1:1.6.3- 35.el7                                      rhel-7-server-rpms                              357 k
  dwz                                                       x86_64                              0.11-3.el7                                          rhel-7-server-rpms                               99 k
  ed                                                        x86_64                              1.9-4.el7                                           rhel-7-server-rpms                               72 k
  gdbm-devel                                                x86_64                              1.10-8.el7                                          rhel-7-server-rpms                               47 k
  glibc-devel                                               x86_64                              2.17-260.el7_6.6                                    rhel-7-server-rpms                              1.1 M
  glibc-headers                                             x86_64                              2.17-260.el7_6.6                                    rhel-7-server-rpms                              684 k
  kernel-headers                                            x86_64                              3.10.0-957.27.2.el7                                 rhel-7-server-rpms                              8.0 M
  keyutils-libs-devel                                       x86_64                              1.5.8-3.el7                                         rhel-7-server-rpms                               37 k
  krb5-devel                                                x86_64                              1.15.1-37.el7_6                                     rhel-7-server-rpms                              271 k
  libcom_err-devel                                          x86_64                              1.42.9-13.el7                                       rhel-7-server-rpms                               31 k
  libdb-devel                                               x86_64                              5.3.21-24.el7                                       rhel-7-server-rpms                               38 k
  libkadm5                                                  x86_64                              1.15.1-37.el7_6                                     rhel-7-server-rpms                              178 k
  libmpc                                                    x86_64                              1.0.1-3.el7                                         rhel-7-server-rpms                               51 k
  libselinux-devel                                          x86_64                              2.5-14.1.el7                                        rhel-7-server-rpms                              187 k
  libsepol-devel                                            x86_64                              2.5-10.el7                                          rhel-7-server-rpms                               77 k
  libverto-devel                                            x86_64                              0.2.5-4.el7                                         rhel-7-server-rpms                               12 k
  m4                                                        x86_64                              1.4.16-10.el7                                       rhel-7-server-rpms                              256 k
  mailx                                                     x86_64                              12.5- 19.el7                                         rhel-7-server-rpms                              245 k
  mpfr                                                      x86_64                              3.1.1-4.el7                                         rhel-7-server-rpms                              203 k
  pcre-devel                                                x86_64                              8.32-17.el7                                         rhel-7-server-rpms                              480 k
  perl                                                      x86_64                              4:5.16.3-294.el7_6                                  rhel-7-server-rpms                              8.0 M
  perl-Carp                                                 noarch                              1.26-244.el7                                        rhel-7-server-rpms                               19 k
  perl-Data-Dumper                                          x86_64                              2.145-3.el7                                         rhel-7-server-rpms                               47 k
  perl-Digest                                               noarch                              1.17-245.el7                                        rhel-7-server-rpms                               23 k
  perl-Encode                                               x86_64                              2.51-7.el7                                          rhel-7-server-rpms                              1.5 M
  perl-Exporter                                             noarch                              5.68-3.el7                                          rhel-7-server-rpms                               28 k
  perl-ExtUtils-Install                                     noarch                              1.58-294.el7_6                                      rhel-7-server-rpms                               75 k
  perl-ExtUtils-Manifest                                    noarch                              1.61-244.el7                                        rhel-7-server-rpms                               31 k
  perl-ExtUtils-ParseXS                                     noarch                              1:3.18-3.el7                                        rhel-7-server-rpms                               77 k
  perl-File-Path                                            noarch                              2.09-2.el7                                          rhel-7-server-rpms                               27 k
  perl-File-Temp                                            noarch                              0.23.01-3.el7                                       rhel-7-server-rpms                               56 k
  perl-Filter                                               x86_64                              1.49-3.el7                                          rhel-7-server-rpms                               76 k
  perl-Getopt-Long                                          noarch                              2.40-3.el7                                          rhel-7-server-rpms                               56 k
  perl-HTTP-Tiny                                            noarch                              0.033-3.el7                                         rhel-7-server-rpms                               38 k
  perl-IPC-Cmd                                              noarch                              1:0.80-4.el7                                        rhel-7-server-rpms                               34 k
  perl-Locale-Maketext                                      noarch                              1.23-3.el7                                          rhel-7-server-rpms                               93 k
  perl-Locale-Maketext-Simple                               noarch                              1:0.21-294.el7_6                                    rhel-7-server-rpms                               50 k
  perl-Module-CoreList                                      noarch                              1:2.76.02-294.el7_6                                 rhel-7-server-rpms                               86 k
  perl-Module-Load                                          noarch                              1:0.24-3.el7                                        rhel-7-server-rpms                               11 k
  perl-Module-Load-Conditional                              noarch                              0.54-3.el7                                          rhel-7-server-rpms                               18 k
  perl-Module-Metadata                                      noarch                              1.000018-2.el7                                      rhel-7-server-rpms                               26 k
  perl-Params-Check                                         noarch                              1:0.38-2.el7                                        rhel-7-server-rpms                               18 k
  perl-PathTools                                            x86_64                              3.40-5.el7                                          rhel-7-server-rpms                               83 k
  perl-Perl-OSType                                          noarch                              1.003-3.el7                                         rhel-7-server-rpms                               20 k
  perl-Pod-Escapes                                          noarch                              1:1.04-294.el7_6                                    rhel-7-server-rpms                               51 k
  perl-Pod-Perldoc                                          noarch                              3.20-4.el7                                          rhel-7-server-rpms                               87 k
  perl-Pod-Simple                                           noarch                              1:3.28-4.el7                                        rhel-7-server-rpms                              216 k
  perl-Pod-Usage                                            noarch                              1.63-3.el7                                          rhel-7-server-rpms                               27 k
  perl-Scalar-List-Utils                                    x86_64                              1.27-248.el7                                        rhel-7-server-rpms                               36 k
  perl-Socket                                               x86_64                              2.010-4.el7                                         rhel-7-server-rpms                               49 k
  perl-Storable                                             x86_64                              2.45-3.el7                                          rhel-7-server-rpms                               77 k
  perl-Test-Harness                                         noarch                              3.28-3.el7                                          rhel-7-server-rpms                              302 k
  perl-Text-ParseWords                                      noarch                              3.29-4.el7                                          rhel-7-server-rpms                               14 k
  perl-Time-HiRes                                           x86_64                              4:1.9725-3.el7                                      rhel-7-server-rpms                               45 k
  perl-Time-Local                                           noarch                              1.2300-2.el7                                        rhel-7-server-rpms                               24 k
  perl-constant                                             noarch                              1.27-2.el7                                          rhel-7-server-rpms                               19 k
  perl-devel                                                x86_64                              4:5.16.3-294.el7_6                                  rhel-7-server-rpms                              453 k
  perl-libs                                                 x86_64                              4:5.16.3-294.el7_6                                  rhel-7-server-rpms                              688 k
  perl-macros                                               x86_64                              4:5.16.3-294.el7_6                                  rhel-7-server-rpms                               44 k
  perl-parent                                               noarch                              1:0.225-244.el7                                     rhel-7-server-rpms                               12 k
  perl-podlators                                            noarch                              2.5.1-3.el7                                         rhel-7-server-rpms                              112 k
  perl-srpm-macros                                          noarch                              1-8.el7                                             rhel-7-server-rpms                              4.7 k
  perl-threads                                              x86_64                              1.87-4.el7                                          rhel-7-server-rpms                               49 k
  perl-threads-shared                                       x86_64                              1.43-6.el7                                          rhel-7-server-rpms                               39 k
  perl-version                                              x86_64                              3:0.99.07-3.el7                                     rhel-7-server-rpms                               84 k
  psmisc                                                    x86_64                              22.20-15.el7                                        rhel-7-server-rpms                              141 k
  pyparsing                                                 noarch                              1.5.6-9.el7                                         rhel-7-server-rpms                               94 k
  python-rpm-macros                                         noarch                              3-24.el7                                            epel-extra                                      7.9 k
  python-srpm-macros                                        noarch                              3-24.el7                                            epel-extra                                      7.3 k
  python3-rpm-macros                                        noarch                              3-24.el7                                            epel-extra                                      6.9 k
  python36-libs                                             x86_64                              3.6.8-2.el7.ius                                     ius                                             8.6 M
  python36-setuptools                                       noarch                              39.2.0-4.el7.ius                                    ius                                             621 k
  redhat-lsb-submod-security                                x86_64                              4.1-27.el7                                          rhel-7-server-rpms                               15 k
  redhat-rpm-config                                         noarch                              9.1.0-87.el7                                        rhel-7-server-rpms                               81 k
  spax                                                      x86_64                              1.5.2-13.el7                                        rhel-7-server-rpms                              260 k
  systemtap-sdt-devel                                       x86_64                              3.3-3.el7                                           rhel-7-server-rpms                               74 k
  time                                                      x86_64                              1.7-45.el7                                          rhel-7-server-rpms                               30 k
  zip                                                       x86_64                              3.0-11.el7                                          rhel-7-server-rpms                              260 k
  zlib-devel                                                x86_64                              1.2.7-18.el7                                        rhel-7-server-rpms                               50 k

 Updating for dependencies:
  glibc                                                     x86_64                              2.17-260.el7_6.6                                    rhel-7-server-rpms                              3.6 M
  glibc-common                                              x86_64                              2.17-260.el7_6.6                                    rhel-7-server-rpms                               11 M
  krb5-libs                                                 x86_64                              1.15.1-37.el7_6                                     rhel-7-server-rpms                              803 k
  libgcc                                                    x86_64                              4.8.5-36.el7_6.2                                    rhel-7-server-rpms                              102 k
  libgomp                                                   x86_64                              4.8.5-36.el7_6.2                                    rhel-7-server-rpms                              158 k
  openssl-libs                                              x86_64                              1:1.0.2k-16.el7_6.1                                 rhel-7-server-rpms                              1.2 M

  Transaction Summary
 ==========================================================================================================
 Install  15 Packages (+84 Dependent packages)
 Upgrade   1 Package  (+ 6 Dependent packages)

 Total download size: 97 M

 Is this ok [y/d/N]: y

 Downloading packages:

 Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
                    .
                    .
                    .
                    .
 + Installing ONTAP Mediator. (Log: /tmp/ontap_mediator.jx6UrF/ontap-mediator/install.log)
 + Install successful. (Moving log to /opt/netapp/lib/ontap_mediator/log/install.log)

 [root@red-hat-enterprise-linux ~]#
----

=== Upgrading the ONTAP Mediator service

The following example shows an upgrade of the Mediator service:

. Use the following steps to configure third-party certification.
+
Third-party certification is recommended.
.. The certificate must be placed in the following directory: /opt/netapp/lib/ontap_mediator/ontap_mediator/ server_config
+
You must overwrite the following files with your certificate, renaming the certificate files if necessary to ontap_mediator_server.crt and ontap_mediator_server.key.
+
 # SSL Certificates
 cert_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ontap_mediator_server.crt'
 key_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ontap_mediator_server.key'
+
Note: You must be sure to follow security best practices for your operating system. If you are not using a third-party certificate, the Mediator installation process will create a self-signed certificate.

.. Along with the server certificates, you must update the CA certificates as well.
+
You must overwrite the following files with your certificate, renaming the certificate files if necessary to:
+
* ontap_mediator_server.crt
* ontap_mediator_server.key
* ca.crt
* ca.key
* ca.srl
+
 # SSL Certificates
 cert_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ontap_mediator_server.crt'
 key_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ontap_mediator_server.key'
 ca_cert_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ca.crt'
 ca_key_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ca.key'
 ca_serial_path: '/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ca.srl'

== Verify the installation.

Run the following command to view the status of the ONTAP Mediator services: systemctl

----
 [root@scspr1915530002 ~]# systemctl status ontap_mediator mediator-scst

        ∙ ontap_mediator.service - ONTAP Mediator
            Loaded: loaded (/opt/netapp/lib/ontap_mediator/systemd/ontap_mediator.service; enabled; vendor preset: disabled)

            Active: active (running) since Thu 2020-06-18 09:55:02 EDT; 3 days ago

         Main PID: 3559 (uwsgi)

            Status: "uWSGI is ready"

            CGroup: /system.slice/ontap_mediator.service

                    \u251c\u25003559 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

                    \u251c\u25004510 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

                    \u2514\u25004512 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini



         Jun 18 09:54:43 scspr1915530002 systemd[1]: Starting ONTAP Mediator...

         Jun 18 09:54:45 scspr1915530002 ontap_mediator[3559]: [uWSGI] getting INI configuration from /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

         Jun 18 09:55:02 scspr1915530002 systemd[1]: Started ONTAP Mediator.



         ∙ mediator-scst.service
            Loaded: loaded (/opt/netapp/lib/ontap_mediator/systemd/mediator-scst.service; enabled; vendor preset: disabled)

            Active: active (running) since Thu 2020-06-18 09:54:51 EDT; 3 days ago

           Process: 3564 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)

         Main PID: 4202 (iscsi-scstd)

            CGroup: /system.slice/mediator-scst.service

                    \u2514\u25004202 /usr/local/sbin/iscsi-scstd



         Jun 18 09:54:43 scspr1915530002 systemd[1]: Starting mediator-scst.service...

         Jun 18 09:54:48 scspr1915530002 iscsi-scstd[4200]: max_data_seg_len 1048576, max_queued_cmds 2048

         Jun 18 09:54:51 scspr1915530002 scst[3564]: Loading and configuring SCST[  OK  ]

         Jun 18 09:54:51 scspr1915530002 systemd[1]: Started mediator-scst.service.

         [root@scspr1915530002 ~]#
----

. Confirm the ports the ONTAP Mediator service is using: netstat

----
         [root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp        0      0 0.0.0.0:31784           0.0.0.0:*               LISTEN

         tcp        0      0 0.0.0.0:3260            0.0.0.0:*               LISTEN

         tcp6       0      0 :::3260                 :::*                    LISTEN
----

== Result

The ONTAP Mediator service is now installed and running. Further configuration must be performed in the ONTAP storage system to use the Mediator features.

// 2021-04-21 ONTAPEX-133437
