---
permalink: install-ip/task_install_and_cable_the_mcc_components.html
sidebar: sidebar
keywords:  ip, switch, configuring
summary: You must configure the IP switches to provide backend MetroCluster IP connectivity.
---
= Learn about configuring the MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You must configure the IP switches to provide backend MetroCluster IP connectivity. The procedure you follow depends on your switch vendor and whether you are configuring your switches for the first time, or as part of another procedure.

== Fresh MetroCluster IP installation

If you are performing a fresh MetroCluster IP installation, you should use the following procedures, depending on your switch vendor:

* link:../install-ip/task_switch_config_broadcom.html[Configure Broadcom IP switches]
* link:../install-ip/task_switch_config_cisco.html[Configure Cisco IP switches]
* link:../install-ip/task_switch_config_nvidia.html[Configure NVIDIA IP switches]

== Configure IP switches as part of other MetroCluster IP procedures

If you need to configure IP switches as part of other MetroCluster IP procedures, such as a switch replacement or upgrade, you must move the cluster LIFs before you configure the IP switches. 

* link:../install-ip/switch-move-cluster-lifs.html[Move the cluster LIFs before a switch or RCF update]

After the cluster LIFs have moved to another switch, you can follow the standard configuration procedures according to your switch vendor:

* link:../install-ip/task_switch_config_broadcom.html[Configure Broadcom IP switches]
* link:../install-ip/task_switch_config_cisco.html[Configure Cisco IP switches]
* link:../install-ip/task_switch_config_nvidia.html[Configure NVIDIA IP switches]






// 2024 May 02, ONTAPDOC-1895