---
permalink: install-ip/task_remove_unconfigure_mediator.html
sidebar: sidebar
keywords: ontap, mediator, service, assist, remove, unconfigure, requirements, mediator requirements
summary: You can remove the ONTAP mediator service from the MetroCluster IP configuration.
---

= Unconfigure the ONTAP Mediator service from the MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]

You can unconfigure the ONTAP Mediator service from the MetroCluster IP configuration.

.Before you begin

You must have successfully installed and configured the ONTAP Mediator on a network location that can be reached by both MetroCluster sites.

.Steps

. Unconfigure the ONTAP Mediator service by using the following command:
+
`metrocluster configuration-settings mediator remove`

.. Check if there are any broken disks by using the following command:
+
`disk show -broken`
+
*Example*
+
....
There are no entries matching your query.
....
. Confirm that the ONTAP Mediator service has been removed from the MetroCluster configuration by running the following commands on both clusters:
+
`metrocluster configuration-settings mediator show`
+
----
This table is currently empty.
----
+
`storage iscsi-initiator show -label mediator`
+
----
There are no entries matching your query.
----


// BURT 1389268, 25 Feb 2022
// GH issue 183, 07 Nov 2022
