---
permalink: install-ip/task_sw_config_differences.html
sidebar: sidebar
keywords: metrocluster, configuration, ontap, node-level, configuration, node, site, relationship, configuring, configure
keywords: metrocluster, configuration, ontap, node-level, configuration, node, site, relationship, configuring, configure, similarities, difference,
summary: The configuration of the nodes in each cluster in a MetroCluster configuration is similar to that of nodes in a standard cluster.
---
= Compare ONTAP standard cluster and MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
The configuration of the nodes in each cluster in a MetroCluster configuration is similar to that of nodes in a standard cluster.

The MetroCluster configuration is built on two standard clusters. Physically, the configuration must be symmetrical, with each node having the same hardware configuration, and all of the MetroCluster components must be cabled and configured. However, the basic software configuration for nodes in a MetroCluster configuration is the same as that for nodes in a standard cluster.

//ontap-metrocluster/issues/101 2021.11.21
|===

h| Configuration step h| Standard cluster configuration h| MetroCluster configuration

a|
Configure management, cluster, and data LIFs on each node.
2+|
Same in both types of clusters
a|
Configure the root aggregate.
2+|
Same in both types of clusters
a|
Set up the cluster on one node in the cluster.
2+|
Same in both types of clusters
a|
Join the other node to the cluster.
2+|
Same in both types of clusters
a|
Create a mirrored root aggregate.
a|
Optional
a|
Required
a|
Peer the clusters.
a|
Optional
a|
Required
a|
Enable the MetroCluster configuration.
a|
Does not apply
a|
Required
|===
