---
permalink: install-ip/task_changing_mediator_password.html
sidebar: sidebar
keywords: mediator, password, change
summary: After you have installed ONTAP Mediator service, you might want to change the password. You can change the password in two ways.
---

= Changing the ONTAP Mediator password
:icons: font
:imagesdir: ../media/

[.lead]
After you have installed ONTAP Mediator service, you might want to change the password. You can change the password in two ways.

.About this task

This task is performed on the Linux host on which the ONTAP Mediator service is installed.

If you are unable to reach this command, you might need to run the command using the full path as shown in the following example:

`/usr/local/bin/mediator_change_password`

.Procedure

Change the password by choosing one of the following options:

* Run the mediator_change_password command and respond to the prompts as shown in the following example:
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....

* Run the following command:
+
`MEDIATOR_USERNAME= mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password`
+
The example shows the password is changed from "mediator1" to "mediator2".
+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....
