---
permalink: install-ip/update-mediator-timeout.html
sidebar: sidebar
keywords: ontap, metrocluster, mediator, timeout, settings, change, update, default, value
summary:
---
= Increase the default ONTAP Mediator mailbox timeout in MetroCluster IP configurations
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP Mediator provides mailbox disks to ONTAP for writing heartbeat and state information. The MetroCluster IP nodes access these mailboxes using iSCSI, which has a default timeout of 10 seconds, with a single retry after 5 seconds. Depending on your ONTAP version, you can extend the default mailbox timeout to a maximum of 60 seconds if your network latency is higher than the default timeout.

NetApp recommends that you increase the default timeout value if you are using network redundancy protocols such as HSRP or VRRP, loop-avoidance protocols such as STP, or if the network latency in your environment exceeds the default timeout of 10 seconds.  

.About this task

* The following ONTAP versions support increasing the mailbox timeout value: 
** 9.15.1P16
** 9.16.1P10
** 9.17.1P3
** ONTAP 9.18.1GA or later
* Increasing the timeout value is supported on all versions of ONTAP Mediator. 
* You must repeat the steps to change the default timeout value each time you upgrade to a new ONTAP version. 
* The timeout value supported range is from 10 to 60 seconds. If you specify an out-of-range value, ONTAP automatically changes it back to the default value of 10 seconds.
* If it takes longer than 10 seconds for the MetroCluster nodes to reconnect to the ONTAP Mediator, you should set the timeout value to be a few seconds longer than the connection time. 

.Step

. If you need to increase the timeout value, refer to the link:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/How_to_Increase_Mediator_Mailbox_Timeout_for_environments_where_network_latency_exceeds_10_seconds[NetApp Knowledge Base article: How to Increase Mediator Mailbox Timeout for environments where network latency exceeds 10 seconds^]


 
