---
permalink: install-ip/using_rcf_generator.html
sidebar: sidebar
keywords: cabling, cable, component, link, site, management, network, hardware, component, switch, cluster, connection, management, data, configuring, configure, rcf, file, generator, RcfFileGenerator
summary: You must understand how to use the information in the port tables to correctly generate your RCF files.
---

= Using the port tables with the RcfFileGenerator tool or multiple MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
You must understand how to use the information in the port tables to correctly generate your RCF files.

.Before you begin

Review these considerations before using the tables:

* The following tables show the port usage for site A. The same cabling is used for site B.
* You cannot configure the switches with ports of different speeds (for example, a mix of 100 Gbps ports and 40 Gbps ports).
* Keep track of the MetroCluster port group (MetroCluster 1, MetroCluster 2, etc.). You'll need this information when using the RcfFileGenerator tool as described later in this configuration procedure.
* You should cable all of the nodes in the same way. If there are different port combination options available to cable the nodes, all nodes should use the same port combinations. For example, e1a on node1 and e1a on node2 should be attached to one switch. Similarly, the second port from both nodes should be attached to the second switch. 

* The https://mysupport.netapp.com/site/tools/tool-eula/rcffilegenerator[RcfFileGenerator for MetroCluster IP^] also provides a per-port cabling overview for each switch.
Use this cabling overview to verify your cabling.

== Cabling two MetroCluster configurations to the switches

When cabling more than one MetroCluster configuration to a switch, you cable each MetroCluster according to the appropriate table. For example, if you are cabling a FAS2750 and an AFF A700 to the same switch, you cable the FAS2750 as per "MetroCluster 1" in Table 1, and the AFF A700 as per "MetroCluster 2" or "MetroCluster 3" in Table 2. You cannot physically cable both the FAS2750 and the AFF A700 as "MetroCluster 1".

== Cabling eight-node MetroCluster configurations

For MetroCluster configuration running ONTAP 9.8 and earlier, some procedures that are performed to transition an upgrade require the addition of a second four-node DR group to the configuration to create a temporary eight-node configuration.  Beginning with ONTAP 9.9.1, permanent eight-node MetroCluster configurations are supported.

.About this task

For eight-node configurations, you use the same method as described above. Instead of a second MetroCluster, you are cabling an additional four-node DR group. 

For example, your configuration includes the following:

* Cisco 3132Q-V switches
* MetroCluster 1: FAS2750 platforms
* MetroCluster 2: AFF A700 platforms (these platforms are being added as a second four-node DR group)

.Steps

. For MetroCluster 1, cable the Cisco 3132Q-V switches using the table for the FAS2750 platform and the rows for MetroCluster 1 interfaces.

. For MetroCluster 2 (the second DR group), cable the Cisco 3132Q-V switches using the table for the AFF A700 platform and the rows for MetroCluster 2 interfaces.

// 2024 Dec 09, ONTAPDOC-2349
// 21 APR 2021, BURT 1374268
