---
permalink: disaster-recovery/task_cfg_switches_mcfc.html
sidebar: sidebar
keywords: configure, fc, switches, metrocluster, configuration
summary: 'If you have replaced the FC switches in the disaster site, you must configure them using the vendor-specific procedures.'
---
= Configuring the FC switches (MetroCluster FC configurations only)
:icons: font
:imagesdir: ../media/

[.lead]
If you have replaced the FC switches in the disaster site, you must configure them using the vendor-specific procedures. You must configure one switch, verify that storage access on the surviving site is not impacted, and then configure the second switch.

*Related information*

xref:task_prepare_for_switchback_in_a_mcc_fc_configuration_supertask.adoc[Configuring a Brocade FC switch after site disaster]

xref:task_prepare_for_switchback_in_a_mcc_fc_configuration_supertask.adoc[Configuring a Cisco FC switch after site disaster]

link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.adoc[]

link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.adoc[]

=== Configuring a Brocade FC switch after site disaster

[.lead]
You must use this Brocade-specific procedure to configure the replacement switch and enable the ISL ports.

The examples in this procedure are based on the following assumptions:

* Site A is the disaster site.
* FC_switch_A_1 has been replaced.
* FC_switch_A_2 has been replaced.
* Site B is the surviving site.
* FC_switch_B_1 is healthy.
* FC_switch_B_2 is healthy.

You must verify that you are using the specified port assignments when you cable the FC switches:

* link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html[Port assignments for FC switches when using ONTAP 9.0]
* link:../install-fc/concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html[Port assignments for FC switches when using ONTAP 9.1 and later]

The examples show two FC-to-SAS bridges. If you have more bridges, you must disable and subsequently enable the additional ports.

. Boot and pre-configure the new switch:
 .. Power up the new switch and let it boot up.
 .. Check the firmware version on the switch to confirm it matches the version of the other FC switches: `firmwareShow`
 .. Configure the new switch as described in the _MetroCluster Installation and Configuration Guide_, skipping the steps for configuring zoning on the switch.
+
link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
+
link:../install-stretch/index.html[Stretch MetroCluster installation and configuration]

 .. Disable the switch persistently: `switchcfgpersistentdisable`
+
The switch will remain disabled after a reboot or fastboot. If this command is not available, you should use the switchdisable command.
+
The following example shows the command on BrocadeSwitchA:
+
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
+
The following example shows the command on BrocadeSwitchB:
+
----
BrocadeSwitchA:admin> switchcfgpersistentdisable
----
. Complete configuration of the new switch:
 .. Enable the ISLs on the surviving site: `portcfgpersistentenable port-number`
+
----
FC_switch_B_1:admin> portcfgpersistentenable 10
FC_switch_B_1:admin> portcfgpersistentenable 11
----

 .. Enable the ISLs on the replacement switches: `portcfgpersistentenable port-number`
+
----
FC_switch_A_1:admin> portcfgpersistentenable 10
FC_switch_A_1:admin> portcfgpersistentenable 11
----

 .. On the replacement switch (FC_switch_A_1 in our example) verify that the ISL's are online:``switchshow``
+
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 71.2
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       4
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
==============================================
...
10   10    030A00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1"
11   11    030B00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)
...
----
. Persistently enable the switch: `switchcfgpersistentenable`
. Verify that the ports are online:``switchshow``

=== Configuring a Cisco FC switch after site disaster

[.lead]
You must use the Cisco-specific procedure to configure the replacement switch and enable the ISL ports.

The examples in this procedure are based on the following assumptions:

* Site A is the disaster site.
* FC_switch_A_1 has been replaced.
* FC_switch_A_2 has been replaced.
* Site B is the surviving site.
* FC_switch_B_1 is healthy.
* FC_switch_B_2 is healthy.

. Configure the switch:
 .. Refer to the _Fabric-attached MetroCluster Installation and Configuration Guide_.
+
link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]

 .. Follow the steps for configuring the switch in the  link:../install-fc/generaltask_fcsw_cisco_configure_the_cisco_fc_switches_with_rcf_files.html[Configuring the Cisco FC switches] section, _except_ for the "`Configuring zoning on a Cisco FC switch`" section:
+
Zoning is configured later in this procedure.
. On the healthy switch (in this example, FC_switch_B_1), enable the ISL ports.
+
The following example shows the commands to enable the ports:
+
----
FC_switch_B_1# conf t
FC_switch_B_1(config)# int fc1/14-15
FC_switch_B_1(config)# no shut
FC_switch_B_1(config)# end
FC_switch_B_1# copy running-config startup-config
FC_switch_B_1#
----

. Verify that the ISL ports are up by using the show interface brief command.
. Retrieve the zoning information from the fabric.
+
The following example shows the commands to distribute the zoning configuration:
+
----
FC_switch_B_1(config-zone)# zoneset distribute full vsan 10
FC_switch_B_1(config-zone)# zoneset distribute full vsan 20
FC_switch_B_1(config-zone)# end
----
+
FC_switch_B_1 is distributed to all other switches in the fabric for vsan 10 and vsan 20, and the zoning information is retrieved from FC_switch_A_1.

. On the healthy switch, verify that the zoning information is properly retrieved from the partner switch: `show zone`
+
----
FC_switch_B_1# show zone
zone name FC-VI_Zone_1_10 vsan 10
  interface fc1/1 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/2 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/1 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/2 swwn 20:00:54:7f:ee:b8:24:c0

zone name STOR_Zone_1_20_25A vsan 20
  interface fc1/5 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0

zone name STOR_Zone_1_20_25B vsan 20
  interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
  interface fc1/5 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
  interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0
FC_switch_B_1#
----

. Determine the worldwide names (WWNs) of the switches in the switch fabric.
+
In this example, the two switch WWNs are as follows:

 ** FC_switch_A_1: 20:00:54:7f:ee:b8:24:c0
 ** FC_switch_B_1: 20:00:54:7f:ee:c6:80:78

+
----
FC_switch_B_1# show wwn switch
Switch WWN is 20:00:54:7f:ee:c6:80:78
FC_switch_B_1#

FC_switch_A_1# show wwn switch
Switch WWN is 20:00:54:7f:ee:b8:24:c0
FC_switch_A_1#
----

. Enter configuration mode for the zone and remove zone members that do not belong to the switch WWNs of the two switches: `no member interface interface-ide swwn wwn`
+
In this example, the following members are not associated with the WWN of either of the switches in the fabric and must be removed:

 ** Zone name FC-VI_Zone_1_10 vsan 10
  *** Interface fc1/1 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/2 swwn 20:00:54:7f:ee:e3:86:50
*Note:* AFF A700 and FAS9000 systems support four FC-VI ports. You must remove all four ports from the FC-VI zone.
 ** Zone name STOR_Zone_1_20_25A vsan 20
  *** Interface fc1/5 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
 ** Zone name STOR_Zone_1_20_25B vsan 20
  *** Interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
  *** Interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
The following example shows the removal of these interfaces:

+
----

 FC_switch_B_1# conf t
 FC_switch_B_1(config)# zone name FC-VI_Zone_1_10 vsan 10
 FC_switch_B_1(config-zone)# no member interface fc1/1 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/2 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25A vsan 20
 FC_switch_B_1(config-zone)# no member interface fc1/5 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25B vsan 20
 FC_switch_B_1(config-zone)# no member interface fc1/8 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/9 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/10 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# no member interface fc1/11 swwn 20:00:54:7f:ee:e3:86:50
 FC_switch_B_1(config-zone)# save running-config startup-config
 FC_switch_B_1(config-zone)# zoneset distribute full 10
 FC_switch_B_1(config-zone)# zoneset distribute full 20
 FC_switch_B_1(config-zone)# end
 FC_switch_B_1# copy running-config startup-config
----

[start=8]
. [[step8]]Add the ports of the new switch to the zones.
+
The following example assumes that the cabling on the replacement switch is the same as on the old switch:
+
----

 FC_switch_B_1# conf t
 FC_switch_B_1(config)# zone name FC-VI_Zone_1_10 vsan 10
 FC_switch_B_1(config-zone)# member interface fc1/1 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/2 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25A vsan 20
 FC_switch_B_1(config-zone)# member interface fc1/5 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# zone name STOR_Zone_1_20_25B vsan 20
 FC_switch_B_1(config-zone)# member interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# member interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
 FC_switch_B_1(config-zone)# save running-config startup-config
 FC_switch_B_1(config-zone)# zoneset distribute full 10
 FC_switch_B_1(config-zone)# zoneset distribute full 20
 FC_switch_B_1(config-zone)# end
 FC_switch_B_1# copy running-config startup-config
----

. Verify that the zoning is properly configured: `show zone`
+
The following example output shows the three zones:
+
----

 FC_switch_B_1# show zone
   zone name FC-VI_Zone_1_10 vsan 10
     interface fc1/1 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/2 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/1 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/2 swwn 20:00:54:7f:ee:b8:24:c0

   zone name STOR_Zone_1_20_25A vsan 20
     interface fc1/5 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0

   zone name STOR_Zone_1_20_25B vsan 20
     interface fc1/8 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/9 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/10 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/11 swwn 20:00:54:7f:ee:c6:80:78
     interface fc1/5 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/8 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/9 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/10 swwn 20:00:54:7f:ee:b8:24:c0
     interface fc1/11 swwn 20:00:54:7f:ee:b8:24:c0
 FC_switch_B_1#
----
