---
permalink: disaster-recovery/task_set_env_mcip.html
sidebar: sidebar
keywords: metrocluster, ip, configuration, setting, require, environmental, variable
summary: In MetroCluster IP configurations, you retrieve the IP address of the MetroCluster interfaces on the Ethernet ports, and then use them to configure the interfaces on the replacement controller modules.
---
= Setting required environmental variables in MetroCluster IP configurations
:icons: font
:imagesdir: ../media/

[.lead]
In MetroCluster IP configurations, you must retrieve the IP address of the MetroCluster interfaces on the Ethernet ports, and then use them to configure the interfaces on the replacement controller modules.

.About this task

* This task is required only in MetroCluster IP configurations.

* Commands in this task are performed from the cluster prompt of the surviving site and from the LOADER prompt of the nodes at the disaster site.

[[vlan_id_supported_platfoms]]
* Certain platforms use a VLAN for the MetroCluster IP interface. By default, each of the two ports use a different VLAN: 10 and 20. 
+
If supported, you can also specify a different (non-default) VLAN higher than 100 (between 101 and 4095) using the `vlan-id` parameter.
+
The following platforms do *not* support the `vlan-id` parameter:
+
** FAS8200 and AFF A300
** AFF A320
** FAS9000 and AFF A700
** AFF C800, ASA C800, AFF A800 and ASA A800
+
All other platforms support the `vlan-id` parameter.

// 2024 Jul 08, ONTAPDOC-1942

* The nodes in these examples have the following IP addresses for their MetroCluster IP connections:
+
NOTE: These examples are for an AFF A700 or FAS9000 system. The interfaces vary by platform model.
+
|===

h| Node h| Port h| IP address

.2+a|
node_A_1
a|
e5a
a|
172.17.26.10
a|
e5b
a|
172.17.27.10
.2+a|
node_A_2
a|
e5a
a|
172.17.26.11
a|
e5b
a|
172.17.27.11
.2+a|
node_B_1
a|
e5a
a|
172.17.26.13
a|
e5b
a|
172.17.27.13
.2+a|
node_B_2
a|
e5a
a|
172.17.26.12
a|
e5b
a|
172.17.27.12
|===
+
The following table summarizes the relationships between the nodes and each node's MetroCluster IP addresses.
+
|===

h| Node h| HA partner h| DR partner h| DR auxiliary partner

a|
node_A_1

* e5a: 172.17.26.10
* e5b: 172.17.27.10

a|
node_A_2

* e5a: 172.17.26.11
* e5b: 172.17.27.11

a|
node_B_1

* e5a: 172.17.26.13
* e5b: 172.17.27.13

a|
node_B_2

* e5a: 172.17.26.12
* e5b: 172.17.27.12

a|
node_A_2

* e5a: 172.17.26.11
* e5b: 172.17.27.11

a|
node_A_1

* e5a: 172.17.26.10
* e5b: 172.17.27.10

a|
node_B_2

* e5a: 172.17.26.12
* e5b: 172.17.27.12

a|
node_B_1

* e5a: 172.17.26.13
* e5b: 172.17.27.13

a|
node_B_1

* e5a: 172.17.26.13
* e5b: 172.17.27.13

a|
node_B_2

* e5a: 172.17.26.12
* e5b: 172.17.27.12

a|
node_A_1

* e5a: 172.17.26.10
* e5b: 172.17.27.10

a|
node_A_2

* e5a: 172.17.26.11
* e5b: 172.17.27.11

a|
node_B_2

* e5a: 172.17.26.12
* e5b: 172.17.27.12

a|
node_B_1

* e5a: 172.17.26.13
* e5b: 172.17.27.13

a|
node_A_2

* e5a: 172.17.26.11
* e5b: 172.17.27.11

a|
node_A_1

* e5a: 172.17.26.10
* e5b: 172.17.27.10

|===

* The MetroCluster bootarg values you set depend on whether your new system uses shared cluster/HA ports or shared MetroCluster/HA ports. Use the following information to determine the ports for your system.
+
include::../_include/shared-metrocluster-ha-or-shared-cluster-ha.adoc[]

.Steps

. From the surviving site, gather the IP addresses of the MetroCluster interfaces on the disaster site:
+
`metrocluster configuration-settings connection show`
+
The required addresses are the DR Partner addresses shown in the *Destination Network Address* column.
+
The command output varies depending on your platform model. 
+
[role="tabbed-block"]
====
.Systems using shared cluster/HA ports
--

----
cluster_B::*> metrocluster configuration-settings connection show
DR                    Source          Destination
DR                    Source          Destination
Group Cluster Node    Network Address Network Address Partner Type Config State
----- ------- ------- --------------- --------------- ------------ ------------
1     cluster_B
              node_B_1
                 Home Port: e5a
                      172.17.26.13    172.17.26.10    DR Partner   completed
                 Home Port: e5a
                      172.17.26.13    172.17.26.11    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.10    DR Partner   completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.11    DR Auxiliary completed
              node_B_2
                 Home Port: e5a
                      172.17.26.12    172.17.26.11    DR Partner   completed
                 Home Port: e5a
                      172.17.26.12    172.17.26.10    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.11    DR Partner   completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.10    DR Auxiliary completed
12 entries were displayed.
----

--
.Systems using shared MetroCluster/HA ports
--
The following output shows the IP addresses for a configuration with AFF A700 and FAS9000 systems with the MetroCluster IP interfaces on ports e5a and e5b. The interfaces can vary depending on the platform type.

----
cluster_B::*> metrocluster configuration-settings connection show
DR                    Source          Destination
DR                    Source          Destination
Group Cluster Node    Network Address Network Address Partner Type Config State
----- ------- ------- --------------- --------------- ------------ ------------
1     cluster_B
              node_B_1
                 Home Port: e5a
                      172.17.26.13    172.17.26.12    HA Partner   completed
                 Home Port: e5a
                      172.17.26.13    172.17.26.10    DR Partner   completed
                 Home Port: e5a
                      172.17.26.13    172.17.26.11    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.12    HA Partner   completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.10    DR Partner   completed
                 Home Port: e5b
                      172.17.27.13    172.17.27.11    DR Auxiliary completed
              node_B_2
                 Home Port: e5a
                      172.17.26.12    172.17.26.13    HA Partner   completed
                 Home Port: e5a
                      172.17.26.12    172.17.26.11    DR Partner   completed
                 Home Port: e5a
                      172.17.26.12    172.17.26.10    DR Auxiliary completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.13    HA Partner   completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.11    DR Partner   completed
                 Home Port: e5b
                      172.17.27.12    172.17.27.10    DR Auxiliary completed
12 entries were displayed.
----
--
====


. If you need to determine the VLAN ID or gateway address for the interface, determine the VLAN IDs from the surviving site:
+
`metrocluster configuration-settings interface show`
+
** You need to determine the VLAN ID if the platform models support VLAN IDs (see the <<vlan_id_supported_platfoms,list above>>) and if you are not using the default VLAN IDs.

** You need the gateway address if you are using link:../install-ip/concept_considerations_layer_3.html[Layer 3 wide-area networks].
+
The VLAN IDs are included in the *Network Address* column of the output. The *Gateway* column shows the gateway IP address.
+
In this example the interfaces are e0a with the VLAN ID 120 and e0b with the VLAN ID 130:
+
----
Cluster-A::*> metrocluster configuration-settings interface show
DR                                                                     Config
Group Cluster Node     Network Address Netmask         Gateway         State
----- ------- ------- --------------- --------------- --------------- ---------
1
      cluster_A
              node_A_1
                  Home Port: e0a-120
                          172.17.26.10  255.255.255.0  -            completed
                  Home Port: e0b-130
                          172.17.27.10  255.255.255.0  -            completed
----

. At the LOADER prompt for each of the disaster site nodes, set the bootarg value depending on the platform model:
+
[NOTE]
====
* If the interfaces are using the default VLANs, or the platform model does not use a VLAN ID (see the <<vlan_id_supported_platfoms,list above>>), the _vlan-id_ is not necessary.
* If the configuration is not using link:../install-ip/concept_considerations_layer_3.html[Layer3 wide-area networks], the value for _gateway-IP-address_ is *0* (zero).
====
+
[role="tabbed-block"]
====
.Systems using shared cluster/HA ports
--

Set the following bootarg:

----
setenv bootarg.mcc.port_a_ip_config local-IP-address/local-IP-mask,gateway-IP-address,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id

setenv bootarg.mcc.port_b_ip_config local-IP-address/local-IP-mask,gateway-IP-address,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id
----

The following commands set the values for node_A_1 using VLAN 120 for the first network and VLAN 130 for the second network:

....
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,0,172.17.26.13,172.17.26.12,120

setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,0,172.17.27.13,172.17.27.12,130
....

The following example shows the commands for node_A_1 without a VLAN ID:

----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,0,172.17.26.13,172.17.26.12

setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,0,172.17.27.13,172.17.27.12
----
--
.Systems using shared MetroCluster/HA ports
--
Set the following bootarg:
....
setenv bootarg.mcc.port_a_ip_config local-IP-address/local-IP-mask,gateway-IP-address,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id

setenv bootarg.mcc.port_b_ip_config local-IP-address/local-IP-mask,gateway-IP-address,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id
....

The following commands set the values for node_A_1 using VLAN 120 for the first network and VLAN 130 for the second network:

....
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120

setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
....

The following example shows the commands for node_A_1 without a VLAN ID:

----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12

setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12
----

--
====

. From the surviving site, gather the UUIDs for the disaster site:
+
`metrocluster node show -fields node-cluster-uuid, node-uuid`
+
----
cluster_B::> metrocluster node show -fields node-cluster-uuid, node-uuid

  (metrocluster node show)
dr-group-id cluster     node     node-uuid                            node-cluster-uuid
----------- ----------- -------- ------------------------------------ ------------------------------
1           cluster_A   node_A_1 f03cb63c-9a7e-11e7-b68b-00a098908039 ee7db9d5-9a82-11e7-b68b-00a098
                                                                        908039
1           cluster_A   node_A_2 aa9a7a7a-9a81-11e7-a4e9-00a098908c35 ee7db9d5-9a82-11e7-b68b-00a098
                                                                        908039
1           cluster_B   node_B_1 f37b240b-9ac1-11e7-9b42-00a098c9e55d 07958819-9ac6-11e7-9b42-00a098
                                                                        c9e55d
1           cluster_B   node_B_2 bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f 07958819-9ac6-11e7-9b42-00a098
                                                                        c9e55d
4 entries were displayed.
cluster_A::*>
----
+

|===

h| Node h| UUID

a|
cluster_B
a|
07958819-9ac6-11e7-9b42-00a098c9e55d
a|
node_B_1
a|
f37b240b-9ac1-11e7-9b42-00a098c9e55d
a|
node_B_2
a|
bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
a|
cluster_A
a|
ee7db9d5-9a82-11e7-b68b-00a098908039
a|
node_A_1
a|
f03cb63c-9a7e-11e7-b68b-00a098908039
a|
node_A_2
a|
aa9a7a7a-9a81-11e7-a4e9-00a098908c35
|===

. At the replacement nodes' LOADER prompt, set the UUIDs:
+
....
setenv bootarg.mgwd.partner_cluster_uuid partner-cluster-UUID

setenv bootarg.mgwd.cluster_uuid local-cluster-UUID

setenv bootarg.mcc.pri_partner_uuid DR-partner-node-UUID

setenv bootarg.mcc.aux_partner_uuid DR-aux-partner-node-UUID

setenv bootarg.mcc_iscsi.node_uuid local-node-UUID`
....

 .. Set the UUIDs on node_A_1.
+
The following example shows the commands for setting the UUIDs on node_A_1:
+
....
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039

setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d

setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d

setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f

setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
....

.. Set the UUIDs on node_A_2:
+
The following example shows the commands for setting the UUIDs on node_A_2:
+
....
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039

setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d

setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f

setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d

setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
....

. If the original systems were configured for ADP, at each of the replacement nodes' LOADER prompt, enable ADP:
+
`setenv bootarg.mcc.adp_enabled true`
. If running ONTAP 9.5, 9.6 or 9.7, at each of the replacement nodes' LOADER prompt, enable the following variable:
+
`setenv bootarg.mcc.lun_part true`

.. Set the variables on node_A_1.
+
The following example shows the commands for setting the values on node_A_1 when running ONTAP 9.6:
+
----
setenv bootarg.mcc.lun_part true
----

.. Set the variables on node_A_2.
+
The following example shows the commands for setting the values on node_A_2 when running ONTAP 9.6:
+
----
setenv bootarg.mcc.lun_part true
----

. If the original systems were configured for end-to-end encryption, at each of the replacement nodes' LOADER prompt, set the following bootarg:
+
`setenv bootarg.mccip.encryption_enabled 1`
 
. If the original systems were configured for ADP, at each of the replacement nodes' LOADER prompt, set the original system ID (*not* the system ID of the replacement controller module) and the system ID of the DR partner of the node:
+
`setenv bootarg.mcc.local_config_id original-sysID`
+
`setenv bootarg.mcc.dr_partner dr_partner-sysID`
+
link:task_replace_hardware_and_boot_new_controllers.html#determine-the-system-ids-and-vlan-ids-of-the-old-controller-modules[Determine the system IDs of the old controller modules]

.. Set the variables on node_A_1.
+
The following example shows the commands for setting the system IDs on node_A_1:

*** The old system ID of node_A_1 is 4068741258.
*** The system ID of node_B_1 is 4068741254.
+
----
setenv bootarg.mcc.local_config_id 4068741258
setenv bootarg.mcc.dr_partner 4068741254
----

.. Set the variables on node_A_2.
+
The following example shows the commands for setting the system IDs on node_A_2:

*** The old system ID of node_A_1 is 4068741260.
*** The system ID of node_B_1 is 4068741256.
+
----
setenv bootarg.mcc.local_config_id 4068741260
setenv bootarg.mcc.dr_partner 4068741256
----

// 2025 Feb 13, ONTAPDOC-2660
// 2024 June 17, ONTAPDOC-2041
// 2024 Feb 23, ONTAPDOC-1675