---
settings:
  name: ONTAP MetroCluster
  harmony_integration: maestro
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: MetroCluster docs
      url: /index.html
    - section: releasenotes
    - section: install-fc
    - section: install-ip
    - section: install-stretch
    - section: tiebreaker
    - title: Understand MetroCluster data protection and disaster recovery
      entries:
        - title: How MetroCluster protects data and provides disaster recovery
          url: /manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html
    - section: manage
    - section: maintain
    - section: transition
    - section: upgrade
    - section: disaster-recovery
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: ONTAP
  repo: ontap-family

