sidebar:
  entries:
    - title: MetroCluster
      url: /index.html
    - title: Release Notes
      url: /releasenotes.html
    - section: install-fc
    - section: install-ip
    - section: install-stretch
    - section: tiebreaker
    - section: maintain
    - title: Understanding MetroCluster data protection and disaster recovery
      url: /manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html
    - section: manage
    - section: transition
    - section: upgrade
    - section: disaster-recovery
    - title: Legal notices
      url: /reference_legal_notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Install MetroCluster IP
          summary: Install a MetroCluster IP configuration.
          url: /install-ip/index.html
        - title: Install Fabric-attached MetroCluster
          summary: Install a fabric-attached MetroCluster configuration.
          url: /install-fc/index.html
        - title: Install Stretch MetroCluster
          summary: Install a stretch MetroCluster configuration.
          url: /install-stretch/index.html
        - title: Install Tiebreaker
          summary: Install the MetroCluster Tiebreaker software on a third location to monitor the MetroCluster sites.
          url: /tiebreaker/index.html
        - title: Install Mediator (MetroCluster IP only)
          summary: Install the ONTAP Mediator software on a third location to monitor the MetroCluster IP sites.
          url: /install-ip/concept_configure_the_ontap_mediator_for_unplanned_automatic_switchover.html
    - title: Maintain
      links:
        - title: FC switches
          summary: Maintain and replace FC switches in MetroCluster FC configurations.
          url: /maintain/concept_performing_fc_switch_maintenance.html
        - title: IP switches
          summary: Maintain and replace IP switches in MetroCluster IP configurations.
          url: /maintain/concept_performing_ip_switch_maintenance.html
        - title: ATTO bridges
          summary: Maintain and replace ATTO FC-to-SAS bridges in MetroCluster FC configurations.
          url: /maintain/concept_performing_fc_to_sas_bridge_maintenance.html
        - title: Drive shelves
          summary: Hot-add and non-disruptively replace drive shelves MetroCluster FC configurations.
          url: /maintain/index.html
    - title: RCF files
      links:
        - title: MetroCluster RCF files
          summary: Generate or download RCF files for your MetroCluster switches.
          url: https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/docsandkb-tab
    - title: Learn more
      links:
        - title: NetApp MetroCluster Solution Architecture and Design | TR-4705
          summary: Understand the MetroCluster FC solution.
          url: https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf
        - title: MetroCluster IP Solution Architecture and Design | TR-4689
          summary: Understand the MetroCluster IP solution.
          url: https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf
    - title: Upgrade, expand, and convert
      links:
        - title: Upgrade and refresh hardware
          summary: Upgrade the controllers in a MetroCluster configuration.
          url: /upgrade/index.html
        - title: Expand
          summary: Add controllers to the MetroCluster configurations to  create a four-node or eight-node configuration.
          url: /upgrade/index.html
        - title: Convert MetroCluster FC to  MetroCluster IP
          summary: Transition an existing MetroCluster IP configuration to a MetroCluster IP configurations.
          url: /transition/index.html
        - title: Upgrade MetroCluster IP RCF files
          summary: Upgrade the switch RCF files in MetroCluster IP configurations.
          url: /maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html
    - title: ATTO bridge firmware
      links:
        - title: FibreBridge 7600N
          summary: Download firmware for a 7600 bridge.
          url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7600N
        - title: FibreBridge 7500N
          summary: Download firmware for a 7500 bridge.
          url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+7500N
        - title: FibreBridge 6500N
          summary: Download firmware for a 6500 bridge.
          url: https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Protocol+Bridge&platform=ATTO+FibreBridge+6500N
    - title: More resources
      links:
        - title: NetApp Config Advisor
          summary: Verify your configuration and cabling.
          url: https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor
        - title: NetApp Hardware Universe
          summary: Verify that your hardware is supported.
          url: https://hwu.netapp.com/
        - title: NetApp Support Knowledge Base
          summary: Search for answers for your support questions.
          url: https://kb.netapp.com/
