---
permalink: transition/concept_choosing_your_transition_procedure_mcc_transition.html
sidebar: sidebar
keywords: select, transition, procedure, depend, exist, metrocluster, fc, configuration, choosing, choose
summary: You must select a transition procedure depending on your existing MetroCluster FC configuration.
---
= Choosing your transition procedure
:icons: font
:imagesdir: ../media/

[.lead]
You must select a transition procedure depending on your existing MetroCluster FC configuration.

A transition procedure replaces the back-end FC switch fabric or FC-VI connection with an IP switch network. The exact procedure depends on your starting configuration.

The original platforms and FC switches (if present) are retired at the end of the transition procedure.

[cols="20,20,20,40"]
|===

h| Starting configuration  h| Disruptive or nondisruptive h| Requirements h| Procedure

a| Four node
a| Nondisruptive
a| New storage shelves are supported on new platforms.
a| link:concept_requirements_for_fc_to_ip_transition_mcc.html[Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)]

a| Two node
a| Disruptive
a| New storage shelves are supported on both original and new platforms.
a| link:task_disruptively_transition_from_a_two_node_mcc_fc_to_a_four_node_mcc_ip_configuration.html[Disruptively transitioning from a two-node MetroCluster FC to a four-node MetroCluster IP configuration (ONTAP 9.8 and later)]

a| Two node
a| Disruptive
a| New storage shelves are supported on both original and new platforms. Old storage shelves must be retired.
a| link:task_disruptively_transition_while_move_volumes_from_old_shelves_to_new_shelves.html[Disruptively transitioning from MetroCluster FC to MetroCluster IP when retiring storage shelves (ONTAP 9.8 and later)]

a| Two node
a| Disruptive
a| Old storage shelves are not supported on new platforms. Old storage shelves must be retired.
a| link:task_disruptively_transition_when_exist_shelves_are_not_supported_on_new_controllers.html[Disruptively transitioning when existing shelves are not supported on new controllers (ONTAP 9.8 and later)]
|===

// BURT 1448684, 13 JAN 2022
