---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html
sidebar: sidebar
keywords: nondisruptive, transition, fc, ip
summary: 'Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.'
---
= Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)
:icons: font
:imagesdir: ../media/

[.lead]
You can perform nondisruptive transitions of workloads and data from an existing MetroCluster FC configuration to a new MetroCluster IP configuration.

Beginning with ONTAP 9.13.1, this procedure is supported in MetroCluster IP configurations in which the MetroCluster and the drive shelves are connected to the same IP switches (a shared storage switch configuration). 

Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.

Beginning with ONTAP 9.8, you can perform a nondisruptive transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration.

* This procedure is nondisruptive.
+
The MetroCluster configuration can continue to serve data during the operation.

* This procedure applies only to four-node and eight-node MetroCluster FC configurations.
+
If you have a two-node MetroCluster FC configuration, see link:concept_choosing_your_transition_procedure_mcc_transition.html[Choosing your transition procedure].

* This procedure describes the steps required to transition one four-node FC DR group. If you have an eight-node configuration (two FC DR groups), you must repeat the entire procedure for each FC DR group.

* You must meet all requirements and follow all steps in the procedure.

.Important information

During the transition, refresh, and expand procedures, you might add a new platform model to your MetroCluster configuration once or multiple times. At any stage during these procedures, if your existing MetroCluster configuration contains a platform that uses shared cluster/HA ports, you cannot add a platform that uses shared MetroCluster/HA ports to the configuration without upgrading your ONTAP version to: 

Use the following information to determine if your platform uses shared cluster/HA or shared MetroCluster/HA ports

include::../_include/shared-metrocluster-ha-or-shared-cluster-ha.adoc[]

