---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html
sidebar: sidebar
keywords: nondisruptive, transition, fc, ip
summary: 'Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.'
---
= Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)
:icons: font
:imagesdir: ../media/

[.lead]
You can perform nondisruptive transitions of workloads and data from an existing MetroCluster FC configuration to a new MetroCluster IP configuration.

Beginning with ONTAP 9.13.1, this procedure is supported in MetroCluster IP configurations in which the MetroCluster and the drive shelves are connected to the same IP switches (a shared storage switch configuration). 

Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new eight-node MetroCluster IP configuration. You use this procedure to transition one four-node FC DR group, remove the empty FC DR group, and then repeat the procedure for the second FC DR group. 

Beginning with ONTAP 9.8, you can perform a nondisruptive transition of workloads and data from an existing four-node MetroCluster FC configuration to a new four-node MetroCluster IP configuration.  After you complete the transition, you can expand to an eight-node MetroCluster IP configuration if required. See link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html[Expand a MetroCluster IP configuration].

* This procedure is nondisruptive.
+
The MetroCluster configuration can continue to serve data during the operation.

* This procedure applies only to four-node and eight-node MetroCluster FC configurations.
+
If you have a two-node MetroCluster FC configuration, see link:concept_choosing_your_transition_procedure_mcc_transition.html[Choosing your transition procedure].

* This procedure describes the steps required to transition one four-node FC DR group. If you have an eight-node configuration (two FC DR groups), you must repeat the entire procedure for each FC DR group.
+
NOTE: When you add or remove a DR group as part of this procedure, you must verify that the DR group removal or addition was successful before adding or removing another DR group.

* You must meet all requirements and follow all steps in the procedure.

== Transition scenarios supported by this procedure

Review the following table to learn about the transition scenarios supported by this procedure.

NOTE: In all transition scenarios, you can only add or remove a single DR group at a time. After the DR group addition or removal is successful, you need to verify that the MetroCluster is healthy and operating normally before proceeding. 

[cols="2*",options="header"]
|===
| For this transition scenario...
| Perform the following...

a| Four-node FC to four-node IP configuration
a| Follow this procedure as written. 

a| Four-node FC to eight-node IP configuration
a| Requires adding one MetroCluster IP DR group. After you add the first MetroCluster IP DR group, check the overall health of the cluster, and repeat the steps for the second MetroCluster IP DR group.

When you are applying the reference configuration file (RCF) as part of this procedure, you can apply the four-node FC to eight-node IP RCF before you add the second DR group. You do not have to apply the four-node FC to four-node IP RCF first.

a| Eight-node FC to four-node IP configuration
a| Follow this procedure as written. During the transition, the MetroCluster configuration will expand from eight nodes to twelve nodes.
After the transition is complete and all MetroCluster FC nodes are unjoined, the final configuration will be a four-node MetroCluster IP configuration.

a| Eight-node FC to eight-node IP configuration
a| This transition requires adding one MetroCluster IP DR group to the cluster.

After you confirm the health of the twelve-node configuration, move data and LIFs (as required) from one of the MetroCluster FC DR groups to the MetroCluster IP DR group. When one of the MetroCluster FC DR groups is empty, remove that DR group and unjoin those nodes. The resulting configuration is an eight-node cluster consisting of one MetroCluster FC and one MetroCluster IP DR group. 

Then, add the second MetroCluster IP DR group to the cluster and transition data and LIFs (as required). When the last remaining MetroCluster FC DR group is empty, remove it and unjoin those nodes.

At any time during the transition, the number of nodes in the MetroCluster configuration does not exceed twelve nodes.
|===






== Important information when adding an older platform model

The following guidance is for an uncommon scenario where you need to add an older platform model (platforms released before ONTAP 9.15.1) to an existing MetroCluster configuration that contains a newer platform model (platforms released in ONTAP 9.15.1 or later). For an eight-node FC to IP transition, this guidance applies if you have transitioned your first FC DR group to a platform model introduced in ONTAP 9.15.1 or later and plan to transition the second DR group to a platform introduced before ONTAP 9.15.1.

If your existing MetroCluster configuration contains a platform that uses *shared cluster/HA ports* (platforms released in ONTAP 9.15.1 or later), you cannot add a platform that uses *shared MetroCluster/HA ports* (platforms released before ONTAP 9.15.1) without upgrading all nodes in the configuration to ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later. 

[CAUTION] 
====
Adding an older platform model that uses *shared/MetroCluster HA ports* to a MetroCluster containing a newer platform model that uses *shared cluster/HA ports* is an uncommon scenario and most combinations are not affected. 
==== 

Use the following table to verify whether your combination is affected. If your existing platform is listed in the first column, and the platform you want to add to the configuration is listed in the second column, all nodes in the configuration must be running ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later to add the new DR group.

[cols="20,20,20,20,20" options="header"]
|===
2+a| If your existing MetroCluster contains..
2+a| And the platform you're adding is...
a| Then... 
a|

An AFF system using *shared cluster/HA ports*: 

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K
a|

A FAS system using *shared cluster/HA ports*: 

* FAS50
* FAS70
* FAS90
a|

An AFF system using *shared MetroCluster/HA ports*: 

* AFF A150, ASA A150 
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900
a|
A FAS system using *shared MetroCluster/HA ports*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500
|
Before you add the new platform to your existing MetroCluster configuration, upgrade all nodes in the existing and new configuration to ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later.

|===

// 2025 Oct 09, GH 506
// 2025 June 06, ONTAPDOC-2897