---
permalink: transition/concept_requirements_for_fc_to_ip_transition_2n_mcc_transition.html
sidebar: sidebar
keywords: 
summary: 'Before starting the transition process, you must make sure the configuration meets the requirements.'
---
= General requirements for disruptive FC-to-IP transition
:icons: font
:imagesdir: ../media/

[.lead]
Before starting the transition process, you must make sure the configuration meets the requirements.

The existing MetroCluster FC configuration must meet the following requirements:

* It must be a two-node configuration and all nodes must be running ONTAP 9.8 or later.
+
It can be a two-node fabric-attached or stretched MetroCluster.

* It must meet all requirements and cabling as described in the _MetroCluster Installation and Configuration Guides_.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html[Stretch MetroCluster installation and configuration]

* It cannot be configured with NetApp Storage Encryption (NSE).
* The MDV volumes cannot be encrypted.

You must have remote console access for all six nodes from either MetroCluster site or plan for travel between the sites as required by the procedure.
