---
permalink: transition/concept_requirements_for_fc_to_ip_transition_mcc.html
sidebar: sidebar
keywords: start, transition, process, configuration, requirement, nondisruptive, fc-to-ip
summary: Before starting the transition process, you must make sure the configuration meets the requirements.
---
= Requirements for nondisruptive FC-to-IP transition
:icons: font
:imagesdir: ../media/

[.lead]
Before starting the transition process, you must make sure the configuration meets the requirements.

* It must be a four-node configuration and all nodes must be running ONTAP 9.8 or later.
* The existing and new platforms must be a supported combination for transition.
+
link:concept_supported_platforms_for_transition.html[Supported platforms for nondisruptive transition]

* It must support a switched cluster configuration.
+
https://hwu.netapp.com[NetApp Hardware Universe]

* It must meet all requirements and cabling as described in the _MetroCluster Installation and Configuration_ procedures.
+
link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
+
link:../install-stretch/concept_considerations_differences.html[Stretch MetroCluster installation and configuration]

// BURT 1448684, 01 FEB 2022
