---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html
sidebar: sidebar
keywords: nondisruptive, transition, fc, ip
summary: 'Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.'
---
= Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)
:icons: font
:imagesdir: ../media/

[.lead]
You can perform nondisruptive transitions of workloads and data from an existing MetroCluster FC configuration to a new MetroCluster IP configuration.

Beginning with ONTAP 9.13.1, this procedure is supported in MetroCluster IP configurations in which the MetroCluster and the drive shelves are connected to the same IP switches (a shared storage switch configuration). 

Beginning with ONTAP 9.13.1, you can perform a nondisruptive transition of workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.

Beginning with ONTAP 9.8, you can perform a nondisruptive transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration.

* This procedure is nondisruptive.
+
The MetroCluster configuration can continue to serve data during the operation.

* This procedure applies only to four-node and eight-node MetroCluster FC configurations.
+
If you have a two-node MetroCluster FC configuration, see link:concept_choosing_your_transition_procedure_mcc_transition.html[Choosing your transition procedure].

* This procedure describes the steps required to transition one four-node FC DR group. If you have an eight-node configuration (two FC DR groups), you must repeat the entire procedure for each FC DR group.

* You must meet all requirements and follow all steps in the procedure.

.Important information

During the transition, refresh, and expand procedures, you might add a new platform model to your MetroCluster configuration. At any stage during these procedures, if your existing MetroCluster configuration contains a platform that uses *shared cluster/HA ports*, you cannot add a platform that uses *shared MetroCluster/HA ports* to the configuration without upgrading your ONTAP version to ONTAP 9.15.1P3. 

Before you start this procedure, review the information in the following table carefully. If your existing platform is listed in the first column, and the platform you want to add to the configuration is listed in the second column, all nodes in the configuration must be running ONTAP 9.15.1P3 or later to support this procedure. 

CAUTION: The existing platform and the platform you want to add to the configuration must both be running ONTAP 9.15.1P3 or later. 

[cols="20,20,20,20,20" options="header"]
|===
2+a| If your existing MetroCluster contains..
2+a| And the platform you're adding is...
a| Then... 
a|

An AFF system using *shared cluster/HA ports*: 

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K
a|

A FAS system using *shared cluster/HA ports*: 

* FAS50
* FAS70
* FAS90
a|

An AFF system using *shared MetroCluster/HA ports*: 

* AFF A150, ASA A150 
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900
a|
A FAS system using *shared MetroCluster/HA ports*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500
|
Upgrade all nodes in the existing and new configuration to ONTAP 9.15.1P3 before you add the new platform to your existing MetroCluster configuration.

|===

