---
permalink: transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html
sidebar: sidebar
keywords: nondisruptive, transition, fc, ip
summary: 'Beginning with ONTAP 9.8, nondisruptive transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration is supported.'
---
= Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.8, nondisruptive transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration is supported.

* This procedure is supported on systems running ONTAP 9.8 and later.
* This procedure is nondisruptive.
+
The MetroCluster configuration can continue to serve data during the operation.

* This procedure applies only to four-node MetroCluster FC configurations.
+
If you have a two-node MetroCluster FC configuration, see link:concept_choosing_your_transition_procedure_mcc_transition.html[Choosing your transition procedure].

* You must meet all requirements and follow all steps in the procedure.
