---
permalink: transition/concept_deciding_which_procedure_to_use_mcc_upgrade_transition_and_expansion_guide.html
sidebar: sidebar
keywords: difference, metrocluster, upgrade, expansion, transition, procedure, match, goal, deciding, decide
summary: You must understand the differences between a MetroCluster upgrade, expansion, or transition and choose the procedure that matches your goal.
---
= Deciding which procedure to use
:icons: font
:imagesdir: ../media/

[.lead]
You must understand the differences between a MetroCluster upgrade, expansion, or transition and choose the procedure that matches your goal.

* *Upgrade*
+
In an upgrade procedure, you are replacing the controller modules with a new model of controller module.

 ** The old controller modules are retired.
 ** The storage is not upgraded.
 ** The storage switch infrastructure technology is not changed.
+
It remains as a MetroCluster IP, fabric-attached MetroCluster or stretch MetroCluster configuration.
+
link:../upgrade/concept_choosing_an_upgrade_method_mcc.html[Choosing an upgrade or refresh method]

* *Refresh*
+
In a refresh procedure, you are replacing the controller modules with a new model of controller module and also replacing the storage shelves.

 ** The old controller modules and storage shelves are retired.
 ** The storage switch infrastructure technology is not changed, unless new switches are required to accommodate the new platform models.
+
The configuration remains as its original type:

  *** MetroCluster IP
  *** Fabric-attached MetroCluster
  *** Stretch MetroCluster configuration
  +
  link:../upgrade/concept_choosing_an_upgrade_method_mcc.html[Choosing an upgrade or refresh method]

* *Transition*
+
In a transition procedure, the backend switch infrastructure is changed from FC switches or connections to IP switches, and the platform models are replaced.

 ** New controller modules are added to the configuration.
 ** The original controller modules are retired after the procedure.
 ** If the original configuration used cluster interconnect switches, they can be reused, depending on the switch and platform models.
 ** The storage can be reused or replaced, depending on the platform models.
+
If the storage shelves are not reused, data is moved from the old shelves to the new shelves.
+
link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html

* *Expansion*
+
In an expansion procedure, additional nodes and storage are added to the MetroCluster FC configuration.

 ** link:../upgrade/task_expand_a_two_node_mcc_fc_configuration_to_a_four_node_fc_configuration_supertask.html[Expanding a two-node MetroCluster FC configuration to a four-node configuration]
 ** link:../upgrade/task_expand_a_four_node_mcc_fc_configuration_to_an_eight_node_configuration.html[Expanding a four-node MetroCluster FC configuration to an eight-node configuration]
+
REMOVED LINK FOR MIGRATION
