---
permalink: transition/concept_considerations_for_using_existing_ip_switches.html
sidebar: sidebar
keywords: ensure, ip, switch, support, exist, model, metrocluster, fc, configuration, ip, consideration, support
summary: You must ensure the IP switches are supported. If the existing switch model is supported by both the original MetroCluster FC configuration and the new MetroCluster IP configuration, you can reuse the existing switches.
---
= Considerations for IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You must ensure the IP switches are supported. If the existing switch model is supported by both the original MetroCluster FC configuration and the new MetroCluster IP configuration, you can reuse the existing switches.

== Supported switches

You must use NetApp-provided switches.

* The use of MetroCluster-compliant switches (switches that are not validated and provided by NetApp) is not supported for transition.
* The IP switches must be supported as a cluster switch by both the MetroCluster FC configuration and the MetroCluster IP configuration.
* The IP switches can be reused in the new MetroCluster IP configuration if the MetroCluster FC is a switched cluster and the IP cluster switches are supported by the MetroCluster IP configuration.
* New IP switches are usually used in the following cases:
 ** The MetroCluster FC is a switchless cluster, so new switches are required.
 ** The MetroCluster FC is a switched cluster but the existing IP switches are not supported in the MetroCluster IP configuration.
 ** You want to use different switches for the MetroCluster IP configuration.

[CAUTION] 
====
If you are using shared storage MetroCluster switches, you can only transition to a four-node MetroCluster IP configuration. Transitioning to an eight-node MetroCluster IP configuration using shared storage MetroCluster switches is not supported. After you complete the transition to a four-node MetroCluster IP configuration, you can link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html[expand to an eight-node MetroCluster IP configuration].
==== 

See the https://hwu.netapp.com[Hardware Universe^] for information on platform models and switch support.

// 2025 Jan 16, ONTAPDOC-2632