---
permalink: transition/task_configuring_the_mcc_ip_nodes_and_disabling_transition.html
sidebar: sidebar
keywords: 
summary: 'You must implement the MetroCluster IP connections, refresh the MetroCluster configuration, and disable transition mode.'
---
= Configuring the MetroCluster IP nodes and disabling transition
:icons: font
:imagesdir: ../media/

[.lead]
You must implement the MetroCluster IP connections, refresh the MetroCluster configuration, and disable transition mode.

. Form the new nodes into a DR group by issuing the following commands from controller node_A_1-IP `metrocluster configuration-settings dr-group create -partner-cluster peer-cluster-name -local-node local-controller-name -remote-node remote-controller-name``metrocluster configuration-settings dr-group show`
. Create MetroCluster IP interfaces (node_A_1-IP, node_A_2-IP, node_B_1-IP, node_B_2-IP) -- two interfaces need to be created per controller; eight interfaces in total, using the following command: `metrocluster configuration-settings interface create -cluster-name cluster-name -home-node controller-name -home-port port -address ip-address -netmask netmask``metrocluster configuration-settings interface show`
. Perform the MetroCluster connect operation from controller node_A_1-IP to connect the MetroCluster sites -- this operation can take a few minutes to complete. `metrocluster configuration-settings connection connect`
. Verify that the remote cluster disks are visible from each controller via the iSCSI connections: `disk show`
+
You should see the remote disks belonging to the other nodes in the configuration.

. Mirror the root aggregate for node_A_1-IP and node_B_1-IP: `aggregate mirror -aggregate root-aggr`
. Assign disks for node_A_2-IP and node_B_2-IP.
+
Pool 1 disk assignments where already made for node_A_1-IP and node_B_1-IP when the boot_after_mcc_transtion command was issued at the boot menu.

 .. Issue the following commands on node_A_2-IP: `+disk assign disk1disk2disk3 ... diskn -sysid node_B_2-IP-controller-sysid -pool 1 -force+`
 .. Issue the following commands on node_B_2-IP: `+disk assign disk1disk2disk3 ... diskn -sysid node_A_2-IP-controller-sysid -pool 1 -force+`

. Confirm ownership has been updated for the remote disks: `disk show`
. If necessary, refresh the ownership information using the following commands:
 .. Go to advanced privilege mode and enter y when prompted to continue: `set priv advanced`
 .. Refresh disk ownership: `disk refresh-ownership controller-name`
 .. Return to admin mode: `set priv admin`
. Mirror the root aggregates for node_A_2-IP and node_B_2-IP: `aggregate mirror -aggregate root-aggr`
. Verify that the aggregate re-synchronization has completed for root and data aggregates: `aggr show``aggr plex show`
+
The resync can take some time but must complete before proceeding with the following steps.

. Refresh the Metrocluster configuration to incorporate the new nodes:
 .. Go to advanced privilege mode and enter y when prompted to continue: `set priv advanced`
 .. Refresh the configuration:
+
|===
| If you have configured...| Issue this command...
a|
A single aggregate in each cluster:
a|
`metrocluster configure -refresh true -allow-with-one-aggregate true`
a|
More than a single aggregate in each cluster
a|
`metrocluster configure -refresh true`
|===

 .. Return to admin mode: `set priv admin`
. Disable MetroCluster transition mode:
 .. Enter advanced privilege mode and enter y when prompted to continue: `set priv advanced`
 .. Disable transition mode: `metrocluster transition disable`
 .. Return to admin mode: `set priv admin`
