---
permalink: transition/task_gathering_information_before_the_transition_2n_mcc_transition.html
sidebar: sidebar
keywords: 
summary: 'Before transitioning, you must gather information for each of the nodes.'
---
= Gathering information from the existing controller modules before the transition
:icons: font
:imagesdir: ../media/

[.lead]
Before transitioning, you must gather information for each of the nodes.

This task is performed on the existing nodes:

* node_A_1-FC
* node_B_1-FC

. Gather the output from the following commands.
+
|===
| Category| Commands
a|
License
a|
system license show
a|
Shelves, numbers of disks in each shelf, flash storage details, memory, NVRAM, and network cards
a|
system node run -node node_name sysconfig
a|
Cluster network and node management LIFs
a|
system node run -node node_name sysconfig network interface show -role cluster,node-mgmt,data
a|
SVM information
a|
vserver show
a|
Protocol information
a|
    nfs show
+
iscsi show
+
cifs show
a|
Physical ports
a|
    network port show -node node_name -type physical
+
network port show
a|
Failover Groups
a|
    network interface failover-groups show -vserver vserver_name
+
Record the names and ports of failover groups that are not clusterwide.
a|
VLAN configuration
a|
network port vlan show -node node_name     Record each network port and VLAN ID pairing.
a|
Interface group configuration
a|
network port ifgrp show -node node_name -instance     Record the names of the interface groups and the ports assigned to them.
a|
Broadcast domains
a|
network port broadcast-domain show
a|
IPspace
a|
network ipspace show
a|
Volume info
a|
    volume show
+
volume show -fields encrypt
a|
Aggregate Info
a|
    storage aggregate show
+
storage aggr encryption show
+
storage aggregate object-store show
a|
Disk ownership information
a|
    storage aggregate show
+
storage aggr encryption show

storage aggregate object-store show
    a|
    Encryption
    a|
        storage failover mailbox-disk show

....
 security key-manager backup show

 Also preserve the passphrase used to enable key-manager. In the case of external key-manager you will need the authentication information for the client and server.

 security key-manager show

 security key-manager external show

 systemshell local kenv kmip.init.ipaddr ip-address

 systemshell local kenv kmip.init.netmask netmask

 systemshell local kenv kmip.init.gateway gateway

 systemshell local kenv kmip.init.interface interface


|===
....
