---
permalink: transition/task_completing_configuration_of_the_nodes_2n_mcc_transition.html
sidebar: sidebar
keywords: 
summary: 'There are miscellaneous configuration steps that can be performed prior to completing the procedures. Some of these steps are optional.'
---
= Completing configuration of the nodes
:icons: font
:imagesdir: ../media/

[.lead]
There are miscellaneous configuration steps that can be performed prior to completing the procedures. Some of these steps are optional.

. Configure the service processor: `system service-processor network modify`
. Set up autosupport on the new nodes: `system node autosupport modify`
. The controllers can be optionally renamed as part of the transition. The following command is used to rename a controller: `system node rename -node <old-name> -newname <new-name>`
+
The renaming operation can take a few minutes to complete. Confirm that any name changes have propagated to each node prior to continuing with other steps using the system show -fields node command.

. Configure a monitoring service as desired.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-33D59B4E-6134-4CD4-9844-440E5114D1ED.html[Considerations for using ONTAP Mediator or MetroCluster Tiebreaker]
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-2A6C990C-E7D5-4184-844D-19142C89E67F.html[Configuring the ONTAP Mediator service for unplanned automatic switchover]
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[Tiebreaker Software Installation and Configuration Guide]
