---
permalink: transition/task_preparing_the_mcc_ip_controllers_fc_to_ip_transition_2n_disruptive.html
sidebar: sidebar
keywords: 
summary: 'You must prepare the four new MetroCluster IP nodes and install the correct ONTAP version.'
---
= Preparing the MetroCluster IP controllers
:icons: font
:imagesdir: ../media/

[.lead]
You must prepare the four new MetroCluster IP nodes and install the correct ONTAP version.

This task must be performed on each of the new nodes:

* node_A_1-IP
* node_A_2-IP
* node_B_1-IP
* node_B_2-IP

The nodes should be connected to any *new* storage shelves. They must *not* be connected to the existing storage shelves containing data.

These steps can be performed now, or later in the procedure when the controllers and shelves are racked. In any case, you must make sure you clear the configuration and prepare the nodes *before* connecting them to the existing storage shelves and *before* making any configuration changes to the MetroCluster FC nodes.

NOTE: Do not perform these steps with the MetroCluster IP controllers connected to the existing storage shelves that were connected to the MetroCluster FC controllers.

In these steps, you clear the configuration on the nodes and clear the mailbox region on new drives.

. Connect the controller modules to the new storage shelves.
. In Maintenance mode, display the HA state of the controller module and chassis: `ha-config show`
+
The HA state for all components should be mccip.

. If the displayed system state of the controller or chassis is not correct, set the HA state: `ha-config modify controller mccip``ha-config modify chassis mccip`
. Exit Maintenance mode: `halt`
+
After you run the command, wait until the node stops at the LOADER prompt.

. Repeat the following substeps on all four nodes to clear the configuration:
 .. Set the environmental variables to default values: `set-defaults`
 .. Save the environment: `saveenv``bye`
. Repeat the following substeps to boot all four nodes using the 9a option on the boot menu.
 .. At the LOADER prompt, launch the boot menu: `boot_ontap menu`
 .. At the boot menu, select option *9a* to reboot the controller.
. Boot each of the four nodes to Maintenance mode using option *5* on the boot menu.
. Record the system ID and from each of the four nodes: `sysconfig`
. Repeat the following steps on node_A_1-IP and node_B_1-IP.
 .. Assign ownership of all disks local to each site: `disk assign adapter.xx.*`
 .. Repeat the previous step for each HBA with attached drive shelves on node_A_1-IP and node_B_1-IP.
. Repeat the following steps on node_A_1-IP and node_B_1-IP to clear the mailbox region on each local disk.
 .. Destroy the mailbox region on each disk: `mailbox destroy local``mailbox destroy partner`
. Halt all four controllers: `halt`
. On each controller, display the boot menu: `boot_ontap menu`
. On each of the four controllers, clear the configuration: `wipeconfig`
+
When the wipeconfig operation completes, the node automatically returns to the boot menu.

. Repeat the following substeps to again boot all four nodes using the 9a option on the boot menu.
 .. At the LOADER prompt, launch the boot menu: `boot_ontap menu`
 .. At the boot menu, select option *9a* to reboot the controller.
 .. Let the controller module complete booting before moving to the next controller module.

+
After 9a completes, the nodes automatically return to the boot menu.
. Power off the controllers.
