---
permalink: transition/task_apply_rcfs.html
sidebar: sidebar
keywords: Generating and applying RCFs to the new IP switches, review, requirement, preparing, prepare, transition, perform, procedure, order, completing, complete, step, task, moving, move, controller, storage, shelves, shelf, exist, configuration, direct, metrocluster, fc, ip, verify, health, removing, remove, tiebreaker, monitor, software, generating, generate, apply, rcf, switch, controller, configure, prepare, preparing
summary: If you are using new IP switches for the MetroCluster IP configuration, you must configure the switches with a custom RCF file.
---
= Generating and applying RCFs to the new IP switches
:icons: font
:imagesdir: ../media/

[.lead]
If you are using new IP switches for the MetroCluster IP configuration, you must configure the switches with a custom RCF file.

This task is required if you are using new switches.

If you are using existing switches, proceed to link:task_move_cluster_connections.html[Moving the local cluster connections].

. Install and rack the new IP switches.
. Prepare the IP switches for the application of the new RCF files.
+
Follow the steps in the section for your switch vendor:
+
* link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults[Reset the Broadcom IP switch to factory defaults]
* link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults[Reset the Cisco IP switch to factory defaults]
* link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults[Reset the NVIDIA IP SN2100 switch to factory defaults] 

. Update the firmware on the switch to a supported version, if necessary.
. Use the RCF generator tool to create the RCF file depending on your switch vendor and the platform models, and then update the switches with the file.
+
Follow the steps in the section for your switch vendor:
+
* link:../install-ip/task_switch_config_broadcom.html[Download and install the Broadcom IP RCF files]
* link:../install-ip/task_switch_config_cisco.html[Download and install the Cisco IP RCF files]
* link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software[Download and install the NVIDIA RCF files]

// BURT 1448684, 01 FEB 2022
