---
permalink: upgrade/concept_choosing_an_upgrade_method_mcc.html
sidebar: sidebar
keywords: metrocluster, upgrade, choose, upgrade, refresh, method
summary: 'The upgrade or refresh procedure you use depends on the platform model, scope of the upgrade, and type of MetroCluster configuration.'
---
= Start here: Choose between controller upgrade, system refresh, or expansion
:icons: font
:imagesdir: ../media/

[.lead]
Depending on the scope of the equipment upgrade, you choose a controller upgrade procedure, a system refresh procedure, or an expansion procedure. 

* Controller upgrade procedures apply only to the controller modules. The controllers are replaced with a new controller model.
+
The storage shelf models are not upgraded.

** In switchover and switchback procedures, the MetroCluster switchover operation is used to provide nondisruptive service to clients while the controller modules on the partner cluster are upgraded.
** In an ARL-based controller upgrade procedure, the aggregate relocation operations are used to nondisruptively move data from the old configuration to the new, upgraded configuration.

* Refresh procedures apply to the controllers and the storage shelves.
+
In the refresh procedures, new controllers and shelves are added to the MetroCluster configuration, creating a second DR group, and then data is nondisruptively migrated to the new nodes.
+
The original controllers are then retired.

* Expansion procedures add additional controllers and shelves to the MetroCluster configuration without removing any.
+
The procedure you use depends on the type of MetroCluster and number of existing controllers.

CAUTION: If SVM migration is in progress, wait until all migration processes are complete before initiating the controller upgrade or system refresh procedures. Do not start new SVM migrate operations during the upgrade or refresh process.

[cols="2,5"]
|===

h| Upgrade type h| Go to...

a|

Controller upgrade

a|

link:../upgrade/concept_choosing_controller_upgrade_mcc.html[Choose a controller upgrade procedure]
a|

System refresh

a|

link:../upgrade/concept_choosing_tech_refresh_mcc.html[Choose a system refresh procedure]

a|

Expansion

a|

* link:../upgrade/task_expand_a_two_node_mcc_fc_configuration_to_a_four_node_fc_configuration_supertask.html[Two-node MetroCluster to four]
* link:../upgrade/task_expand_a_four_node_mcc_fc_configuration_to_an_eight_node_configuration.html[Four-node MetroCluster FC to eight]
* link:../upgrade/task_expand_a_four_node_mcc_ip_configuration.html[Four-node MetroCluster IP to eight]

|===

// 2024 Nov 11, ONTAPDOC-2406