---
permalink: upgrade/concept_choosing_tech_refresh_mcc.html
sidebar: sidebar
keywords: metrocluster, upgrade, choose, upgrade, refresh, method
summary: 'The refresh procedure you use depends on the platform model, scope of the upgrade, and type of MetroCluster configuration.'
---
= Choosing a system refresh method
:icons: font
:imagesdir: ../media/

[.lead]
The system refresh procedure you use depends on the platform model, scope of the upgrade, and type of MetroCluster configuration.
Refresh procedures apply to the controllers and the storage shelves.
In the refresh procedures, new controllers and shelves are added to the MetroCluster configuration,
creating a second DR group, and then data is nondisruptively migrated to the new nodes.
The original controllers are then retired.

[%header,cols="2,1,1,2"]
|===
a| Refresh method
a| Config type
a| ONTAP support
a| Procedure

a|

* Method: Expand the MetroCluster configuration and then remove the old nodes
a|
Four-node
a|
9.6 and later
a|
link:task_refresh_4n_mcc_fc.html[Refreshing a four-node MetroCluster FC configuration]

a|
* Method: Expand the MetroCluster configuration and then remove the old nodes
a|
Four-node
a|
9.8
a|
link:task_refresh_4n_mcc_ip.html[Refreshing a four-node MetroCluster IP configuration (ONTAP 9.8 and later)]

|===


// BURT 1491888  August 8th, 2022
