---
permalink: upgrade/expand-four-node-mcc-ip-requirements.html
sidebar: sidebar
keywords: metrocluster, upgrade, expand, expansion, four, node, ip, configuration, requirements, dr group
summary: 'Review the requirements and restrictions before expanding your MetroCluster IP configuration.'
---
= Requirements for expanding a MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
Depending on your ONTAP version, you can expand your MetroCluster IP configuration by adding four new nodes as a new DR group.

Beginning with ONTAP 9.13.1, you can temporarily expand an eight-node MetroCluster configuration to refresh the controllers and storage. See link:task_refresh_4n_mcc_ip.html[Refreshing a four-node or an eight-node MetroCluster IP configuration (ONTAP 9.8 and later)] for more information.

Beginning with ONTAP 9.9.1, you can add four new nodes to the MetroCluster IP configuration as a second DR group. This creates an eight-node MetroCluster configuration.

.Important information if you are adding an older platform model

The following guidance is for an uncommon scenario where you need to add an older platform model (platforms released before ONTAP 9.15.1) to an existing MetroCluster configuration that contains a newer platform model (platforms released in ONTAP 9.15.1 or later). 

If your existing MetroCluster configuration contains a platform that uses *shared cluster/HA ports* (platforms released in ONTAP 9.15.1 or later), you cannot add a platform that uses *shared MetroCluster/HA ports* (platforms released before ONTAP 9.15.1) without upgrading all nodes in the configuration to ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later. 

[CAUTION] 
====
Adding an older platform model that uses *shared MetroCluster/HA ports* to a MetroCluster containing a newer platform model that uses *shared cluster/HA ports* is an uncommon scenario and most combinations are not affected. 
==== 

Use the following table to verify whether your combination is affected. If your existing platform is listed in the first column, and the platform you want to add to the configuration is listed in the second column, all nodes in the configuration must be running ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later to add the new DR group.

[cols="20,20,20,20,20" options="header"]
|===
2+a| If your existing MetroCluster contains..
2+a| And the platform you're adding is...
a| Then... 
a|

An AFF system using *shared cluster/HA ports*: 

* AFF A20
* AFF A30
* AFF C30
* AFF A50
* AFF C60
* AFF C80
* AFF A70
* AFF A90
* AFF A1K
a|

A FAS system using *shared cluster/HA ports*: 

* FAS50
* FAS70
* FAS90
a|

An AFF system using *shared MetroCluster/HA ports*: 

* AFF A150, ASA A150 
* AFF A220
* AFF C250, ASA C250
* AFF A250, ASA A250
* AFF A300
* AFF A320
* AFF C400, ASA C400
* AFF A400, ASA A400
* AFF A700
* AFF C800, ASA C800
* AFF A800, ASA A800
* AFF A900, ASA A900
a|
A FAS system using *shared MetroCluster/HA ports*:

* FAS2750
* FAS500f
* FAS8200
* FAS8300
* FAS8700
* FAS9000
* FAS9500
|
Before you add the new platform to your existing MetroCluster configuration, upgrade all nodes in the existing and new configuration to ONTAP 9.15.1P11 or ONTAP 9.16.1P4 or later.

|===

// 2025 Oct 09, GH 506
// 2025 June 06, ONTAPDOC-2897

.Before you begin

* The old and new nodes must be running the same version of ONTAP.

* This procedure describes the steps required to add one four-node DR group to an existing MetroCluster IP configuration. If you are refreshing an eight-node configuration, you must repeat the entire procedure for each DR group, adding one at a time.

* Verify that the old and new platform models are supported for platform mixing.
+
https://hwu.netapp.com[NetApp Hardware Universe^]

* Verify that the old and new platform models are both supported by the IP switches.
+
https://hwu.netapp.com[NetApp Hardware Universe^]

* If you are link:task_refresh_4n_mcc_ip.html[refreshing a four-node or an eight-node MetroCluster IP configuration], the new nodes must have enough storage to accommodate the data of the old nodes, along with adequate disks for root aggregates and spare disks.

* Verify that you have a default broadcast domain created on the old nodes. 
+
When you add new nodes to an existing cluster without a default broadcast domain, node management LIFs are created for the new nodes using universal unique identifiers (UUIDs) instead of the expected names. For more information, see the Knowledge Base article https://kb.netapp.com/onprem/ontap/os/Node_management_LIFs_on_newly-added_nodes_generated_with_UUID_names[Node management LIFs on newly-added nodes generated with UUID names^].

== Example naming in this procedure

This procedure uses example names throughout to identify the DR groups, nodes, and switches involved.

|===

h| DR groups h| cluster_A at site_A h| cluster_B at site_B
a|
dr_group_1-old
a|

* node_A_1-old
* node_A_2-old

a|

* node_B_1-old
* node_B_2-old

a|
dr_group_2-new
a|

* node_A_3-new
* node_A_4-new

a|

* node_B_3-new
* node_B_4-new

|===

.What's next?

link:expand-four-node-mcc-ip-supported-platforms.html[Review the supported platform combinations].

// 2024 Aug 13, ONTAPDOC-1988
