---
permalink: upgrade/task_prepare_cluster_ports_on_the_exist_controller.html
sidebar: sidebar
keywords: 
summary: 'Before installing a new controller module, you must configure cluster ports on the existing controller module so that the cluster ports can provide cluster communication with the new controller module.'
---
= Preparing cluster ports on an existing controller module
:icons: font
:imagesdir: ../media/

[.lead]
Before installing a new controller module, you must configure cluster ports on the existing controller module so that the cluster ports can provide cluster communication with the new controller module.

If you are creating a two-node switchless cluster (with no cluster network switches), you must enable the switchless cluster networking mode.

For detailed information about port, LIF, and network configuration in ONTAP, see the _Network Management Guide_.

. Determine which ports should be used as the node's cluster ports.
+
For a list of the default port roles for your platform, see the _Hardware Universe_ at https://hwu.netapp.com/[hwu.netapp.com]
+
The _Installation and Setup Instructions_ for your platform on the NetApp Support Site contains information about the ports for cluster network connections.

. For each cluster port, identify the port roles: `network port show`
+
In the following example, ports e0a, e0b, e0c, and e0d must be changed to cluster ports:
+
----
cluster_A::> network port show

Node: controller_A_1
Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link  MTU    Admin/Oper  Status
--------- ------------ ---------------- ----  ----   ----------- --------
e0M       Default      mgmt_bd_1500     up    1500   auto/1000   healthy
e0a       Default      Default          up    1500   auto/10000  healthy
e0b       Default      Default          up    1500   auto/10000  healthy
e0c       Default      Default          up    1500   auto/10000  healthy
e0d       Default      Default          up    1500   auto/10000  healthy
e0i       Default      Default          down  1500   auto/10     -
e0j       Default      Default          down  1500   auto/10     -
e0k       Default      Default          down  1500   auto/10     -
e0l       Default      Default          down  1500   auto/10     -
e2a       Default      Default          up    1500   auto/10000  healthy
e2b       Default      Default          up    1500   auto/10000  healthy
e4a       Default      Default          up    1500   auto/10000  healthy
e4b       Default      Default          up    1500   auto/10000  healthy
13 entries were displayed.
----

. For any data LIF that is using a cluster port as the home-port or current-port, modify the LIF to use a data port as its home-port: `network interface modify`
+
The following example changes the home port of a data LIF to a data port:
+
----
cluster1::> network interface modify -lif datalif1 -vserver vs1 -home-port e1b
----

. For each LIF that you modified, revert the LIF to its new home port: `network interface revert`
+
The following example reverts the LIF datalif1 to its new home port e1b:
+
----
cluster1::> network interface revert -lif datalif1 -vserver vs1
----

. Remove any VLAN ports using cluster ports as member ports and ifgrps using cluster ports as member ports.
 .. Delete VLAN ports: `network port vlan delete -node node-name -vlan-name portid-vlandid`
+
For example:
+
----
network port vlan delete -node node1 -vlan-name e1c-80
----

 .. Remove physical ports from the interface groups: `network port ifgrp remove-port -node node-name -ifgrp interface-group-name -port portid`
+
For example:
+
----
network port ifgrp remove-port -node node1 -ifgrp a1a -port e0d
----

 .. Remove VLAN and interface group ports from broadcast domain:: `network port broadcast-domain remove-ports -ipspace ipspace -broadcast-domain broadcast-domain-name -ports nodename:portname,nodename:portname,..`
 .. Modify interface group ports to use other physical ports as member as needed.: `ifgrp add-port -node node-name -ifgrp interface-group-name -port port-id`
. Verify that the port roles have changed: `network port show`
+
The following example shows that ports e0a, e0b, e0c, and e0d are now cluster ports:
+
----
Node: controller_A_1
Speed(Mbps) Health
Port      IPspace      Broadcast Domain Link  MTU    Admin/Oper  Status
--------- ------------ ---------------- ----  ----   ----------- --------
e0M       Default      mgmt_bd_1500     up    1500   auto/1000   healthy
e0a       Cluster      Cluster          up    9000   auto/10000  healthy
e0b       Cluster      Cluster          up    9000   auto/10000  healthy
e0c       Cluster      Cluster          up    9000   auto/10000  healthy
e0d       Cluster      Cluster          up    9000   auto/10000  healthy
e0i       Default      Default          down  1500   auto/10 -
e0j       Default      Default          down  1500   auto/10 -
e0k       Default      Default          down  1500   auto/10 -
e0l       Default      Default          down  1500   auto/10 -
e2a       Default      Default          up    1500   auto/10000  healthy
e2b       Default      Default          up    1500   auto/10000  healthy
e4a       Default      Default          up    1500   auto/10000  healthy
e4b       Default      Default          up    1500   auto/10000  healthy
13 entries were displayed.
----

. If your system is part of a switched cluster, create cluster LIFs on the cluster ports: `network interface create`
+
The following example creates a cluster LIF on one of the node's cluster ports. The -auto parameter configures the LIF to use a link-local IP address.
+
----
cluster1::> network interface create -vserver Cluster -lif clus1 -role cluster -home-node node0 -home-port e1a -auto true
----

. If you are creating a two-node switchless cluster, enable the switchless cluster networking mode:
 .. Change to the advanced privilege level from either node: `set -privilege advanced`
+
You can respond `y` when prompted whether you want to continue into advanced mode. The advanced mode prompt appears (`*>`).

 .. Enable the switchless cluster networking mode: `network options switchless-cluster modify -enabled true`
 .. Return to the admin privilege level: `set -privilege admin`

+
IMPORTANT: Cluster interface creation for the existing node in a two-node switchless cluster system is completed after cluster setup is completed through a netboot on the new controller module.

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html[Network and LIF management]
