---
permalink: upgrade/task_determining_the_new_cabling_layout_mcc_expansion.html
sidebar: sidebar
keywords: 
summary: 'You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.'
---
= Determining the new cabling layout
:icons: font
:imagesdir: ../media/

[.lead]
You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.

This task must be performed at each MetroCluster site.

. Use the _Fabric-attached MetroCluster Installation and Configuration Guide_ and create a cabling layout for your switch type, using the port usage for an eight-node MetroCluster configuration.
+
The FC switch port usage must match the usage described in the guide so that the Reference Configuration Files (RCFs) can be used.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
+
NOTE: If your environment cannot be cabled in such a way that RCF files can be used, you must manually configure the system according to instructions found in the _Fabric-attached MetroCluster Installation and Configuration Guide_. Do not use this procedure if the cabling cannot use RCF files.
