---
permalink: upgrade/task_install_and_cable_the_new_controller.html
sidebar: sidebar
keywords: metrocluster, upgrade, install, cable, new, controller, module
summary: 'You must physically install the new controller module in the chassis, and then cable it.'
---
= Installing and cabling the new controller module
:icons: font
:imagesdir: ../media/

[.lead]
You must physically install the new controller module in the chassis, and then cable it.

.Steps
. If you have an I/O expansion module (IOXM) in your system and are creating a single-chassis HA pair, you must uncable and remove the IOXM.
+
You can then use the empty bay for the new controller module. However, the new configuration will not have the extra I/O provided by the IOXM.

. Physically install the new controller module and, if necessary, install additional fans:
+

|===

h| If you are adding a controller module... h| Then perform these steps...

a|
To an empty bay to create a single-chassis HA pair and the system belongs to one of the following platforms:
a|

.. Remove the blank plate in the rear of the chassis that covers the empty bay that will contain the new controller module.
.. Gently push the controller module halfway into the chassis.
+
To prevent the controller module from automatically booting, do not fully seat it in the chassis until later in this procedure.

a|
In a separate chassis from its HA partner to create a dual-chassis HA pair when the existing configuration is in a controller-IOX module configuration.

 ** FAS8200
 ** 80xx

a|
Install the new system in the rack or system cabinet.
|===

. Cable the cluster network connections, as necessary:
.. Identify the ports on the controller module for the cluster connections.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-a320-install-setup/home.html[AFF A320 systems: Installation and setup]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842666[AFF A220/FAS2700 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2842668[AFF A800 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2469722[AFF A300 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769[FAS8200 Systems Installation and Setup Instructions]

.. If you are configuring a switched cluster, identify the ports that you will use on the cluster network switches.
+
See the _Clustered Data ONTAP Switch Setup Guide for Cisco Switches_, _NetApp 10G Cluster-Mode Switch Installation Guide_ or _NetApp 1G Cluster-Mode Switch Installation Guide_, depending on what switches you are using.

.. Connect cables to the cluster ports:

+

|===

h| If the cluster is... h| Then...

a|
A two-node switchless cluster
a|
Directly connect the cluster ports on the existing controller module to the corresponding cluster ports on the new controller module.
a|
A switched cluster
a|
Connect the cluster ports on each controller to the ports on the cluster network switches identified in substep b.
|===
