---
permalink: upgrade/task_moving_a_metadata_volume_in_mcc_configurations.html
sidebar: sidebar
keywords: 
summary: 'You can move a metadata volume from one aggregate to another aggregate in a MetroCluster configuration. You might want to move a metadata volume when the source aggregate is decommissioned or unmirrored, or for other reasons that make the aggregate ineligible.'
---
= Moving a metadata volume in MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
You can move a metadata volume from one aggregate to another aggregate in a MetroCluster configuration. You might want to move a metadata volume when the source aggregate is decommissioned or unmirrored, or for other reasons that make the aggregate ineligible.

* You must have cluster administrator privileges to perform this task.
* The target aggregate must be mirrored and should not be in the degraded state.
* The available space in the target aggregate must be larger than the metadata volume that you are moving.

. Set the privilege level to advanced: `set -privilege advanced`
. Identify the metadata volume that should be moved: `volume show MDV_CRS*`
+
----
Cluster_A::*> volume show MDV_CRS*
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_A
                       Node_A_1_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_14c00d4ac9f311e7922800a0984395f1_B
                       Node_A_2_aggr1
                                    online     RW         10GB     9.50GB    5%
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_A
                       Node_B_1_aggr1
                                    -          RW            -          -     -
Cluster_A
          MDV_CRS_15035e66c9f311e7902700a098439625_B
                       Node_B_2_aggr1
                                    -          RW            -          -     -
4 entries were displayed.

Cluster_A::>
----

. Identify an eligible target aggregate: `metrocluster check config-replication show-aggregate-eligibility`
+
The following command identifies the aggregates in cluster_A that are eligible to host metadata volumes:
+
----

Cluster_A::*> metrocluster check config-replication show-aggregate-eligibility

Aggregate Hosted Config Replication Vols Host Addl Vols Comments
------------ ------------------------------------------ -------------- --------
Node_A_1_aggr0 - false Root Aggregate
Node_A_2_aggr0 - false Root Aggregate
Node_A_1_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_A true -
Node_A_2_aggr1 MDV_CRS_1bc7134a5ddf11e3b63f123478563412_B true -
Node_A_1_aggr2 - true
Node_A_2_aggr2 - true
Node_A_1_Aggr3 - false Unable to determine available space of aggregate
Node_A_1_aggr5 - false Unable to determine mirror configuration
Node_A_2_aggr6 - false Mirror configuration does not match requirement
Node_B_1_aggr4 - false NonLocal Aggregate
----
+
NOTE: In the previous example, Node_A_1_aggr2 and Node_A_2_aggr2 are eligible.

. Start the volume move operation: `volume move start -vserver svm_name -volume metadata_volume_name -destination-aggregate destination_aggregate_name`
+
The following command moves metadata volume `MDV_CRS_14c00d4ac9f311e7922800a0984395f1` from `aggregate Node_A_1_aggr1` to `aggregate Node_A_1_aggr2`:
+
----
Cluster_A::*> volume move start -vserver svm_cluster_A -volume MDV_CRS_14c00d4ac9f311e7922800a0984395f1
-destination-aggregate aggr_cluster_A_02_01

Warning: You are about to modify the system volume
         "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A".  This may cause severe
         performance or stability problems.  Do not proceed unless directed to
         do so by support.  Do you want to proceed? {y|n}: y
[Job 109] Job is queued: Move "MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" in Vserver
"svm_cluster_A" to aggregate "aggr_cluster_A_02_01".
Use the "volume move show -vserver svm_cluster_A -volume
MDV_CRS_9da04864ca6011e7b82e0050568be9fe_A" command to view the status of this operation.
----

. Verify the state of the volume move operation: `volume move show -volume vol_constituent_name`
. Return to the admin privilege level: `set -privilege admin`
