---
permalink: upgrade/task_configuring_intercluster_lifs_to_share_data_ports.html
sidebar: sidebar
keywords: 
summary: 'You can configure intercluster LIFs on ports shared with the data network. Doing so reduces the number of ports you need for intercluster networking.'
---
= Configuring intercluster LIFs on shared data ports
:icons: font
:imagesdir: ../media/

[.lead]
You can configure intercluster LIFs on ports shared with the data network. Doing so reduces the number of ports you need for intercluster networking.

. List the ports in the cluster:``network port show``
+
For complete command syntax, see the man page.
+
The following example shows the network ports in cluster01:
+
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----

. Create intercluster LIFs on the system SVM:
+
|===
    a|
*In ONTAP 9.6 and later:*
a|
`network interface create -vserver system_SVM -lif LIF_name -service-policy default-intercluster -home-node node -home-port port -address port_IP -netmask netmask`
a|
*In ONTAP 9.5 and earlier:*
a|
`network interface create -vserver system_SVM -lif LIF_name -role intercluster -home-node node -home-port port -address port_IP -netmask netmask`
|===
For complete command syntax, see the man page.
+
The following example creates intercluster LIFs cluster01_icl01 and cluster01_icl02:
+
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----

. Verify that the intercluster LIFs were created:
+
|===
    a|
*In ONTAP 9.6 and later:*
a|
`network interface show -service-policy default-intercluster`
a|
*In ONTAP 9.5 and earlier:*
a|
`network interface show -role intercluster`
|===
For complete command syntax, see the man page.
+
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----

. Verify that the intercluster LIFs are redundant:
+
|===
    a|
*In ONTAP 9.6 and later:*
a|
`network interface show –service-policy default-intercluster -failover`
a|
*In ONTAP 9.5 and earlier:*
a|
`network interface show -role intercluster -failover`
|===
For complete command syntax, see the man page.
+
The following example shows that the intercluster LIFs cluster01_icl01 and cluster01_icl02 on the e0c port will fail over to the e0d port.
+
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----
