---
permalink: upgrade/task_refresh_the_mcc_configuration_mcc_configure_refresh.html
sidebar: sidebar
keywords: metrocluster, upgrade, refresh, configuration, new, controller
summary: 'You must refresh the MetroCluster configuration when expanding it from a two-node configuration to a four-node configuration.'
---
= Refreshing the MetroCluster configuration with new controllers
:icons: font
:imagesdir: ../media/

[.lead]
You must refresh the MetroCluster configuration when expanding it from a two-node configuration to a four-node configuration.

. Refresh the MetroCluster configuration:
 .. Enter advanced privilege mode:
 +
`*set -privilege advanced*`
 .. Refresh the MetroCluster configuration:
 +
`*metrocluster configure -refresh true*`
+
The following command refreshes the MetroCluster configuration on all of the nodes in the DR group that contains controller_A_1:
+
----
controller_A_1::*> metrocluster configure -refresh true

[Job 726] Job succeeded: Configure is successful.
----

 .. Return to admin privilege mode:
 +
`*set -privilege admin*`
. Verify the networking status on site A:
+
`*network port show*`
+
The following example shows the network port usage on a four-node MetroCluster configuration:
+
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----

. Verify the MetroCluster configuration from both sites in the MetroCluster configuration.
 .. Verify the configuration from site A:
+
`*metrocluster show*`
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----

 .. Verify the configuration from site B:
+
`*metrocluster show*`
+
----
cluster_B::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----

 .. Verify that the DR relationships have been created correctly:
 +
`*metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner*`
+
----
metrocluster node show -fields dr-cluster,dr-auxiliary,node-object-limit,automatic-uso,ha-partner,dr-partner
dr-group-id cluster     node    ha-partner dr-cluster  dr-partner   dr-auxiliary  node-object-limit automatic-uso
----------- ---------   ----    ---------- ----------  ----------   ------------  ----------------- -------------
2           cluster_A   node_A_1 node_A_2    cluster_B  node_B_1     node_B_2      on                true
2           cluster_A   node_A_2 node_A_1    cluster_B  node_B_2     node_B_1      on                true
2           cluster_B   node_B_1 node_B_2    cluster_A  node_A_1     node_A_2      on                true
2           cluster_B   node_B_2 node_B_1    cluster_A  node_A_2     node_A_1      on                true
4 entries were displayed.
----
