---
permalink: upgrade/task_verify_the_state_of_the_mcc_configuration_mcc_expansion.html
sidebar: sidebar
keywords: metrocluster, upgrade, verfiy, state, configuration
summary: 'You should identify the existing controllers and confirm the disaster recovery \(DR\) relationships between them, that the controllers are in normal mode, and that the aggregates are mirrored.'
---
= Verifying the state of the MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
You should identify the existing controllers and confirm the disaster recovery (DR) relationships between them, that the controllers are in normal mode, and that the aggregates are mirrored.

.Steps
. Display the details of the nodes in the MetroCluster configuration from any node in the configuration:
+
`*metrocluster node show -fields node,dr-partner,dr-partner-systemid*`
+
The following output shows that this MetroCluster configuration has a single DR group and one node in each cluster.
+
----
cluster_A::> metrocluster node show -fields node,dr-partner,dr-partner-systemid

dr-group-id  cluster         node            dr-partner      dr-partner-systemid
-----------  -------------   -------         ----------      -------------------
1            cluster_A       controller_A_1  controller_B_1  536946192
1            cluster_B       controller_B_1  controller_A_1  536946165
2 entries were displayed.
----

. Display the state of the MetroCluster configuration:
+
`*metrocluster show*`
+
The following output shows that the existing nodes in the MetroCluster configuration are in normal mode:
+
----

cluster_A::> metrocluster show

Configuration: two-node-fabric

Cluster                        Entry Name             State
------------------------------ ---------------------- ---------------------
Local: cluster_A               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
Remote: controller_B_1_siteB
                               Configuration State    configured
                               Mode                   normal
                               AUSO Failure Domain    auso-on-cluster-disaster
----

. Check the state of the aggregates on each node in the MetroCluster configuration:
+
`*storage aggregate show*`
+
The following output shows that the aggregates on cluster_A are online and mirrored:
+
----
cluster_A::> storage aggregate show


Aggregate                Size     Available Used%  State   #Vols  Nodes            RAID Status
---------                -------- --------- -----  ------- ------ ---------------- ------------
aggr0_controller_A_1_0   1.38TB   68.63GB   95%    online    1    controller_A_1   raid_dp,mirrored
controller_A_1_aggr1     4.15TB   4.14TB    0%     online    2    controller_A_1   raid_dp,mirrored
controller_A_1_aggr2     4.15TB   4.14TB    0%     online    1    controller_A_1   raid_dp,mirrored
3 entries were displayed.

cluster_A::>
----
