---
permalink: upgrade/task_power_up_both_controller_modules_and_display_the_loader_prompt_2_node_mcc_expansion.html
sidebar: sidebar
keywords:
summary: 'You power up the existing controller module and the new controller module to display the LOADER prompt.'
---
= Powering up both controller modules and displaying the LOADER prompt
:icons: font
:imagesdir: ../media/

[.lead]
You power up the existing controller module and the new controller module to display the LOADER prompt.

.Steps
. Power up the controller modules and interrupt the boot process, using the steps for your configuration:
+
[options="header"]
|===
| If the controller modules are...| Then...
a|
In the same chassis
a|

 .. Verify that the new controller module is *not* fully inserted into the bay.
+
The existing controller module should be fully inserted into the bay because it was never removed from the chassis, but the new controller module should not be.

 .. Connect the power and turn on the power supplies so that the existing controller module receives power.
 .. Interrupt the boot process on the existing controller module by pressing Ctrl-C.
 .. Push the new controller module firmly into the bay.
+
When fully seated, the new controller module receives power and automatically boots.

 .. Interrupt the boot process by pressing Ctrl-C.
 .. Tighten the thumbscrew on the cam handle, if present.
 .. Install the cable management device, if present.
 .. Bind the cables to the cable management device with the hook and loop strap.

a|
In separate chassis
a|

 .. Turn on the power supplies on the existing controller module.
 .. Interrupt the boot process by pressing Ctrl-C.
 .. Repeat these steps for the new controller module

+
|===
Each controller module should display the LOADER prompt (`LOADER>`, `LOADER-A>`, or `LOADER-B>`).
+
NOTE: If there is no LOADER prompt, record the error message and contact technical support. If the system displays the boot menu, reboot and attempt to interrupt the boot process again.
