---
permalink: upgrade/task_implement_the_mcc_configuration_mcc_refresh_mcc_expansion.html
sidebar: sidebar
keywords: 
summary: 'You must run the metrocluster configure -refresh true command to start data protection on the nodes that you have added to a MetroCluster configuration.'
---
= Implementing the MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
You must run the metrocluster configure -refresh true command to start data protection on the nodes that you have added to a MetroCluster configuration.

You issue the metrocluster configure -refresh true command once, on one of the newly added nodes, to refresh the MetroCluster configuration. You do not need to issue the command on each of the sites or nodes.

The metrocluster configure -refresh true command automatically pairs the two nodes with the lowest system IDs in each of the two clusters as disaster recovery (DR) partners. In a four-node MetroCluster configuration, there are two DR partner pairs. The second DR pair is created from the two nodes with higher system IDs.

. Refresh the MetroCluster configuration:
 .. Enter advanced privilege mode: `set -privilege advanced`
 .. Refresh the MetroCluster configuration on one of the new nodes: `metrocluster configure -refresh true`
+
The following example shows the MetroCluster configuration refreshed on both DR groups:
+
----
controller_A_2::*> metrocluster configure -refresh true

[Job 726] Job succeeded: Configure is successful.
----
+
----
controller_A_4::*> metrocluster configure -refresh true

[Job 740] Job succeeded: Configure is successful.
----

 .. Return to admin privilege mode: `set -privilege admin`
. Verify the networking status on site A: `network port show`
+
The following example shows the network port usage on a four-node MetroCluster configuration:
+
----
cluster_A::> network port show
                                                          Speed (Mbps)
Node   Port      IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ --------- --------- ---------------- ----- ------- ------------
controller_A_1
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
controller_A_2
       e0a       Cluster   Cluster          up     9000  auto/1000
       e0b       Cluster   Cluster          up     9000  auto/1000
       e0c       Default   Default          up     1500  auto/1000
       e0d       Default   Default          up     1500  auto/1000
       e0e       Default   Default          up     1500  auto/1000
       e0f       Default   Default          up     1500  auto/1000
       e0g       Default   Default          up     1500  auto/1000
14 entries were displayed.
----

. Verify the MetroCluster configuration from both sites in the MetroCluster configuration:
 .. Verify the configuration from site A: `metrocluster show`
+
----
cluster_A::> metrocluster show

Configuration: IP fabric

Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
Remote: cluster_B         Configuration state configured
                          Mode                normal
----

 .. Verify the configuration from site B: `metrocluster show`
+
----
cluster_B::> metrocluster show

Configuration: IP fabric

Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_B         Configuration state configured
                          Mode                normal
Remote: cluster_A         Configuration state configured
                          Mode                normal
----
