---
permalink: upgrade/task_assign_disk_ownership_to_non_aff_systems_mcc.html
sidebar: sidebar
keywords: 
summary: 'If the MetroCluster nodes do not have the disks correctly assigned, or if you are using DS460C disk shelves in your configuration, you must assign disks to each of the nodes in the MetroCluster configuration on a shelf-by-shelf basis. You will create a configuration in which each node has the same number of disks in its local and remote disk pools.'
---
= Assigning disk ownership in non-AFF systems
:icons: font
:imagesdir: ../media/

[.lead]
If the MetroCluster nodes do not have the disks correctly assigned, or if you are using DS460C disk shelves in your configuration, you must assign disks to each of the nodes in the MetroCluster configuration on a shelf-by-shelf basis. You will create a configuration in which each node has the same number of disks in its local and remote disk pools.

The storage controllers must be in Maintenance mode.

If your configuration does not include DS460C disk shelves, this task is not required if disks were correctly assigned when received from the factory.

NOTE: Pool 0 always contains the disks that are found at the same site as the storage system that owns them.

Pool 1 always contains the disks that are remote to the storage system that owns them.

If your configuration includes DS460C disk shelves, you should manually assign the disks using the following guidelines for each 12-disk drawer:

|===
| Assign these disks in the drawer...| To this node and pool...
a|
0 - 2
a|
Local node's pool 0
a|
3 - 5
a|
HA partner node's pool 0
a|
6 - 8
a|
DR partner of the local node's pool 1
a|
9 - 11
a|
DR partner of the HA partner's pool 1
|===
This disk assignment pattern ensures that an aggregate is minimally affected in case a drawer goes offline.

. If you have not done so, boot each system into Maintenance mode.
. Assign the disk shelves to the nodes located at the first site (site A):
+
Disk shelves at the same site as the node are assigned to pool 0 and disk shelves located at the partner site are assigned to pool 1.
+
You should assign an equal number of shelves to each pool.

 .. On the first node, systematically assign the local disk shelves to pool 0 and the remote disk shelves to pool 1: `disk assign -shelf local-switch-name:shelf-name.port -p pool`
+
If storage controller Controller_A_1 has four shelves, you issue the following commands:
+
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf1 -p 0
*> disk assign -shelf FC_switch_A_1:1-4.shelf2 -p 0

*> disk assign -shelf FC_switch_B_1:1-4.shelf1 -p 1
*> disk assign -shelf FC_switch_B_1:1-4.shelf2 -p 1
----

 .. Repeat the process for the second node at the local site, systematically assigning the local disk shelves to pool 0 and the remote disk shelves to pool 1: `disk assign -shelf local-switch-name:shelf-name.port -p pool`
+
If storage controller Controller_A_2 has four shelves, you issue the following commands:
+
----
*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1

*> disk assign -shelf FC_switch_A_1:1-4.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-4.shelf4 -p 1
----

. Assign the disk shelves to the nodes located at the second site (site B):
+
Disk shelves at the same site as the node are assigned to pool 0 and disk shelves located at the partner site are assigned to pool 1.
+
You should assign an equal number of shelves to each pool.

 .. On the first node at the remote site, systematically assign its local disk shelves to pool 0 and its remote disk shelves to pool 1: `disk assign -shelf local-switch-nameshelf-name -p pool`
+
If storage controller Controller_B_1 has four shelves, you issue the following commands:
+
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf1 -p 0
*> disk assign -shelf FC_switch_B_1:1-5.shelf2 -p 0

*> disk assign -shelf FC_switch_A_1:1-5.shelf1 -p 1
*> disk assign -shelf FC_switch_A_1:1-5.shelf2 -p 1
----

 .. Repeat the process for the second node at the remote site, systematically assigning its local disk shelves to pool 0 and its remote disk shelves to pool 1: `disk assign -shelf shelf-name -p pool`
+
If storage controller Controller_B_2 has four shelves, you issue the following commands:
+
----
*> disk assign -shelf FC_switch_B_1:1-5.shelf3 -p 0
*> disk assign -shelf FC_switch_B_1:1-5.shelf4 -p 0

*> disk assign -shelf FC_switch_A_1:1-5.shelf3 -p 1
*> disk assign -shelf FC_switch_A_1:1-5.shelf4 -p 1
----

. Confirm the shelf assignments: `storage show shelf`
. Exit Maintenance mode: `halt`
. Display the boot menu: `boot_ontap menu`
. On each node, select option *4* to initialize all disks.
