---
permalink: upgrade/task_determin_the_new_cable_layout_mcc_expansion.html
sidebar: sidebar
keywords: metrocluster, upgrade, determine, new, cabling, layout
summary: 'You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.'
---
= Determining the new cabling layout
:icons: font
:imagesdir: ../media/

[.lead]
You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.

.About this task

This task must be performed at each MetroCluster site.

.Steps
. Use the procedure in link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration] to create a cabling layout for your switch type, using the port usage for an eight-node MetroCluster configuration.
+
The FC switch port usage must match the usage described in the procedure so that the Reference Configuration Files (RCFs) can be used.
+
NOTE: If your environment cannot be cabled in such a way that RCF files can be used, you must manually configure the system according to instructions found in link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]. Do not use this procedure if the cabling cannot use RCF files.

// BURT 1448684, 01 FEB 2022
