---
permalink: upgrade/task_apply_the_rcf_files_and_recable_the_switches.html
sidebar: sidebar
keywords: metrocluster, upgrade, apply, rcf, files, recable, switches
summary: 'You must apply the RCF files to reconfigure your zoning to accommodate the new nodes.'
---
= Applying the RCF files and recabling the switches
:icons: font
:imagesdir: ../media/

[.lead]
You must apply the RCF files to reconfigure your zoning to accommodate the new nodes.

.Steps
. Locate the RCF files for your configuration.
+
You must use the RCF files for an eight-node configuration and that match your switch model.

. Apply the RCF files, following the directions on the download page, adjusting the ISL settings as needed.
. Ensure that the switch configuration is saved.
. Reboot the FC switches.
. Cable both the pre-existing and the new FC-to-SAS bridges to the FC switches, using the cabling layout you created previously.
+
The FC switch port usage must match the MetroCluster eight-node usage described in the _Fabric-attached MetroCluster Installation and Configuration Guide_ so that the Reference Configuration Files (RCFs) can be used.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
+
NOTE: If your environment cannot be cabled in such a way that RCF files can be used then contact technical support. Do NOT use this procedure if the cabling cannot use RCF files.

. Verify that the ports are online by using the correct command for your switch.
+
[options="header"]
|===
| Switch vendor| Command
a|
Brocade
a|
switchshow
a|
Cisco
a|
show interface brief
|===

. Cable the FC-VI ports from the existing and new controllers, using the cabling layout you created previously.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
+
The FC switch port usage must match the MetroCluster eight-node usage described in the _Fabric-attached MetroCluster Installation and Configuration Guide_ so that the Reference Configuration Files (RCFs) can be used.
+
NOTE: If your environment cannot be cabled in such a way that RCF files can be used then contact technical support. Do NOT use this procedure if the cabling cannot use RCF files.

. From the existing nodes, verify that the FC-VI ports are online:
+
`*metrocluster interconnect adapter show*`
+
`*metrocluster interconnect mirror show*`
. Cable the HBA ports from the current and the new controllers.
. On the existing controller modules, e-enable the ports connected to the switch fabric undergoing maintenance:
+
`*storage port enable -node _node-name_ -port _port-ID_*`
. Start the new controllers and boot them into Maintenance mode:
+
`*boot_ontap maint*`
. Verify that only storage that will be used by the new DR group is visible to the new controller modules.
+
None of the storage that is used by the other DR group should be visible.

. Return to the beginning of this process to recable the second switch fabric.
