---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'You can use this guided automated MetroCluster switchover operation to perform a non-disruptive controller upgrade for a four-node MetroCluster IP configuration.'
---
= Set the required bootarg on the existing system (systems introduced in 9.15.1 or later)
:icons: font
:imagesdir: ../media/

[.lead]
Upgrades to systems introduced in 9.15.1 or later require you to set a bootarg before you can proceed with the upgrade.

.About this task 

This task is required when you upgrade to any of the following platforms: AFF A70, AFF A90, AFF A1K, FAS70, FAS90, or AFF C80. 

CAUTION: If you are upgrading to an AFF A70, AFF A90, AFF A1K, FAS70, FAS90, or AFF C80 system, you *must* set the `hw.cxgbe.toe_keepalive_disable=1` bootarg before performing the upgrade. This task *only* applies to upgrades to an AFF A70, AFF A90, AFF A1K,  FAS70, FAS90, or AFF C80 system from a supported system.  For all other upgrades, you can skip this task and go directly to link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].

.Steps

. Halt one node at each site and allow its HA partner to perform a storage takeover of the node:
+
`halt  -node <node_name>`

. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv hw.cxgbe.toe_keepalive_disable 1` 
+
`saveenv` 
+
`printenv hw.cxgbe.toe_keepalive_disable`  

. Boot the node:
+
`boot_ontap`
    
. When the node boots, perform a giveback for the node at the prompt: 
+
`storage failover giveback -ofnode <node_name>`

. Repeat the steps on each node in the DR group that is being upgraded.

== Upgrades to AFF A30 or AFF C30 systems

.About this task 

This task is required when you upgrade from an AFF A250 to an AFF A30 or from an AFF C250 to an AFF C30 system.

CAUTION: If you are upgrading to an AFF A30 or AFF C30 system, you *must* set the `setenv bootarg.siw.interop_enabled 1` bootarg before performing the upgrade. This task *only* applies to upgrades to an AFF A70, AFF A90, AFF A1K,  FAS70, FAS90, or AFF C80 system from a supported system. For all other upgrades, you can skip this task and go directly to link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].

.Steps

. Halt one node at each site and allow its HA partner to perform a storage takeover of the node:
+
`halt  -node <node_name>`

. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv bootarg.siw.interop_enabled 1` 

. Boot the node:
+
`boot_ontap`
    
. When the node boots, perform a giveback for the node at the prompt: 
+
`storage failover giveback -ofnode <node_name>`

. Repeat the steps on each node in the DR group that is being upgraded.



