---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-remove-tb.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'You can use this guided automated MetroCluster switchover operation to perform a non-disruptive controller upgrade for a four-node MetroCluster IP configuration.'
---
= Remove the existing configuration from Tiebreaker or other monitoring software
:icons: font
:imagesdir: ../media/

[.lead]
Before you start the upgrade, remove the existing configuration from the Tiebreaker or other monitoring software.

If the existing configuration is monitored with the MetroCluster Tiebreaker configuration or other third-party applications (for example, ClusterLion) that can initiate a switchover, you must remove the MetroCluster configuration from the Tiebreaker or other software prior to replacing the old controller.

.Steps

. link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations[Remove the existing MetroCluster configuration] from the Tiebreaker software.

. Remove the existing MetroCluster configuration from any third-party application that can initiate switchover.
+
Refer to the documentation for the application.

