---
permalink: upgrade/upgrade-mcc-ip-a700-fas9000-boot-new-controllers.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'You can use this guided automated MetroCluster switchover operation to perform a non-disruptive controller upgrade for a four-node MetroCluster IP configuration.'
---
= Boot up the new controllers and restore LIF configuration
:icons: font
:imagesdir: ../media/

[.lead]
Boot the new controllers and verify that LIFs are hosted on appropriate nodes and ports.

== Boot up the new controllers

You must boot the new controllers, taking care to ensure that the bootarg variables are correct and, if needed, perform the encryption recovery steps.

.Steps

. Halt the new nodes:
+
`halt`
. If external key manager is configured, set the related bootargs:
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`
+
`setenv bootarg.kmip.init.netmask <netmask>`
+
`setenv bootarg.kmip.init.gateway <gateway-address>`
+
`setenv bootarg.kmip.init.interface <interface-id>`
. Check if the partner-sysid is the current:
+
`printenv partner-sysid`
+
If the partner-sysid is not correct, set it:
+
`setenv partner-sysid <partner-sysID>`

. Display the ONTAP boot menu:
+
`boot_ontap menu`
. If root encryption is used, select the boot menu option for your key management configuration.
+

|===

h| If you are using... h| Select this boot menu option...

a|
Onboard key management
a|
Option 10 and follow the prompts to provide the required inputs to recover or restore the key-manager configuration
a|
External key management
a|
Option 11 and follow the prompts to provide the required inputs to recover or restore the key-manager configuration
|===

. From the boot menu, select `(6) Update flash from backup config`.
+
NOTE: Option 6 will reboot the node twice before completing.

+
Respond `y` to the system id change prompts. Wait for the second reboot messages:
+
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----

. Interrupt the AUTOBOOT to stop the controllers at LOADER.
+
NOTE: On each node, check the bootargs set in link:upgrade-mcc-ip-a700-fas9000-apply-rcf-set-bootarg.html#set-the-metrocluster-ip-bootarg-variables[Setting the MetroCluster IP bootarg variables] and correct any incorrect values. Only move to the next step after you have checked the bootarg values.

. Double-check that the partner-sysid is the correct:
+
`printenv partner-sysid`
+
If the partner-sysid is not correct, set it:
+
`setenv partner-sysid <partner-sysID>`

. If root encryption is used, select the boot menu option for your key management configuration.
+

|===

h| If you are using... h| Select this boot menu option...

a|
Onboard key management
a|
Option 10 and follow the prompts to provide the required inputs to recover or restore the key-manager configuration
a|
External key management
a|
Option 11 and follow the prompts to provide the required inputs to recover or restore the key-manager configuration
|===
+
You need to perform the recovery procedure by selecting Option 10 or option 11 depending on the key manager setting and Option 6 at the boot menu prompt. To boot the nodes completely, you might need to perform the recovery procedure continued by option 1 (normal boot).

. Wait for the new nodes, node_B_1-A900 and node_B_2-A900 to boot up.
+
If either node is in takeover mode, perform a giveback using the `storage failover giveback` command.

. If encryption is used, restore the keys using the correct command for your key management configuration.
+

|===

h| If you are using... h| Use this command...
a|
Onboard key management
a|
`security key-manager onboard sync`

For more information, see https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html[Restoring onboard key management encryption keys^].
a|
External key management
a|
`security key-manager external restore -vserver <SVM> -node <node> -key-server <host_name\|IP_address:port> -key-id <key_id> -key-tag key_tag <node-name>`

For more information, see https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html[Restoring external key management encryption keys^].

|===

. Verify that all ports are in a broadcast domain:
 .. View the broadcast domains:
+
`network port broadcast-domain show`

.. Add any ports to a broadcast domain as needed.
+
https://docs.netapp.com/us-en/ontap/networking/add_or_remove_ports_from_a_broadcast_domain97.html[Adding or removing ports from a broadcast domain^]

.. Recreate VLANs and interface groups as needed.
+
VLAN and interface group membership might be different than that of the old node.
+
https://docs.netapp.com/us-en/ontap/networking/configure_vlans_over_physical_ports.html#create-a-vlan[Creating a VLAN^]
+
https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html[Combining physical ports to create interface groups^]

== Verify and restore LIF configuration

Verify that LIFs are hosted on appropriate nodes and ports as mapped out at the beginning of the upgrade procedure.

.About this task

* This task is performed on site_B.
* See the port mapping plan you created in link:upgrade-mcc-ip-a700-fas9000-prepare-system.html#upgrade_a700_a900_ip_map[Map ports from the old nodes to the new nodes].

.Steps

. Verify that LIFs are hosted on the appropriate node and ports prior to switchback.

.. Change to the advanced privilege level:
+
`set -privilege advanced`

.. Override the port configuration to ensure proper LIF placement:
+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>`
+
When entering the network interface modify command within the `vserver config override` command, you cannot use the tab autocomplete feature. You can create the network `interface modify` using autocomplete and then enclose it in the `vserver config override` command.

.. Return to the admin privilege level:
+
`set -privilege admin`
. Revert the interfaces to their home node:
+
`network interface revert * -vserver <svm-name>`
+
Perform this step on all SVMs as required.