---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'You can use this guided automated MetroCluster switchover operation to perform a non-disruptive controller upgrade for a four-node MetroCluster IP configuration.'
---
= Set the required bootarg (for upgrades to systems introduced in 9.15.1 or later)
:icons: font
:imagesdir: ../media/

[.lead]
Upgrades to systems introduced in 9.15.1 or later require you to set a bootarg before you can proceed with the upgrade.

== Upgrades to AFF A70, AFF A90, AFF A1K, FAS70, FAS90, or AFF C80 systems 

.About this task 

This task is *only* required when you upgrade to an AFF A70, AFF A90, AFF A1K, FAS70, FAS90, or AFF C80 system.

CAUTION: If you are upgrading to an AFF A70, AFF A90, AFF A1K, FAS70, FAS90, or AFF C80 system, you *must* set the `setenv hw.cxgbe.toe_keepalive_disable 1` bootarg before performing the upgrade.  For all other upgrades, you can skip this task and go directly to link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].

.Steps

. Halt one node at each site and allow its HA partner to perform a storage takeover of the node:
+
`halt  -node <node_name>`

. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv hw.cxgbe.toe_keepalive_disable 1` 
+
`saveenv` 
+
`printenv hw.cxgbe.toe_keepalive_disable`  

. Boot the node:
+
`boot_ontap`
    
. When the node boots, perform a giveback for the node at the prompt: 
+
`storage failover giveback -ofnode <node_name>`

. Repeat the steps on each node in the DR group that is being upgraded.

== Upgrades to AFF A30, AFF A20, or AFF C30 systems

.About this task 

This task is *only* required for the following upgrades:

[[upgrade_paths_bootarg_manual]]
[cols=2*,options="header"]
|===
| From this controller...
| To this controller...
| AFF A250 system | AFF A30 system
| AFF C250 system | AFF C30 system
| AFF A150 system| AFF A20 system
| AFF A220 system  | AFF A20 system
|===

CAUTION: If the upgrade you are performing is listed in the table, you *must* set the `setenv bootarg.siw.interop_enabled 1` bootarg on the existing system before performing the upgrade. For all other upgrades, you can skip this task and go directly to link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].

.Steps

. Halt one node at each site and allow its HA partner to perform a storage takeover of the node:
+
`halt  -node <node_name>`

. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv bootarg.siw.interop_enabled 1` 
+
`saveenv` 
+
`printenv bootarg.siw.interop_enable` 

. Boot the node:
+
`boot_ontap`
    
. When the node boots, perform a giveback for the node at the prompt: 
+
`storage failover giveback -ofnode <node_name>`

. Repeat the steps on each node in the DR group that is being upgraded.





