---
permalink: upgrade/upgrade-mcc-ip-a700-fas9000-apply-rcf-set-bootarg.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Update the switch RCF files for the new platforms and set the MetroCluster IP bootarg values on the controller modules.'
---
= Update the switch RCF files and set the MetroCluster IP bootarg values 
:icons: font
:imagesdir: ../media/

[.lead]
Update the switch RCF files for the new platforms and set the MetroCluster IP bootarg values on the controller modules. 

== Update the switch RCF files to accommodate the new platforms

include::../_include/update_the_switch_rcf_files.adoc[]

== Set the MetroCluster IP bootarg variables

Certain MetroCluster IP bootarg values must be configured on the new controller modules. The values must match those configured on the old controller modules.

.About this task

In this task, you will use the UUIDs and system IDs identified earlier in the upgrade procedure in link:upgrade-mcc-ip-a700-fas9000-prepare-system.html#gather-information-before-the-upgrade[Gather information before the upgrade].

.Steps

.	At the `LOADER>` prompt, set the following bootargs on the new nodes at site_B:
+
`setenv bootarg.mcc.port_a_ip_config _local-IP-address/local-IP-mask,0,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id_`
+
`setenv bootarg.mcc.port_b_ip_config _local-IP-address/local-IP-mask,0,HA-partner-IP-address,DR-partner-IP-address,DR-aux-partnerIP-address,vlan-id_`
+
The following example sets the values for node_B_1-A900 using VLAN 120 for the first network and VLAN 130 for the second network:
+
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.10/23,0,172.17.26.11,172.17.26.13,172.17.26.12,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.10/23,0,172.17.27.11,172.17.27.13,172.17.27.12,130
----
+
The following example sets the values for node_B_2-A900 using VLAN 120 for the first network and VLAN 130 for the second network:
+
----
setenv bootarg.mcc.port_a_ip_config 172.17.26.11/23,0,172.17.26.10,172.17.26.12,172.17.26.13,120
setenv bootarg.mcc.port_b_ip_config 172.17.27.11/23,0,172.17.27.10,172.17.27.12,172.17.27.13,130
----



. At the new nodes' `LOADER` prompt, set the UUIDs:
+
`setenv bootarg.mgwd.partner_cluster_uuid _partner-cluster-UUID_`
+
`setenv bootarg.mgwd.cluster_uuid _local-cluster-UUID_`
+
`setenv bootarg.mcc.pri_partner_uuid _DR-partner-node-UUID_`
+
`setenv bootarg.mcc.aux_partner_uuid _DR-aux-partner-node-UUID_`
+
`setenv bootarg.mcc_iscsi.node_uuid _local-node-UUID_`


.. Set the UUIDs on node_B_1-A900.
+
The following example shows the commands for setting the UUIDs on node_B_1-A900:
+
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.aux_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc_iscsi.node_uuid f03cb63c-9a7e-11e7-b68b-00a098908039
----

.. Set the UUIDs on node_B_2-A900:
+
The following example shows the commands for setting the UUIDs on node_B_2-A900:
+
----
setenv bootarg.mgwd.cluster_uuid ee7db9d5-9a82-11e7-b68b-00a098908039
setenv bootarg.mgwd.partner_cluster_uuid 07958819-9ac6-11e7-9b42-00a098c9e55d
setenv bootarg.mcc.pri_partner_uuid bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
setenv bootarg.mcc.aux_partner_uuid f37b240b-9ac1-11e7-9b42-00a098c9e55d
setenv bootarg.mcc_iscsi.node_uuid aa9a7a7a-9a81-11e7-a4e9-00a098908c35
----

. If the original systems were configured for ADP, at each of the replacement nodes' LOADER prompt, enable ADP:
+
`setenv bootarg.mcc.adp_enabled true`

. Set the following variables:
+
`setenv bootarg.mcc.local_config_id _original-sys-id_`
+
`setenv bootarg.mcc.dr_partner _dr-partner-sys-id_`
+
NOTE: The `setenv bootarg.mcc.local_config_id` variable must be set to the sys-id of the *original* controller module, node_B_1-A700.

.. Set the variables on node_B_1-A900.
+
The following example shows the commands for setting the values on node_B_1-A900:
+
----
setenv bootarg.mcc.local_config_id 537403322
setenv bootarg.mcc.dr_partner 537403324
----

.. Set the variables on node_B_2-A900.
+
The following example shows the commands for setting the values on node_B_2-A900:
+
----
setenv bootarg.mcc.local_config_id 537403321
setenv bootarg.mcc.dr_partner 537403323
----

. If using encryption with external key manager, set the required bootargs:
+
`setenv bootarg.kmip.init.ipaddr`
+
`setenv bootarg.kmip.kmip.init.netmask`
+
`setenv bootarg.kmip.kmip.init.gateway`
+
`setenv bootarg.kmip.kmip.init.interface`