---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-complete-upgrade.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Complete the automated controller upgrade process by verifying the network reachability and restoring any monitoring configuration.'
---
= Complete the MetroCluster IP controller upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Complete the automated controller upgrade process by verifying the network reachability and restoring any monitoring configuration.   

== Verify network reachability 

The automation operation runs verification system checks and then pauses so you can verify the network reachability. After verification, the resource regain phase is initiated and the automation operation executes switchback at site A and pauses at the post upgrade checks. After you resume the automation operation, it performs the post upgrade checks and if no errors are detected, marks the upgrade as complete.

.Steps

.	Verify the network reachability by following the console message.
.	After you complete the verification, resume the operation:
+
`system controller replace resume`
.	The automation operation performs `heal-aggregate`, `heal-root-aggregate`, and switchback operations at site A, and the post upgrade checks. When the operation pauses, manually check the SAN LIF status and verify the network configuration by following the console message.
.	After you complete the verification, resume the operation:
+
`system controller replace resume`

.	Check the post upgrade checks status:
+
`system controller replace show`
+
If the post upgrade checks didn't report any errors, the upgrade is complete.

.	After you complete the controller upgrade, log in at site B and verify that the replaced controllers are configured correctly.

== Upgrade the nodes on cluster_A

You must repeat the upgrade tasks to upgrade the nodes on cluster_A at site A.

.Steps

. Repeat the steps to upgrade the nodes on cluster_A, beginning with link:upgrade-mcc-ip-system-controller-replace-supported-platforms.html[Prepare for the upgrade].
+
When you repeat the procedure, all example references to the clusters and nodes are reversed.

== Re-add internal drives to the new controller

If you upgraded from a system that only has external drives to a system with internal drives (disks and controllers in the same chassis), you can add or re-seat the disks that you removed or unseated from the internal slots of the new system. You can do this at any time after the upgrade is completed on both sites and the cluster is in a healthy state.

After you re-add or re-seat the drives, they can be used in ONTAP as required.

NOTE: This task only applies to certain upgrade combinations. Refer to link:upgrade-mcc-ip-system-controller-replace-restore-hba-set-ha.html#remove-internal-drives-from-the-chassis-on-the-new-controller[remove internal drives from the chassis on the new controller] for more information.

== Reconfigure ONTAP Mediator 

Manually configure ONTAP Mediator which was automatically removed before you started the upgrade. 

. Use the steps in link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html[Configure ONTAP Mediator from a MetroCluster IP configuration]. 

==  Restore Tiebreaker monitoring

If the MetroCluster configuration was previously configured for monitoring by the Tiebreaker software, you can restore the Tiebreaker connection.

. Use the steps in http://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/GUID-7259BCA4-104C-49C6-BAD0-1068CA2A3DA5.html[Add MetroCluster configurations].


== Configure end-to-end encryption

If it is supported on your system, you can encrypt back-end traffic, such as NVlog and storage replication data, between the MetroCluster IP sites. Refer to link:../maintain/task-configure-encryption.html[Configure end-to-end encryption] for more information.

// 2024 Jan 27, ONTAPDOC-2651
// 2024 Nov 12, ONTAPDOC-2351
