---
permalink: upgrade/upgrade-mcc-ip-a700-fas9000-requirements.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Verify your system meets all the requirements before performing the controller upgrade.'
---
= Requirements for using this upgrade procedure
:icons: font
:imagesdir: ../media/

[.lead]
Verify your system meets all the requirements before performing the controller upgrade. 

== Requirements

* To upgrade AFF A700 controller modules to AFF A900, the controllers must be running ONTAP 9.10.1 or later.
* To upgrade FAS9000 controller modules to FAS9500, the controllers must be running ONTAP 9.10.1P3 or later.

* All controllers in the configuration should be upgraded during the same maintenance period.
+
Operating the MetroCluster configuration with an AFF A700 and an AFF A900, or a FAS9000 and a FAS9500 controller is not supported outside of this maintenance activity.

* The IP switches must be running a supported firmware version.

* You will reuse the IP addresses, netmasks, and gateways of the original platforms on the new platforms.
* The following example names are used in this procedure, in both examples and graphics:
 ** Site_A
  *** Before upgrade:
   **** node_A_1-A700
   **** node_A_2-A700
  *** After upgrade:
   **** node_A_1-A900
   **** node_A_2-A900
 ** Site_B
  *** Before upgrade:
   **** node_B_1-A700
   **** node_B_2-A700
  *** After upgrade:
   **** node_B_1-A900
   **** node_B_2-A900
