---
permalink: upgrade/upgrade-mcc-ip-prepare-system.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Before making any changes to the existing MetroCluster configuration, you must check the health of the configuration, prepare the new platforms, and perform other miscellaneous tasks.'
---
= Prepare the MetroCluster IP system for upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Before making any changes to the existing MetroCluster configuration, check the health of the configuration, prepare the new platforms, and perform other miscellaneous tasks.

== Update the MetroCluster switch RCF files before upgrading controllers


You might need to update the MetroCluster switch RCF files before you upgrade controllers depending on the old and new platform models, if the switch configuration is not on the minimum version, or if you need to change VLAN IDs used by the back-end MetroCluster connections.

.About this task

You must update the RCF file in the following scenarios:

* If the VLAN IDs for the MetroCluster are *not* 10, 20, or in the range of 101 to 4096, and the old or new platform is *not* one of the following:

** FAS8200 or AFF A300

** AFF A320

**  FAS9000 or AFF A700

** AFF A800, AFF C800, ASA A800, or ASA C800
+
[NOTE] 
====
* You can only change the MetroCluster VLAN for the platforms listed. If the old and new platforms are not listed above, you cannot change the VLAN ID. It is configured when you create the MetroCluster interfaces and cannot be changed. In this case, the VLANs are in the correct range.

* The local cluster connections can use any VLAN, they do not need to be in the given range. 
==== 

* The switch configuration was not configured with minimum supported RCF version:
+
|===

h| Switch model h| Required RCF file version

a|
Cisco 3132Q-V
a|
1.7 or later
a|
Cisco 3232C
a|
1.7 or later
a|
Broadcom BES-53248
a|
1.3 or later
a| NVIDIA SN2100
a| 2.0 or later
|===


The switches at site_A will be upgraded when the controllers on site_A are upgraded.

.Steps

. Prepare the IP switches for the application of the new RCF files.
+
Follow the steps in the section for your switch vendor: 

 ** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults[Reset the Broadcom IP switch to factory defaults]
 ** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults[Reset the Cisco IP switch to factory defaults]
 ** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults[Reset the NVIDIA IP SN2100 switch to factory defaults]

. Download and install the RCF files.
+
Follow the steps in the section for your switch vendor: 

 ** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files[Download and install the Broadcom RCF files]
 ** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files[Download and install the Cisco IP RCF files]
 ** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files[Download and install the NVIDIA IP RCF files]

== Map ports from the old nodes to the new nodes

You must verify that the physical ports on node_A_1-old map correctly to the physical ports on node_A_1-new, which will allow node_A_1-new to communicate with other nodes in the cluster and with the network after the upgrade.

.About this task

When the new node is first booted during the upgrade process, it will replay the most recent configuration of the old node it is replacing. When you boot node_A_1-new, ONTAP attempts to host LIFs on the same ports that were used on node_A_1-old. Therefore, as part of the upgrade you must adjust the port and LIF configuration so it is compatible with that of the old node. During the upgrade procedure, you will perform steps on both the old and new nodes to ensure correct cluster, management, and data LIF configuration.

The following table shows examples of configuration changes related to the port requirements of the new nodes.

|===

3+h| Cluster interconnect physical ports
h| Old controller h| New controller h| Required action

a|
e0a, e0b

a|
e3a, e3b

a|
No matching port. After upgrade, you must recreate cluster ports.

a|
e0c, e0d

a|
e0a,e0b,e0c,e0d

a|
e0c and e0d are matching ports. You do not have to change the configuration, but after upgrade you can spread your cluster LIFs across the available cluster ports.

|===

.Steps
. Determine what physical ports are available on the new controllers and what LIFs can be hosted on the ports.
+
The controller's port usage depends on the platform module and which switches you will use in the MetroCluster IP configuration. You can gather the port usage of the new platforms from the link:https://hwu.netapp.com[NetApp Hardware Universe].

. Plan your port usage and fill in the following tables for reference for each of the new nodes.
+
You will refer to the table as you carry out the upgrade procedure.
+

|===

h|  3+h| node_A_1-old 3+h| node_A_1-new
h| LIF h| Ports h| IPspaces h| Broadcast domains h| Ports h| IPspaces h| Broadcast domains

a|
Cluster 1
a|

a|

a|

a|

a|

a|

a|
Cluster 2
a|

a|

a|

a|

a|

a|

a|
Cluster 3
a|

a|

a|

a|

a|

a|

a|
Cluster 4
a|

a|

a|

a|

a|

a|

a|
Node management
a|

a|

a|

a|

a|

a|

a|
Cluster management
a|

a|

a|

a|

a|

a|

a|
Data 1
a|

a|

a|

a|

a|

a|

a|
Data 2
a|

a|

a|

a|

a|

a|

a|
Data 3
a|

a|

a|

a|

a|

a|

a|
Data 4
a|

a|

a|

a|

a|

a|

a|
SAN
a|

a|

a|

a|

a|

a|

a|
Intercluster port
a|

a|

a|

a|

a|

a|

|===

== Netboot the new controllers

After you install the new nodes, you need to netboot to ensure the new nodes are running the same version of ONTAP as the original nodes. The term netboot means you are booting from an ONTAP image stored on a remote server. When preparing for netboot, you must put a copy of the ONTAP 9 boot image onto a web server that the system can access.

.Steps

. Netboot the new controllers:
 .. Access the https://mysupport.netapp.com/site/[NetApp Support Site] to download the files used for performing the netboot of the system.
 .. Download the appropriate ONTAP software from the software download section of the NetApp Support Site and store the `ontap-version_image.tgz` file on a web-accessible directory.
 .. Change to the web-accessible directory and verify that the files you need are available.
+
Your directory listing should contain a netboot folder with a kernel file:
+
`_ontap-version_image.tgz`
+
You do not need to extract the `_ontap-version_image.tgz` file.


.. At the LOADER prompt, configure the netboot connection for a management LIF:
+

|===

h| If IP addressing is... h| Then...

a|
DHCP
a|
Configure the automatic connection:

`ifconfig e0M -auto`
a|
Static
a|
Configure the manual connection:

`ifconfig e0M -addr=_ip_addr_ -mask=_netmask_ -gw=_gateway_`
|===

..  Perform the netboot.
+
`netboot \http://_web_server_ip/path_to_web-accessible_directory/ontap-version_image.tgz`

.. From the boot menu, select option **(7) Install new software first** to download and install the new software image to the boot device.
+
Disregard the following message:
+
`"This procedure is not supported for Non-Disruptive Upgrade on an HA pair"`. It applies to nondisruptive upgrades of software, not to upgrades of controllers.

.. If you are prompted to continue the procedure, enter `y`, and when prompted for the package, enter the URL of the image file:
+
`http://__web_server_ip/path_to_web-accessible_directory/ontap-version___image.tgz`

.. Enter the user name and password if applicable, or press Enter to continue.

.. Be sure to enter `n` to skip the backup recovery when you see a prompt similar to the following:
+
----
Do you want to restore the backup configuration now? {y|n} n
----

.. Reboot by entering `*y*` when you see a prompt similar to the following:
+
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----

== Clear the configuration on a controller module

// include reference

include::../_include/steps_clear_config_boot_to_maint_mode.adoc[]

// end include reference

== Verify MetroCluster health before site upgrade

You must verify the health and connectivity of the MetroCluster configuration prior to performing the upgrade.

.Steps

. Verify the operation of the MetroCluster configuration in ONTAP:
.. Check whether the nodes are multipathed:
 +
`node run -node <node_name> sysconfig -a`
+
You should issue this command for each node in the MetroCluster configuration.

 .. Verify that there are no broken disks in the configuration:
 +
`storage disk show -broken`
+
You should issue this command on each node in the MetroCluster configuration.

.. Check for any health alerts:
+
`system health alert show`
+
You should issue this command on each cluster.

.. Verify the licenses on the clusters:
+
`system license show`
+
You should issue this command on each cluster.

.. Verify the devices connected to the nodes:
+
`network device-discovery show`
+
You should issue this command on each cluster.

.. Verify that the time zone and time is set correctly on both sites:
+
`cluster date show`
+
You should issue this command on each cluster. You can use the `cluster date` commands to configure the time and time zone.
. Confirm the operational mode of the MetroCluster configuration and perform a MetroCluster check.
 .. Confirm the MetroCluster configuration and that the operational mode is `normal`:
 +
`metrocluster show`
 .. Confirm that all expected nodes are shown:
 +
`metrocluster node show`
 .. Issue the following command:
+
`metrocluster check run`
 .. Display the results of the MetroCluster check:
+
`metrocluster check show`
. Check the MetroCluster cabling with the Config Advisor tool.
 .. Download and run Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[NetApp Downloads: Config Advisor]

 .. After running Config Advisor, review the tool's output and follow the recommendations in the output to address any issues discovered.

== Gather information before the upgrade

Before upgrading, you must gather information for each of the nodes, and, if necessary, adjust the network broadcast domains, remove any VLANs and interface groups, and gather encryption information.

.Steps

. Record the physical cabling for each node, labelling cables as needed to allow correct cabling of the new nodes.
. Gather interconnect, port and LIF information for each node.
+
You should gather the output of the following commands for each node:

 ** `metrocluster interconnect show`
 ** `metrocluster configuration-settings connection show`
 ** `network interface show -role cluster,node-mgmt`
 ** `network port show -node <node_name> -type physical`
 ** `network port vlan show -node <node_name>`
 ** `network port ifgrp show -node <node_name> -instance`
 ** `network port broadcast-domain show`
 ** `network port reachability show -detail`
 ** `network ipspace show`
 ** `volume show`
 ** `storage aggregate show`
 ** `system node run -node <node_name> sysconfig -a`
  ** `aggr show -r` 
 ** `disk show`  
 ** `system node run <node-name> disk show`  
 ** `vol show -fields type` 
 ** `vol show -fields type , space-guarantee`
 ** `vserver fcp initiator show`
 ** `storage disk show`
 ** `metrocluster configuration-settings interface show`

. Gather the UUIDs for the site_B (the site whose platforms are currently being upgraded):
+
`metrocluster node show -fields node-cluster-uuid, node-uuid`
+
These values must be configured accurately on the new site_B controller modules to ensure a successful upgrade. Copy the values to a file so that you can copy them into the proper commands later in the upgrade process.
+
The following example shows the command output with the UUIDs:
+
----
cluster_B::> metrocluster node show -fields node-cluster-uuid, node-uuid
  (metrocluster node show)
dr-group-id cluster     node   node-uuid                            node-cluster-uuid
----------- --------- -------- ------------------------------------ ------------------------------
1           cluster_A node_A_1 f03cb63c-9a7e-11e7-b68b-00a098908039 ee7db9d5-9a82-11e7-b68b-00a098908039
1           cluster_A node_A_2 aa9a7a7a-9a81-11e7-a4e9-00a098908c35 ee7db9d5-9a82-11e7-b68b-00a098908039
1           cluster_B node_B_1 f37b240b-9ac1-11e7-9b42-00a098c9e55d 07958819-9ac6-11e7-9b42-00a098c9e55d
1           cluster_B node_B_2 bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f 07958819-9ac6-11e7-9b42-00a098c9e55d
4 entries were displayed.
cluster_B::*
----
+
It is recommended that you record the UUIDs into a table similar to the following.
+

|===

h| Cluster or node h| UUID

a|
cluster_B
a|
07958819-9ac6-11e7-9b42-00a098c9e55d
a|
node_B_1
a|
f37b240b-9ac1-11e7-9b42-00a098c9e55d
a|
node_B_2
a|
bf8e3f8f-9ac4-11e7-bd4e-00a098ca379f
a|
cluster_A
a|
ee7db9d5-9a82-11e7-b68b-00a098908039
a|
node_A_1
a|
f03cb63c-9a7e-11e7-b68b-00a098908039
a|
node_A_2
a|
aa9a7a7a-9a81-11e7-a4e9-00a098908c35
|===

. If the MetroCluster nodes are in a SAN configuration, collect the relevant information.
+
You should gather the output of the following commands:

 ** `fcp adapter show -instance`
 ** `fcp interface show -instance`
 ** `iscsi interface show`
 ** `ucadmin show`

. If the root volume is encrypted, collect and save the passphrase used for key-manager:
+
`security key-manager backup show`

. If the MetroCluster nodes are using encryption for volumes or aggregates, copy information about the keys and passphrases.
+
For additional information, see https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html[Backing up onboard key management information manually].

 .. If Onboard Key Manager is configured:
 +
`security key-manager onboard show-backup`
+
You will need the passphrase later in the upgrade procedure.

 .. If enterprise key management (KMIP) is configured, issue the following commands:
+
`security key-manager external show -instance`
`security key-manager key query`

. Gather the system IDs of the existing nodes:
+
`metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid`
+
The following output shows the reassigned drives.
+
----
::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid

dr-group-id cluster     node     node-systemid ha-partner-systemid dr-partner-systemid dr-auxiliary-systemid
----------- ----------- -------- ------------- ------------------- ------------------- ---------------------
1           cluster_A node_A_1   537403324     537403323           537403321           537403322
1           cluster_A node_A_2   537403323     537403324           537403322           537403321
1           cluster_B node_B_1   537403322     537403321           537403323           537403324
1           cluster_B node_B_2   537403321     537403322           537403324           537403323
4 entries were displayed.
----

== Remove Mediator or Tiebreaker monitoring

Before the upgrading the platforms, you must remove monitoring if the MetroCluster configuration is monitored with the Tiebreaker or Mediator utility.

.Steps

. Collect the output for the following command:
+
`storage iscsi-initiator show`

. Remove the existing MetroCluster configuration from Tiebreaker, Mediator, or other software that can initiate switchover.
+

|===

h| If you are using... h| Use this procedure...

a|
Tiebreaker
a|
link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations[Removing MetroCluster Configurations] 
a|
Mediator
a|
Issue the following command from the ONTAP prompt:

`metrocluster configuration-settings mediator remove`
a|
Third-party applications
a|
Refer to the product documentation.
|===

== Send a custom AutoSupport message prior to maintenance

Before performing the maintenance, you should issue an AutoSupport message to notify NetApp technical support that maintenance is underway. Informing technical support that maintenance is underway prevents them from opening a case on the assumption that a disruption has occurred.

.About this task

This task must be performed on each MetroCluster site.

.Steps

. Log in to the cluster.

. Invoke an AutoSupport message indicating the start of the maintenance:
+
`system node autosupport invoke -node * -type all -message MAINT=__maintenance-window-in-hours__`
+
The `maintenance-window-in-hours` parameter specifies the length of the maintenance window, with a maximum of 72 hours. If the maintenance is completed before the time has elapsed, you can invoke an AutoSupport message indicating the end of the maintenance period:
+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Repeat these steps on the partner site.

.What's next?
link:upgrade-mcc-ip-manual-switchover.html[Switch over the MetroCluster configuration].

// 2024 Nov 12, ONTAPDOC-2351