---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-boot-new-controllers.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Reboot the controllers from the boot menu to update the controller flash image. Additional steps are required if encryption is configured.'
---
= Boot the new MetroCluster IP controllers and restore LIF configuration
:icons: font
:imagesdir: ../media/

[.lead]
Boot the new controllers and verify that LIFs are hosted on appropriate nodes and ports.

You can reconfigure VLANs and interface groups. If required, manually modify the ports for the cluster LIFs and broadcast domain details before resuming the operation by using the `system controller replace resume` command.

.About this task

This task must be performed on all the new controllers.

.Steps

. Halt the node:
+
`halt`

. If external key manager is configured, set the related bootargs:
+
`setenv bootarg.kmip.init.ipaddr <ip-address>`
+
`setenv bootarg.kmip.init.netmask <netmask>`
+
`setenv bootarg.kmip.init.gateway <gateway-address>`
+
`setenv bootarg.kmip.init.interface <interface-id>`
. Display the boot menu:
+
`boot_ontap menu`
. If root encryption is used, select the boot menu option for your key management configuration.
+

|===

h| If you are using... h| Select this boot menu option...

a|
Onboard key management
a|
Option "`10`"

Follow the prompts to provide the required inputs to recover and restore the key-manager configuration.
a|
External key management
a|
Option "`11`"

Follow the prompts to provide the required inputs to recover and restore the key-manager configuration.
|===


. From the boot menu, run option "`6`".
+
NOTE: Option "`6`" reboots the node twice before the process completes.
+

Respond with "`y`" to the system ID change prompts. Wait for the second reboot messages:
+
----
Successfully restored env file from boot media...

Rebooting to load the restored env file...
----
+
During one of the reboots after option "`6`", the confirmation prompt `Override system ID? {y|n}` appears. Enter `y`.
. If root encryption is used, select the boot menu option again for your key management configuration.
+

|===

h| If you are using... h| Select this boot menu option...

a|
Onboard key management
a|
Option "`10`"

Follow the prompts to provide the required inputs to recover and restore the key-manager configuration.
a|
External key management
a|
Option "`11`"

Follow the prompts to provide the required inputs to recover and restore the key-manager configuration.
|===
+
Depending on the key manager setting, perform the recovery procedure by selecting option "`10`" or option "`11`", followed by option "`6`" at the first boot menu prompt. To boot the nodes completely, you might need to repeat the recovery procedure continued by option "`1`" (normal boot).

. Boot the nodes:
+
`boot_ontap`

. Wait for the replaced nodes to boot up.
+
If either node is in takeover mode, perform a giveback using the `storage failover giveback` command.

. Verify that all ports are in a broadcast domain:

.. View the broadcast domains:
+
`network port broadcast-domain show`

.. If a new broadcast domain is created for the data ports on the newly upgraded controllers, delete the broadcast domain:
+
NOTE: Only delete the new broadcast domain. Do not delete any of the broadcast domains that existed before starting the upgrade.
+
`broadcast-domain delete -broadcast-domain <broadcast_domain_name>`
.. Add any ports to a broadcast domain as needed.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-003BDFCD-58A3-46C9-BF0C-BA1D1D1475F9.html[Add or remove ports from a broadcast domain^]

.. Add the physical port that will host the intercluster LIFs to the corresponding broadcast domain.
.. Modify intercluster LIFs to use the new physical port as home port.
.. After the intercluster LIFs are up, check the cluster peer status and re-establish cluster peering as needed.
+
You might need to reconfigure cluster peering.
+
link:../install-ip/task_sw_config_configure_clusters.html#peering-the-clusters[Create a cluster peer relationship]

.. Recreate VLANs and interface groups as needed.
+
VLAN and interface group membership might be different than that of the old node.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-8929FCE2-5888-4051-B8C0-E27CAF3F2A63.html[Create a VLAN^]
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/GUID-DBC9DEE2-EAB7-430A-A773-4E3420EE2AA1.html[Combine physical ports to create interface groups^]

.. Verify that the partner cluster is reachable and that the
configuration is successfully resynchronized on the partner cluster: 
+
`metrocluster switchback -simulate true`

. If encryption is used, restore the keys using the correct command for your key management configuration.
+

|===

h| If you are using... h| Use this command...

a|
Onboard key management
a|
`security key-manager onboard sync`

For more information, see https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-E4AB2ED4-9227-4974-A311-13036EB43A3D.html[Restore onboard key management encryption keys^].
a|
External key management
a|
`security key-manager external restore -vserver <svm-name> -node <node-name> -key-server <host_name\|IP_address:port> -key-id <key_id> -key-tag key_tag <node-name>`

For more information, see https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-32DA96C3-9B04-4401-92B8-EAF323C3C863.html[Restore external key management encryption keys^].

|===

. Verify that the MetroCluster is configured correctly. Check the node status:
+
`metrocluster node show`
+
Verify that the new nodes (site_B) are in *Waiting for switchback state* from site_A.

== Verify and restore LIF configuration

Verify that LIFs are hosted on appropriate nodes before you proceed with the automated switchback operation.

.About this task

* This task is performed on site_B.

CAUTION: You must verify that the location of the data LIFs is correct on the new nodes before you perform a switchback. When you switchback the configuration, ONTAP attempts to resume traffic on the home port used by the LIFs. I/O failure can occur when the home port connection to the switch port and VLAN is incorrect.

.Steps

. Verify that LIFs are hosted on the appropriate node and ports before switchback.

.. Change to the advanced privilege level:
+
`set -privilege advanced`

..  Display the LIFs, and confirm that each data LIF is using the correct home port:
+
`network interface show` 

.. Modify any LIFs that aren't using the correct home port:
+
`network interface modify -vserver <svm-name> -lif <data-lif> -home-port <port-id>`
+
If the command returns an error, you can override the port configuration:
+
`vserver config override -command "network interface modify -vserver <svm-name> -home-port <active_port_after_upgrade> -lif <lif_name> -home-node <new_node_name>"`
+
When entering the network interface modify command within the `vserver config override` command, you cannot use the tab autocomplete feature. You can create the network `interface modify` using autocomplete and then enclose it in the `vserver config override` command.

.. Confirm that all data LIFs are now on the correct home port:
+
`network interface show` 

.. Return to the admin privilege level:
+
`set -privilege admin`
. Revert the interfaces to their home node:
+
`network interface revert * -vserver <svm-name>`
+
Perform this step on all SVMs as required.

. Resume the operation:
+
`system controller replace resume`

.What's next?
link:upgrade-mcc-ip-system-controller-replace-complete-upgrade.html[Complete the controller upgrade].

// 2024 Nov 12, ONTAPDOC-2351
