---
permalink: upgrade/upgrade-mcc-ip-manual-hba-set-ha.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'Configure the HBA cards in the controller module and verify and set the HA state of the controller and chassis.'
---
= Restore the HBA configuration and set the HA state of the MetroCluster IP controller and chassis
:icons: font
:imagesdir: ../media/

[.lead]
Configure the HBA cards in the controller module and verify and set the HA state of the controller and chassis. 

== Restore the HBA configuration

Depending on the presence and configuration of HBA cards in the controller module, you need to configure them correctly for your site.

.Steps

. In Maintenance mode, configure the settings for any HBAs in the system:
.. Check the current settings of the ports: `ucadmin show`
.. Update the port settings as needed.

+

|===

h| If you have this type of HBA and desired mode... h| Use this command...

a|
CNA FC
a|
`ucadmin modify -m fc -t initiator <adapter-name>`
a|
CNA Ethernet
a|
`ucadmin modify -mode cna <adapter-name>`
a|
FC target
a|
`fcadmin config -t target <adapter-name>`
a|
FC initiator
a|
`fcadmin config -t initiator <adapter-name>`
|===
. Exit Maintenance mode:
+
`halt`
+
After you run the command, wait until the node stops at the `LOADER` prompt.

. Boot the node back into Maintenance mode to apply the configuration changes:
+
`boot_ontap maint`
. Verify the changes:
+

|===

h| If you have this type of HBA... h| Use this command...

a|
CNA
a|
`ucadmin show`
a|
FC
a|
`fcadmin show`
|===

== Set the HA state on the new controllers and chassis

You must verify the HA state of the controllers and chassis, and, if necessary, update the state to match your system configuration.

.Steps

. In Maintenance mode, display the HA state of the controller module and chassis:
+
`ha-config show`
+
The HA state for all components should be `mccip`.

. If the displayed system state of the controller or chassis isn't correct, set the HA state:
+
`ha-config modify controller mccip`
+
`ha-config modify chassis mccip`

. Verify and modify the Ethernet ports connected to NS224 shelves or storage switches.
+
.. Verify the Ethernet ports connected to NS224 shelves or storage switches:
+
`storage port show`
+
.. Set all Ethernet ports connected to Ethernet shelves or storage switches, including shared switches for storage and cluster, to `storage` mode:
+ 
`storage port modify -p <port> -m storage` 
+
Example:
+
----
*> storage port modify -p e5b -m storage
Changing NVMe-oF port e5b to storage mode
----
+
NOTE: This must be set on all affected ports for a successful upgrade.
+
Disks from the shelves attached to the Ethernet ports are reported in the `sysconfig -v` output. 
+
Refer to the link:https://hwu.netapp.com[Hardware Universe^] for information on the storage ports for the system you are upgrading to.

.. Verify that `storage` mode is set and confirm that the ports are in the online state:
+
`storage port show`

. Halt the node: `halt`
+
The node should stop at the `LOADER>` prompt.

.	On each node, check the system date, time, and time zone: `show date`
.	If necessary, set the date in UTC or GMT: `set date <mm/dd/yyyy>`
.	Check the time by using the following command at the boot environment prompt: `show time`
.	If necessary, set the time in UTC or GMT: `set time <hh:mm:ss>`

.	Save the settings: `saveenv`
.	Gather environment variables: `printenv`

[remove-internal-drives-integrated-manual]
== Remove or unseat internal drives from integrated systems

When you upgrade from a modular system that doesn't support internal drives to an integrated system with disks and controllers in the same chassis, you need to remove or unseat all internal drives from the integrated system until you have completed the upgrade. This only applies if you are upgrading from a modular system to an integrated system.

CAUTION: This task is mandatory for a successful controller upgrade when you upgrade from a modular to an integrated system.

The following table is for example purposes only, not all upgrade combinations listed are supported. To determine if your upgrade combination is affected, refer to the table in link:concept_choosing_controller_upgrade_mcc.html#all-other-supported-metrocluster-ip-controller-upgrades[Supported controller upgrades]. If your upgrade combination is marked with *Note 3*, you must remove or unseat the internal drives from the integrated system. 

[cols="2,2,2a" options="header"]
|===
// header row
| If you upgrade from a modular system...
| To an integrated system...
| Then...

a|The following lists examples of modular systems:

* AFF A400, AFF C400
* AFF A300
* AFF A900
* AFF A700
* AFF A1K
* FAS9000, FAS9500
* FAS70, FAS90 
* FAS8300, FAS8700, FAS8200 

a|The following lists examples of integrated systems:

* AFF A150, AFF A220 
* AFF A250, AFF C250
* AFF C800, AFF A800
* AFF A70, AFF A90 
* AFF C80
* AFF A20
* AFF A30, AFF C30
* AFF A50
* AFF C60 

a| Remove or unseat the internal drives from the integrated system
// table end
|===




.What's next?
link:upgrade-mcc-ip-manual-apply-rcf-set-bootarg.html[Update the switch RCFs and set the MetroCluster IP bootarg values].

// 2024 Nov 12, ONTAPDOC-2351