---
permalink: upgrade/upgrade-mcc-ip-system-controller-replace-prechecks.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc
summary: 'To prepare for the controller upgrade, you perform system prechecks and collect the configuration information.'
---
= Prepare the MetroCluster IP system for upgrade
:icons: font
:imagesdir: ../media/

[.lead]
To prepare for the controller upgrade, you might need to upgrade the switch reference configuration files (RCFs) depending on the old and new platform models. You then perform system prechecks, collect the configuration information, and remove existing monitoring software.

== Update the MetroCluster switch RCFs before upgrading controllers

Depending on the old and new platform models, you might need to update the MetroCluster switch reference configuration files (RCFs) before you upgrade controllers.

.About this task

Perform this task in the following circumstances: 

** The switch RCF configuration isn't on the minimum version.
** You need to change VLAN IDs used by the back-end MetroCluster connections.

.Before you begin

Determine whether you need to update the RCFs before you upgrade your controllers: 

* If the switch configuration wasn't configured with the minimum supported RCF version, you need to update the RCFs before you upgrade your controllers:
+
|===

h| Switch model h| Required RCF version

a|
Cisco 3132Q-V
a|
1.7 or later
a|
Cisco 3232C
a|
1.7 or later
a|
Broadcom BES-53248
a|
1.3 or later
a| NVIDIA SN2100
a| 2.0 or later
|===

* If both of your old and new platform models are in the following list, you do *not* need to update the VLAN ID before you upgrade controllers:

** FAS8200 or AFF A300

** AFF A320

** FAS9000 or AFF A700

** AFF A800, AFF C800, ASA A800, or ASA C800
+
If either of your old or new platform models are not listed above, you must confirm that the MetroCluster interfaces are using a supported VLAN ID. Supported VLAN IDs for the MetroCluster interfaces are: 10, 20, or in the range of 101 to 4096.
+
[CAUTION] 
====
* If the VLAN ID is not 10, 20, or in the range of 101 to 4096, you must upgrade the switch RCF before you upgrade controllers. 
* The local cluster connections can use any VLAN, they don't need to be in the given range.
* The new RCF that you are upgrading to must use the VLANs 10, 20, or be in the range 101 to 4096. Don't change the VLAN for the local cluster unless it is required. 
====

.Steps

. Prepare the IP switches for the application of the new RCFs.
+
Follow the steps in the section for your switch vendor: 
+
NOTE: You should update the switches in the following order: switch_A_1, switch_B_1, switch_A_2, switch_B_2.

 ** link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults[Reset the Broadcom IP switch to factory defaults]
 ** link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults[Reset the Cisco IP switch to factory defaults]
 ** link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults[Reset the NVIDIA IP SN2100 switch to factory defaults]

. Download and install the RCFs.
+
Follow the steps in the section for your switch vendor: 

 ** link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files[Download and install the Broadcom RCFs]
 ** link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files[Download and install the Cisco IP RCFs]
 ** link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files[Download and install the NVIDIA IP RCFs]


== Start the controller replacement operation and perform system prechecks 

Before the prechecks start, if ONTAP Mediator is installed, it is automatically detected and removed. To confirm the removal, you are prompted to enter a username and password. When you complete the upgrade, or if prechecks fail or you choose not to proceed with the upgrade, you must manually link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html[re-configure the ONTAP Mediator service].

At any stage during the upgrade, you can run the `system controller replace show` or `system controller replace show-details` command from site A to check the status. If the commands return a blank output, wait for a few minutes and rerun the command.

.Steps

. Start the automated controller replacement procedure depending on whether you are performing this procedure on the first site (from site A to replace the controllers at site B), or if you are repeating the procedure after already replacing the controllers at site B.
+
NOTE: If you do not use the `-nso true` parameter in the command, the controller upgrade procedure chooses NSO based automated switchover and switchback as the default procedure on MetroCluster IP systems.
+
[role="tabbed-block"]
====
.Upgrade controllers at the first site
--
. Run the following command from site A to replace the controllers at site B:
+
`system controller replace start -nso true`
+
The automated operation executes the prechecks. If no issues are found, the operation pauses so you can manually collect the configuration related information.

* The current source system and all compatible target systems are displayed. If you have replaced the source controller with a controller that has a different ONTAP version or a non-compatible platform, the automation operation halts and reports an error after the new nodes are booted up. To bring the cluster back to a healthy state, you need to follow the manual recovery procedure.
+
The `system controller replace start` command might report the following precheck error:
+
----
Cluster-A::*>system controller replace show
Node        Status         Error-Action
----------- -------------- ------------------------------------
Node-A-1    Failed         MetroCluster check failed. Reason : MCC check showed errors in component aggregates
----
+
Check if this error occurred because you have unmirrored aggregates or due to another aggregate issue. Verify that all mirrored aggregates are healthy and not degraded or mirror-degraded. If this error is due to unmirrored aggregates only, you can override this error by selecting the `-skip-metrocluster-check true` option on the `system controller replace start` command. If remote storage is accessible, the unmirrored aggregates come online after switchover. If the remote storage link fails, the unmirrored aggregates fail to come online.
--
.Upgrade controllers at the second site (repeating the procedure)
--
. Run the following command from site B to replace the controllers at site A:
+
`system controller replace start -nso true -skip-metrocluster-check true`
+
This skips the prechecks to avoid an error caused by having two different platform models at each site.
--
====


.	Manually collect the configuration information by logging in at site B and following the commands listed in the console message under the `system controller replace show` or `system controller replace show-details` command.


== Gather information before the upgrade

Before upgrading, if the root volume is encrypted, you must gather the backup key and other information to boot the new controllers with the old encrypted root volumes.

.About this task

This task is performed on the existing MetroCluster IP configuration.

.Steps

. Label the cables for the existing controllers, so you can easily identify the cables when setting up the new controllers.
. Display the commands to capture the backup key and other information:
+
`system controller replace show`
+
Run the commands listed under the `show` command from the partner cluster.
+
The `show` command output displays three tables containing the MetroCluster interface IPs, system IDs, and system UUIDs. This information is required later in the procedure to set the bootargs when you boot the new node. 

. Gather the system IDs of the nodes in the MetroCluster configuration:
+
--
`metrocluster node show -fields node-systemid,dr-partner-systemid`

During the upgrade procedure, you will replace these old system IDs with the system IDs of the new controller modules.

In this example for a four-node MetroCluster IP configuration, the following old system IDs are retrieved:

** node_A_1-old: 4068741258
** node_A_2-old: 4068741260
** node_B_1-old: 4068741254
** node_B_2-old: 4068741256

----
metrocluster-siteA::> metrocluster node show -fields node-systemid,ha-partner-systemid,dr-partner-systemid,dr-auxiliary-systemid
dr-group-id        cluster           node            node-systemid     ha-partner-systemid     dr-partner-systemid    dr-auxiliary-systemid
-----------        ---------------   ----------      -------------     -------------------     -------------------    ---------------------
1                    Cluster_A       Node_A_1-old    4068741258        4068741260              4068741256             4068741256
1                    Cluster_A       Node_A_2-old    4068741260        4068741258              4068741254             4068741254
1                    Cluster_B       Node_B_1-old    4068741254        4068741256              4068741258             4068741260
1                    Cluster_B       Node_B_2-old    4068741256        4068741254              4068741260             4068741258
4 entries were displayed.
----

In this example for a two-node MetroCluster IP configuration, the following old system IDs are retrieved:

** node_A_1: 4068741258
** node_B_1: 4068741254

----
metrocluster node show -fields node-systemid,dr-partner-systemid

dr-group-id cluster    node          node-systemid dr-partner-systemid
----------- ---------- --------      ------------- ------------
1           Cluster_A  Node_A_1-old  4068741258    4068741254
1           Cluster_B  node_B_1-old  -             -
2 entries were displayed.
----
--

. Gather port and LIF information for each old node.
+
You should gather the output of the following commands for each node:

 ** `network interface show -role cluster,node-mgmt`
 ** `network port show -node <node-name> -type physical`
 ** `network port vlan show -node <node-name>`
 ** `network port ifgrp show -node <node-name> -instance`
 ** `network port broadcast-domain show`
 ** `network port reachability show -detail`
 ** `network ipspace show`
 ** `volume show`
 ** `storage aggregate show`
 ** `system node run -node <node-name> sysconfig -a`
 ** `aggr show -r` 
 ** `disk show`  
 ** `system node run <node-name> disk show`   
 ** `vol show -fields type` 
 ** `vol show -fields type , space-guarantee` 
 ** `vserver fcp initiator show` 
 ** `storage disk show`
 ** `metrocluster configuration-settings interface show` 

. If the MetroCluster nodes are in a SAN configuration, collect the relevant information.
+
You should gather the output of the following commands:

 ** `fcp adapter show -instance`
 ** `fcp interface show -instance`
 ** `iscsi interface show`
 ** `ucadmin show`

. If the root volume is encrypted, collect and save the passphrase used for key-manager:
+
`security key-manager backup show`
. If the MetroCluster nodes are using encryption for volumes or aggregates, copy information about the keys and passphrases.
+
For additional information, see https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/GUID-1677AE0A-FEF7-45FA-8616-885AA3283BCF.html[Back up onboard key management information manually^].

.. If Onboard Key Manager is configured:
+
`security key-manager onboard show-backup`
+
You will need the passphrase later in the upgrade procedure.

.. If enterprise key management (KMIP) is configured, issue the following commands:
+
`security key-manager external show -instance`
+
`security key-manager key query`

. After you finish collecting the configuration information, resume the operation:
+
`system controller replace resume`

== Remove the existing configuration from Tiebreaker or other monitoring software

Before you start the upgrade, remove the existing configuration from the Tiebreaker or other monitoring software.

If the existing configuration is monitored with the MetroCluster Tiebreaker configuration or other third-party applications (for example, ClusterLion) that can initiate a switchover, you must remove the MetroCluster configuration from the Tiebreaker or other software prior to replacing the old controller.

.Steps

. link:../tiebreaker/concept_configuring_the_tiebreaker_software.html#removing-metrocluster-configurations[Remove the existing MetroCluster configuration] from the Tiebreaker software.

. Remove the existing MetroCluster configuration from any third-party application that can initiate switchover.
+
Refer to the documentation for the application.

.What's next?
link:upgrade-mcc-ip-system-controller-replace-prepare-network-configuration.html[Prepare the network configuration of the old controllers].

// 2024 Nov 12, ONTAPDOC-2351