---
permalink: upgrade/upgrade-mcc-ip-manual-set-bootarg.html
sidebar: sidebar
keywords: metrocluster, upgrade, controllers, switchover, switchback, ip, configuration, net, boot, root, aggregate, system, commands, mcc, bootarg
summary: 'Upgrades to systems introduced in ONTAP 9.15.1 or later require you to set a bootarg before you can proceed with the controller upgrade.'
---
= Set the required bootarg (for MetroCluster IP upgrades to systems introduced in ONTAP 9.15.1 or later)
:icons: font
:imagesdir: ../media/

[.lead]
If you are upgrading to a system introduced in ONTAP 9.15.1 or later, you might need to set a bootarg on the old controllers before you can start the upgrade.

NOTE: If your upgrade combination is affected, you must set the required bootarg on all of the old nodes at both sites before you start the upgrade. 

== Step 1: Determine whether you need to set a bootarg on the old controllers

You do *not* have to set a bootarg on the old controllers if the following applies to your upgrade combination: 

* You are upgrading from an AFF A70 to an AFF A90 system
* You are upgrading from a FAS70 to a FAS90 system
* You are *not* upgrading to any of the following systems:
** AFF A70, AFF A90, AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60
** FAS50

You *must* set a bootarg on the old controllers before starting the upgrade if the following applies to your upgrade combination:

* You are upgrading to an AFF A90 from any supported system except for AFF A70
* You are upgrading to a FAS90 from any supported system except for FAS70
* All other supported upgrades to the following systems require you to set a bootarg on the old controllers: 
** AFF A70, AFF A90,  AFF A1K
** FAS70, FAS90
** AFF C80
** AFF A50, AFF A20, AFF A30
** AFF C30, AFF C60 
** FAS50

CAUTION: If your upgrade is affected, you *must* set a required bootarg on the existing system before performing the upgrade. If your upgrade isn't affected, you can skip this task and go directly to link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].
 

== Step 2: Determine the bootarg you need to set on the old controllers

Most affected upgrades require you to set the `hw.cxgbe.toe_keepalive_disable` bootarg on the old controllers. However, certain upgrade paths require you to set the `bootarg.siw.interop_enabled` bootarg instead.

Use the following table to determine which bootarg you need to set for your specific upgrade combination.  

[[upgrade_paths_bootarg_assisted]]
[cols=2*,options="header"]
|===
| For this upgrade...
| Set the bootarg...
| From AFF A250 to AFF A30 | `bootarg.siw.interop_enabled`
| From AFF C250 to AFF C30 | `bootarg.siw.interop_enabled`
| From AFF A150 to AFF A20 | `bootarg.siw.interop_enabled`
| From AFF A220 to AFF A20 | `bootarg.siw.interop_enabled`
a| All other affected and supported upgrades to AFF A70, AFF A90, AFF A1K, FAS70, FAS90, AFF C80, AFF A50, AFF A20, AFF A30, AFF C30, AFF C60, or FAS50 systems

*Note:* If you are upgrading from an AFF A70 to an AFF A90, or from a FAS70 to a FAS90, you don't need to set any bootarg before the upgrade. | `hw.cxgbe.toe_keepalive_disable`
|===


== Step 3: Set the required bootarg on the old controllers

This task is *only* required for affected upgrades. Refer to <<Step 1: Determine whether you need to set a bootarg on the old controllers>> to confirm whether you need to perform this task.

.Steps

. Halt one node at both sites and allow its HA partner to perform a storage takeover of the node:
+
`halt  -node <node_name>`

. Set the required bootarg for your upgrade combination. You already determined the bootarg that you need to set by using the table in <<upgrade_paths_bootarg_manual,determine which bootarg you need to set>>. 
+
[role="tabbed-block"]
====
.hw.cxgbe.toe_keepalive_disable
--
.. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv hw.cxgbe.toe_keepalive_disable 1` 
+
`saveenv` 
+
`printenv hw.cxgbe.toe_keepalive_disable`
--
.bootarg.siw.interop_enabled
--

.. At the `LOADER` prompt of the halted node, enter the following: 
+
`setenv bootarg.siw.interop_enabled 1` 
+
`saveenv` 
+
`printenv bootarg.siw.interop_enabled` 

-- 

====
  

. Boot the node:
+
`boot_ontap`
    
. When the node boots, perform a giveback for the node at the prompt: 
+
`storage failover giveback -ofnode <node_name>`

. Repeat the steps on all nodes in the DR group or DR groups that you are upgrading.

.What's next?
link:upgrade-mcc-ip-prepare-system.html[Prepare the system for upgrade].

// 2025 Apr 17, ONTAPDOC-2917
// 2024 Nov 12, ONTAPDOC-2351


