---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html
sidebar: sidebar
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure, launch, cli, add, command, modify, removing
summary: After installation of the Tiebreaker software, you can add or modify MetroCluster configurations, or remove them from the Tiebreaker software.
---
= Configure the MetroCluster Tiebreaker software
:icons: font
:imagesdir: ../media/

[.lead]
After installation of the Tiebreaker software, you can add or modify MetroCluster configurations, or remove them from the Tiebreaker software.

== Launch the Tiebreaker software CLI

After installing the Tiebreaker software, you must launch its CLI to configure the software.

. Launch the CLI from the prompt of the host on which you installed the software:
+
`netapp-metrocluster-tiebreaker-software-cli`

. After installation and during the first startup, enter the password for the Tiebreaker user to access the database. 
This is the password that you specified for the database user during installation.

== Add MetroCluster configurations

After installing the NetApp MetroCluster Tiebreaker software, you can add more MetroCluster configurations, one at a time.

You must have installed the MetroCluster configuration in an ONTAP environment and enabled the settings in the software.

. Use the Tiebreaker command-line interface (CLI) monitor add command to add MetroCluster configurations.
+
If you are using the host name, it must be the fully qualified domain name (FQDN).
+
The following example shows the configuration of cluster_A:
+
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: cluster_A
Enter Cluster IP Address: 10.222.196.130
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: 10.222.196.40
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----

. Confirm that the MetroCluster configuration was added properly by using the Tiebreaker CLI `monitor show -status` command.
+
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

. Disable the observer mode for the Tiebreaker software to automatically initiate a switchover after it detects a site failure:
+
`monitor modify -monitor-name monitor_name -observer-mode false`
+
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker installation and configuration.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----

.Related information

link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html[Risks and limitations of using MetroCluster Tiebreaker in active mode]

== Import certificates 

To enable seamless monitoring in Tiebreaker 1.6 or later, you need to import the server Secure Sockets Layer (SSL) certificate, intermediate certificate (if one exists), and the root certificate from ONTAP to the key store in the Java Virtual Machine (JVM). 

.About this task

* This task is required in Tiebreaker 1.6 or later. 
* You perform this task after you have successfully added a MetroCluster configuration to Tiebreaker or if your certificates expire.

.Step

. Perform switchover simulation status checks:
+
.. Check the Tiebreaker monitoring status:
`monitor show -status`
+
.Example
[%collapsible]
=====
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Trigger a switchover simulation:
+
`monitor switchover-simulate -monitor-name <system_name> -cluster <cluster_name>`
+
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----

. Run the following command for each certificate you need to import (SSL server, intermediate, or root).
+
`/opt/netapp/java/bin/keytool -import -trustcacerts -file <certificate_file_name> -keystore "/opt/netapp/java/lib/security/cacerts" -alias <certificate>`
+
* The `<certificate_file_name>` value specifies the file name of the certificate that you want to import.
* The `-alias <certificate>` value specifies the name that you want to store the certificate under after it is imported to the JVM.
+
The following example shows how to import a root certificate with the file name `root.crt` and an SSL server certificate with the file name `ssl_cert.crt`:
+
----
/opt/netapp/java/bin/keytool -import -trustcacerts -file root.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias root

/opt/netapp/java/bin/keytool -import -trustcacerts -file ssl_cert.crt -keystore "/opt/netapp/java/lib/security/cacerts" -alias ssl_cert
----

. Restart the Tiebreaker software:
+
`systemctl restart netapp-metrocluster-tiebreaker-software`

. Perform the switchover simulation status checks again:
+
.. Check the Tiebreaker monitoring status:
`monitor show -status`
+
.Example
[%collapsible]
=====
----
NetApp MetroCluster Tiebreaker :> monitor show -status
MetroCluster: A700
    Disaster: false
    Monitor State: Normal
    Observer Mode: false
    Silent Period: 5
    Override Vetoes: false
    Cluster: ClusterA_siteA(UUID:713e5ab2-b4e8-11f0-91aa-00a098ef36a2)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_A1(UUID:9f6cecbf-b4e4-11f0-9d0f-00a098ef36a2)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_A2(UUID:2719bb56-b4e7-11f0-996c-00a09897caa3)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
    Cluster: ClusterB_siteB(UUID:72839591-b4e8-11f0-b688-00a09897cb73)
        Reachable: true
        Intersite Connectivity Available: true
            Node: node_B1(UUID:abfeab89-b4e4-11f0-a077-00a09897cb73)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
            Node: node_B2(UUID:31e395bf-b4e7-11f0-bf99-00a09897cb2f)
                Reachable: true
                Intersite Connectivity Available: true
                State: normal
----
=====
.. Trigger a switchover simulation:
+
`monitor switchover-simulate -monitor-name <name> -cluster <cluster_name>`
+
----
Successfully triggered Switchover Simulation. Please check the status of the Switchover Simulation on the ONTAP cluster using command "metrocluster operation history show"
----



== Commands for modifying MetroCluster Tiebreaker configurations

You can modify the MetroCluster configuration whenever you need to change the settings.

The Tiebreaker CLI monitor modify command can be used with any of the following options. You can confirm your changes with the monitor show -status command.

[cols="30,70"]
|===

h| Option h| Description

a|
-monitor-name
a|
Name of the MetroCluster configuration
a|
-enable-monitor
a|
Enables and disables monitoring of the MetroCluster configuration
a|
-silent-period
a|
Period in seconds for which the MetroCluster Tiebreaker software waits to confirm a site failure after detection
a|
-observer-mode
a|
Observer mode (true) provides monitoring only, and does not trigger a switchover if a site disaster occurs. Online mode (false) triggers a switchover if a site disaster occurs.

* link:concept_overview_of_the_tiebreaker_software.html[How the Tiebreaker software detects site failure]
* link:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.html[Risks and limitations of using MetroCluster Tiebreaker in active mode]

|===

The following example changes the silent period for the configuration.

----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----

The Tiebreaker CLI `debug` command can be used to change the logging mode.

[cols="30,70"]
|===

h| Command h| Description

a|
debug status
a|
Displays the status of the debug mode
a|
debug enable
a|
Enables the debug mode for logging
a|
debug disable
a|
Disables the debug mode for logging
|===

In systems running Tiebreaker 1.4 and earlier, the Tiebreaker CLI `update-mcctb-password` command can be used to update the user password. This command is deprecated in Tiebreaker 1.5 and later.

[cols="30,70"]
|===

h| Command h| Description

a|
update-mcctb-password
a|
The user password is successfully updated
|===

== Remove MetroCluster configurations

You can remove the MetroCluster configuration that is being monitored by the Tiebreaker software when you no longer want to monitor a MetroCluster configuration.

. Use the Tiebreaker CLI `monitor remove` command to remove the MetroCluster configuration.
+
In the following example, "`cluster_A`" is removed from the software:
+
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----

. Confirm that the MetroCluster configuration is removed properly by using the Tiebreaker CLI `monitor show -status` command.
+
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
