---
permalink: tiebreaker/concept_monitoring_the_mcc_configuration.html
sidebar: sidebar
keywords:
summary: ''
---
= Monitoring the MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
MetroCluster Tiebreaker software automates the recovery process by enabling you to monitor the MetroCluster configuration status, evaluate SNMP events and traps that are sent to NetApp customer support, and view the status of monitoring operations.

== Configuring AutoSupport

[.lead]
By default, AutoSupport messages are sent to NetApp a week after installation of the Tiebreaker software. Events that trigger AutoSupport notification include Tiebreaker software panics, detection of disaster conditions on MetroCluster configurations, or an unknown MetroCluster configuration status.

You must have a direct access for setting up AutoSupport messages.

. Use the Tiebreaker CLI autosupport command with any of the following options:
+
[cols=2*,options="header"]
|===
| Option| Description
a|
-invoke
a|
Sends an AutoSupport message to customer support
a|
-configure wizard
a|
Wizard to configure proxy server credentials
a|
-delete configuration
a|
Deletes the proxy server credentials
a|
--enable
a|
Enables AutoSupport notification (This is the default.)
a|
-disable
a|
Disables AutoSupport notification
a|
-show
a|
Displays AutoSupport status
|===
The following example shows that AutoSupport is enabled or disabled and the destination to which the AutoSupport content is posted:
+
----

NetApp MetroCluster Tiebreaker :> autosupport enable
AutoSupport already enabled.

NetApp MetroCluster Tiebreaker :> autosupport disable
AutoSupport status            : disabled
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup

NetApp MetroCluster Tiebreaker :> autosupport enable
AutoSupport status            : enabled
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup

NetApp MetroCluster Tiebreaker :> autosupport invoke
AutoSupport transmission      : success
Proxy Server IP Address       : 10.234.168.79
Proxy Server Port Number      : 8090
Proxy Server Username         : admin
AutoSupport destination       : https://support.netapp.com/asupprod/post/1.0/postAsup
----
+
The following example shows AutoSupport configured by means of an authenticated proxy server, using an IP address and port number:
+
----
NetApp MetroCluster Tiebreaker :> autosupport configure wizard
Enter Proxy Server IP address :  10.234.168.79
Enter Proxy Server port number :  8090
Enter Proxy Server Username :  admin
Enter Proxy Server Password : 123abc
Autosupport configuration updated successfully.
----
+
The following example shows the deletion of an AutoSupport configuration:
+
----
NetApp MetroCluster Tiebreaker :> autosupport delete configuration
Autosupport configuration deleted successfully.
----

=== SNMP events and traps

[.lead]
NetApp MetroCluster Tiebreaker software uses SNMP traps to notify you of significant events. These traps are part of the NetApp MIB file. Each trap contains the following information: trap name, severity, impact level, timestamp, and message.

[cols=2*,options="header"]
|===
| Event name| Event detail| Trap number
a|
MetroCluster Tie-Breaker is unable to reach the MetroCluster configuration
a|
Warns the administrator that the software cannot detect a disaster. This event occurs when both clusters are not reachable.
a|
25000
a|
MetroCluster Tie-Breaker is unable to reach cluster
a|
Warns the administrator that the software cannot reach one of the clusters.
a|
25001
a|
MetroCluster Tie-Breaker detected disaster at cluster
a|
Notifies the administrator that the software detects a site failure. A notification will be delivered.
a|
25002
a|
All links between partner cluster are severed.
a|
The software detects that both clusters are reachable, but all the network paths between the two clusters are down, and the clusters cannot communicate with each other.
a|
25005
a|
SNMP Test Trap
a|
SNMP configuration can now be tested by running the snmp config test command.
a|
25006
|===

== Displaying the status of monitoring operations

[.lead]
You can display the overall status of monitoring operations for a MetroCluster configuration.

. Use the Tiebreaker CLI monitor show command to display the status of a MetroCluster operation with any of the following options:
+
[cols=2*,options="header"]
|===
| Option| Description
a|
-monitor-name
a|
Displays the status for the specified monitor name
a|
-operation-history
a|
Displays up to 10 monitoring operations that were last performed on a cluster
a|
-stats
a|
Displays the statistics related to the specified cluster
a|
-status
a|
Displays the status of the specified cluster    *Note:* The MetroCluster Tiebreaker software might take up to 10 minutes to reflect the completion status of operations such as heal aggregates, heal roots, or switchback.
+
|===
The following example shows that the clusters cluster_A and cluster_B are connected and healthy:
+
----

NetApp MetroCluster Tiebreaker:> monitor show -status
MetroCluster: cluster_A
    Disaster: false
    Monitor State: Normal
    Observer Mode: true
    Silent Period: 15
    Override Vetoes: false
    Cluster: cluster_Ba(UUID:4d9ccf24-080f-11e4-9df2-00a098168e7c)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-a1(UUID:78b44707-0809-11e4-9be1-e50dab9e83e1)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-a2(UUID:9a8b1059-0809-11e4-9f5e-8d97cdec7102)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
    Cluster: cluster_B(UUID:70dacd3b-0823-11e4-a7b9-00a0981693c4)
        Reachable: true
        All-Links-Severed: FALSE
            Node: mcc5-b1(UUID:961fce7d-081d-11e4-9ebf-2f295df8fcb3)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
            Node: mcc5-b2(UUID:9393262d-081d-11e4-80d5-6b30884058dc)
                Reachable: true
                All-Links-Severed: FALSE
                State: normal
----
+
In the following example, the last seven operations that were run on cluster_B are displayed:
+
----

NetApp MetroCluster Tiebreaker:> monitor show -operation-history
MetroCluster: cluster_B
 [ 2014-09-15 04:48:32.274 ] MetroCluster Monitor is initialized
 [ 2014-09-15 04:48:32.278 ] Started Discovery and validation of MetroCluster Setup
 [ 2014-09-15 04:48:35.078 ] Discovery and validation of MetroCluster Setup succeeded. Started monitoring.
 [ 2014-09-15 04:48:35.246 ] NetApp MetroCluster Tiebreaker software is able to reach cluster "mcc5a"
 [ 2014-09-15 04:48:35.256 ] NetApp MetroCluster Tiebreaker software is able to reach cluster "mcc5b"
 [ 2014-09-15 04:48:35.298 ] Link to remote DR cluster is up for cluster "mcc5a"
 [ 2014-09-15 04:48:35.308 ] Link to remote DR cluster is up for cluster "mcc5b"
----

== Displaying MetroCluster configuration information

[.lead]
You can display the monitor name and IP address of all instances of MetroCluster configurations in the Tiebreaker software.

. Use the Tiebreaker CLI configuration show command to display the MetroCluster configuration information.
+
The following example shows the information for clusters cluster_A and cluster_B:
+
----
MetroCluster: North America
    Monitor Enabled: true
    ClusterA name: cluster_A
    ClusterA IpAddress: 10.222.196.130
    ClusterB name: cluster_B
    ClusterB IpAddress: 10.222.196.140
----

== Creating dump files

[.lead]
You save the overall status the Tiebreaker software to a dump file for debugging purposes.

. Use the Tiebreaker CLI monitor dump -status command to create a dump file of the overall status of all MetroCluster configurations.
+
The following example shows the successful creation of the /var/log/netapp/mcctb/metrocluster-tiebreaker-status.xml dump file:
+
----

NetApp MetroCluster Tiebreaker :> monitor dump -status
MCCTB status successfully dumped in file /var/log/netapp/mcctb/metrocluster-tiebreaker-status.xml
----
