---
permalink: tiebreaker/concept_configuring_the_tiebreaker_software.html
sidebar: sidebar
keywords: installation, tiebreaker, software, add, modify, metrocluster, configuration, remove, configuring, configure
summary: After installation of the Tiebreaker software, you can add or modify MetroCluster configurations, or remove them from the Tiebreaker software.
---
= Configuring the Tiebreaker software
:icons: font
:imagesdir: ../media/

[.lead]
After installation of the Tiebreaker software, you can add or modify MetroCluster configurations, or remove them from the Tiebreaker software.

== Launching the Tiebreaker software CLI

[.lead]
After installing the Tiebreaker software you must launch its CLI to configure the software.

. Launch the CLI from the prompt of the host on which you installed the software:``netapp-metrocluster-tiebreaker-software-cli``

== Adding MetroCluster configurations

[.lead]
After installing the NetApp MetroCluster Tiebreaker software, you can add more MetroCluster configurations, one at a time.

You must have installed the MetroCluster configuration in an ONTAP environment and enabled the settings in the software.

. Use the Tiebreaker command-line interface (CLI) monitor add command to add MetroCluster configurations.
+
If you are using the host name, it must be the fully qualified domain name (FQDN).
+
The following example shows the configuration of cluster_A:
+
----

NetApp MetroCluster Tiebreaker :> monitor add wizard
Enter monitor Name: cluster_A
Enter Cluster IP Address: 10.222.196.130
Enter Cluster Username: admin
Enter Cluster Password:
Enter Peer Cluster IP Address: 10.222.196.40
Enter Peer Cluster Username: admin
Enter Peer Cluster Password:
Successfully added monitor to NetApp MetroCluster Tiebreaker software.
----

. Confirm that the MetroCluster configuration was added properly by using the Tiebreaker CLI monitor show -status command.
+
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----

. Disable the observer mode for the Tiebreaker software to automatically initiate a switchover after it detects a site failure: `monitor modify -monitor-name monitor_name -observer-mode false`
+
----
NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name 8pack -observer-mode false
Warning: If you are turning observer-mode to false, make sure to review the 'risks and limitations'
as described in the MetroCluster Tiebreaker Installation and Configuration Guide.
Are you sure you want to enable automatic switchover capability for monitor "8pack"? [Y/N]: y
----

*Related information*

xref:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.adoc[Risks and limitations of using MetroCluster Tiebreaker in active mode]

== Commands for modifying MetroCluster Tiebreaker configurations

[.lead]
You can modify the MetroCluster configuration whenever you need to change the settings.

The Tiebreaker CLI monitor modify command can be used with any of the following options. You can confirm your changes with the monitor show -status command.

[cols=2*,options="header"]
|===
| Option| Description
a|
-monitor-name
a|
Name of the MetroCluster configuration
a|
-enable-monitor
a|
Enables and disables monitoring of the MetroCluster configuration
a|
-silent-period
a|
Period in seconds for which the MetroCluster Tiebreaker software waits to confirm a site failure after detection
a|
-observer-mode
a|
Observer mode (true) provides monitoring only, and does not trigger a switchover if a site disaster occurs. Online mode (false) triggers a switchover if a site disaster occurs.

* xref:concept_overview_of_the_tiebreaker_software.adoc[How the Tiebreaker software detects site failure]
* xref:concept_risks_and_limitation_of_using_mcc_tiebreaker_in_active_mode.adoc[Risks and limitations of using MetroCluster Tiebreaker in active mode]

|===
The following example changes the silent period for the configuration.

----

NetApp MetroCluster Tiebreaker :> monitor modify -monitor-name cluster_A -silent-period 15
Successfully modified monitor in NetApp MetroCluster Tiebreaker
software.
----

The Tiebreaker CLI debug command can be used to change the logging mode.

[cols=2*,options="header"]
|===
| Command| Description
a|
debug status
a|
Displays the status of the debug mode
a|
debug enable
a|
Enables the debug mode for logging
a|
debug disable
a|
Disables the debug mode for logging
|===
The Tiebreaker CLI update-mcctb-password command can be used to update the user password.

|===
| Command| Description
a|
update-mcctb-password
a|
The user password is successfully updated
|===

== Removing MetroCluster configurations

[.lead]
You can remove the MetroCluster configuration that is being monitored by the Tiebreaker software when you no longer want to monitor a MetroCluster configuration.

. Use the Tiebreaker CLI monitor remove command to remove the MetroCluster configuration.
+
In the following example, cluster_A is removed from the software:
+
----

NetApp MetroCluster Tiebreaker :> monitor remove -monitor-name cluster_A
Successfully removed monitor from NetApp MetroCluster Tiebreaker
software.
----

. Confirm that the MetroCluster configuration is removed properly by using the Tiebreaker CLI monitor show -status command.
+
----

NetApp MetroCluster Tiebreaker :> monitor show -status
----
