---
permalink: tiebreaker/install_security.html
sidebar: sidebar
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database
summary: "The Tiebreaker software provides monitoring capabilities for a clustered storage environment. It also sends SNMP notifications in the event of node connectivity issues and site disasters."
---
= Secure the Tiebreaker installation
:icons: font
:imagesdir: ../media/

[.lead]
The Tiebreaker software provides monitoring capabilities for a clustered storage environment. It also sends SNMP notifications in the event of node connectivity issues and site disasters.

==  Secure the host and database installation 
For configurations running MetroCluster Tiebreaker 1.5 and later, you can secure and harden the host OS and the database. 

=== Secure the host

The following guidelines show you how to secure the host where the Tiebreaker software is installed.

** Limit access of the "root" user.
*  You can use users that are able to elevate to root access to install and administer the Tiebreaker software.
* You can use users that are not able to elevate to root access to administer Tiebreaker software.
+
NOTE: During installation, you should create a group named "mcctbgrp". The host root user and the user created during the installation are both members. Only members of this group can fully administer the Tiebreaker software.
* Users who are not members of this group cannot access the Tiebreaker software or CLI.
You can create additional users on the host and make them members of the group. These additional members cannot fully administer the Tiebreaker software -- they have ReadOnly access and cannot add, change, or delete monitors.

** Use disk encryption
* You can enable disk encryption. This can be FullDiskEncryption (hardware), or encryption provided by the HostOS (software), or by the SVM host.
** Disable unused services that allow incoming connections. You can disable any service that isn’t in use. The Tiebreaker software does not require a service for incoming connections because all connections from the Tiebreaker installation are outgoing.
The services that might be enabled by default and can be disabled are:
* HTTP/HTTPS server
* FTP server
* Telnet, RSH, rlogin 
* NFS, CIFS, and other protocol access
* RDP (RemoteDesktopProtocol), X11 Server, VNC or other remote "desktop" service providers.
+
NOTE: You must leave either serial console access (if supported) or at least one protocol enabled to administer the host remotely. If you disable all protocols, then you require physical access to the host for administration.
** Secure the host using FIPS
* You can install the host OS in FIPS-compliant mode and then install Tiebreaker.
+
NOTE: OpenJDK 19 checks on startup whether the host is installed in FIPS mode. No manual changes should be required.

** Baseline recommendations 

* Do not run Tiebreaker as a root user. Use a dedicated, unprivileged service account to run Tiebreaker. 
* Change the default community string in the "/etc/snmp/snmpd.conf" file.

  

* Allow minimal write privileges. The unprivileged Tiebreaker service account should not have access to overwrite its executable binary or any configuration files. Only directories and files for local Tiebreaker storage (eg., for integrated backend storage) or audit logs should be writable by the Tiebreaker user. 

* End-to-End Transport Layer Security (TLS). Tiebreaker should always be used with TLS. If intermediate load balancers or reverse proxies are used to front Tiebreaker, you should use TLS for all network connections between every component of the system (including backend storage) to ensure all traffic is encrypted in transit to and from Tiebreaker. When possible, you should set the HTTP Strict Transport Security (HSTS) header by using Tiebreaker's custom response headers feature. 

* You must install and run the latest version of OpenSSH. 
* Do not permit anonymous users. 
* Set AllowTcpForwarding to "no" or use the Match directive to restrict anonymous users.

  

* Disable Shell Command History.  

* Upgrade frequently. Tiebreaker is actively developed, and updating frequently is important to incorporate security fixes and any changes in default settings such as key lengths or cipher suites. 

* Subscribe to the HashiCorp Announcement mailing list to receive announcements of new releases and visit the Tiebreaker CHANGELOG for details on recent updates for new releases. 

  

* Use the correct file permissions. Always ensure appropriate permissions are applied to files before starting the Tiebreaker software, especially those containing sensitive information. 

  

* Multifactor authentication (MFA) enhances your organization's security by requiring administrators to identify themselves by using more than a username and password. While important, usernames and passwords are vulnerable to brute force attacks and can be stolen by third parties. RHEL 8 provides MFA that requires users to provide more than one piece of information to authenticate successfully to an account or Linux host. The additional information might be a one-time password sent to your cell phone via SMS or credentials from an app like Google Authenticator, Twilio Authy, or FreeOTP. 

==== Related information
.User Management

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_getting-started-with-managing-user-accounts_configuring-basic-system-settings[Getting started with managing user accounts^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/introduction-to-managing-user-and-group-accounts_configuring-basic-system-settings[Introduction to managing user and group accounts^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-user-accounts-in-the-web-console-new_configuring-basic-system-settings[Managing user accounts in the web console^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-users-from-the-command-line_configuring-basic-system-settings[Managing users from the command line^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/editing-user-groups-using-the-command-line_configuring-basic-system-settings[Editing user groups using the command line^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-sudo-access_configuring-basic-system-settings[Managing sudo access^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/changing-and-resetting-the-root-password-from-the-command-line_configuring-basic-system-settings[Managing and resetting the root password^]


link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/index[Security hardening^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/securing_networks/index[Securing networks^]


link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/managing-system-services-with-systemctl_configuring-basic-system-settings[Managing system services with systemctl^]

link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8[RHEL 8 documentation^]

link:https://access.redhat.com/documentation/ru-ru/openjdk/8/html/configuring_openjdk_8_on_rhel_with_fips/openjdk-default-fips-configuration[Default FIPS configuration in OpenJDK 8^]

NOTE: If you secure the host, then you must ensure that the host is able to boot without user intervention. If user intervention is required, then Tiebreaker functionality might not be available in case the host unexpectedly reboots. In this case, Tiebreaker functionality is only available after the manual intervention and when the host is fully booted.

=== Secure the database installation

The following guidelines show how to secure and harden the MariaDB 10.x database installation.

** Limit the access of the "root" user.
* Tiebreaker uses a dedicated account. The account and tables for storing (configuration) data is created during the installation of Tiebreaker. The only time elevated access to the database is required is during installation.
** During installation the following access and privileges are required:
+
* The ability to create a database and tables
* The ability to create global options
* The ability to create a database user and set the password
* The ability to associate the database user with the database and tables and assign access rights
+
NOTE: The user account that you specify during the Tiebreaker installation must have all these privileges. Using multiple user accounts for the different tasks is not supported.
** Use encryption of the database
* Data-at-rest encryption is supported
* Data in flight is not encrypted. Data in flight uses a local "socks" file connection.
* FIPS compliancy for MariaDB -- you do not need to enable FIPS compliancy on the database. Installation of the host in FIPS-compliant mode is sufficient.
  
+
NOTE: If you require encryption, the encryption settings must be enabled before installation of the Tiebreaker software.


==== Related information
* Database user management
+
link:https://dev.mysql.com/doc/refman/8.0/en/access-control.html[Access Control and Account Management^]

* Secure the database
+
link:https://dev.mysql.com/doc/refman/8.0/en/security-against-attack.html[Making MySQL Secure Against Attackers^]
+
link:https://mariadb.com/kb/en/securing-mariadb/[Securing MariaDB^]

* Encryption for data-at-rest
+
link:https://mariadb.com/kb/en/data-at-rest-encryption-overview/[Data-at-Rest Encryption Overview^]
+
link:https://www.mysql.com/products/enterprise/tde.html[MySQL Enterprise Transparent Data Encryption (TDE)^]

* Secure the Vault installation
+
link:https://developer.hashicorp.com/vault/tutorials/operations/production-hardening/[Production hardening^]
