---
permalink: tiebreaker/reference_firewall_requirements_for_mcc_tiebreaker.html
sidebar: sidebar
keywords:
summary: 'MetroCluster Tiebreaker uses a number of ports to communicate with specific services.'
---
= Firewall requirements for MetroCluster Tiebreaker
:icons: font
:imagesdir: ../media/

[.lead]
MetroCluster Tiebreaker uses a number of ports to communicate with specific services.

The following table lists the ports that you must allow in your firewall:

[cols=2*,options="header"]
|===
| Port/services| Source| Destination| Purpose
a|
443 / TCP

a|
Tiebreaker
a|
Internet
a|
Sending AutoSupport messages to NetApp
a|
22 / TCP

a|
Management host
a|
Tiebreaker
a|
Tiebreaker Management
a|
443 / TCP

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Secure communications via HTTP (SSL)
a|
22 / TCP

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Secure communications via SSH
a|
443 / TCP

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Secure communications via HTTP (SSL)
a|
22 / TCP

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Secure communications via SSH
a|
162 / UDP

a|
Tiebreaker
a|
SNMP trap host
a|
Used to send alert notification SNMP traps
a|
ICMP (ping)

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Check if cluster IP is reachable
a|
ICMP (ping)

a|
Tiebreaker
a|
MetroCluster management LIFs
a|
Check if node IP is reachable
|===
