---
permalink: tiebreaker/reference_where_to_find_additional_information_tb_icg.html
sidebar: sidebar
keywords: metrocluster, configuration, operation, netapp, documentation, library, additional, information, miscellaneous, guide
summary: You can learn more about MetroCluster configuration and operation in from the NetApp documentation library.
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about MetroCluster configuration and operation in from the NetApp documentation library.

== MetroCluster and miscellaneous guides

[options="header"]
|===
| Guide| Content
a|
https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]

a|

* All MetroCluster guides

a|
http://www.netapp.com/us/media/tr-4375.pdf[NetApp Technical Report 4375: NetApp MetroCluster for ONTAP 9.3]
a|

* A technical overview of the MetroCluster configuration and operation.
* Best practices for MetroCluster configuration.

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html[Stretch MetroCluster installation and configuration]
a|

* Stretch MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the MetroCluster in ONTAP

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html[MetroCluster IP installation and configuration]
a|

* MetroCluster IP architecture
* Cabling the MetroCluster IP configuration
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-service/home.html[MetroCluster Service Guide]
a|

* Guidelines for maintenance in a MetroCluster configuration
* Hardware replacement or upgrade and firmware upgrade procedures for FC-to-SAS bridges and FC switches
* Hot-adding a disk shelf in a fabric-attached or stretch MetroCluster configuration
* Hot-removing a disk shelf in a fabric-attached or stretch MetroCluster configuration
* Replacing hardware at a disaster site in a fabric-attached or stretch MetroCluster configuration
* Expanding a two-node fabric-attached or stretch MetroCluster configuration to a four-node MetroCluster configuration.
* Expanding a four-node fabric-attached or stretch MetroCluster configuration to an eight-node MetroCluster configuration.

a|
Active IQ Unified Manager documentationhttps://docs.netapp.com[NetApp Documentation: Product Guides and Resources]

a|

* Monitoring the MetroCluster configuration and performance

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

|===
