---
permalink: tiebreaker/whats_new.html
sidebar: sidebar
keywords: install, tiebreaker, software, monitor, capabilities, capability, cluster, storage, environment, snmp, notification, event, node, connectivity, issue, site, disaster, system, install, upgrade, upgrading, software, dependencies, dependency, package, ntp, requirements, requirements for tiebreaker, tiebreaker requirements, mysql, mariadb, autostart, database
summary: The Tiebreaker software provides monitoring capabilities for a clustered storage environment. It also sends SNMP notifications in the event of node connectivity issues and site disasters.
---
= What's new
:icons: font
:imagesdir: ../media/

[.lead]
[.lead]
New enhancements to the MetroCluster Tiebreaker are provided with each release.  Here's what's new.

== Enhancements

[cols="25,75"]
|===

h| ONTAP Tiebreaker version h| Enhancements

a| 1.5
a|
* item
* item

a| 1.4 
a| 
* item
* item



|===

== OS support matrix

[cols="16,12,12,12"]
|===

h|Tiebreaker version h| CentOS 7 - 7.9 h| RedHat 7 - 7.9 h| RedHat 8.1 - 8.7 

a| 1.5 
a| Yes
a| Yes
a| Yes


a| 1.4
a| No 
a| No
a| Yes

|===

== Resolved issues

[cols="20,20,60"]
|===

h| Date of change h| Change ID h| Description

a| 10 Jan 2023
a| 6567145
a| The following changes were made:

* Added support for additional operating systems for ONTAP Mediator: RHEL 9.6, 8.7, 9.0, and 9.1.
* Added new SCST version 3.7.0 to unblock issues for newly supported operating systems.
* Added support for Rocky Linux:  Rocky 8 and 9.

a| 24 Jan 2023
a| 6621319
a| Allowed pre-installed SCST library for ONTAP Mediator installations.

a| 27 Feb 2023
a| 6623764
a| Implemented changes to always load the scst_disk kernel module when the mediator-scst service restarts.  These changes ensure the service will always be ready to create new iSCSI targets using the standard logic.

a| 28 Feb 2023
a| 6625194
a| Added a new option to the ONTAP Mediator installer:  `--skip-yum-dependencies`

a| 24 Mar 2023
a| 6652840
a| Updated the ONTAP Mediator installer so that it is able to reinstall or repair the SCST installation.

a| 27 Mar 2023
a| 6655179
a| Fixed a parsing issue that occurred when the support bundle collection with a complex password was triggered.

a| 28 Mar 2023
a| 6656739
a| Changed the SCST comparison logic so that is will install the right version when ONTAP Mediator is upgraded.

|===