---
permalink: install-fc/brocade-fc-port-config-isls.html
sidebar: sidebar
keywords:  ONTAP, FAS, FC, Brocade, metrocluster
summary: 'The following tables show port usage on Brocade switches.'
---
= Brocade port usage for ISLs in a MetroCluster FC configuration 
:icons: font
:imagesdir: ../media/

[.lead]
Review the information in this section to learn how to cable Brocade FC switches to ISLs. 

NOTE: AFF A700 or FAS9000 systems support up to eight ISLs for improved performance. Eight ISLs are supported on the Brocade 6510 and G620 switches.


|===

.2+h| ISL port 6+h| Brocade Switch Model Port Connection
h| 6505, G610 h| 6520 h| 7810	h| 7840
(10-Gbps) h|7840 (40-Gbps) h| 6510, G620, G620-1, G630, G630-1, G720, G730

a|
ISL port 1
a|
20
a|
22
a|
ge2
a|
ge2
a|
ge0
a|
40

a|
ISL port 2
a|
21
a|
23
a|
ge3
a|
ge3
a|
ge1
a|
41
a|
ISL port 3
a|
22
a|
46
a|
ge4
a|
ge10
a|
Not applicable
a|
42

a|
ISL port 4
a|
23
a|
47
a|
ge5
a|
ge11
a|
Not applicable
a|
43

a|
ISL port 5
a|
Not applicable
a|
70
a|
ge6
a|
Not applicable
a|
Not applicable
a|
44

a|
ISL port 6
a|
Not applicable
a|
71
a|
ge7
a|
Not applicable
a|
Not applicable
a|
45

a|
ISL port 7
a|
Not applicable
a|
94
a|
Not applicable
a|
Not applicable
a|
Not applicable
a|
47

a|
ISL port 8
a|
Not applicable
a|
95
a|
Not applicable
a|
Not applicable
a|
Not applicable
a|
47
|===

