---
permalink: install-fc/concept_fcsw_brocade_reviewing_brocade_license_requirements.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, review, brocade, license, requirements
summary: 'You need certain licenses for the switches in a MetroCluster configuration. You must install these licenses on all four switches.'
---
= Reviewing Brocade license requirements
:icons: font
:imagesdir: ../media/

[.lead]
You need certain licenses for the switches in a MetroCluster configuration. You must install these licenses on all four switches.

The MetroCluster configuration has the following Brocade license requirements:

* Trunking license for systems using more than one ISL, as recommended.
* Extended Fabric license (for ISL distances over 6 km)
* Enterprise license for sites with more than one ISL and an ISL distance greater than 6 km
+
The Enterprise license includes Brocade Network Advisor and all licenses except for additional port licenses.

You can verify that the licenses are installed by using the `licenseshow` command. If you do not have these licenses, you should contact your sales representative before proceeding.
