---
permalink: install-fc/concept_implementing_a_mcc_configuration_with_both_disks_and_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, implement, configuration, disks, array, luns
summary: 'To implement a MetroCluster configuration with native disks and array LUNs, you must ensure that the ONTAP systems used in the configuration can attach to storage arrays.'
---
= Implementing a MetroCluster configuration with both disks and array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
To implement a MetroCluster configuration with native disks and array LUNs, you must ensure that the ONTAP systems used in the configuration can attach to storage arrays.

A MetroCluster configuration with disks and array LUNs can have either two or four nodes. Although the four-node MetroCluster configuration must be fabric-attached, the two-node configuration can either be stretch or fabric-attached.

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

In the IMT, you can use the Storage Solution field to select your MetroCluster solution. You use the *Component Explorer* to select the components and ONTAP version to refine your search. You can click *Show Results* to display the list of supported configurations that match the criteria.

*Related information*

xref:reference_example_of_a_two_node_fabric_attached_mcc_configuration_with_disks_and_array_luns.adoc[Example of a two-node fabric-attached MetroCluster configuration with disks and array LUNs]

xref:concept_example_of_a_four_node_mcc_configuration_with_disks_and_array_luns.adoc[Example of a four-node MetroCluster configuration with disks and array LUNs]
