---
permalink: /install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html
sidebar: sidebar
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster
summary: 'You need to verify that you are using the specified port assignments when you cable the FC switches when using ONTAP 9.1 and later.'
---
= Port assignments for FC switches when using AFF A900 systems
:icons: font
:imagesdir: ../media/

You need to verify that you are using the specified port assignments when you cable the FC switches when using ONTAP 9.10.1 and later.

Ports that are not used for attaching initiator ports, FC-VI ports, or ISLs can be reconfigured to act as storage ports. However, if the supported RCFs are being used, the zoning must be changed accordingly.

If the supported RCFs are used, ISL ports might not connect to the same ports shown and might need to be reconfigured manually.

If you configured your switches using the port assignments for ONTAP 9, you can continue to use the older assignments. However, new configurations running ONTAP 9.1 or later releases should use the port assignments shown here.

== Overall cabling guidelines

You should be aware of the following guidelines when using the cabling tables:

* AFF A900 storage systems require eight FC-VI ports. If you are using an AFF A900, you need to use the eight port configuration. If the configuration includes the other storage system models, use the cabling shown in the tables but ignore the cabling for unneeded FC-VI ports.
* If you have two MetroCluster configurations sharing ISLs, use the same port assignments as that for an eight-node MetroCluster cabling.
* The number of ISLs you cable may vary depending on site's requirements.
* See the section on ISL considerations.
+
link:concept_considerations_isls_mcfc.html[Considerations for ISLs]
