---
permalink: install-fc/concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, example, eight, node, array, luns
summary: 'Switch zoning defines paths between connected nodes. Configuring the zoning enables you to define which array LUNs can be viewed by specific ONTAP systems.'
---
= Example of switch zoning in an eight-node MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
Switch zoning defines paths between connected nodes. Configuring the zoning enables you to define which array LUNs can be viewed by specific ONTAP systems.

An eight-node MetroCluster configuration consists of two four-node DR groups. The first DR group consists of the following nodes:

* controller_A_1
* controller_A_2
* controller_B_1
* controller_B_2

The second DR group consists of the following nodes:

* controller_A_3
* controller_A_4
* controller_B_3
* controller_B_4

To configure the switch zoning, you can use the zoning examples for a four-node MetroCluster configuration for the first DR group.

xref:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.adoc[Example of switch zoning in a four-node MetroCluster configuration with array LUNs]

To configure zoning for the second DR group, follow the same examples and requirements for the FC initiator ports and array LUNs belonging to the controllers in the second DR group.

*Related information*

xref:reference_requirements_for_switch_zoning_in_a_mcc_configuration_with_array_luns.adoc[Requirements for switch zoning in a MetroCluster configuration with array LUNs]

xref:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.adoc[Example of switch zoning in a two-node MetroCluster configuration with array LUNs]

xref:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.adoc[Example of switch zoning in a four-node MetroCluster configuration with array LUNs]
