---
permalink: install-fc/concept_switch_ports_required_for_a_eight_node_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: ontap, metrocluster,
summary: 'When you are connecting ONTAP systems to FC switches for setting up a MetroCluster configuration with array LUNs, you must connect FC-VI and HBA ports from each controller to specific switch ports.'
---
= Switch ports required for a MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
When you are connecting ONTAP systems to FC switches for setting up a MetroCluster configuration with array LUNs, you must connect FC-VI and HBA ports from each controller to specific switch ports.


If you are using both array LUNs and disks in the MetroCluster configuration, you must ensure that the controller ports are connected to the switch ports recommended for configuration with disks, and then use the remaining ports for configuration with array LUNs.

The following table lists the specific FC switch ports to which you must connect the different controller ports in an eight-node MetroCluster configuration with array LUNs.

== Overall cabling guidelines with array LUNs

You should be aware of the following guidelines when using the cabling tables:

* The Brocade and Cisco switches use different port numbering:
 ** On Brocade switches, the first port is numbered 0.
 ** On Cisco switches, the first port is numbered 1.
* The cabling is the same for each FC switch in the switch fabric.
* FAS8200 storage systems can be ordered with one of two options for FC-VI connectivity:
 ** Onboard ports 0e and 0f configured in FC-VI mode.
 ** Ports 1a and 1b on an FC-VI card in slot 1.
* #AFF A900 storage systems require eight FC-VI ports. If you are using A900, you need to use the eight port configuration. For other storage systems, use the cabling shown in the tables but ignore the cabling for unneeded FC-VI ports.#
* FAS9000 storage systems require four FC-VI ports. The following tables show cabling for the FC switches with four FC-VI ports on each controller.
+
For other storage systems, use the cabling shown in the tables but ignore the cabling for FC-VI ports c and d.
+
You can leave those ports empty.

== Brocade port usage for controllers in a MetroCluster configuration

The following tables show port usage on Brocade switches. The tables show the maximum supported configuration, with eight controller modules in two DR groups. For smaller configurations, ignore the rows for the additional controller modules. Note that eight ISLs are supported on the Brocade 6510 and G620 switches.

NOTE: Port usage for the Brocade 6505 switch in an eight-node MetroCluster configuration is not shown. Due to the limited number of ports, port assignments must be made on a site-by-site basis depending on the controller module model and the number of ISLs and bridge pairs in use.

The following table shows the cabling for the first DR group:


|===

2+h|  2+h| Brocade 6520, 6510, 6505, G620, G610, or 7840 switch

h| *Component* h| *Port* h| *Switch 1* h| *Switch 2*

.8+| controller_x_1
a|
FC-VI port a
a|
0
a|

a|
FC-VI port b
a|
-
a|
0
a|
FC-VI port c
a|
1
a|
-
a|
FC-VI port d
a|
-
a|
1
a|
HBA port a
a|
2
a|
-
a|
HBA port b
a|
-
a|
2
a|
HBA port c
a|
3
a|
-
a|
HBA port d
a|
-
a|
3
.8+| controller_x_2
a|
FC-VI port a
a|
4
a|
-
a|
FC-VI port b
a|
-
a|
4
a|
FC-VI port c
a|
5
a|
-
a|
FC-VI port d
a|
-
a|
5
a|
HBA port a
a|
6
a|
-
a|
HBA port b
a|
-
a|
6
a|
HBA port c
a|
7
a|
-
a|
HBA port d
a|
-
a|
7
|===

The following table shows the cabling for the second DR group:


|===

2+h|  2+h| Brocade 6510 2+h| Brocade 6520 2+h| Brocade G620

h| *Component* h| *Port* h| *Switch 1* h| *Switch 2* h| *Switch 1* h| *Switch 2* h| *Switch 1* h| *Switch 2*

.8+| controller_x_3
a|
FC-VI port a
a|
24
a|
-
a|
48
a|
-
a|
18
a|
-
a|
FC-VI port b
a|
-
a|
24
a|
-
a|
48
a|
-
a|
18
a|
FC-VI port c
a|
25
a|
-
a|
49
a|
-
a|
19
a|
-
a|
FC-VI port d
a|
-
a|
25
a|
-
a|
49
a|
-
a|
19
a|
HBA port a
a|
26
a|
-
a|
50
a|
-
a|
24
a|
-
a|
HBA port b
a|
-
a|
26
a|
-
a|
50
a|
-
a|
24
a|
HBA port c
a|
27
a|
-
a|
51
a|
-
a|
25
a|
-
a|
HBA port d
a|
-
a|
27
a|
-
a|
51
a|
-
a|
25
.8+| controller_x_4
a|
FC-VI port a
a|
28
a|
-
a|
52
a|
-
a|
22
a|
-
a|
FC-VI port b
a|
-
a|
28
a|
-
a|
52
a|
-
a|
22
a|
FC-VI port c
a|
29
a|
-
a|
53
a|
-
a|
23
a|
-
a|
FC-VI port d
a|
-
a|
29
a|
-
a|
53
a|
-
a|
23
a|
HBA port a
a|
30
a|
-
a|
54
a|
-
a|
28
a|
-
a|
HBA port b
a|
-
a|
30
a|
-
a|
54
a|
-
a|
28
a|
HBA port c
a|
31
a|
-
a|
55
a|
-
a|
29
a|
-
a|
HBA port d
a|
-
a|
31
a|
-
a|
55
a|
-
a|
29

8+h| *ISLs*

2+a|
ISL 1
a|
40
a|
40
a|
23
a|
23
a|
40
a|
40
2+a|
ISL 2
a|
41
a|
41
a|
47
a|
47
a|
41
a|
41
2+a|
ISL 3
a|
42
a|
42
a|
71
a|
71
a|
42
a|
42
2+a|
ISL 4
a|
43
a|
43
a|
95
a|
95
a|
43
a|
43
2+a|
ISL 5
a|
44
a|
44
2.4+^|
Not supported
a|
44
a|
44

2+a|
ISL 6
a|
45
a|
45
a|
45
a|
45
2+a|
ISL 7
a|
46
a|
46
a|
46
a|
46
2+a|
ISL 8
a|
47
a|
47
a|
47
a|
47
|===

== Cisco port usage for controllers in a MetroCluster configuration running ONTAP 9.4 or later

The tables show the maximum supported configuration, with eight controller modules in two DR groups. For smaller configurations, ignore the rows for the additional controller modules.

=== Cisco 9396S port usage


|===

4+^h| Cisco 9396S
h| *Component* h| *Port* h| *Switch 1* h| *Switch 2*

.8+| controller_x_1
a|
FC-VI port a
a|
1
a|
-
a|
FC-VI port b
a|
-
a|
1
a|
FC-VI port c
a|
2
a|
-
a|
FC-VI port d
a|
-
a|
2
a|
HBA port a
a|
3
a|
-
a|
HBA port b
a|
-
a|
3
a|
HBA port c
a|
4
a|
-
a|
HBA port d
a|
-
a|
4
.8+| controller_x_2
a|
FC-VI port a
a|
5
a|
-
a|
FC-VI port b
a|
-
a|
5
a|
FC-VI port c
a|
6
a|
-
a|
FC-VI port d
a|
-
a|
6
a|
HBA port a
a|
7
a|
-
a|
HBA port b
a|
-
a|
7
a|
HBA port c
a|
8
a|
-
a|
HBA port d
a|
-
a|
8
.8+| controller_x_3
a|
FC-VI port a
a|
49
a|

a|
FC-VI port b
a|
-
a|
49
a|
FC-VI port c
a|
50
a|

a|
FC-VI port d
a|
-
a|
50
a|
HBA port a
a|
51
a|

a|
HBA port b
a|
-
a|
51
a|
HBA port c
a|
52
a|

a|
HBA port d
a|
-
a|
52
.8+| controller_x_4
a|
FC-VI port a
a|
53
a|
-
a|
FC-VI port b
a|
-
a|
53
a|
FC-VI port c
a|
54
a|
-
a|
FC-VI port d
a|
-
a|
54
a|
HBA port a
a|
55
a|
-
a|
HBA port b
a|
-
a|
55
a|
HBA port c
a|
56
a|
-
a|
HBA port d
a|
-
a|
56
|===

=== Cisco 9148S port usage

|===

4+^h| Cisco 9148S
h| *Component* h| *Port* h| *Switch 1* h| *Switch 2*

.8+| controller_x_1
a|
FC-VI port a
a|
1
a|
-
a|
FC-VI port b
a|
-
a|
1
a|
FC-VI port c
a|
2
a|
-
a|
FC-VI port d
a|
-
a|
2
a|
HBA port a
a|
3
a|
-
a|
HBA port b
a|
-
a|
3
a|
HBA port c
a|
4
a|
-
a|
HBA port d
a|
-
a|
4
.8+| controller_x_2
a|
FC-VI port a
a|
5
a|
-
a|
FC-VI port b
a|
-
a|
5
a|
FC-VI port c
a|
6
a|
-
a|
FC-VI port d
a|
-
a|
6
a|
HBA port a
a|
7
a|
-
a|
HBA port b
a|
-
a|
7
a|
HBA port c
a|
8
a|
-
a|
HBA port d
a|
-
a|
8
.8+| controller_x_3
a|
FC-VI port a
a|
25
a|

a|
FC-VI port b
a|
-
a|
25
a|
FC-VI port c
a|
26
a|
-
a|
FC-VI port d
a|
-
a|
26
a|
HBA port a
a|
27
a|
-
a|
HBA port b
a|
-
a|
27
a|
HBA port c
a|
28
a|
-
a|
HBA port d
a|
-
a|
28
.8+| controller_x_4
a|
FC-VI port a
a|
29
a|
-
a|
FC-VI port b
a|
-
a|
29
a|
FC-VI port c
a|
30
a|
-
a|
FC-VI port d
a|
-
a|
30
a|
HBA port a
a|
31
a|
-
a|
HBA port b
a|
-
a|
31
a|
HBA port c
a|
32
a|
-
a|
HBA port d
a|
-
a|
32
|===

=== Cisco 9132T port usage

|===

4+^h| Cisco 9132T
4+^h| MDS module 1
h| *Component* h| *Port* h| *Switch 1* h| *Switch 2*

.8+| controller_x_1
a|
FC-VI port a
a|
1
a|
-
a|
FC-VI port b
a|
-
a|
1
a|
FC-VI port c
a|
2
a|
-
a|
FC-VI port d
a|
-
a|
2
a|
HBA port a
a|
3
a|
-
a|
HBA port b
a|
-
a|
3
a|
HBA port c
a|
4
a|
-
a|
HBA port d
a|
-
a|
4
.8+| controller_x_2
a|
FC-VI port a
a|
5
a|
-
a|
FC-VI port b
a|
-
a|
5
a|
FC-VI port c
a|
6
a|
-
a|
FC-VI port d
a|
-
a|
6
a|
HBA port a
a|
7
a|
-
a|
HBA port b
a|
-
a|
7
a|
HBA port c
a|
8
a|
-
a|
HBA port d
a|
-
a|
8

4+^h|
*MDS module 2*

h|
*Component*
h|
*Port*
h|
*Switch 1*
h|
*Switch 2*

.8+| controller_x_3
a|
FC-VI port a
a|
1
a|
-
a|
FC-VI port b
a|
-
a|
1
a|
FC-VI port c
a|
2
a|
-
a|
FC-VI port d
a|
-
a|
2
a|
HBA port a
a|
3
a|
-
a|
HBA port b
a|
-
a|
3
a|
HBA port c
a|
4
a|
-
a|
HBA port d
a|
-
a|
4
.8+| controller_x_4
a|
FC-VI port a
a|
5
a|
-
a|
FC-VI port b
a|
-
a|
5
a|
FC-VI port c
a|
6
a|
-
a|
FC-VI port d
a|
-
a|
6
a|
HBA port a
a|
7
a|
-
a|
HBA port b
a|
-
a|
7
a|
HBA port c
a|
8
a|
-
a|
HBA port d
a|
-
a|
8
|===

=== Cisco 9250 port usage

--
NOTE: The following table shows systems with two FC-VI ports. AFF A700 and FAS9000 systems have four FC-VI ports (a, b, c, and d). If using an AFF A700 or FAS9000 system, the port assignments move along by one position. For example, FC-VI ports c and d go to switch port 2 and HBA ports a and b go to switch port 3.

--

|===

4+^h| Cisco 9250i
4+^h|The Cisco 9250i switch is not supported for eight-node MetroCluster configurations.
h| *Component* h| *Port* h| *Switch 1* h| *Switch 2*

.6+| controller_x_1
a|
FC-VI port a
a|
1
a|
-
a|
FC-VI port b
a|
-
a|
1
a|
HBA port a
a|
2
a|
-
a|
HBA port b
a|
-
a|
2
a|
HBA port c
a|
3
a|
-
a|
HBA port d
a|
-
a|
3
.6+| controller_x_2
a|
FC-VI port a
a|
4
a|
-
a|
FC-VI port b
a|
-
a|
4
a|
HBA port a
a|
5
a|
-
a|
HBA port b
a|
-
a|
5
a|
HBA port c
a|
6
a|
-
a|
HBA port d
a|
-
a|
6
.6+| controller_x_3
a|
FC-VI port a
a|
7
a|
-
a|
FC-VI port b
a|
-
a|
7
a|
HBA port a
a|
8
a|
-
a|
HBA port b
a|
-
a|
8
a|
HBA port c
a|
9
a|
-
a|
HBA port d
a|
-
a|
9
.6+| controller_x_4
a|
FC-VI port a
a|
10
a|
-
a|
FC-VI port b
a|
-
a|
10
a|
HBA port a
a|
11
a|
-
a|
HBA port b
a|
-
a|
11
a|
HBA port c
a|
13
a|
-
a|
HBA port d
a|
-
a|
13

|===


== Shared initiator and shared target support for MetroCluster configuration with array LUNs

Being able to share a given FC initiator port or target ports is useful for organizations that want to minimize the number of initiator or target ports used. For example, an organization that expects low I/O usage over an FC initiator port or target ports might prefer to share FC initiator port or target ports instead of dedicating each FC initiator port to a single target port.

However sharing of initiator or target ports can adversely affect performance.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/MetroCluster/How_to_support_Shared_Initiator_and_Shared_Target_configuration_with_Array_LUNs_in_a_MetroCluster_environment[How to support Shared Initiator and Shared Target configuration with Array LUNs in a MetroCluster environment]
