---
permalink: install-fc/concept_deciding_whether_to_use_this_guide_fabric_attached_mcc_installation_and_configuration_guide.html
sidebar: sidebar
keywords: 
summary: 'This guide describes how to install and configure the MetroCluster hardware and software components in a fabric configuration.'
---
= Deciding whether to use the Fabric-attached MetroCluster Installation and Configuration Guide
:icons: font
:imagesdir: ../media/

[.lead]
This guide describes how to install and configure the MetroCluster hardware and software components in a fabric configuration.

You should use this guide for planning, installing, and configuring a fabric-attached MetroCluster configuration under the following circumstances:

* You want to understand the architecture of a fabric-attached MetroCluster configuration.
* You want to understand the requirements and best practices for configuring a fabric-attached MetroCluster configuration.
* You want to use the command-line interface (CLI), not an automated scripting tool.

You can find other MetroCluster documentation in the following location:

https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]
