---
permalink: install-fc/concept_switch_zoning_in_a_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, switch, zonging, array, luns
summary: 'Configuring switch zoning enables you to define which array LUNs can be viewed by a specific ONTAP system in the MetroCluster configuration.'
---
= Switch zoning in a MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
Configuring switch zoning enables you to define which array LUNs can be viewed by a specific ONTAP system in the MetroCluster configuration.

.Related information

Switch zoning defines paths between connected nodes.  Configuring the zoning enables you to define which array LUNs can be viewed by specific ONTAP systems.

link:concept_example_of_switch_zoning_in_a_two_node_mcc_configuration_with_array_luns.html[Example of switch zoning in a two-node MetroCluster configuration with array LUNs]

link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html[Example of switch zoning in a four-node MetroCluster configuration with array LUNs]

link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html[Example of switch zoning in an eight-node MetroCluster configuration with array LUNs]
