---
permalink: install-fc/concept_considerations_for_implementing_a_mcc_configuration_with_disks_and_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, considerations, configuration, disks, array, luns
summary: 'When planning your MetroCluster configuration for use with disks and array LUNs, you must consider various factors, such as the order of setting up access to storage, root aggregate location, and the usage of FC initiator ports, switches, and FC-to-SAS bridges.'
---
= Considerations when implementing a MetroCluster configuration with disks and array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
When planning your MetroCluster configuration for use with disks and array LUNs, you must consider various factors, such as the order of setting up access to storage, root aggregate location, and the usage of FC initiator ports, switches, and FC-to-SAS bridges.

Consider the information in the following table when planning your configuration:


|===

h| Consideration h| Guideline

a|Order of setting up access to the storage
a|
You can set up access to either disks or array LUNs first. You must complete all setup for that type of storage and verify that it is set up correctly before setting up the other type of storage.
a|
Location of the root aggregate
a|

* If you are setting up a _new_ MetroCluster deployment with both disks and array LUNs, you must create the root aggregate on native disks.
+
When doing this, ensure that _at least one_ disk shelf (with 24 disk drives) is set up at each of the sites.

* If you are adding native disks to an _existing_ MetroCluster configuration that uses array LUNs, the root aggregate can remain on an array LUN.

a|
Using switches and FC-to-SAS bridges
a|
FC-to-SAS bridges are required in four-node configurations and two-node fabric-attached configurations to connect the ONTAP systems to the disk shelves through the switches.

You must use the same switches to connect to the storage arrays and the FC-to-SAS bridges.

a|
Using FC initiator ports
a|
The initiator ports used to connect to an FC-to-SAS bridge must be different from the ports used to connect to the switches, which connect to the storage arrays.

A minimum of eight initiator ports is required to connect an ONTAP system to both disks and array LUNs.

|===

.Related information

* Switch configuration procedures and commands are different, depending on the switch vendor.
+
link:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.html[Configuring the Brocade FC switches manually]
+
link:task_fcsw_cisco_configure_a_cisco_switch_supertask.html[Configuring the Cisco FC switches manually]

* You install and cable ATTO FibreBridge bridges and SAS disk shelves when adding new storage to the configuration.
+
link:task_fb_new_install.html[Installing FC-to-SAS bridges and SAS disk shelves]

* Switch zoning defines paths between connected nodes.  Configuring the zoning enables you to define which array LUNs can be viewed by a specific ONTAP system.
+
link:concept_example_of_switch_zoning_in_a_four_node_mcc_configuration_with_array_luns.html[Example of switch zoning in a four-node MetroCluster configuration with array LUNs]
+
link:concept_example_of_switch_zoning_in_an_eight_node_mcc_configuration_with_array_luns.html[Example of switch zoning in an eight-node MetroCluster configuration with array LUNs]

* https://hwu.netapp.com[NetApp Hardware Universe]
