---
permalink: install-fc/concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html
sidebar: sidebar
keywords: AFF, A900, ONTAP, FAS, FC, Brocade, ISL, Cisco, metrocluster
summary: 'You need to verify that you are using the specified port assignments when you cable the FC switches when using ONTAP 9.1 and later.'
---
= Port assignments for MetroCluster FC switches
:icons: font
:imagesdir: ../media/

[.lead]
You need to verify that you are using the specified port assignments when you cable the FC switches.

You can reconfigure ports that are not used for attaching initiator ports, FC-VI ports, or ISLs to act as storage ports. However, if you are using the supported RCFs, you must change the zoning accordingly.

If you use the supported RCFs, ISL ports might not connect to the same ports shown and might need to be reconfigured manually.

If you configured your switches using the port assignments for ONTAP 9, you can continue to use the older assignments. However, new configurations running ONTAP 9.1 or later should use the port assignments shown here.

== Overall cabling guidelines

You should be aware of the following guidelines when using the cabling tables:

* The Brocade and Cisco switches use different port numbering:
 ** On Brocade switches, the first port is numbered 0.
 ** On Cisco switches, the first port is numbered 1.
* The cabling is the same for each FC switch in the switch fabric.
* You can order AFF A300 and FAS8200 storage systems with one of two options for FC-VI connectivity:
 ** Onboard ports 0e and 0f configured in FC-VI mode.
 ** Ports 1a and 1b on an FC-VI card in slot 1.
* AFF A700 and FAS9000 storage systems require four FC-VI ports. The following tables show cabling for the FC switches with four FC-VI ports on each controller except for the Cisco 9250i switch.
+
For other storage systems, use the cabling shown in the tables but ignore the cabling for FC-VI ports c and d.
+
You can leave those ports empty.

* AFF A400 and FAS8300 storage systems use ports 2a and 2b for FC-VI connectivity.
* If you have two MetroCluster configurations sharing ISLs, use the same port assignments as that for an eight-node MetroCluster cabling.
* The number of ISLs you cable can vary depending on site's requirements.
* See the section on ISL considerations.
+
link:concept_considerations_isls_mcfc.html[Considerations for ISLs]

== AFF A900 and FAS9500 cabling guidelines

* AFF A900 or FAS9500 storage systems require eight FC-VI ports. If you are using an AFF A900 or FAS9500, you need to use the eight port configuration. If the configuration includes the other storage system models, use the cabling shown in the tables but ignore the cabling for unneeded FC-VI ports.


// BURT 1484611 June 17th 2022
