---
permalink: install-fc/concept_considerations_8510.html
sidebar: sidebar
keywords: preparing, prepare, metrocluster, mcc, installation, install, differences, configurations, between, considerations, all, san, array, asa, cluster, peering, prerequisites, dedicated, ports, sharing, data, ports, native, disk, shelves, array, luns, transitions, 7-mode, isls, tdm/wdm, fabric-attached, iod, ood, encryption, devices, unmirrored, aggregates, maintenance, requiring, power, shutdown, firewall, hardware, racking, cabling, setup, checklist, all san array, asa
summary: 'As you prepare for the MetroCluster installation, you should understand the MetroCluster hardware architecture and required components.'
---

= Requirements for using a Brocade DCX 8510-8 switch
:icons: font
:imagesdir: ../media/

[.lead]
As you prepare for the MetroCluster installation, you should understand the MetroCluster hardware architecture and required components.

* The DCX 8510-8 switches used in MetroCluster configurations must be purchased from NetApp.
* For scalability, you should leave one port-chunk between MetroCluster configurations if cabling only two MetroClusters in 4x48-port modules. This enables you to expand port usage in MetroCluster configurations without recabling.
* Each Brocade DCX 8510-8 switch in the MetroCluster configuration must be correctly configured for the ISL ports and storage connections. For port usage, see the following section: link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html[Port assignments for FC switches when using ONTAP 9.1 and later].
* ISLs cannot be shared and each MetroCluster requires two ISLs for each fabric.
* The DCX 8510-8 switch used for backend MetroCluster connectivity should not be used for any other connectivity.
+
Non-MetroCluster devices should not be connected to these switches and non-MetroCluster traffic should not flow through DCX 8510-8 switches.

* One line card can either be connected to ONTAP MetroClusters *or* ONTAP 7-Mode MetroClusters.

NOTE: RCF files are not available for this switch.

The following are the requirements for using two Brocade DCX 8510-8 switches:

* You must have one DCX 8510-8 switch at each site.
* You must use a minimum of two 48-port blades that contain 16Gb SFPs in each switch.

The following are the requirements for using four DCX 8510-8 switches at each site in a MetroCluster configuration:

* You must have two DCX 8510-8 switches at each site.
* You must use at least one 48-port blade for each DCX 8510-8 switch.
* Each blade is configured as a virtual switch using virtual fabrics.

The following NetApp products are not supported by Brocade DCX 8510-8 switches:

* Config Advisor
* Fabric Health Monitor
* MyAutoSupport (system risks might show false positives)
* Active IQ Unified Manager (formerly OnCommand Unified Manager)

NOTE: Ensure that all the components needed for this configuration are in the https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]. Read the notes section in the Interoperability Matrix Tool for information on supported configurations.
