---
permalink: install-fc/reference_requirements_for_a_mcc_configuration_with_array_luns_reference.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, requirements, array, luns
summary: 'The ONTAP systems, storage arrays, and FC switches used in MetroCluster configurations must meet the requirements for such types of configurations. In addition, you must also consider the SyncMirror requirements for MetroCluster configurations with array LUNs.'
---
= Requirements for a MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
The ONTAP systems, storage arrays, and FC switches used in MetroCluster configurations must meet the requirements for such types of configurations. In addition, you must also consider the SyncMirror requirements for MetroCluster configurations with array LUNs.

== Requirements for ONTAP systems

* The ONTAP systems must be identified as supported for MetroCluster configurations.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
+
In the IMT, you can use the Storage Solution field to select your MetroCluster solution. You use the *Component Explorer* to select the components and ONTAP version to refine your search. You can click *Show Results* to display the list of supported configurations that match the criteria.
+
NOTE: You must refer to the alert details associated with any configuration that you select in the Interoperability Matrix.

* All the ONTAP systems in a MetroCluster configuration must be of the same model.
* FC-VI adapters must be installed in the appropriate slots for each ONTAP system, depending on the model.
+
https://hwu.netapp.com[NetApp Hardware Universe]

== Requirements for storage arrays

* The storage arrays must be identified as supported for MetroCluster configurations.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

* The storage arrays in the MetroCluster configuration must be symmetric:
 ** The two storage arrays must be from the same supported vendor family and have the same firmware version installed.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-es/home.html[FlexArray virtualization implementation for NetApp E-Series storage]
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-ig-third/home.html[FlexArray virtualization implementation for third-party storage]

 ** Disk types (for example, SATA, SSD, or SAS) used for mirrored storage must be the same on both storage arrays.
 ** The parameters for configuring storage arrays, such as RAID type and tiering, must be the same across both sites.

== Requirements for FC switches

* The switches and switch firmware must be identified as supported for MetroCluster configurations.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

* Each fabric must have two FC switches.
* Each ONTAP system must be connected to storage using redundant components so that there is redundancy in case of device and path failures.
* FAS9000 storage systems support up to eight ISLs per fabric. Other storage system models support up to four ISLs per fabric.

The switches must use the MetroCluster basic switch configuration, ISL settings, and FC-VI configurations.

xref:task_fcsw_configure_the_cisco_or_brocade_fc_switches_manually.adoc[Configuring the Cisco or Brocade FC switches manually]

== SyncMirror requirements

* SyncMirror is required for a MetroCluster configuration.
* Two separate storage arrays, one at each site, are required for the mirrored storage.
* Two sets of array LUNs are required.
+
One set is required for the aggregate on the local storage array (pool0) and another set is required at the remote storage array for the mirror of the aggregate (the other plex of the aggregate, pool1).
+
The array LUNs must be of the same size for mirroring the aggregate.

* Unmirrored aggregates are also supported in the MetroCluster configuration.
+
They are not protected in the event of a site disaster.
