---
permalink: install-fc/reference_configuration_gathering_worksheet_for_fc_switches_and_fc_to_sas_bridges.html
sidebar: sidebar
keywords:
summary: 'Before beginning to configure the MetroCluster sites, you should gather required configuration information.'
---
= Configuration worksheet for FC switches and FC-to-SAS bridges
:icons: font
:imagesdir: ../media/

[.lead]
Before beginning to configure the MetroCluster sites, you should gather required configuration information.

== Download worksheets

link:_include/MetroCluster-FC_setup_worksheet_site-A.csv[Site A worksheet]

link:_include/MetroCluster-FC_setup_worksheet_site-B.csv[Site A worksheet]

[%header,format=csv]
|===
// include reference
include::_include/MetroCluster-FC_setup_worksheet_site-A.csv[]
// end include reference
|===

[%header,format=csv]
|===
// include reference
include::_include/MetroCluster-FC_setup_worksheet_site-B.csv[]
// end include reference
|===

== Site A, FC switch one (FC_switch_A_1)

|===
| Switch configuration parameter| Your value
a|
FC_switch_A_1 IP address
a|

a|
FC_switch_A_1 Username
a|

a|
FC_switch_A_1 Password
a|

|===

== Site A, FC switch two (FC_switch_A_2)

|===
| Switch configuration parameter| Your value
a|
FC_switch_A_2 IP address
a|

a|
FC_switch_A_2 Username
a|

a|
FC_switch_A_2 Password
a|

|===

== Site A, FC-to-SAS bridge 1 (FC_bridge_A_1a)

Each SAS stack requires two FC-to-SAS bridges.

* For FibreBridge 7500N or 7600N bridges using both FC ports (FC1 and FC2), each bridge connects to FC_switch_A_1_port-number and FC_switch_A_2_port-number.
* For FibreBridge 6500N bridges or FibreBridge 7500N or 7600N bridges using one FC port (FC1 or FC2) only, one bridge connects to FC_switch_A_1_port-number and the second connects to FC_switch_A_2_port-number.

|===
| Site A| Your value
a|
Bridge_A_1a IP address
a|

a|
Bridge_A_1a Username
a|

a|
Bridge_A_1a Password
a|

|===

== Site A, FC-to-SAS bridge 2 (FC_bridge_A_2_port-number)

Each SAS stack requires two FC-to-SAS bridges.

* For FibreBridge 7500N or 7600N bridges using both FC ports (FC1 and FC2), each bridge connects to FC_switch_A_1_port-number and FC_switch_A_2_port-number.
* For FibreBridge 6500N bridges or FibreBridge 7500N or 7600N bridges using one FC port (FC1 or FC2) only, one bridge connects to FC_switch_A_1_port-number and the second connects to FC_switch_A_2_port-number.

|===
| Site A| Your value
a|
Bridge_A_1b IP address
a|

a|
Bridge_A_1b Username
a|

a|
Bridge_A_1b Password
a|

|===

== Site B, FC switch one (FC_switch_B_1)

|===
| Site B| Your value
a|
FC_switch_B_1 IP address
a|

a|
FC_switch_B_1 Username
a|

a|
FC_switch_B_1 Password
a|

|===

== Site B, FC switch two (FC_switch_B_2)

|===
| Site B| Your value
a|
FC_switch_B_2 IP address
a|

a|
FC_switch_B_2 Username
a|

a|
FC_switch_B_2 Password
a|

|===

== Site B, FC-to-SAS bridge 1 (FC_bridge_B_1a)

Each SAS stack requires two FC-to-SAS bridges.

* For FibreBridge 7500N or 7600N bridges using both FC ports (FC1 and FC2), each bridge connects to FC_switch_B_1_port-number and FC_switch_B_2_port-number.
* For FibreBridge 6500N bridges or FibreBridge 7500N or 7600N bridges using one FC port (FC1 or FC2) only, one bridge connects to FC_switch_B_1_port-number and the second connects to FC_switch_B_2_port-number.

|===
| Site B| Your value
a|
Bridge_B_1a IP address
a|

a|
Bridge_B_1a Username
a|

a|
Bridge_B_1a Password
a|

|===

== Site B, FC-to-SAS bridge 2 (FC_bridge_B_2b)

Each SAS stack requires two FC-to-SAS bridges.

* For FibreBridge 7500N or 7600N bridges using both FC ports (FC1 and FC2), each bridge connects to FC_switch_B_1_port-number and FC_switch_B_2_port-number.
* For FibreBridge 6500N bridges or FibreBridge 7500N or 7600N bridges using one FC port (FC1 or FC2) only, one bridge connects to FC_switch_B_1_port-number and the second connects to FC_switch_B_2_port-number.

|===
| Site B| Your value
a|
Bridge_B_1b IP address
a|

a|
Bridge_B_1b Username
a|

a|
Bridge_B_1b Password
a|

|===
*Related information*

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
