---
permalink: install-fc/reference_where_to_find_additional_information_icg.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, additional, information
summary: 'You can learn more about MetroCluster configuration and operation from the NetApp documentation library.'
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about MetroCluster configuration and operation from the NetApp documentation library.

== MetroCluster and miscellaneous guides

|===

h| Guide h| Content

a| https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]
a| * All MetroCluster guides


|https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf[NetApp MetroCluster
Solution Architecture and Design, TR-4705]
a|
* A technical overview of the MetroCluster FC configuration and operation.
* Best practices for MetroCluster FC configuration.

|https://www.netapp.com/pdf.html?item=/media/13481-tr4689.pdf[MetroCluster IP Solution Architecture and Design, TR-4689]
a|
* A technical overview of the MetroCluster IP configuration and operation.
* Best practices for MetroCluster IP configuration.
a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html[Stretch MetroCluster installation and configuration]
a|

* Stretch MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html[MetroCluster IP installation and configuration: Differences among the ONTAP MetroCluster configurations]
a|

* MetroCluster IP architecture
* Cabling the configuration
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html[MetroCluster management and disaster recovery]
a|

* Understanding the MetroCluster configuration
* Switchover, healing and switchback
* Disaster recovery

a|
https://docs.netapp.com/us-en/ontap-metrocluster/maintain/index.html[MetroCluster Maintenance Guide]
a|

* Guidelines for maintenance in a MetroCluster FC configuration
* Hardware replacement or upgrade and firmware upgrade procedures for FC-to-SAS bridges and FC switches
* Hot-adding a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Hot-removing a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Replacing hardware at a disaster site in a fabric-attached or stretch MetroCluster FC configuration
* Expanding a two-node fabric-attached or stretch MetroCluster FC configuration to a four-node MetroCluster configuration.
* Expanding a four-node fabric-attached or stretch MetroCluster FC configuration to an eight-node MetroCluster FC configuration.

a|
https://docs.netapp.com/us-en/ontap-metrocluster/transition/index.html[MetroCluster Transition Guide]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/index.html[MetroCluster Upgrade and Expansion Guide]

a|

* Upgrading or refreshing a MetroCluster configuration
* Transitioning from a MetroCluster FC configuration to a MetroCluster IP configuration
* Expanding a MetroCluster configuration by adding additional nodes

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[MetroCluster Tiebreaker Software Installation and Configuration Guide]
a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
Active IQ Digital Advisor documentation

https://www.netapp.com/support-and-training/documentation/[NetApp Documentation: Product Guides and Resources]

a|

* Monitoring the MetroCluster configuration and performance

a|
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts]
a|

* How mirrored aggregates work

|===
