---
permalink: install-fc/reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_metrocluster_configuration.html
sidebar: sidebar
keywords: 
summary: 'In a MetroCluster configuration with array LUNs, you must connect the storage array ports that form a redundant port pair to alternate FC switches.'
---
= Example of cabling storage array ports to FC switches in an eight-node MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
In a MetroCluster configuration with array LUNs, you must connect the storage array ports that form a redundant port pair to alternate FC switches.

An eight-node MetroCluster configuration consists of two four-node DR groups. The first DR group consists of the following nodes:

* controller_A_1
* controller_A_2
* controller_B_1
* controller_B_2

The second DR group consists of the following nodes:

* controller_A_3
* controller_A_4
* controller_B_3
* controller_B_4

To cable the array ports for the first DR group, you can use the cabling examples for a four-node MetroCluster configuration for the first DR group.

link:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_metrocluster_configuration.md#[Example of cabling storage array ports to FC switches in a four-node MetroCluster configuration]

To cable the array ports for the second DR group, follow the same examples and extrapolate for the FC-VI ports and FC initiator ports belonging to the controllers in the second DR group.
