---
permalink: install-fc/reference_supported_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, supported, array, luns
summary: 'You can set up either a MetroCluster configuration with array LUNs. Both stretch and fabric-attached configurations are supported. AFF systems are not supported with array LUNs.'
---
= Supported MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
You can set up either a MetroCluster configuration with array LUNs. Both stretch and fabric-attached configurations are supported. AFF systems are not supported with array LUNs.

The features supported on the MetroCluster configurations vary with the configuration types. The following table lists the features supported on the different types of MetroCluster configurations with array LUNs:

[options="header"]
|===
.2+| Feature 3+| Fabric-attached configurations| Stretch configurations
| Eight-node| Four-node| Two-node| Two-node
a|
Number of controllers
a|
Eight
a|
Four
a|
Two
a|
Two
a|
Uses an FC switch storage fabric
2+a|
Yes
a|
Yes
a|
Yes
a|
Uses FC-to-SAS bridges
2+a|
Yes
a|
Yes
a|
Yes
a|
Supports local HA
2+a|
Yes
a|
No
a|
No
a|
Supports automatic switchover
2+a|
Yes
a|
Yes
a|
Yes
|===
*Related information*

xref:concept_prepare_for_the_mcc_installation.adoc[Differences between the ONTAP MetroCluster configurations]
