---
permalink: install-fc/task_fmc_mcc_transition_cable_the_new_mcc_controllers_to_the_exist_fc_fabrics.html
sidebar: sidebar
keywords: cabling, metrocluster, fabric, installation, fc, controllers
summary: 'On each controller in the clustered ONTAP MetroCluster configuration, the FC-VI adapter and HBAs must be cabled to specific ports on the existing FC switches.'
---
= Cabling the new MetroCluster controllers to the existing FC fabrics
:icons: font
:imagesdir: ../media/

[.lead]
On each controller in the clustered ONTAP MetroCluster configuration, the FC-VI adapter and HBAs must be cabled to specific ports on the existing FC switches.

.Steps
. Cable the FC-VI and HBA ports according to the following table:
+
[options="header"]
|===
2+| Site A 2+| Site B
| Connect this Site A component and port...| FC_switch_A_1 port...| Connect this Site B component and port...| FC_switch_B_1 port...
a|
controller_A_1 FC-VI port 1
a|
32
a|
controller_B_1 FC-VI port 1
a|
32
a|
controller_A_1 HBA port 1
a|
33
a|
controller_B_1 HBA port 1
a|
33
a|
controller_A_1 HBA port 2
a|
34
a|
controller_B_1 HBA port 2
a|
34
a|
controller_A_2 FC-VI port 1
a|
35
a|
controller_B_2 FC-VI port 1
a|
35
a|
controller_A_2 HBA 1
a|
36
a|
controller_B_2 HBA 1
a|
36
a|
controller_A_2 HBA 2
a|
37
a|
controller_B_2 HBA 2
a|
37
|===

. Cable each FC-SAS bridge in the first switch fabric to the FC switches.
+
The number of bridges varies depending on the number of SAS storage stacks.
+
[options="header"]
|===
2+| Site A 2+| Site B
| Cable this site A bridge...| FC_switch_A_1 port...| Cable this Site B bridge...| FC_switch_B_1 port...
a|
bridge_A_1_38
a|
38
a|
bridge_B_1_38
a|
38
a|
bridge_A_1_39
a|
39
a|
bridge_B_1_39
a|
39
|===

. Cable each bridge in the second switch fabric to the FC switches.
+
The number of bridges varies depending on the number of SAS storage stacks.
+
[options="header"]
|===
2+| Site A 2+| Site B
| Cable this site A bridge...| FC_switch_A_2 port...| Cable this Site B bridge...| FC_switch_B_2 port...
a|
bridge_A_2_38
a|
38
a|
bridge_B_2_38
a|
38
a|
bridge_A_2_39
a|
39
a|
bridge_B_2_39
a|
39
|===
