---
permalink: install-fc/task_cabling_the_isl_between_the_metrocluster_sites_fabric_config.html
sidebar: sidebar
keywords: ISLs
summary: 'You must connect the FC switches at each site through the fiber-optic Inter-Switch Links \(ISLs\) to form the switch fabrics that connect the MetroCluster components.'
---
= Cabling the ISLs between MetroCluster sites
:icons: font
:imagesdir: ../media/

[.lead]
You must connect the FC switches at each site through the fiber-optic Inter-Switch Links (ISLs) to form the switch fabrics that connect the MetroCluster components.

This must be done for both switch fabrics.

. Connect the FC switches at each site to all ISLs, using the cabling in the table that corresponds to your configuration and switch model.
 ** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.md#[Port assignments for FC switches when using ONTAP 9.1 and later]
 ** xref:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.adoc[Port assignments for FC switches when using ONTAP 9.0]

*Related information*

link:concept_preparing_for_the_metrocluster_installation.md#[Considerations for ISLs]
