---
permalink: install-fc/task_fmc_mcc_transition_disable_one_of_the_switch_fabrics.html
sidebar: sidebar
keywords: 
summary: 'You must disable one of the switch fabrics so you can modify its configuration. After you complete the configuration and reenable the switch fabric, you will repeat the process on the other fabric.'
---
= Disabling one of the switch fabrics
:icons: font
:imagesdir: ../media/

[.lead]
You must disable one of the switch fabrics so you can modify its configuration. After you complete the configuration and reenable the switch fabric, you will repeat the process on the other fabric.

You must have run the fmc_dc utility on the existing 7-Mode fabric MetroCluster configuration and resolved any issues prior to beginning the configuration process.

To ensure continued operation of the MetroCluster configuration, you must not disable the second fabric while the first fabric is disabled.

. Disable each of the switches in the fabric: `switchCfgPersistentDisable`
+
If this command is not available, use the switchDisable command.
+
The following example shows the command issued on FC_switch_A_1:
+
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----
+
The following example shows the command issued on FC_switch_B_1:
+
----
FC_switch_B_1:admin> switchCfgPersistentDisable
----

. Ensure that the 7-Mode MetroCluster configuration is functioning correctly using the redundant fabric:
 .. Confirm that controller failover is healthy: `cf status`
+
----
node_A> cf status
Controller Failover enabled, node_A is up.
VIA Interconnect is up (link 0 down, link 1 up).
----

 .. Confirm that disks are visible: `storage show disk –p`
+
----
node_A> storage show disk –p

PRIMARY                     PORT  SECONDARY          PORT SHELF BAY
--------------------------- ----  ------------------ ---- ---------
Brocade-6510-2K0GG:5.126L27  B                              1    0
Brocade-6510-2K0GG:5.126L28  B                              1    1
Brocade-6510-2K0GG:5.126L29  B                              1    2
Brocade-6510-2K0GG:5.126L30  B                              1    3
Brocade-6510-2K0GG:5.126L31  B                              1    4

.
.
.
----

 .. Confirm that the aggregates are healthy: `aggr status`
+
----
node_A> aggr status
           Aggr State           Status              Options
          aggr0 online          raid_dp, aggr       root, nosnap=on
                                mirrored
                                64-bit
----
