---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html
sidebar: sidebar
keywords: 
summary: 'You must download the reference configuration \(RCF\) file to each switch in the MetroCluster fabric configuration.'
---
= Downloading the Brocade FC switch RCF file
:icons: font
:imagesdir: ../media/

[.lead]
You must download the reference configuration (RCF) file to each switch in the MetroCluster fabric configuration.

To use these RCF files, the system must be running ONTAP 9.1 or later and you must use the port layout for ONTAP 9.1 or later.

If you are planning to use only one of the FC ports on the FibreBridge bridges, configure the back-end fibre channel switches manually using the instructions found in the section, _Port assignments for FC switches when using ONTAP 9.1 and later_.

xref:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.adoc[Port assignments for FC switches when using ONTAP 9.1 and later]

. Refer to the RCF file table on the Brocade RCF download page and identify the correct RCF file for each switch in your configuration.
+
The RCF files must be applied to the correct switches.

. Download the RCF files for the switches from the Brocade RCF download page.
+
The files must be placed in a location where they can be transferred to the switch. There is a separate file for each of the four switches that make up the two-switch fabric.

. Repeat these steps on each switch in the configuration.
