---
permalink: install-fc/task_cable_storage_arrays_to_fc_switches_in_a_mcc_configuration.html
sidebar: sidebar
keywords: 
summary: 'You must connect storage arrays to FC switches so that the ONTAP systems in the MetroCluster configuration can access a specific array LUN through at least two paths.'
---
= Cabling storage arrays to FC switches in a MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
You must connect storage arrays to FC switches so that the ONTAP systems in the MetroCluster configuration can access a specific array LUN through at least two paths.

* The storage arrays must be set up to present array LUNs to ONTAP.
* The ONTAP controllers must be connected to the FC switches.
* The ISLs must be cabled between the FC switches across the MetroCluster sites.
* You must repeat this task for each storage array at both of the MetroCluster sites.
* You must connect the controllers in a MetroCluster configuration to the storage arrays through FC switches.

. Connect the storage array ports to FC switch ports.
+
At each site, connect the redundant port pairs in the storage array to FC switches on alternate fabrics. This provides redundancy in the paths for accessing the array LUNs.

*Related information*

xref:concept_switch_zoning_in_a_mcc_configuration_with_array_luns.adoc[Switch zoning in a MetroCluster configuration with array LUNs]

xref:reference_example_of_cabling_array_luns_to_fc_switches_in_a_two_node_mcc_configuration.adoc[Example of cabling storage array ports to FC switches in a two-node MetroCluster configuration]

xref:reference_example_of_cabling_array_luns_to_fc_switches_in_a_four_node_mcc_configuration.adoc[Example of cabling storage array ports to FC switches in a four-node MetroCluster configuration]

xref:reference_example_of_cabling_array_luns_to_fc_switches_in_an_eight_node_mcc_configuration.adoc[Example of cabling storage array ports to FC switches in an eight-node MetroCluster configuration]
