---
permalink: install-fc/task_verify_the_ha_state_of_components_is_mcc_or_mcc_2n_in_maintenance_mode.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, verify, ha, state, components, maintenance, mode
summary: 'When configuring a storage system in a MetroCluster configuration, you must make sure that the high-availability \(HA\) state of the controller module and chassis components is mcc or mcc-2n so that these components boot properly.'
---
= Verifying and configuring the HA state of components in Maintenance mode
:icons: font
:imagesdir: ../media/

[.lead]
When configuring a storage system in a MetroCluster configuration, you must make sure that the high-availability (HA) state of the controller module and chassis components is "mcc" or "mcc-2n" so that these components boot properly.

.Before you begin

The system must be in Maintenance mode.

.About this task

This task is not required on systems that are received from the factory.

.Steps

. In Maintenance mode, display the HA state of the controller module and chassis:
+
`ha-config show`
+
The correct HA state depends on your MetroCluster configuration.
+

|===
h| Number of controllers in the MetroCluster configuration h| HA state for all components should be...

a|
Eight- or four-node MetroCluster FC configuration
a|
mcc
a|
Two-node MetroCluster FC configuration
a|
mcc-2n
a|
MetroCluster IP configuration
a|
mccip
|===

. If the displayed system state of the controller is not correct, set the HA state for the controller module:
+

|===
h| Number of controllers in the MetroCluster configuration h| Command

a|
Eight- or four-node MetroCluster FC configuration
a|
`ha-config modify controller mcc`
a|
Two-node MetroCluster FC configuration
a|
`ha-config modify controller mcc-2n`
a|
MetroCluster IP configuration
a|
`ha-config modify controller mccip`
|===

. If the displayed system state of the chassis is not correct, set the HA state for the chassis:
+

|===
h| Number of controllers in the MetroCluster configuration h| Command

a|
Eight- or four-node MetroCluster FC configuration
a|
`ha-config modify chassis mcc`
a|
Two-node MetroCluster FC configuration
a|
`ha-config modify chassis mcc-2n`
a|
MetroCluster IP configuration
a|
`ha-config modify chassis mccip`
|===

. Boot the node to ONTAP:
+
`boot_ontap`

. Repeat these steps on each node in the MetroCluster configuration.
