---
permalink: install-fc/task_install_the_license_for_us_array_luns_in_a_mcc_configuration.html
sidebar: sidebar
keywords: 
summary: 'You must install the V_StorageAttach license on each MetroCluster node that you want to use with array LUNs. You cannot use array LUNs in an aggregate until the license is installed.'
---
= Installing the license for using array LUNs in a MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
You must install the V_StorageAttach license on each MetroCluster node that you want to use with array LUNs. You cannot use array LUNs in an aggregate until the license is installed.

* The cluster must be installed.
* You must have the license key for the V_StorageAttach license.

You must use a separate license key for each node on which you want to install the V_StorageAttach license.

. Use the system license add command to install the V_StorageAttach license.
+
Repeat this step for each cluster node on which you want to install the license.

. Use the system license show command to verify that the V_StorageAttach license is installed on all required nodes in a cluster.
+
The following sample output shows that the V_StorageAttach license is installed on the nodes of cluster_A:
+
----

cluster_A::> system license show
Serial Number: nnnnnnnn
Owner: controller_A_1
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage


Serial Number: llllllll
Owner: controller_A_2
Package           Type    Description           Expiration
----------------- ------- --------------------- --------------------
V_StorageAttach   license Virtual Attached Storage
----
