---
permalink: install-fc/task_cable_the_controller_module_s_fc_vi_hba_ports_to_the_fc_switches_controller_to_fc_sw.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, cable, new, controller, module, fc, vi, hba, ports, fc, switches, mcc
summary: 'The FC-VI ports and HBAs \(host bus adapters\) must be cabled to the site FC switches on each controller module in the MetroCluster configuration.'
---
= Cabling the new controller module's FC-VI and HBA ports to the FC switches
:icons: font
:imagesdir: ../media/

[.lead]
The FC-VI ports and HBAs (host bus adapters) must be cabled to the site FC switches on each controller module in the MetroCluster configuration.

.Steps
. Cable the FC-VI ports and HBA ports, using the table for your configuration and switch model.
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html[Port assignments for FC switches when using ONTAP 9.1 and later]
** link:concept_port_assignments_for_fc_switches_when_using_ontap_9_0.html[Port assignments for FC switches when using ONTAP 9.0]
** link:concept_AFF_A900_port_assign_fc_switches_ontap_9_1.html[Port assignments for FC switches when using AFF A900 systems]
** link:concept_port_assignments_for_systems_using_two_initiator_ports.html[Port assignments for systems using two initiator ports]
