---
permalink: install-fc/task_rack_the_hardware_components_in_a_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, rack, hardware, components, array, luns
summary: 'You must ensure that the hardware components required to set up a MetroCluster configuration with array LUNs are properly racked.'
---
= Racking the hardware components in a MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
You must ensure that the hardware components required to set up a MetroCluster configuration with array LUNs are properly racked.

.About this task

You must perform this task at both the MetroCluster sites.

.Steps
. Plan the positioning of the MetroCluster components.
+
The rack space depends on the platform model of the storage controllers, the switch types, and the number of disk shelf stacks in your configuration.

. Properly ground yourself.
. Install the storage controllers in the rack or cabinet.
+
NOTE: AFF systems are not supported with array LUNs.
+
http://docs.netapp.com/platstor/index.jsp?topic=%2Fcom.netapp.doc.hw-9000-install-setup%2Fhome.html[AFF A700 and FAS9000 Installation and setup]
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2316769[FAS8200 Systems Installation and Setup Instructions]
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1199907[Installation and Setup Instructions FAS8040/FAS8060 Systems]
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1504186[Installation and setup Instructions FAS80xx Systems with I/O Expansion Modules]
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1199906[Installation and Setup Instructions FAS8020 systems]
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1147995[Installation and Setup Instructions 62xx Systems]
+
https://library.netapp.com/ecm/ecm_download_file/ECMP1213632[Installation and Setup Instructions 32xx Systems]

. Install the FC switches in the rack or cabinet.
