---
permalink: install-fc/task_fmc_mcc_transition_ensure_isls_are_in_the_same_port_group_and_configure_zon.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, ensure, port, group, configure, zoning
summary: 'You must make sure that the Inter-Switch Links \(ISLs\) are in the same port group and configure zoning for the MetroCluster configurations to successfully share the switch fabrics.'
---
= Ensuring ISLs are in the same port group and configuring zoning
:icons: font
:imagesdir: ../media/

[.lead]
You must make sure that the Inter-Switch Links (ISLs) are in the same port group and configure zoning for the MetroCluster configurations to successfully share the switch fabrics.

.Steps
. If the ISLs are not in the same port group, move one of the ISL ports to the same port group as the other one.
+
You can use any available port except 32 through 45, which are used by the new MetroCluster configuration. The recommended ISL ports are 46 and 47.

. Follow the steps in the Configuring zoning on a Brocade FC switch section to enable trunking and the QoS zone.
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[Configuring zoning on Brocade FC switches]
+
The port numbers when sharing fabrics are different than those shown in the section. When sharing, use ports 46 and 47 for the ISL ports. If you moved your ISL ports, you need to use the procedure in the Configuring the E-ports (ISL ports) on a Brocade FC switch section to configure the ports.
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[Configuring the E-ports (ISL ports) on a Brocade FC switch]

. Follow the steps in the Configuring the non-E ports on the Brocade switch section to configure the non-E ports.
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[Configuring the non-E ports on the Brocade switch]

. Do not delete the zones or zone sets that already exist in the backend switches (for the 7-Mode fabric MetroCluster) except the Traffic Isolation (TI) zones in Step 3.
. Follow the steps in the Configuring the E-ports (ISL ports) on a Brocade FC switch section to add the zones required by the new MetroCluster to the existing zone sets.
+
xref:task_fcsw_brocade_configure_the_brocade_fc_switches_supertask.adoc[Configuring the E-ports (ISL ports) on a Brocade FC switch]
+
The following example shows the commands and system output for creating the zones:
+
----
Brocade-6510-2K0GG:admin> zonecreate "QOSH2_FCVI_1", "2,32; 2,35; 1,32; 1,35"

Brocade-6510-2K0GG:admin> zonecreate "STOR_A_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 1,47"

Brocade-6510-2K0GG:admin> zonecreate "STOR_B_2_47", "2,33; 2,34; 2,36; 2,37; 1,33; 1,34; 1,36; 1,37; 2,47"


Brocade-6510-2K0GG:admin> cfgadd config_1_FAB2, "QOSH2_FCVI_1; STOR_A_2_47; STOR_B_2_47"

Brocade-6510-2K0GG:admin> cfgenable "config_1_FAB2"
You are about to enable a new zoning configuration.
This action will replace the old zoning configuration with the
current configuration selected. If the update includes changes
to one or more traffic isolation zones, the update may result in
localized disruption to traffic on ports associated with
the traffic isolation zone changes
Do you want to enable 'config_1_FAB2' configuration  (yes, y, no, n): [no] yes

Brocade-6510-2K0GG:admin> cfgsave
You are about to save the Defined zoning configuration. This
action will only save the changes on Defined configuration.
Do you want to save the Defined zoning configuration only?  (yes, y, no, n): [no] yes
Nothing changed: nothing to save, returning ...
Brocade-6510-2K0GG:admin>
----
