---
permalink: install-fc/task_fmc_mcc_transition_configure_zone_and_qos.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, delete, ti, zoning, tod, settings
summary: 'You must delete the existing TI zoning and reconfigure in-order-delivery \(IOD\) settings on the switch fabric.'
---
= Deleting TI zoning and configuring IOD settings
:icons: font
:imagesdir: ../media/

[.lead]
You must delete the existing TI zoning and reconfigure in-order-delivery (IOD) settings on the switch fabric.

. Identify the TI zones that are configured on the fabric:
+
`*zone –-show*`
+
The following example shows the zone FCVI_TI_FAB_2.
+
----
Brocade-6510:admin> zone --show
   Defined TI zone configuration:
   TI Zone Name:   FCVI_TI_FAB_2
   Port List:      1,0; 1,3; 2,0; 2,3
   configured Status: Activated / Failover-Disabled
   Enabled Status: Activated / Failover-Disabled
----

. Delete the TI zones:
+
`*zone -–delete zone-name*`
+
The following example shows the deletion of zone FCVI_TI_FAB_2.
+
----
Brocade-6510:admin> zone --delete FCVI_TI_FAB_2
----

. Confirm that the zones have been deleted:
+
`*zone –-show*`
+
The output should be similar to the following:
+
----
Brocade-6510:admin> zone -–show

    Defined TI zone configuration:
    no TI zone configuration defined
----

. Save the configuration:
+
`*cfgsave*`
. Enable in-order-delivery:
+
`*iodset*`
. Select Advanced Performance Tuning (APT) policy 1, the Port Based Routing Policy:
+
`*aptpolicy 1*`
. Disable Dynamic Load Sharing (DLS):
+
`*dlsreset*`
. Verify the IOD settings using the following commands:
+
`*iodshow*`
+
`*aptpolicy*`
+
`*dlsshow*`
+
The output should be similar to the following:
+
----
Brocade-6510:admin> iodshow

IOD is set

Brocade-6510:admin> aptpolicy
 Current Policy: 1

 3 : Default Policy
 1: Port Based Routing Policy
 2: Device Based Routing Policy (FICON support only)
 3: Exchange Based Routing Policy
Brocade-6510:admin> dlsshow

DLS is not set
----
