---
permalink: install-fc/task_cable_the_ha_interconnect.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, cable, ha, interconnect
summary: 'If you have an eight- or a four-node MetroCluster configuration and the storage controllers within the HA pairs are in separate chassis, you must cable the HA interconnect between the controllers.'
---
= Cabling the HA interconnect, if necessary
:icons: font
:imagesdir: ../media/

[.lead]
If you have an eight- or a four-node MetroCluster configuration and the storage controllers within the HA pairs are in separate chassis, you must cable the HA interconnect between the controllers.

* This task does not apply to two-node MetroCluster configurations.
* This task must be performed at both MetroCluster sites.
* The HA interconnect must be cabled only if the storage controllers within the HA pair are in separate chassis.
+
Some storage controller models support two controllers in a single chassis, in which case they use an internal HA interconnect.

.Steps
. Cable the HA interconnect if the storage controller's HA partner is in a separate chassis.
+
https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

. If the MetroCluster site includes two HA pairs, repeat the previous steps on the second HA pair.
. Repeat this task at the MetroCluster partner site.
