---
permalink: install-fc/task_cable_the_isls_in_a_mcc_configuration_with_array_luns.html
sidebar: sidebar
keywords: 
summary: 'You must connect the FC switches across the sites through Inter-Switch Links \(ISLs\) to form switch fabrics in your MetroCluster configuration with array LUNs.'
---
= Cabling the ISLs in a MetroCluster configuration with array LUNs
:icons: font
:imagesdir: ../media/

[.lead]
You must connect the FC switches across the sites through Inter-Switch Links (ISLs) to form switch fabrics in your MetroCluster configuration with array LUNs.

. Connect the switches at each site to the ISL or ISLs, using the cabling in the table that corresponds to your configuration and switch model.
+
The switch port numbers that you can use for the FC ISLs are as follows:
+
|===
| Switch model| ISL port| Switch port
a|
Brocade 6520
a|
ISL port 1
a|
23
a|
ISL port 2
a|
47
a|
ISL port 3
a|
71
a|
ISL port 4
a|
95
a|
Brocade 6505
a|
ISL port 1
a|
20
a|
ISL port 2
a|
21
a|
ISL port 3
a|
22
a|
ISL port 4
a|
23
a|
Brocade 6510 and Brocade DCX 8510-8
a|
ISL port 1
a|
40
a|
ISL port 2
a|
41
a|
ISL port 3
a|
42
a|
ISL port 4
a|
43
a|
ISL port 5
a|
44
a|
ISL port 6
a|
45
a|
ISL port 7
a|
46
a|
ISL port 8
a|
47
a|
Brocade 7810
a|
ISL port 1
a|
ge2 (10-Gbps)
a|
ISL port 2
a|
ge3(10-Gbps)
a|
ISL port 3
a|
ge4 (10-Gbps)
a|
ISL port 4
a|
ge5 (10-Gbps)
a|
ISL port 5
a|
ge6 (10-Gbps)
a|
ISL port 6
a|
ge7 (10-Gbps)
a|
Brocade 7840    *Note:* The Brocade 7840 switch supports either two 40 Gbps VE-ports or up to four 10 Gbps VE-ports per switch for the creation of FCIP ISLs.
a|
ISL port 1
a|
ge0 (40-Gbps) or ge2 (10-Gbps)
a|
ISL port 2
a|
ge1 (40-Gbps) or ge3 (10-Gbps)
a|
ISL port 3
a|
ge10 (10-Gbps)
a|
ISL port 4
a|
ge11 (10-Gbps)
a|
Brocade G610
a|
ISL port 1
a|
20
a|
ISL port 2
a|
21
a|
ISL port 3
a|
22
a|
ISL port 4
a|
23
a|
Brocade G620, G620-1, G630, G630-1, G720
a|
ISL port 1
a|
40
a|
ISL port 2
a|
41
a|
ISL port 3
a|
42
a|
ISL port 4
a|
43
a|
ISL port 5
a|
44
a|
ISL port 6
a|
45
a|
ISL port 7
a|
46
a|
ISL port 8
a|
47
|===
|===
| Switch model| ISL port| Switch port
a|
Cisco 9396S
a|
ISL 1
a|
44
a|
ISL 2
a|
48
a|
ISL 3
a|
92
a|
ISL 4
a|
96
a|
Cisco 9250i with 24 port license
a|
ISL 1
a|
12
a|
ISL 2
a|
16
a|
ISL 3
a|
20
a|
ISL 4
a|
24
a|
Cisco 9148S
a|
ISL 1
a|
20
a|
ISL 2
a|
24
a|
ISL 3
a|
44
a|
ISL 4
a|
48
a|
Cisco 9132T
a|
ISL 1
a|
MDS module 1 port 13
a|
ISL 2
a|
MDS module 1 port 14
a|
ISL 3
a|
MDS module 1 port 15
a|
ISL 4
a|
MDS module 1 port 16
|===
*** The Cisco 9250i switch uses the FCIP ports for the ISL. There are certain limitations and procedures for using the FCIP ports.
+
Ports 40 through 48 are 10 GbE ports and are not used in the MetroCluster configuration.
