---
permalink: install-fc/task_download_the_brocade_fc_rcf_switch_software.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, download, brocade, fc, switch, rcf, file
summary: 'You must download the reference configuration \(RCF\) file to each switch in the MetroCluster fabric configuration.'
---
= Download the Brocade FC switch RCF file for MetroCluster FC
:icons: font
:imagesdir: ../media/

[.lead]
You must download the reference configuration file (RCF) to each switch in the MetroCluster fabric configuration.

.About this task

To use these RCFs, the system must be running ONTAP 9.1 or later and you must use the port layout for ONTAP 9.1 or later.

If you are planning to use only one of the FC ports on the FibreBridge bridges, configure the back-end fibre channel switches manually using the instructions found in the section, link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html[Port assignments for FC switches].

.Steps
. Refer to the RCF table on the Brocade RCF download page and identify the correct RCF for each switch in your configuration.
+
The RCFs must be applied to the correct switches.

. Download the RCFs for the switches from the https://mysupport.netapp.com/site/products/all/details/metrocluster-rcf/downloads-tab[MetroCluster RCF download] page.
+
The files must be placed in a location where they can be transferred to the switch. There is a separate file for each of the four switches that make up the two-switch fabric.

. Repeat these steps on each switch in the configuration.
