---
permalink: install-fc/task_install_the_brocade_fc_switch_rcf_file.html
sidebar: sidebar
keywords: metrocluster, fabric, installation, brocade, fc, switch, rcf, file
summary: 'When you configure a Brocade FC switch, you can install the switch configuration files that provide the complete switch settings for certain configurations.'
---
= Installing the Brocade FC switch RCF file
:icons: font
:imagesdir: ../media/

[.lead]
When you configure a Brocade FC switch, you can install the switch configuration files that provide the complete switch settings for certain configurations.

These steps must be repeated on each of the Brocade FC switches in the MetroCluster fabric configuration.

.Steps

. Initiate the download and configuration process:
+
`*configDownload*`
+
Respond to the prompts as shown in the following example.
+
----
FC_switch_A_1:admin> configDownload
Protocol (scp, ftp, sftp, local) [ftp]:
Server Name or IP Address [host]: <user input>
User Name [user]:<user input>
Path/Filename [<home dir>/config.txt]:path to configuration file
Section (all|chassis|switch [all]): all
.
.
.
Do you want to continue [y/n]: y
Password: <user input>
----
+
After entering your password, the switch downloads and executes the configuration file.

. Persistently enable the switch: `*switchcfgpersistentenable*`
+
The example shows how to persistently enable FC switch_A_1.
+
----
FC_switch_A_1:admin> switchcfgpersistentenable
----

. Run the following command to confirm that the configuration file has set the switch domain:
+
`*switchShow*`
+
Each switch is assigned a different domain number depending on which configuration file the switch used.
+
----
FC_switch_A_1:admin> switchShow
switchName: FC_switch_A_1
switchType: 109.1
switchState: Online
switchMode: Native
switchRole: Subordinate
switchDomain: 5
----

. Verify that your switch is assigned the correct domain value as indicated in the following table.
+
[options="header"]
|===
| Fabric| Switch| Switch domain
.2+a|
1
a|
A_1
a|
5
a|
B_1
a|
7
.2+a|
2
a|
A_2
a|
6
a|
B_2
a|
8
|===

. Change the port speed: `*portcfgspeed*`
+
----
FC_switch_A_1:admin> portcfgspeed port number port speed
----
+
[NOTE]
====
By default, all the ports are configured to operate at 16 Gbps. You might change the port speed for the following reasons:

 ** The interconnect switch ports speed should be changed when an 8-Gbps FC-VI adapter is used and the switch port speed should set to 8 Gbps.
 ** The switch ports speed should be changed when an 8-Gbps HBA adapter is used for ATTO FibreBridge 6500N.
 ** The ISL ports' speed must be changed when the ISL is not capable of running at 16 Gbps.

====

. Calculate the ISL distance.
+
Due to the behavior of the FC-VI, you must set the distance to 1.5 times the real distance with a minimum of 10 (LE). The distance for the ISL is calculated as follows, rounded up to the next full kilometer: 1.5 × real distance = distance.
+
If the distance is 3 km, then 1.5 × 3 km = 4.5. This is lower than 10; therefore, you must set the ISL to the LE distance level.
+
The distance is 20 km, then 1.5 × 20 km = 30. You must set the ISL to the LS distance level.

. Set the distance for each ISL port using the following command: `*portcfglongdistance* _port levelvc_link_initdistance_`
+
A vc_link_init value of 1 uses the fillword 'ARB' by default. A value of 0 uses the fillword 'IDLE'. The required value might vary depending on the link you use. In this example, the default is set and the distance is assumed to be 20 km. Hence, the setting is '30' with a vc_link_init value of 1, and the ISL port is 21.
+
Example: LS
+
----
FC_switch_A_1:admin> portcfglongdistance 21 LS 1 -distance 30
----
+
Example: LE
+
----
FC_switch_A_1:admin> portcfglongdistance 21 LE 1
----

. Verify if the IP address is set correctly: `*ipAddrshow*`
+
----
FC_switch_A_1:admin> ipAddrshow
----
+
You can set the IP address with the following command if required: `*ipAddrSet*`

. Set the timezone from the switch prompt: `*tstimezone --interactive*`
+
You should respond to the prompts as required.
+
----
FC_switch_A_1:admin>  tstimezone --interactive
----

. Reboot the switch: `*reboot*`
+
The example shows how to reboot FC switch _A_1.
+
----
FC_switch_A_1:admin> reboot
----

. Verify the distance setting: `*portbuffershow*`
+
A distance setting of LE appears as 10 km.
+
----
FC_Switch_A_1:admin> portbuffershow
User Port Lx   Max/Resv Buffer Needed  Link     Remaining
Port Type Mode Buffers  Usage  Buffers Distance Buffers
---- ---- ---- ------- ------ ------- --------- ----------
...
21    E    -      8      67     67      30 km
22    E    -      8      67     67      30 km
...
23    -    8      0       -      -      466
----

. Reconnect the ISL cables to the ports on the switches where they were removed.
+
The ISL cables were disconnected when the factory settings were reset to the default settings.
+
xref:task_reset_the_brocade_fc_switch_to_factory_defaults.adoc[Resetting the Brocade FC switch to factory defaults]

. Validate the configuration.
 .. Verify that the switches form one fabric: `*switchshow*`
+
The following example shows the output for a configuration that uses ISLs on ports 20 and 21.
+
----
FC_switch_A_1:admin> switchshow
switchName: FC_switch_A_1
switchType: 109.1
switchState:Online
switchMode: Native
switchRole: Subordinate
switchDomain:       5
switchId:   fffc01
switchWwn:  10:00:00:05:33:86:89:cb
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
===========================================
...
20   20  010C00   id    16G  Online FC  LE E-Port  10:00:00:05:33:8c:2e:9a "FC_switch_B_1" (downstream)(trunk master)
21   21  010D00   id    16G  Online FC  LE E-Port  (Trunk port, master is Port 20)
...
----

 .. Confirm the configuration of the fabrics: `*fabricshow*`
+
----
FC_switch_A_1:admin> fabricshow
   Switch ID   Worldwide Name      Enet IP Addr FC IP Addr Name
-----------------------------------------------------------------
1: fffc01 10:00:00:05:33:86:89:cb 10.10.10.55  0.0.0.0    "FC_switch_A_1"
3: fffc03 10:00:00:05:33:8c:2e:9a 10.10.10.65  0.0.0.0   >"FC_switch_B_1"
----

 .. Very that the ISLs are working: `*islshow*`
+
----
FC_switch_A_1:admin> islshow
----

 .. Confirm that zoning is properly replicated by running the following commands:
 +
`*cfgshow*`
 +
`*zoneshow*`
+
Both outputs should show the same configuration information and zoning information for both switches.

 .. If trunking is used, you can confirm the trunking with the following command: `*trunkShow*`
+
----
FC_switch_A_1:admin> trunkshow
----
