
[.lead]
The various MetroCluster configurations have key differences in the required components.

In all configurations, each of the two MetroCluster sites is configured as an ONTAP cluster. In a two-node MetroCluster configuration, each node is configured as a single-node cluster.

[cols=6*,options="header"]
|===
| Feature | IP configurations   2+| Fabric attached configurations 2+| Stretch configurations

a|
a|
a| *Four- or eight-node*
a| *Two-node*
a| *Two-node bridge-attached*
a| *Two-node direct-attached*

a|
Number of controllers
a|
Four or eight*
a|
Four or eight
a|
Two
a|
Two
a|
Two
a|
Uses an FC switch storage fabric
a|
No
a|
Yes
a|
Yes
a|
No
a|
No
a|
Uses an IP switch storage fabric
a|
Yes
a|
No
a|
No
a|
No
a|
No
a|
Uses FC-to-SAS bridges
a|
No
a|
Yes
a|
Yes
a|
Yes
a|
No
a|
Uses direct-attached SAS storage
a|
Yes (local attached only)
a|
No
a|
No
a|
No
a|
Yes
a|
Supports ADP
a|
Yes (starting in ONTAP 9.4)
a|
No
a|
No
a|
No
a|
No
a|
Supports local HA
a|
Yes
a|
Yes
a|
No
a|
No
a|
No
a|
Supports ONTAP AUSO
a|
No
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Supports unmirrored aggregates
a|
Yes (starting in ONTAP 9.8)
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Supports array LUNs
a|
No
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Supports ONTAP Mediator
a|
Yes (starting in ONTAP 9.7)
a|
No
a|
No
a|
No
a|
No
a|
Supports MetroCluster Tiebreaker
a|
Yes (not in combination with ONTAP Mediator)
a|
Yes
a|
Yes
a|
Yes
a|
Yes
|===

*Note the following considerations for eight-node MetroCluster IP configurations:

* Eight-node configurations are supported starting in ONTAP 9.9.1.
* Only NetApp-validated MetroCluster switches (ordered from NetApp) are supported.
* Configurations using IP-routed (layer 3) backend connections are not supported.
* Configurations using shared private layer 2 networks are not supported.
* Configurations using a Cisco 9336C-FX2 shared switch are not supported.
//2021-04-21 1374268

== Support for All SAN Array systems in MetroCluster configurations

Some All SAN Arrays (ASAs) are supported in MetroCluster configurations. In the MetroCluster documentation, the information for AFF models applies to the corresponding ASA system. For example, all cabling and other information for the AFF A400 system also applies to the ASA AFF A400 system.

Supported platform configurations are listed in the https://hwu.netapp.com[NetApp Hardware Universe].
