
+
--
[NOTE]
====
* Certain platforms use a VLAN for the MetroCluster IP interface. By default, each of the two ports use a different VLAN: 10 and 20. You can also specify a different (non-default) VLAN higher than 100 (between 101 and 4095) using the `-vlan-id parameter` in the `metrocluster configuration-settings interface create` command.
* Beginning with ONTAP 9.9.1, if you are using a layer 3 configuration, you must also specify the `-gateway` parameter when creating MetroCluster IP interfaces. Refer to link:../install-ip/concept_considerations_layer_3.html[Considerations for layer 3 wide-area networks].
====
--

+
The following platform models can be added to the existing MetroCluster configuration if the VLANs used are 10/20 or greater than 100. If any other VLANs are used, then these platforms cannot be added
to the existing configuration as the MetroCluster interface cannot be configured.
If you are using any other platform, the VLAN configuration is not relevant as this is not required in ONTAP.
+

|===

h| AFF platforms h| FAS platforms

a|

* AFF A220
* AFF A250
* AFF A400

a|

* FAS2750
* FAS500f
* FAS8300
* FAS8700

|===
// 22 APR 2021, BURT 1180776
