
+
--
[NOTE]
====
* Beginning with ONTAP 9.9.1, if you are using a layer 3 configuration, you must also specify the `-gateway` parameter when creating MetroCluster IP interfaces. Refer to link:../install-ip/concept_considerations_layer_3.html[Considerations for layer 3 wide-area networks].
====

Certain platforms use a VLAN for the MetroCluster IP interface. By default, each of the two ports use a different VLAN: 10 and 20. 

If supported, you can also specify a different (non-default) VLAN higher than 100 (between 101 and 4095) using the `-vlan-id parameter` in the `metrocluster configuration-settings interface create` command.

--
Platforms that do *not* support the `vlan-id` parameter:

* FAS8200 and AFF A300
* AFF A320
* FAS9000 and AFF A700
* AFF C800, ASA C800, AFF A800 and ASA A800

All other platforms support the `vlan-id` parameter.

The following shows default and valid VLAN assignments depending on if the platform supports the `vlan-id` parameter:

[role="tabbed-block"]
====
.Platforms that support `vlan-id`
--
Default VLAN:

* When not specifying the vlan-ip parameter, then the interfaces will be created with VLAN 10 for the "A" port and VLAN 20 for the "B" ports
* The VLAN specified must match the VLAN selected in the RCF file

Valid VLAN ranges:

* Default VLAN 10 and 20
* VLANs 101 and higher
--
.Platforms that do not support `vlan-id`
--
Default VLAN: 

* Not applicable. The interface does not require a VLAN to be specified on the MetroCluster interface. The switch port will define the VLAN to be used.
Valid VLAN ranges:

** All VLANs not explicitly excluded when generating the RCF file
** Default excluded VLANs are 1, 30-34, 50-59 (subject to change)
--
====

Important considerations:

* When you expand a four-node MetroCluster configuration to an eight-node MetroCluster configuration, both of the DR groups use the same VLANs. 
* If both of the DR groups cannot be configured using the same VLAN, then you must upgrade the DR group that doesn't support the `vlan-id` parameter to a VLAN that is supported by the other DR group.
* You cannot change the specified `vlan-id` on platforms that support the parameter after the interface has been created.
+
For example, you have a four-node MetroCluster configuration with FAS8200 nodes  configured using VLAN 80 and 81 and you want to refresh it to a AFF A900. The AFF A900 does not support VLAN 80 and 81. In this scenario, you change the current RCF file to a VLAN that is supported, such as 110 and 120. You can use the same procedure to upgrade the RCF, and use the new VLAN IDs. 
+
You *must* upgrade one network at a time, in the following order: Switch-A1, Switch-B1, Switch-A2, Switch-B2

NOTE: When you change the VLAN in a shared layer 2 and layer 3 network, the ISL configurations in your network also need to be updated to the allow the new VLANs.


The following platform models can be added to the existing MetroCluster configuration if the VLANs used are 10/20 or greater than 100. If any other VLANs are used, then these platforms cannot be added
to the existing configuration as the MetroCluster interface cannot be configured.
If you are using any other platform, the VLAN configuration is not relevant as this is not required in ONTAP.


|===

h| AFF platforms h| FAS platforms

a|

* AFF A220
* AFF A250
* AFF A400

a|

* FAS2750
* FAS500f
* FAS8300
* FAS8700

|===
// 22 APR 2021, BURT 1180776
