
Certain platforms use a VLAN for the MetroCluster IP interface. By default, each of the two ports use a different VLAN: 10 and 20. 
+
If supported, you can also specify a different (non-default) VLAN higher than 100 (between 101 and 4095) using the `-vlan-id` parameter in the `metrocluster configuration-settings interface create` command.
+
The following platforms do *not* support the `vlan-id` parameter:
+
** FAS8200 and AFF A300
** AFF A320
** FAS9000 and AFF A700
** AFF C800, ASA C800, AFF A800 and ASA A800
+
All other platforms support the `vlan-id` parameter.
+
The default and valid VLAN assignments depend on whether the platform supports the `vlan-id` parameter:
+
[role="tabbed-block"]
====
.Platforms that support `vlan-id`
--
Default VLAN:

* When the `vlan-ip` parameter is not specified, the interfaces are created with VLAN 10 for the "A" port and VLAN 20 for the "B" ports.
* The VLAN specified must match the VLAN selected in the RCF.

Valid VLAN ranges:

* Default VLAN 10 and 20
* VLANs 101 and higher
--
.Platforms that do not support `vlan-id`
--
Default VLAN: 

* Not applicable. The interface does not require a VLAN to be specified on the MetroCluster interface. The switch port defines the VLAN that is used.

Valid VLAN ranges:

* All VLANs not explicitly excluded when generating the RCF. The RCF alerts you if the VLAN is invalid. 

--
====

// 01 May 2024, ONTAPDOC-1942
// 22 APR 2021, BURT 1180776
