Synchronizing the system time using NTP

Each cluster needs its own Network Time Protocol (NTP) server to synchronize the time between the nodes and their clients. You can use the Edit DateTime dialog box in System Manager to configure the NTP server.

.About this task
* You cannot modify the time zone settings for a failed node or the partner node after takeover occurs.
* Each cluster in the Stretch MetroCluster configuration should have its own separate NTP server or servers used by the nodes at that MetroCluster site.

If you are using the MetroCluster Tiebreaker software, it should also have its own separate NTP server.

.Steps

You can configure the Network Time Protocol (NTP) from the Cluster or Insights tab in the System Manager UI.

.Cluster
You can configure the NTP from the System Manger UI Cluster tab using two different options:

[role="tabbed-block"]
====

.Cluster
You can configure the NTP from the System Manger UI Cluster tab using two different options:
--
.Option 1:
. Go to Cluster > Overview
. Then select the More option and select Edit.
. In the Edit Cluster Details window, select the +Add option below NTP Servers .
. Add the name, location, and specify the IP addresses of the time servers.
. Then, select Save.

.Option 2:
. Go to Cluster > Overview
. Scroll down to Too few NTP servers are configured and select Fix It.
. Specify the IP addresses of the time servers, and then select Save.
--

.Insights
You can also configure the NTP by using the System Manager UI Insights tab:
--
. Go to the Insights tab in the System Manager UI.
. Scroll down to Too few NTP servers are configured and select Fix It.
. Select Save.
--
====


