
[.lead]
You can learn more about MetroCluster configuration and operation from the NetApp documentation library.

== MetroCluster and miscellaneous guides


|===

h| Guide h| Content

a|
link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
link:../install-stretch/index.html[Stretch MetroCluster installation and configuration]
a|

* Stretch MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the MetroCluster in ONTAP

a|
link:../manage/index.html[MetroCluster management]
a|

* Understanding the MetroCluster configuration
* Switchover, healing and switchback
* Disaster recovery

a|
link:../maintain/index.html[MetroCluster Maintenance Guide]
a|

* Guidelines for maintenance in a MetroCluster FC configuration
* Hardware replacement or upgrade and firmware upgrade procedures for FC-to-SAS bridges and FC switches
* Hot-adding a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Hot-removing a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Replacing hardware at a disaster site in a fabric-attached or stretch MetroCluster FC configuration
* Expanding a two-node fabric-attached or stretch MetroCluster FC configuration to a four-node MetroCluster configuration.
* Expanding a four-node fabric-attached or stretch MetroCluster FC configuration to an eight-node MetroCluster FC configuration.

a|
link:../upgrade/index.html[MetroCluster Upgrade and Expansion Guide]

a|

* Upgrading or refreshing a MetroCluster configuration
* Expanding a MetroCluster configuration by adding additional nodes

a|
link:../transition/index.html[MetroCluster Transition Guide]

a|

* Transitioning from a MetroCluster FC configuration to a MetroCluster IP configuration

a|
link:../tiebreaker/index.html[MetroCluster Upgrade, Transition, and Expansion Guide]

a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

*Note:* The standard storage shelf maintenance procedures can be used with MetroCluster IP configurations.

a|

* Hot-adding a disk shelf
* Hot-removing a disk shelf

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts]
a|

* How mirrored aggregates work

|===
