---
permalink: releasenotes/mcc-mediator-whats-new.html
sidebar: sidebar
keywords: metrocluster, mediator, new, release, update, install,
summary: "New capabilities of the ONTAP Mediator are provided with each release.  Here's what's new."
---

= What's new in ONTAP Mediator support
:icons: font
:imagesdir: ../media/

[.lead]
Learn about the new MetroCluster features and enhancements for ONTAP Mediator support.

For details on the features and enhancements for each release of ONTAP Mediator, refer to link:https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html[What's new in ONTAP Mediator^].

[cols="75,25"]
|===

h| ONTAP Mediator capability h| Available beginning 

a| IPv6 is supported for ONTAP Mediator 1.11 or later in MetroCluster IP configurations. 

link:../install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html[Set up the ONTAP Mediator for a MetroCluster IP configuration]
a| ONTAP 9.18.1
a| ONTAP Mediator 1.11 adds support for managing up to ten MetroCluster IP configurations using a single ONTAP Mediator instance.

link:../install-ip/concept_mediator_requirements.html[Prepare to install the ONTAP Mediator in a MetroCluster IP configuration]
a| ONTAP 9.18.1
a|Mediator-assisted automatic unplanned switchover (MAUSO) is supported in the case of an environmental shutdown.	

If one site shuts down gracefully due to an environmental shutdown, MAUSO is triggered.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html[How ONTAP Mediator supports automatic unplanned switchover]
a|ONTAP 9.13.1
a|Initial support for ONTAP Mediator in MetroCluster IP configurations
a|ONTAP 9.7
|===
