---
permalink: releasenotes/mcc-ip-config-platform-support.html
sidebar: sidebar
keywords: metrocluster, ip configuration, platform, support
summary: ''
---
= MetroCluster IP configuration platform support
:icons: font
:imagesdir: ./media/

[.lead]
MetroCluster IP configurations are not supported with array LUNs.
[cols="2*",options="header"]
|===
| Supported platforms in MetroCluster IP configurations| Available beginning
a|
AFF A150
a|
ONTAP 9.13.1 and later ONTAP releases

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12
a|
AFF C250, AFF C400, AFF C800
a|
ONTAP 9.12.1P1

ONTAP 9.13.1 GA and later ONTAP releases.

[NOTE]
====
These platforms are not supported with ONTAP 9.13.1 RC1. 
====
a|
AFF A900

MetroCluster IP configurations are limited to 400 kilometers in this release.

a|
ONTAP 9.10.1
a|
AFF A250
a|
ONTAP 9.8
a|
FAS500f
a|
ONTAP 9.8
a|
All-Flash SAN Array platforms

In the MetroCluster documentation, the information for AFF models applies to the corresponding ASA system. For example, all cabling and other information for the AFF A400 system also applies to the ASA AFF A400 system.
a|
ONTAP 9.8
a|
AFF A320 is supported on Broadcom switches
a|
ONTAP 9.7
a|
AFF A320
a|
ONTAP 9.6P3
a|
AFF A220 and FAS2750
a|
ONTAP 9.6
a|
AFF A300 and FAS8200
a|
ONTAP 9.5
|===
