---
permalink: releasenotes/mcc-new-features.html
sidebar: sidebar
keywords: new metrocluster features
summary: ''
---

= What's new in MetroCluster features
:icons: font
:imagesdir: ../media/

[.lead]
Each release of the ONTAP 9 data management software delivers new and enhanced features that improve the capabilities, manageability, and performance of ONTAP MetroCluster configurations.

For details about known issues, limitations, and upgrade cautions affecting ONTAP MetroCluster configurations,  refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]. You must sign in with your NetApp account or create an account to access the Release Notes. 

[cols="20,65,15"*,options="header"]
|===
| Supported features in MetroCluster configuration| Description and where to learn more| Available beginning
a|
MetroCluster IP support for end-to-end encryption
a|
End-to-end encryption is supported on the following systems to encrypt back-end traffic, such as NVlog and storage replication data, between the sites in a MetroCluster IP configuration.

* AFF A800, AFF C800
* AFF A20, AFF A30, AFF C30, AFF A50, AFF C60
* AFF A70, AFF A90, AFF A1K, AFF C80
* FAS50, FAS70, FAS90

link:../maintain/task-configure-encryption.html[Configure end-to-end encryption in a MetroCluster IP configuration]
a|
ONTAP 9.17.1
a|
Limit changes for MetroCluster IP configurations
a|
ONTAP 9.17.1 includes the following limit updates for four-node MetroCluster IP configurations: 

* AFF C800, AFF A800, AFF A900, AFF A90, and AFF A1K systems have the following updated limits: 
** FlexVol volume limits per node: 1250 
** SVM limits: 64 SVMs per cluster
** LIF count: 256 LIFs per cluster

* AFF A400, AFF C400, ASA A400, ASA C400, AFF C80, AFF A70, and AFF A50 systems have the following updated limits:

** FlexVol volume limits per aggregate (single or multiple): 625
** FlexVol volume limits per node: 1250
** FlexVol volume limits per high-availability (HA) pair: 2500
** FlexVol volume limits per cluster: 5000
** SVM limits: 64 SVMs per cluster
** LIF count: 256 LIFs per cluster

Refer to the link:https://hwu.netapp.com[Hardware Universe^] for more information. 
a|
ONTAP 9.17.1
a|
FibreBridge firmware update using credentials
a|
You can update the firmware on FibreBridge bridges using credentials if they are required by the server to download the firmware package.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html[Update firmware on a FibreBridge bridge]
a|
ONTAP 9.16.1 
a|
SVM data mobility support for migrating MetroCluster configurations
a|
ONTAP supports the following MetroCluster SVM migrations: 

* Migrating an SVM between a non-MetroCluster HA pair and a MetroCluster IP configuration
* Migrating an SVM between two MetroCluster IP configurations 
* Migrating an SVM between a MetroCluster FC configuration and a MetroCluster IP configuration

link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html[SVM data mobility^]
a|
ONTAP 9.16.1
a|
MD5 authentication support for BGP peer groups
a|
ONTAP supports MD5 authentication on BGP peer groups to protect BGP sessions. When MD5 is enabled, BGP sessions can only be established and processed among authorized peers, preventing potential disruptions of the session by an unauthorized actor.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html[Configure virtual IP (VIP) LIFs^]
a|
ONTAP 9.16.1
a|
MetroCluster IP support for end-to-end encryption
a|
End-to-end encryption is supported on AFF A400, FAS8300, and FAS8700 systems to encrypt back-end traffic, such as NVlog and storage replication data, between the sites in a MetroCluster IP configuration.

link:../maintain/task-configure-encryption.html[Configure end-to-end encryption in a MetroCluster IP configuration]
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A800 and AFF C800 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for AFF A800 and AFF C800 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from 200 to 625.
* The maximum number of FlexVol volumes per node increased from 800 to 1250.
* The maximum number of FlexVol volumes per HA pair increased from 1600 to 2500.
a|
ONTAP 9.15.1
a|
MetroCluster IP support for NVMe
a|
The NVMe/TCP front-end host protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A900 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for AFF A900 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from 200 to 625.
* The maximum number of FlexVol volumes per node increased from 800 to 1250.
* The maximum number of FlexVol volumes per HA pair increased from 1600 to 2500.
a|
ONTAP 9.14.1
a|
S3 object storage support on mirrored and unmirrored aggregates
a|
You can enable an S3 object storage server on an SVM in a mirrored or unmirrored aggregate in MetroCluster IP and FC configurations.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster[S3 support with MetroCluster^]
a|
ONTAP 9.14.1
a|
Support for provisioning an S3 bucket on mirrored and unmirrored aggregates in a MetroCluster cluster 
a|
You can create a bucket on a mirrored or unmirrored aggregate in MetroCluster configurations.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets[Create an ONTAP S3 bucket on a mirrored or unmirrored aggregate in a MetroCluster configuration^]
a|
ONTAP 9.14.1
a|
Transition from MetroCluster FC to MetroCluster IP using a shared switch for MetroCluster IP and Ethernet attached storage 
a|
You can transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration using a shared storage switch. 

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)]
a|
ONTAP 9.13.1
a|
Nondisruptive transitions from an eight-node MetroCluster FC configuration to a MetroCluster IP configuration
a|
You can nondisruptively transition workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Four-node MetroCluster IP configuration upgrades using switchover and switchback
a|
You can upgrade controllers in a four-node MetroCluster IP configuration using switchover and switchback with `system controller replace` commands.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html[Upgrade controllers in a four node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Mediator-assisted automatic unplanned switchover (MAUSO) is triggered for an environmental shutdown
a|
If one site shuts down gracefully due to an environmental shutdown, MAUSO is triggered.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html[How the ONTAP Mediator supports automatic unplanned switchover]
a|
ONTAP 9.13.1
a|
Eight-node MetroCluster IP configurations support
a|
You can upgrade the controllers and storage in an eight-node MetroCluster IP configuration by expanding the configuration to become a temporary twelve-node configuration and then removing the old DR groups.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html[Refresh a four-node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
MetroCluster IP configuration conversion to a shared storage MetroCluster switch configuration
a|
You can convert a MetroCluster IP configuration to a shared storage MetroCluster switch configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html[Replace an IP switch]
a|
ONTAP 9.13.1
a|
MetroCluster automatic forced switchover feature in a MetroCluster IP configuration
a|
You can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover (MAUSO) feature.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html[Automatic switchover limitations]
a|
ONTAP 9.12.1
a|
S3 on an SVM on an unmirrored aggregate in a MetroCluster IP configuration
a|
You can enable an ONTAP Simple Storage Service (S3) object storage server on an SVM on an unmirrored aggregate in a MetroCluster IP configuration. 

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster[S3 support with MetroCluster^]
a|
ONTAP 9.12.1
a|
MetroCluster IP support for NVMe
a|
The NVMe/FC protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.12.1
a|
IPsec support for front-end host protocol in MetroCluster IP and MetroCluster fabric-attached configurations
a|
IPsec support for front-end host protocol (such as NFS and iSCSI) is available in MetroCluster IP and MetroCluster fabric-attached configurations.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html[Configure IP security (IPsec) over wire encryption^]
a|
ONTAP 9.12.1
a|
Transition from a MetroCluster FC configuration to an AFF A250 or FAS500f MetroCluster IP configuration
a|
You can transition from a MetroCluster FC configuration to an AFF A250 or FAS500f MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move[Move the local cluster connections]
a|
ONTAP 9.11.1
a|
Consistency groups
a|
Consistency groups are supported in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups[Consistency groups in MetroCluster configurations^]
a|
ONTAP 9.11.1
a|
Simplified controller upgrade of nodes in a MetroCluster FC configuration
a|
The upgrade procedure for the upgrade process using switchover and switchback has been simplified.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html[Upgrade controllers in a MetroCluster FC configuration using switchover and switchback]
a|
ONTAP 9.10.1
a|
IP support for shared link at layer 3
a|
MetroCluster IP configurations can be implemented with IP-routed (layer 3) back-end connections.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html[Considerations for layer 3 wide-area networks]
a|
ONTAP 9.9.1
a|
Support for eight-node MetroCluster configurations
a|
Permanent eight-node clusters are supported in IP and Fabric-attached MetroCluster configurations.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html[Install and cable MetroCluster components]
a|
ONTAP 9.9.1

|===


// 2025 April 09, ONTAPDOC-2282
// 2025 March 29, ONTAPDOC-2607
// 2024 Nov 07, ONTAPDOC-2299
// 2024 May 15, ONTAPDOC-1602 (9.15.1)
// 2024 Nov 07, ONTAPDOC-2070
// 2024 May 15, ONTAPDOC-1657, ONTAPDOC-1684 (9.15.1)