---
permalink: releasenotes/mcc-ip-config-platform-support.html
sidebar: sidebar
keywords: metrocluster, ip configuration, platform, support
summary: ''
---

= What's new in MetroCluster IP platform support
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new in MetroCluster IP platform support.

== Platform support

[cols="2*",options="header"]
|===
| Supported platforms in MetroCluster IP configurations| Available beginning
a|
AFF A70, AFF A90, and AFF A1k
a| ONTAP 9.15.1 and later
a|
AFF A150
a|
ONTAP 9.13.1 and later 

ONTAP 9.12.1P1

ONTAP 9.11.1P8

ONTAP 9.10.1P12
a|
AFF C250, AFF C400, AFF C800
a|
ONTAP 9.12.1P1

ONTAP 9.13.1 GA and later 
a|
AFF A900
a|
ONTAP 9.10.1
a|
AFF A250
a|
ONTAP 9.8
a|
FAS500f
a|
ONTAP 9.8
a|
All-Flash SAN Array platforms

In the MetroCluster documentation, the information for AFF models applies to the corresponding ASA system. For example, all cabling and other information for the AFF A400 system also applies to the ASA AFF A400 system.
a|
ONTAP 9.7
a|
AFF A320
a|
ONTAP 9.6P3
a|
AFF A220 and FAS2750
a|
ONTAP 9.6
a|
AFF A300 and FAS8200
a|
ONTAP 9.5
|===

== Switch support

[cols="2*",options="header"]
|===
| Broadcom IP switches| Available beginning
a|
Quanta IX8
a|
ONTAP 9.6
|===
[cols="2*",options="header"]
|===
| Cisco IP switches| Available beginning
a|
Nexus 9336C-FX2
a|
ONTAP 9.9.1
a|
9336C
a|
ONTAP 9.8
|===
[cols="2*",options="header"]
|===
| NVIDIA switches| Available beginning
a|
Multiple MC IP configs on the same NVIDIA SN2100 switch
a|
ONTAP 9.14.1
a|
SN2100 
a|
ONTAP 9.12.1
|===
