---
permalink: releasenotes/mcc-config-support-features.html
sidebar: sidebar
keywords: metrocluster, configuration, support for ontap features
summary: ''
---

= What's new in MetroCluster configuration support for ONTAP features
:icons: font
:imagesdir: ./media/

[.lead]
Each release of the ONTAP 9 data management software delivers new and enhanced features that improve the capabilities, manageability, and performance of ONTAP MetroCluster configurations.

For details about known issues, limitations, and upgrade cautions affecting ONTAP MetroCluster configurations,  refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]. You must sign in with your NetApp account or create an account to access the Release Notes.

[cols="20,65,15"*,options="header"]
|===
| Supported features in MetroCluster configuration| Description| Available beginning
a|
MetroCluster IP support for NVMe
a|
The NVMe/TCP front-end host protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.15.1
a|
S3 object storage support on mirrored and unmirrored aggregates
a|
You can enable an S3 object storage server on an SVM in a mirrored or unmirrored aggregate in MetroCluster IP and FC configurations.

https://docs.netapp.com/us-en/ontap/s3-config/index.html[S3 configuration overview]
a|
ONTAP 9.14.1
a|
Support for provisioning an S3 bucket on mirrored and unmirrored aggregates in a MetroCluster cluster
a|
You can create a bucket on a mirrored or unmirrored aggregate in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html[Create a bucket on a mirrored or unmirrored aggregate in a MetroCluster configuration]
a|
ONTAP 9.12.1
a|
MetroCluster IP support for NVMe
a|
The NVMe/FC protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.12.1
a|
IPsec support for front-end host protocol in MetroCluster IP and MetroCluster fabric-attached configurations
a|
IPsec support for front-end host protocol (such as NFS and iSCSI) is available in MetroCluster IP and MetroCluster fabric-attached configurations.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html[Configure IP security (IPsec) over wire encryption]
a|
ONTAP 9.11.1
a|
Consistency groups
a|
Consistency groups are supported in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service]
a|
ONTAP 9.7
a|
FabricPool mirrors on MetroCluster configurations
a|
You can set up a mirrored FabricPool on MetroCluster configurations to tier cold data to two different fault zones.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html[Setting up object stores for FabricPool in a MetroCluster configuration]
a|
ONTAP 9.7
a|
SVM disaster recovery
a|
Active storage virtual machines (SVMs) in a MetroCluster configuration can be used as sources with the SnapMirror SVM disaster recovery feature.
a|
ONTAP 9.5
|===

// 2024 May 15, ONTAPDOC-1602 (9.15.1)