---
permalink: releasenotes/mcc-mediator-whats-new.html
sidebar: sidebar
keywords: metrocluster, mediator, new, release, update, install,
summary: "New capabilities of the ONTAP Mediator are provided with each release.  Here's what's new."
---

= What's new in ONTAP Mediator support
:icons: font
:imagesdir: ../media/

[.lead]
New enhancements to the ONTAP Mediator are provided with each release.  Here's what's new.

[cols="75,25"]
|===

h| ONTAP Mediator version/capability h| ONTAP Version

a|ONTAP Mediator 1.5 is available for monitoring MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service^]

a|ONTAP 9.12.1
a|ONTAP Mediator software version 1.4 is supported in MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service^]

a|ONTAP 9.11.1
a|The ONTAP Mediator service can assist the MetroCluster IP configuration in performing automatic unplanned switchover by providing a physically separate repository for status information.
Configuring the ONTAP Mediator service for unplanned automatic switchover
a|ONTAP 9.7
|===
