---
permalink: releasenotes/mcc-new-features.html
sidebar: sidebar
keywords: new metrocluster features
summary: ''
---

= What's new in MetroCluster features
:icons: font
:imagesdir: ../media/

[.lead]
Each release of the ONTAP 9 data management software delivers new and enhanced features that improve the capabilities, manageability, and performance of ONTAP MetroCluster configurations.

For details about known issues, limitations, and upgrade cautions affecting ONTAP MetroCluster configurations,  refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508[ONTAP 9 Release Notes^]. You must sign in with your NetApp account or create an account to access the Release Notes. 

[cols="20,65,15"*,options="header"]
|===
| Supported features in MetroCluster configuration| Description and where to learn more| Available beginning
a|
Fibrebridge firmware update using credentials
a|
You can update the firmware on Fibrebridge bridges using credentials if they are required by the server to download the firmware package.

link:../maintain/task_update_firmware_on_a_fibrebridge_bridge_parent_topic.html[Update firmware on a FibreBridge bridge]
a|
ONTAP 9.16.1 
a|
SVM data mobility support for migrating MetroCluster configurations
a|
ONTAP supports the following MetroCluster SVM migrations: 

* Migrating an SVM between a non-MetroCluster HA pair and a MetroCluster IP configuration
* Migrating an SVM between two MetroCluster IP configurations 
* Migrating an SVM between a MetroCluster FC configuration and a MetroCluster IP configuration

link:https://docs.netapp.com/us-en/ontap/svm-migrate/index.html[SVM data mobility^]
a|
ONTAP 9.16.1
a|
MD5 authentication support for BGP peer groups
a|
ONTAP supports MD5 authentication on BGP peer groups to protect BGP sessions. When MD5 is enabled, BGP sessions can only be established and processed among authorized peers, preventing potential disruptions of the session by an unauthorized actor.

link:https://docs.netapp.com/us-en/ontap/networking/configure_virtual_ip_@vip@_lifs.html[Configure virtual IP (VIP) LIFs^]
a|
ONTAP 9.16.1
a|
MetroCluster IP support for end-to-end encryption
a|
End-to-end encryption is supported on AFF A400, FAS8300, and FAS8700 systems to encrypt back-end traffic, such as NVlog and storage replication data, between the sites in a MetroCluster IP configuration.

link:../maintain/task-configure-encryption.html[Configure end-to-end encryption in a MetroCluster IP configuration]
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A800 and AFF C800 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for AFF A800 and AFF C800 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from 200 to 625.
* The maximum number of FlexVol volumes per node increased from 800 to 1250.
* The maximum number of FlexVol volumes per high-availability (HA) pair increased from 1600 to 2500.
a|
ONTAP 9.15.1
a|
MetroCluster IP support for NVMe
a|
The NVMe/TCP front-end host protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A900 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for AFF A900 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from 200 to 625.
* The maximum number of FlexVol volumes per node increased from 800 to 1250.
* The maximum number of FlexVol volumes per high-availability (HA) pair increased from 1600 to 2500.
a|
ONTAP 9.14.1
a|
S3 object storage support on mirrored and unmirrored aggregates
a|
You can enable an S3 object storage server on an SVM in a mirrored or unmirrored aggregate in MetroCluster IP and FC configurations.

https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html#s3-support-with-metrocluster[S3 support with MetroCluster^]
a|
ONTAP 9.14.1
a|
Support for provisioning an S3 bucket on mirrored and unmirrored aggregates in a MetroCluster cluster 
a|
You can create a bucket on a mirrored or unmirrored aggregate in MetroCluster configurations.

link:https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html#process-to-create-buckets[Create an ONTAP S3 bucket on a mirrored or unmirrored aggregate in a MetroCluster configuration^]
a|
ONTAP 9.14.1
a|
Transition from MetroCluster FC to MetroCluster IP using a shared switch for MetroCluster IP and Ethernet attached storage 
a|
You can transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration using a shared storage switch. 

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)]
a|
ONTAP 9.13.1
a|
Nondisruptive transitions from an eight-node MetroCluster FC configuration to a MetroCluster IP configuration
a|
You can nondisruptively transition workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Four-node MetroCluster IP configuration upgrades using switchover and switchback
a|
You can upgrade controllers in a four-node MetroCluster IP configuration using switchover and switchback with `system controller replace` commands.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html[Upgrade controllers in a four node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Mediator-assisted automatic unplanned switchover (MAUSO) is triggered for an environmental shutdown
a|
If one site shuts down gracefully due to an environmental shutdown, MAUSO is triggered.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-ontap-mediator-supports-automatic-unplanned-switchover.html[How the ONTAP Mediator supports automatic unplanned switchover]
a|
ONTAP 9.13.1
a|
Eight-node MetroCluster IP configurations support
a|
You can upgrade the controllers and storage in an eight-node MetroCluster IP configuration by expanding the configuration to become a temporary twelve-node configuration and then removing the old DR groups.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html[Refresh a four-node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
MetroCluster IP configuration conversion to a shared storage MetroCluster switch configuration
a|
You can convert a MetroCluster IP configuration to a shared storage MetroCluster switch configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html[Replace an IP switch]
a|
ONTAP 9.13.1
a|
MetroCluster automatic forced switchover feature in a MetroCluster IP configuration
a|
You can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover (MAUSO) feature.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html[Automatic switchover limitations]
a|
ONTAP 9.12.1
a|
S3 on an SVM on an unmirrored aggregate in a MetroCluster IP configuration
a|
You can enable an ONTAP Simple Storage Service (S3) object storage server on an SVM on an unmirrored aggregate in a MetroCluster IP configuration. 

https://docs.netapp.com/us-en/ontap/s3-config/index.html#s3-configuration-with-system-manager-and-the-ontap-cli[S3 configuration with System Manager and the ONTAP CLI]
a|
ONTAP 9.12.1
a|
MetroCluster IP support for NVMe
a|
The NVMe/FC protocol is supported on four-node MetroCluster IP configurations.

link:https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html[SAN configurations in a MetroCluster environment^]
a|
ONTAP 9.12.1
a|
IPsec support for front-end host protocol in MetroCluster IP and MetroCluster fabric-attached configurations
a|
IPsec support for front-end host protocol (such as NFS and iSCSI) is available in MetroCluster IP and MetroCluster fabric-attached configurations.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html[Configure IP security (IPsec) over wire encryption^]
a|
ONTAP 9.12.1
a|
Transition from a MetroCluster FC configuration to an AFF A250 or FAS500f MetroCluster IP configuration
a|
You can transition from a MetroCluster FC configuration to an AFF A250 or FAS500f MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move[Move the local cluster connections]
a|
ONTAP 9.11.1
a|
Consistency groups
a|
Consistency groups are supported in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/consistency-groups/index.html#multi-admin-verification-support-for-consistency-groups[Consistency groups in MetroCluster configurations^]
a|
ONTAP 9.11.1
a|
Simplified controller upgrade of nodes in a MetroCluster FC configuration
a|
The upgrade procedure for the upgrade process using switchover and switchback has been simplified.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html[Upgrade controllers in a MetroCluster FC configuration using switchover and switchback]
a|
ONTAP 9.10.1
a|
IP support for shared link at layer 3
a|
MetroCluster IP configurations can be implemented with IP-routed (layer 3) back-end connections.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html[Considerations for layer 3 wide-area networks]
a|
ONTAP 9.9.1
a|
Support for 8-node clusters
a|
Permanent 8-node clusters are supported in IP and Fabric-attached configurations.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html[Install and cable MetroCluster components]
a|
ONTAP 9.9.1
a|
Simplified interface to manage IP MetroCluster operations with System Manager
a|
You can manage IP MetroCluster operations with System Manager, including setting up IP MetroCluster sites, pairing the sites, and configuring the clusters.

https://docs.netapp.com/us-en/ontap/concept_metrocluster_manage_nodes.html[Manage MetroCluster sites]
a|
ONTAP 9.8
a|
IP MetroCluster switchover and switchback with System Manager
a|
You can use System Manager to perform all the steps of planned or unplanned switchover and switchback procedures for IP MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/task_metrocluster_switchover_switchback.html[MetroCluster switchover and switchback]
a|
ONTAP 9.8
a|
Transition from MetroCluster FC to MetroCluster IP configurations
a|
Transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration is supported.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[Upgrade, refresh, or expand the MetroCluster configuration]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]
a|
ONTAP 9.8
a|
New upgrade and refresh procedures
a|
Hardware upgrade or refresh of four-node MetroCluster FC and IP configurations is supported.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[Upgrade, refresh, or expand the MetroCluster configuration]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]
a|
ONTAP 9.8
a|
Unmirrored aggregates
a|
Unmirrored aggregates are supported in MetroCluster IP configurations.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html[Considerations for unmirrored aggregates]
a|
ONTAP 9.8
a|
MetroCluster compliant switches
a|
MetroCluster IP configurations can support switches which are not NetApp validated provided that they are compliant with NetApp specifications.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html[Considerations for using MetroCluster-compliant switches]
a|
ONTAP 9.7
a|
FabricPool mirrors on MetroCluster configurations
a|
You can set up a mirrored FabricPool on MetroCluster configurations to tier cold data to two different fault zones.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html[Set up object stores for FabricPool in a MetroCluster configuration^]
a|
ONTAP 9.7
a|
Private layer 2 network sharing
a|
MetroCluster IP configurations with supported Cisco switches can share existing networks for ISLs, rather than using dedicated MetroCluster ISLs. Earlier ONTAP versions require dedicated ISLs.

The MetroCluster IP switches are dedicated to the MetroCluster configuration and cannot be shared. Only the MetroCluster ISL ports on the MetroCluster IP switches can connect to the shared switches.

[CAUTION]
====
If using a shared network, the customer is responsible for meeting the MetroCluster network requirements in the shared network.
====

link:../install-ip/index.html[MetroCluster IP installation and configuration]
a|
ONTAP 9.6
a|
MetroCluster switchover and switchback
a|
You can allow one cluster site to take over the tasks of another cluster site. This capability allows you to facilitate maintenance or recovery from disasters.

link:../manage/index.html[MetroCluster switchover and switchback]
a|
ONTAP 9.6
a|
SVM disaster recovery
a|
Active storage virtual machines (SVMs) in a MetroCluster configuration can be used as sources with the SnapMirror SVM disaster recovery feature.
a|
ONTAP 9.5
|===


// 2025 April 09, ONTAPDOC-2282
// 2025 March 29, ONTAPDOC-2607
// 2024 Nov 07, ONTAPDOC-2299
// 2024 May 15, ONTAPDOC-1602 (9.15.1)
// 2024 Nov 07, ONTAPDOC-2070
// 2024 May 15, ONTAPDOC-1657, ONTAPDOC-1684 (9.15.1)