---
permalink: releasenotes/mcc-new-features.html
sidebar: sidebar
keywords: new metrocluster features
summary: ''
---

= What's new in MetroCluster features
:icons: font
:imagesdir: ./media/

[.lead]
Learn about the new MetroCluster features. 

[cols="20,65,15"*,options="header"]
|===
| Supported features in MetroCluster configuration| Description and where to learn more| Available beginning
a|
MetroCluster IP support for end-to-end encryption
a|
End-to-end encryption is supported on AFF A400, FAS8300, and FAS8700 systems to encrypt back-end traffic, such as NVlog and storage replication data, between the sites in a MetroCluster IP configuration.

link:../maintain//task-configure-encryption.html[Configure end-to-end encryption in a MetroCluster IP configuration]
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A800 and AFF C800 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for
AFF A800 and AFF C800 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from
200 to 625.
* The maximum number of FlexVol volumes per node increased from 800
to 1250.
* The maximum number of FlexVol volumes per high-availability (HA) pair
increased from 1600 to 2500.
a|
ONTAP 9.15.1
a|
Volume limit increase for four-node MetroCluster IP configurations on AFF A900 systems
a|
In four-node MetroCluster IP configurations, the following volume limits for
AFF A900 systems have increased:

* The maximum number of FlexVol volumes per aggregate increased from
200 to 625.
* The maximum number of FlexVol volumes per node increased from 800
to 1250.
* The maximum number of FlexVol volumes per high-availability (HA) pair
increased from 1600 to 2500.
a|
ONTAP 9.14.1
a|
Transition from MetroCluster FC to MetroCluster IP using a shared switch for MetroCluster IP and Ethernet attached storage 
a|
You can transition nondisruptively from a MetroCluster FC to a MetroCluster IP configuration using a shared storage switch. 

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration (ONTAP 9.8 and later)]
a|
ONTAP 9.13.1
a|
Nondisruptive transitions from an eight-node MetroCluster FC configuration to a MetroCluster IP configuration
a|
You can nondisruptively transition workloads and data from an existing eight-node MetroCluster FC configuration to a new MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_nondisruptively_transitioning_from_a_four_node_mcc_fc_to_a_mcc_ip_configuration.html[Transitioning nondisruptively from a MetroCluster FC to a MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Four-node MetroCluster IP configuration upgrades using switchover and switchback
a|
You can upgrade controllers in a four-node MetroCluster IP configuration using switchover and switchback with `system controller replace` commands.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_system_control_commands_in_a_four_node_mcc_ip.html[Upgrade controllers in a four node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
Mediator-assisted automatic unplanned switchover (MAUSO) is triggered for an environmental shutdown
a|
If one site shuts down gracefully due to an environmental shutdown, MAUSO is triggered.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mediator.html#interoperability-of-ontap-mediator-with-other-applications-and-appliances[Interoperability of ONTAP Mediator with other applications and appliances]
a|
ONTAP 9.13.1
a|
Eight-node MetroCluster IP configurations support
a|
You can upgrade the controllers and storage in an eight-node MetroCluster IP configuration by expanding the configuration to become a temporary twelve-node configuration and then removing the old DR groups.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_refresh_4n_mcc_ip.html[Refreshing a four-node MetroCluster IP configuration]
a|
ONTAP 9.13.1
a|
MetroCluster IP configuration conversion to a shared storage MetroCluster switch configuration
a|
You can convert a MetroCluster IP configuration to a shared storage MetroCluster switch configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/maintain/task_replace_an_ip_switch.html[Replacing an IP switch]
a|
ONTAP 9.13.1
a|
MetroCluster automatic forced switchover feature in a MetroCluster IP configuration
a|
You can enable the MetroCluster automatic forced switchover feature in a MetroCluster IP configuration. This feature is an extension of the Mediator-assisted unplanned switchover (MAUSO) feature.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept-risks-limitations-automatic-switchover.html[Automatic switchover limitations]
a|
ONTAP 9.12.1
a|
S3 on an SVM on an unmirrored aggregate in a MetroCluster IP configuration
a|
You can enable an ONTAP Simple Storage Service (S3) object storage server on an SVM on an unmirrored aggregate in a MetroCluster IP configuration. 

https://docs.netapp.com/us-en/ontap/s3-config/index.html#s3-configuration-with-system-manager-and-the-ontap-cli[S3 configuration with System Manager and the ONTAP CLI]
a|
ONTAP 9.12.1
a|
Transitioning from a MetroCluster FC configuration to an AFF A250 or FAS500f  MetroCluster IP configuration
a|
You can transition from a MetroCluster FC configuration to an AFF A250 or FAS500f MetroCluster IP configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_cluster_connections.html#which-connections-to-move[Move the local cluster connections]
a|
ONTAP 9.11.1
a|
Configuration of layer 3 MetroCluster IP address in MetroCluster IP configurations
a|
You can edit the MetroCluster IP address, netmask, and gateway for nodes in a layer 3 configuration.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_modify_ip_netmask_gateway_properties.html[Modifying address, netmask, and gateway in a MetroCluster IP]
a|
ONTAP 9.10.1
a|
Simplified controller upgrade of nodes in a MetroCluster FC configuration
a|
The upgrade procedure for the upgrade process using switchover and switchback has been simplified.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html[Upgrading controllers in a MetroCluster FC configuration using switchover and switchback]
a|
ONTAP 9.10.1
a|
IP support for shared link at layer 3
a|
MetroCluster IP configurations can be implemented with IP-routed (layer 3) back-end connections.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_layer_3.html[Considerations for layer 3 wide-area networks]
a|
ONTAP 9.9.1
a|
Support for 8-node clusters
a|
Permanent 8-node clusters are supported in IP and Fabric-attached configurations.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html[Installing and cabling MetroCluster components]
a|
ONTAP 9.9.1
a|
Simplified interface to manage IP MetroCluster operations with System Manager
a|
You can manage IP MetroCluster operations with System Manager, including setting up IP MetroCluster sites, pairing the sites, and configuring the clusters.

https://docs.netapp.com/us-en/ontap/concept_metrocluster_manage_nodes.html[Manage MetroCluster sites]
a|
ONTAP 9.8
a|
IP MetroCluster switchover and switchback with System Manager
a|
You can use System Manager to perform all the steps of planned or unplanned switchover and switchback procedures for IP MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/task_metrocluster_switchover_switchback.html[MetroCluster switchover and switchback]
a|
ONTAP 9.8
a|
Transition from MetroCluster FC to MetroCluster IP configurations
a|
Transition of workloads and data from an existing four-node MetroCluster FC configuration to a new MetroCluster IP configuration is supported.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[Upgrade, refresh, or expand the MetroCluster configuration]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]
a|
ONTAP 9.8
a|
New upgrade and refresh procedures
a|
Hardware upgrade or refresh of four-node MetroCluster FC and IP configurations is supported.

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[Upgrade, refresh, or expand the MetroCluster configuration]

https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]
a|
ONTAP 9.8
a|
Unmirrored aggregates
a|
Unmirrored aggregates are supported in MetroCluster IP configurations.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html[Considerations for unmirrored aggregates]
a|
ONTAP 9.8
a|
MetroCluster compliant switches
a|
MetroCluster IP configurations can support switches which are not NetApp validated provided that they are compliant with NetApp specifications.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_mc_compliant_switches.html[Considerations for using MetroCluster-compliant switches]
a|
ONTAP 9.7
a|
Private layer 2 network sharing
a|
MetroCluster IP configurations with supported Cisco switches can share existing networks for ISLs, rather than using dedicated MetroCluster ISLs. Earlier ONTAP versions require dedicated ISLs.

The MetroCluster IP switches are dedicated to the MetroCluster configuration and cannot be shared. Only the MetroCluster ISL ports on the MetroCluster IP switches can connect to the shared switches.

[CAUTION]
====
If using a shared network, the customer is responsible for meeting the MetroCluster network requirements in the shared network.
====

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html[MetroCluster IP installation and configuration]
a|
ONTAP 9.6
a|
MetroCluster switchover and switchback
a|
You can allow one cluster site to take over the tasks of another cluster site. This capability allows you to facilitate maintenance or recovery from disasters.

https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html[MetroCluster switchover and switchback]
a|
ONTAP 9.6
|===

// 2024 May 15, ONTAPDOC-1657, ONTAPDOC-1684 (9.15.1)