---
permalink: releasenotes/mcc-config-support-features.html
sidebar: sidebar
keywords: metrocluster, configuration, support for ontap features
summary: ''
---

= What's new in MetroCluster configuration support for ONTAP features
:icons: font
:imagesdir: ./media/

[.lead]

[cols="20,65,15"*,options="header"]
|===
| Supported features in MetroCluster configuration| Description| Available beginning
a|
S3 object storage support on mirrored and unmirrored aggregates
a|
You can enable an S3 object storage server on an SVM in a mirrored or unmirrored aggregate in MetroCluster IP and FC configurations.

https://docs.netapp.com/us-en/ontap/s3-config/index.html[S3 configuration overview]
a|
ONTAP 9.14.1
a|
Support for provisioning an S3 bucket on mirrored and unmirrored aggregates in a MetroCluster cluster
a|
You can create a bucket on a mirrored or unmirrored aggregate in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-mcc-task.html[Create a bucket on a mirrored or unmirrored aggregate in a MetroCluster configuration]
a|
ONTAP 9.14.1
a|
ONTAP Mediator 1.5 is supported in a MetroCluster IP configuration
a|
ONTAP Mediator 1.5 is available for monitoring MetroCluster IP configurations.

https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service]
a|
ONTAP 9.12.1
a|
IPsec support for front-end host protocol in MetroCluster IP and MetroCluster fabric-attached configurations
a|
IPsec support for front-end host protocol (such as NFS and iSCSI) is available in MetroCluster IP and MetroCluster fabric-attached configurations.

https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html[Configure IP security (IPsec) over wire encryption]
a|
ONTAP 9.12.1
a|
ONTAP Mediator 1.4
a|
ONTAP Mediator software version 1.4 is supported in MetroCluster IP configurations.

https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service]
a|
ONTAP 9.11.1
a|
Consistency groups
a|
Consistency groups are supported in MetroCluster configurations.

https://docs.netapp.com/us-en/ontap/mediator/index.html[Install or upgrade the ONTAP Mediator service]
a|
ONTAP 9.11.1
a|
ONTAP Mediator is supported in MetroCluster IP configurations
a|
The ONTAP Mediator service can assist the MetroCluster IP configuration in performing automatic unplanned switchover by providing a physically separate repository for status information.

https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html[Configuring the ONTAP Mediator service for unplanned automatic switchover]
a|
ONTAP 9.7
a|
FabricPool mirrors on MetroCluster configurations
a|
You can set up a mirrored FabricPool on MetroCluster configurations to tier cold data to two different fault zones.

https://docs.netapp.com/us-en/ontap/fabricpool/setup-object-stores-mcc-task.html[Setting up object stores for FabricPool in a MetroCluster configuration]
a|
ONTAP 9.7
a|
SVM disaster recovery
a|
Active storage virtual machines (SVMs) in a MetroCluster configuration can be used as sources with the SnapMirror SVM disaster recovery feature.
a|
ONTAP 9.5
|===
