---
permalink: maintain/concept_where_to_find_procedures_for_metrocluster_maintenance_tasks.html
sidebar: sidebar
keywords: 
summary: 'You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.'
---
= Where to find procedures for MetroCluster maintenance tasks
:icons: font
:imagesdir: ../media/

[.lead]
You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.

NOTE: With the release of ONTAP 9.8, the MetroCluster upgrade and expansion procedures have moved to the _MetroCluster Transition, Upgrade, and Expansion Guide._

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-upgrade/home.html[MetroCluster Upgrade, Transition, and Expansion Guide]

|===
| Component| MetroCluster type (FC or IP)| Task| Procedure
a|
ONTAP software
a|
Both
a|
ONTAP software upgrade
a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html[Upgrade, revert, or downgrade]

a|
Controller module
a|
Both
a|
FRU replacement (including controller modules, PCIe cards, FC-VI card, and so on)*Note:* Moving a storage controller module or NVRAM card among the MetroCluster storage systems is not supported.

a|
https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

a|
Upgrade, transition, expansion
a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-upgrade/home.html[MetroCluster Upgrade, Transition, and Expansion Guide]

a|
Drive shelf
a|
FC
a|
Shelf addition (stack with bridges or individual shelf)
a|
link:task_hot_add_a_stack_to_existing_7500n_pair.md#[Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7500N bridges]

link:task_fb_hot_add_stack_of_shelves_and_bridges.md#[Hot-adding a stack of SAS disk shelves and bridges to a MetroCluster system]

link:task_fb_hot_add_shelf.md#[Hot-adding a SAS disk shelf to a stack of SAS disk shelves]

a|
FC
a|
Shelf removal
a|
link:task_hot_removing_storage_from_a_metrocluster_fc_configuration.md#[Hot-removing storage from a MetroCluster FC configuration]

a|
FC
a|
All other shelf maintenance procedures.The standard procedures can be used.

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Service Guide for DS460C DS224C and DS212C Disk Shelves]

a|
IP
a|
All shelf maintenance procedures.The standard procedures can be used.

If adding shelves for an unmirrored aggregate, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html[Considerations when using unmirrored aggregates]

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Service Guide for DS460C DS224C and DS212C Disk Shelves]

a|
Both
a|
Hot adding IOM12 shelves to a stack of IOM6 shelves
a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules]
a|
FC-to-SAS bridge
a|
FC
a|
Bridge replacement
a|
link:task_replacing_a_single_fc_to_sas_bridge.md#[Replacing a single FC-to-SAS bridge]

link:task_fb_consolidate_replacing_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.md#[Replacing a pair of FibreBridge 6500N bridges with 7600N or 7500N bridges]

link:task_replacing_a_single_fc_to_sas_bridge.md#[Hot-swapping a FibreBridge 7500N with a 7600N bridge]
a|
FC
a|
Firmware upgrade
a|
link:task_updating_firmware_on_a_fibrebridge_bridge_parent_topic.md#[Updating the firmware on a FibreBridge bridge]

a|
FC
a|
Replacing a failed power supply module
a|
xref:reference_fb_replacing_a_power_supply.adoc[Hot-replacing a failed power supply module]

a|
FC switch
a|
FC
a|
Switch upgrade
a|
link:task_upgrading_to_new_brocade_switches.md#[Upgrading to new Brocade FC switches]

a|
FC
a|
Switch replacement
a|
xref:task_replacing_a_brocade_fc_switch_metrocluster.adoc[Replacing a Brocade FC switch (MetroCluster)]

xref:task_replacing_a_cisco_fc_switch_metrocluster.adoc[Replacing a Cisco FC switch]

a|
FC
a|
Firmware upgrade
a|
xref:task_upgrading_or_downgrading_the_firmware_on_a_brocade_fc_switch_metrocluster.adoc[Updating firmware on a Brocade FC switch]

xref:task_upgrading_or_downgrading_the_firmware_on_a_cisco_fc_switch_metrocluster.adoc[Updating firmware on a Cisco FC switch]

a|
SAS optical cables
a|
FC
a|
Cable replacement
a|

a|
Cluster interconnect switches
a|
FC
a|
Switch replacement
a|

a|
Both
a|
Firmware upgrade
a|

|===
