---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html
sidebar: sidebar
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks
summary: 'You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.'
---
= Where to find procedures for MetroCluster maintenance tasks
:icons: font
:imagesdir: ../media/

[.lead]
You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.

NOTE: With the release of ONTAP 9.8, the MetroCluster upgrade and expansion procedures have moved to the link:../upgrade/concept_choosing_an_upgrade_method_mcc.html[MetroCluster Upgrade and Expansion] and link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP].

.Maintenance procedures for different types of MetroCluster configurations 

* If you have a MetroCluster IP configuration, review the procedures in link:concept_identifying_storage_in_a_mcc_ip_configuration.html[Maintenance procedures for MetroCluster IP configurations].
* If you have a MetroCluster FC configuration, review the procedures in link:task_modify_switch_or_bridge_ip_address_for_health_monitoring.html[Maintenance procedures for MetroCluster FC configurations].
* If you cannot find the procedure in the specific section for your configuration, review the procedures in link:task_replace_a_shelf_nondisruptively_in_a_stretch_mcc_configuration.html[Maintenance procedures for all MetroCluster configurations].

.All other maintenance procedures

The following table provides links to procedures related to MetroCluster maintenance that are not located in the three sections listed above: 

|===

h| Component h| MetroCluster type (FC or IP) h| Task h| Procedure

a|
ONTAP software
a|
Both
a|
ONTAP software upgrade
a|
https://docs.netapp.com/us-en/ontap/upgrade/index.html[Upgrade, revert, or downgrade^]

.3+a|
Controller module
.3+a|
Both
a|
FRU replacement (including controller modules, PCIe cards, FC-VI card, and so on)

NOTE: Moving a storage controller module or NVRAM card among the MetroCluster storage systems is not supported.

a|
https://docs.netapp.com/platstor/index.jsp[ONTAP Hardware Systems Documentation^]

a|
Upgrade and expansion
a| link:../upgrade/concept_choosing_an_upgrade_method_mcc.html[MetroCluster Upgrade and Expansion]

a|
Transition from FC to IP connectivity
a| link:../transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]
.5+a|
Drive shelf

a|
FC
a|
All other shelf maintenance procedures. The standard procedures can be used.

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Maintain DS460C DS224C and DS212C disk shelves^]

a|
IP
a|
All shelf maintenance procedures. The standard procedures can be used.

If adding shelves for an unmirrored aggregate, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html[Considerations when using unmirrored aggregates^]

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Maintain DS460C DS224C and DS212C disk shelves^]

a|
Both
a|
Hot adding IOM12 shelves to a stack of IOM6 shelves
a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules^]

|===

// 28 July, Gh issue 293
// BURT 1448684, 01 FEB 2022
