---
permalink: maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html
sidebar: sidebar
keywords: metrocluster, maintain, service, find, procedures, maintenance, tasks
summary: 'You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.'
---
= Where to find procedures for MetroCluster maintenance tasks
:icons: font
:imagesdir: ../media/

[.lead]
You should be sure you select the correct procedure when you perform MetroCluster hardware maintenance tasks.

NOTE: With the release of ONTAP 9.8, the MetroCluster upgrade and expansion procedures have moved to the link:https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/index.html[MetroCluster Upgrade and Expansion Guide] and link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/index.html[MetroCluster Transition Guide].

[options="header"]
|===
| Component| MetroCluster type (FC or IP)| Task| Procedure
a|
ONTAP software
a|
Both
a|
ONTAP software upgrade
a|
https://docs.netapp.com/us-en/ontap/upgrade/index.html[Upgrade, revert, or downgrade]

.2+a|
Controller module
.2+a|
Both
a|
FRU replacement (including controller modules, PCIe cards, FC-VI card, and so on)

NOTE: Moving a storage controller module or NVRAM card among the MetroCluster storage systems is not supported.

a|
https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

a|
Upgrade, transition, expansion
a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-upgrade/home.html[MetroCluster Upgrade, Transition, and Expansion Guide]

.5+a|
Drive shelf
a|
FC
a|
Shelf addition (stack with bridges or individual shelf)
a|
xref:task_hot_add_a_stack_to_exist_7500n_pair.adoc[Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7500N bridges]

xref:task_fb_hot_add_stack_of_shelves_and_bridges.adoc[Hot-adding a stack of SAS disk shelves and bridges to a MetroCluster system]

xref:task_fb_hot_add_shelf.adoc[Hot-adding a SAS disk shelf to a stack of SAS disk shelves]

a|
FC
a|
Shelf removal
a|
xref:task_hot_remove_storage_from_a_mcc_fc_configuration.adoc[Hot-removing storage from a MetroCluster FC configuration]

a|
FC
a|
All other shelf maintenance procedures.The standard procedures can be used.

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Service Guide for DS460C DS224C and DS212C Disk Shelves]

a|
IP
a|
All shelf maintenance procedures.The standard procedures can be used.

If adding shelves for an unmirrored aggregate, see http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/GUID-EA385AF8-7786-4C3C-B5AE-1B4CFD3AD2EE.html[Considerations when using unmirrored aggregates]

a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-sas3-service/home.html[Service Guide for DS460C DS224C and DS212C Disk Shelves]

a|
Both
a|
Hot adding IOM12 shelves to a stack of IOM6 shelves
a|
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules]
.3+a|
FC-to-SAS bridge
a|
FC
a|
Bridge replacement
a|
xref:task_replace_a_sle_fc_to_sas_bridge.adoc[Replacing a single FC-to-SAS bridge]

xref:task_fb_consolidate_replace_a_pair_of_fibrebridge_6500n_bridges_with_7500n_bridges.adoc[Replacing a pair of FibreBridge 6500N bridges with 7600N or 7500N bridges]

link:task_replace_a_sle_fc_to_sas_bridge.html#hot-swapping-a-fibrebridge-7500n-with-a-7600n-bridge[Hot-swapping a FibreBridge 7500N with a 7600N bridge]
a|
FC
a|
Firmware upgrade
a|
xref:task_update_firmware_on_a_fibrebridge_bridge_parent_topic.adoc[Updating the firmware on a FibreBridge bridge]

a|
FC
a|
Replacing a failed power supply module
a|
xref:reference_fb_replace_a_power_supply.adoc[Hot-replacing a failed power supply module]

.3+a|
FC switch
a|
FC
a|
Switch upgrade
a|
xref:task_upgrade_to_new_brocade_switches.adoc[Upgrading to new Brocade FC switches]

a|
FC
a|
Switch replacement
a|
xref:task_replace_a_brocade_fc_switch_mcc.adoc[Replacing a Brocade FC switch (MetroCluster)]

xref:task_replace_a_cisco_fc_switch_mcc.adoc[Replacing a Cisco FC switch]

a|
FC
a|
Firmware upgrade
a|
xref:task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.adoc[Updating firmware on a Brocade FC switch]

xref:task_upgrade_or_downgrad_the_firmware_on_a_cisco_fc_switch_mcc.adoc[Updating firmware on a Cisco FC switch]

a|
SAS optical cables
a|
FC
a|
Cable replacement
a|

.2+a|
Cluster interconnect switches
a|
FC
a|
Switch replacement
a|

a|
Both
a|
Firmware upgrade
a|

|===
