---
permalink: maintain/concept_using_fibrebridge_7600n_bridges_in_mcc_configurations.html
sidebar: sidebar
keywords: 
summary: 'The FibreBridge 7600N bridge is supported on ONTAP 9.5 and later as a replacement for the FibreBridge 7500N or 6500N bridge or when adding new storage to the MetroCluster configuration. The zoning requirements and restrictions regarding use of the bridge’s FC ports are the same as that of the FibreBridge 7500N bridge.'
---
= Support for FibreBridge 7600N bridges in MetroCluster configurations
:icons: font
:imagesdir: ../media/

[.lead]
The FibreBridge 7600N bridge is supported on ONTAP 9.5 and later as a replacement for the FibreBridge 7500N or 6500N bridge or when adding new storage to the MetroCluster configuration. The zoning requirements and restrictions regarding use of the bridge's FC ports are the same as that of the FibreBridge 7500N bridge.

https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

NOTE: FibreBridge 6500N bridges are not supported in configurations running ONTAP 9.8 and later.

|===
| Use case| Zoning changes needed?| Restrictions| Procedure
a|
Replacing a single FibreBridge 7500N bridge with a single FibreBridge 7600N bridge
a|
No
a|
The FibreBridge 7600N bridge must be configured exactly the same as the FibreBridge 7500N bridge.
a|
link:task_replacing_a_single_fc_to_sas_bridge.md#[Hot-swapping a FibreBridge 7500N with a 7600N bridge]
a|
Replacing a single FibreBridge 6500N bridge with a single FibreBridge 7600N bridge
a|
No
a|
The FibreBridge 7600N bridge must be configured exactly the same as the FibreBridge 6500N bridge.
a|
link:task_replacing_a_single_fc_to_sas_bridge.md#[Hot-swapping a FibreBridge 6500N bridge with a FibreBridge 7600N or 7500N bridge]
a|
Adding new storage through adding a new pair of FibreBridge 7600N bridges
a|
YesYou must add storage zones for each of the FC ports of the new bridges.

a|
You must have available ports on the FC switch fabric (in a fabric-attached MetroCluster configuration) or on the storage controllers (in a stretch MetroCluster configuration).Each pair of FibreBridge 7500N or 7600N bridges can support up to four stacks.

a|
link:task_fb_hot_add_stack_of_shelves_and_bridges.md#[Hot-adding a stack of SAS disk shelves and bridges to a MetroCluster system]
|===
