---
permalink: maintain/enable-console-logging-before-maintenance.html
sidebar: sidebar
keywords: metrocluster, maintain, enable, autosupport, logging, maintenance, service,ip, switch, replacement, rename
summary: 'Enable console logging on your devices before performing maintenance tasks.'
---
= Enable console logging before performing maintenance tasks
:icons: font
:imagesdir: ../media/

[.lead]
Enable console logging on your devices before performing maintenance tasks.

NetApp strongly recommends that you enable console logging on the devices that you are using and take the following actions before performing maintenance procedures:

* Leave AutoSupport enabled during maintenance.
 
* Trigger a maintenance AutoSupport message before and after maintenance to disable case creation for the duration of the maintenance activity.
+
See the Knowledge Base article link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92[How to suppress automatic case creation during scheduled maintenance windows^].
 
* Enable session logging for any CLI session. For instructions on how to enable session logging, review the "Logging Session Output" section in the Knowledge Base article link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems[How to configure PuTTY for optimal connectivity to ONTAP systems^].

// 2024 July 02, ONTAPDOC-1988