---
permalink: maintain/reference_where_to_find_additional_information_mcc_service_guide.html
sidebar: sidebar
keywords: metrocluster, maintain, service, additional, information
summary: 'You can learn more about configuring, operating, and monitoring a MetroCluster configuration in NetApp’s extensive documentation.'
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about configuring, operating, and monitoring a MetroCluster configuration in NetApp's extensive documentation.

|===

h| Information h| Subject

a|
link:../index.html[MetroCluster documentation]

a|

* All MetroCluster information

a|
https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf[NetApp MetroCluster Solution Architecture and Design^]
a|

* A technical overview of the MetroCluster configuration and operation.
* Best practices for MetroCluster configuration.
//ontap-metrocluster/issues/36
a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-stretch/concept_considerations_differences.html[Stretch MetroCluster installation and configuration]
a|

* Stretch MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html[MetroCluster IP installation and configuration]
a|

* MetroCluster IP architecture
* Cabling the MetroCluster IP configuration
* Configuring the MetroCluster in ONTAP

a|
https://www.netapp.com/support-and-training/documentation/[NetApp Documentation: Product Guides and Resources^]

a|

* Monitoring the MetroCluster configuration and performance

a|
https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/concept_overview_of_the_tiebreaker_software.html[MetroCluster Tiebreaker Software installation and configuration]
a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

|===

// BURT 1448684, 01 FEB 2022
