---
permalink: maintain/reference_fb_replace_a_power_supply.html
sidebar: sidebar
keywords: 
summary: 'When there is a change in status of a power supply module to the bridge, you can remove and install the power supply module.'
---
= Hot-replacing a failed power supply module
:icons: font
:imagesdir: ../media/

[.lead]
When there is a change in status of a power supply module to the bridge, you can remove and install the power supply module.

You can view the change in status of a power supply module through the LEDs on the bridge. You can also view the status of power supply modules via ExpressNAV GUI and the bridge CLI, via serial port, or via Telnet.

* This procedure is NDO (non-disruptive) and takes approximately 15 minutes to complete.
* You need the admin password and access to an FTP or SCP server.

NOTE: The _ATTO FibreBridge Installation and Operation Manual_ for your model bridge has more information about management interfaces.

You can access this and other content on the ATTO web site by using the link provided on the ATTO Fibrebridge Description page.
