---
permalink: maintain/reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html
sidebar: sidebar
keywords: metrocluster, maintain, service, requirements, interfaces, fibrebridge, bridges, manage, configures
summary: 'You can use the combination of a serial port, Telnet, and FTP to manage the FibreBridge bridges instead of the recommended management interfaces. Your system must meet the requirements for the applicable interface before you install the bridges.'
---
= Requirements for using other interfaces to configure and manage FibreBridge bridges
:icons: font
:imagesdir: ../media/

[.lead]
You can use the combination of a serial port, Telnet, and FTP to manage the FibreBridge bridges instead of the recommended management interfaces. Your system must meet the requirements for the applicable interface before you install the bridges.

You can use a serial port or Telnet to configure the bridge and Ethernet management 1 port, and to manage the bridge. You can use FTP to update the bridge firmware.

NOTE: The _ATTO FibreBridge Installation and Operation Manual_ for your model bridge has more information about management interfaces.

You can access this document on the ATTO web site by using the link provided on the ATTO Fibrebridge Description page.

== Serial port

When using the serial port to configure and manage a bridge, and to configure the Ethernet management 1 port, your system must meet the following requirements:

* A serial cable (which connects from the bridge serial port to a serial (COM) port on the computer you are using for setup)
+
The bridge serial port is RJ-45 and has the same pin-out as the controllers.

* A terminal emulation program such as Hyperterminal, Teraterm, or PuTTY to access the console
+
The terminal program should be capable of logging screen output to a file.

== Telnet

When using Telnet to configure and manage a bridge, your system must meet the following requirements:

* A serial cable (which connects from the bridge serial port to a serial (COM) port on the computer you are using for setup)
+
The bridge serial port is RJ-45 and has the same pin-out as the controllers.

* (Recommended) A non-default user name and password (for accessing the bridge)
* A terminal emulation program such as Hyperterminal, Teraterm, or PuTTY to access the console
+
The terminal program should be capable of logging screen output to a file.

* An IP address, subnet mask, and gateway information for the Ethernet management 1 port on each bridge

== FTP

When using FTP to update bridge firmware, your system must meet the following requirements:

* A standard Ethernet cable (which connects from the bridge Ethernet management 1 port to your network)
* (Recommended) A non-default user name and password (for accessing the bridge)
