---
permalink: maintain/task_hot_remove_storage_from_a_mcc_fc_configuration.html
sidebar: sidebar
keywords: metrocluster, maintain, service, hot, remove, storage, fc, configuration
summary: 'You can hot-remove drive shelves—physically remove shelves that have had the aggregates removed from the drives—from a MetroCluster FC configuration that is up and serving data. You can hot-remove one or more shelves from anywhere within a stack of shelves or remove a stack of shelves.'
---
= Hot-removing storage from a MetroCluster FC configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can hot-remove drive shelves--physically remove shelves that have had the aggregates removed from the drives--from a MetroCluster FC configuration that is up and serving data. You can hot-remove one or more shelves from anywhere within a stack of shelves or remove a stack of shelves.

* Your system must be a multipath HA, multipath, quad-path HA, or quad-path configuration.
* In a four-node MetroCluster FC configuration, the local HA pair cannot be in a takeover state.
* You must have already removed all aggregates from the drives in the shelves that you are removing.
+
IMPORTANT: If you attempt this procedure on non-MetroCluster FC configurations with aggregates on the shelf you are removing, you could cause the system to fail with a multidrive panic.
+
Removing aggregates involves splitting the mirrored aggregates on the shelves you are removing, and then re-creating the mirrored aggregates with another set of drives.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[Disk and aggregate management]

* You must have removed drive ownership after removing the aggregates from the drives in the shelves that you are removing.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[Disk and aggregate management]

* If you are removing one or more shelves from within a stack, you must have factored the distance to bypass the shelves that you are removing.
+
If the current cables are not long enough, you need to have longer cables available.

This task applies to the following MetroCluster FC configurations:

* Direct-attached MetroCluster FC configurations, in which the storage shelves are directly connected to the storage controllers with SAS cables
* Fabric-attached or bridge-attached MetroCluster FC configurations, in which the storage shelves are connected using FC-to-SAS bridges

.Steps
. Verify the operation of the MetroCluster configuration in ONTAP:
 .. Check whether the system is multipathed:
 +
`*node run -node _node-name_ sysconfig -a*`
 .. Check for any health alerts on both clusters:
+
`*system health alert show*`
 .. Confirm the MetroCluster configuration and that the operational mode is normal:
 +
`*metrocluster show*`
 .. Perform a MetroCluster check:
+
`*metrocluster check run*`
 .. Display the results of the MetroCluster check:
+
`*metrocluster check show*`
 .. Check for any health alerts on the switches (if present):
+
`*storage switch show*`
 .. Run Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[NetApp Downloads: Config Advisor]

 .. After running Config Advisor, review the tool's output and follow the recommendations in the output to address any issues discovered.
. Set the privilege level to advanced:
+
`*set -privilege advanced*`
. Verify that no mailbox drive is on the shelves:
`*storage failover mailbox-disk show*`
. Remove the shelf according to the steps for the relevant scenario.
+
[options="header"]
|===
| Scenario| Steps
a|
To remove an aggregate when the shelf contains either unmirrored, mirrored, or both types of aggregate...
a|

 .. Use the `*storage aggregate delete -aggregate _aggregate name_*` command to remove the aggregate.
 .. Use the standard procedure to remove ownership of all drives in that shelf, and then physically remove the shelf.
+
Follow the instructions in the _SAS Disk Shelves Service Guide_ for your shelf model to hot-remove shelves.

a|
To remove a plex from a mirrored aggregate, you need to unmirror the aggregate.
a|

 .. Identify the plex that you want to remove by using the `*run -node local sysconfig -r*` command.
+
In the following example, you can identify the plex from the line `Plex /dpg_mcc_8020_13_a1_aggr1/plex0`. In this case, the plex to specify is plex0.
+
----
dpgmcc_8020_13_a1a2::storage aggregate> run -node local sysconfig -r
*** This system has taken over dpg-mcc-8020-13-a1
Aggregate dpg_mcc_8020_13_a1_aggr1 (online, raid_dp, mirrored) (block checksums)
  Plex /dpg_mcc_8020_13_a1_aggr1/plex0 (online, normal, active, pool0)
    RAID group /dpg_mcc_8020_13_a1_aggr1/plex0/rg0 (normal, block checksums)
      RAID Disk Device                          HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------                          ------------- ---- ---- ---- ----- --------------    --------------
      dparity   mcc-cisco-8Gb-fab-2:1-1.126L16  0c    32  15  FC:B   0   SAS 15000 272000/557056000  274845/562884296
      parity    mcc-cisco-8Gb-fab-2:1-1.126L18  0c    32  17  FC:B   0   SAS 15000 272000/557056000  274845/562884296
      data      mcc-cisco-8Gb-fab-2:1-1.126L19  0c    32  18  FC:B   0   SAS 15000 272000/557056000  274845/562884296
      data      mcc-cisco-8Gb-fab-2:1-1.126L21  0c    32  20  FC:B   0   SAS 15000 272000/557056000  274845/562884296
      data      mcc-cisco-8Gb-fab-2:1-1.126L22  0c    32  21  FC:B   0   SAS 15000 272000/557056000  274845/562884296

  Plex /dpg_mcc_8020_13_a1_aggr1/plex1 (online, normal, active, pool1)
    RAID group /dpg_mcc_8020_13_a1_aggr1/plex1/rg0 (normal, block checksums)

      RAID Disk Device                          HA  SHELF BAY CHAN Pool Type  RPM  Used (MB/blks)    Phys (MB/blks)
      --------- ------                          ------------- ---- ---- ---- ----- --------------    --------------
      dparity   mcc-cisco-8Gb-fab-3:1-1.126L37  0d    34  10  FC:A   1   SAS 15000 272000/557056000  280104/573653840
      parity    mcc-cisco-8Gb-fab-3:1-1.126L14  0d    33  13  FC:A   1   SAS 15000 272000/557056000  280104/573653840
      data      mcc-cisco-8Gb-fab-3:1-1.126L41  0d    34  14  FC:A   1   SAS 15000 272000/557056000  280104/573653840
      data      mcc-cisco-8Gb-fab-3:1-1.126L15  0d    33  14  FC:A   1   SAS 15000 272000/557056000  280104/573653840
      data      mcc-cisco-8Gb-fab-3:1-1.126L45  0d    34  18  FC:A   1   SAS 15000 272000/557056000  280104/573653840
----

 .. Use the `*storage aggregate plex delete -aggregate _aggr_name_ -plex _plex_name_*` command to remove the plex.
+
plex defines the plex name, such as `plex3` or `plex6`.

 .. Use the standard procedure to remove ownership of all drives in that shelf, and then physically remove the shelf.
+
Follow the instructions in the _SAS Disk Shelves Service Guide_ for your shelf model to hot-remove shelves.

+
|===
