---
permalink: maintain/task_change_an_fc_switch.html
sidebar: sidebar
keywords: metrocluster, maintain, service, change, fc, switch
summary: "You might need to to change the vendor of an FC switch (Cisco to Brocade or vice versa), change the switch model, or both."
---
= Change the vendor or model of FC switches

:icons: font
:imagesdir: ../media/

[.lead]
You might need to to change the vendor for FC switches from Cisco to Brocade or vice versa, change the switch model, or change both.  

.About this task

* This procedure applies when you are using NetApp validated switches.
* You must perform the steps in this procedure on one Fabric at a time, for both Fabrics in the configuration. 

.Steps

. [[step_1,Step 1]]Check the health of the configuration.
 .. Check that the MetroCluster is configured and in normal mode on each cluster: `*metrocluster show*`
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----

 .. Check that mirroring is enabled on each node: `*metrocluster node show*`
+
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----

 .. Check that the MetroCluster components are healthy: `*metrocluster check run*`
+
----
cluster_A::> metrocluster check run

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----

 .. Check that there are no health alerts: `*system health alert show*`
. Configure the new switches before installation.
+
Follow the steps in link:../install-fc/concept-configure-fc-switches.html[Configure the FC switches].


. Disconnect the connections from the old switches by removing the connections in the following order:
+
.. Disconnect the MetroCluster FC and FCVI interfaces.
.. Disconnect the ATTO FibreBridge bridges.
.. Disconnect the MetroCluster ISLs.

. Power off the old switches, remove the cables, and physically replace the old switches with the new switch.


. Cable the switches in the following order: 
+
You must follow the steps in link:../install-fc/task_configure_the_mcc_hardware_components_fabric.html[Cabling a fabric-attached MetroCluster configuration]. 
+
.. Cable the ISLs to the remote site.
.. Cable the ATTO FibreBridge bridges.
..  Cable the MetroCluster FC and FCVI interfaces.

. Power up the switches.

. Verify that the MetroCluster configuration is healthy by repeating <<Step 1>>.

. Repeat Step 1 to Step 7 for the second Fabric in the configuration. 

// 2024 Jul 08, ONTAPDOC-2160
// 2024 Mar 07, ONTAPDOC-1722
// 2023 May 18, BURT 1491844