---
permalink: maintain/task_hot_add_a_stack_to_exist_7500n_pair.html
sidebar: sidebar
keywords: metrocluster, maintain, service, hot, add, stack, sas, disk, shelves, existing, pair, fibrebridge, bridge
summary: 'You can hot-add a stack of SAS disk shelves to an existing pair of FibreBridge 7600N or 7500N bridges that have available ports.'
---
= Hot-adding a stack of SAS disk shelves to an existing pair of FibreBridge 7600N or 7500N bridges
:icons: font
:imagesdir: ../media/

[.lead]
You can hot-add a stack of SAS disk shelves to an existing pair of FibreBridge 7600N or 7500N bridges that have available ports.

.Before you begin

* You must have downloaded the latest disk and disk shelf firmware.
* All of the disk shelves in the MetroCluster configuration (existing shelves) must be running the same firmware version. If one or more of the disks or shelves are not running the latest firmware version, update the firmware before attaching the new disks or shelves. 
//GH issue #99 26/01/2022
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[NetApp Downloads: Disk Drive Firmware^]
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware[NetApp Downloads: Disk Shelf Firmware^]

* The FibreBridge 7600N or 7500N bridges must be connected and have available SAS ports.

.About this task

This procedure is written with the assumption that you are using the recommended bridge management interfaces: the ATTO ExpressNAV GUI and the ATTO QuickNAV utility.

You can use the ATTO ExpressNAV GUI to configure and manage a bridge, and to update the bridge firmware. You can use the ATTO QuickNAV utility to configure the bridge Ethernet management 1 port.

You can use other management interfaces, if required. These options include using a serial port or Telnet to configure and manage a bridge and to configure the Ethernet management 1 port, and using FTP to update the bridge firmware. If you choose any of these management interfaces, you must meet the applicable requirements in link:reference_requirements_for_using_other_interfaces_to_configure_and_manage_fibrebridge_bridges.html[Other bridge management interfaces].

IMPORTANT: If you insert a SAS cable into the wrong port, when you remove the cable from a SAS port, you must wait at least 120 seconds before plugging the cable into a different SAS port. If you fail to do so, the system will not recognize that the cable has been moved to another port.

.Steps
. Properly ground yourself.
. From the console of either controller, verify that your system has disk autoassignment enabled:
+
`storage disk option show`
+
The Auto Assign column indicates whether disk autoassignment is enabled.
+
----

Node        BKg. FW. Upd.  Auto Copy   Auto Assign  Auto Assign Policy
----------  -------------  ----------  -----------  ------------------
node_A_1             on           on           on           default
node_A_2             on           on           on           default
2 entries were displayed.
----

. On each bridge in the pair, enable the SAS port that will connect to the new stack:
+
`SASPortEnable _port-letter_`
+
The same SAS port (B, C, or D) must be used on both bridges.

. Save the configuration and reboot each bridge:
+
`SaveConfiguration Restart`
. Cable the disk shelves to the bridges:
 .. Daisy-chain the disk shelves in each stack.
+
The _Installation and Service Guide_ for your disk shelf model provides detailed information about daisy-chaining disk shelves.

 .. For each stack of disk shelves, cable IOM A of the first shelf to SAS port A on FibreBridge A, and then cable IOM B of the last shelf to SAS port A on FibreBridge B
+
link:../install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
+
link:../install-stretch/concept_considerations_differences.html[Stretch MetroCluster installation and configuration]
+
Each bridge has one path to its stack of disk shelves; bridge A connects to the A-side of the stack through the first shelf, and bridge B connects to the B-side of the stack through the last shelf.
+
NOTE: The bridge SAS port B is disabled.
. Verify that each bridge can detect all of the disk drives and disk shelves to which the bridge is connected.
+

[cols="30,70"]
|===

h| If you are using the... h| Then...

a|
ATTO ExpressNAV GUI
a|

 .. In a supported web browser, enter the IP address of a bridge in the browser box.
+
You are brought to the ATTO FibreBridge home page, which has a link.

 .. Click the link, and then enter your user name and the password that you designated when you configured the bridge.
+
The ATTO FibreBridge status page appears with a menu to the left.

 .. Click *Advanced* in the menu.
 .. View the connected devices:
+
`sastargets`
 .. Click *Submit*.

a|
Serial port connection
a|
View the connected devices:

`sastargets`
|===
+
The output shows the devices (disks and disk shelves) to which the bridge is connected. The output lines are sequentially numbered so that you can quickly count the devices.
+
NOTE: If the text "`response truncated`" appears at the beginning of the output, you can use Telnet to connect to the bridge, and then view all of the output by using the `sastargets` command.
+

The following output shows that 10 disks are connected:
+
----
Tgt VendorID ProductID        Type        SerialNumber
  0 NETAPP   X410_S15K6288A15 DISK        3QP1CLE300009940UHJV
  1 NETAPP   X410_S15K6288A15 DISK        3QP1ELF600009940V1BV
  2 NETAPP   X410_S15K6288A15 DISK        3QP1G3EW00009940U2M0
  3 NETAPP   X410_S15K6288A15 DISK        3QP1EWMP00009940U1X5
  4 NETAPP   X410_S15K6288A15 DISK        3QP1FZLE00009940G8YU
  5 NETAPP   X410_S15K6288A15 DISK        3QP1FZLF00009940TZKZ
  6 NETAPP   X410_S15K6288A15 DISK        3QP1CEB400009939MGXL
  7 NETAPP   X410_S15K6288A15 DISK        3QP1G7A900009939FNTT
  8 NETAPP   X410_S15K6288A15 DISK        3QP1FY0T00009940G8PA
  9 NETAPP   X410_S15K6288A15 DISK        3QP1FXW600009940VERQ
----

. Verify that the command output shows that the bridge is connected to all of the appropriate disks and disk shelves in the stack.
+
[cols="30,70"]
|===

h| If the output is... h| Then...

a|
Correct
a|
Repeat the previous step for each remaining bridge.
a|
Not correct
a|

 .. Check for loose SAS cables or correct the SAS cabling by repeating the step to cable the disk shelves to the bridges.
 .. Repeat the previous step for each remaining bridge.

|===

. Update the disk drive firmware to the most current version from the system console:
+
`disk_fw_update`
+
You must run this command on both controllers.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[NetApp Downloads: Disk Drive Firmware^]

. Update the disk shelf firmware to the most current version by using the instructions for the downloaded firmware.
+
You can run the commands in the procedure from the system console of either controller.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware[NetApp Downloads: Disk Shelf Firmware^]

. If your system does not have disk autoassignment enabled, assign disk drive ownership.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html[Disk and aggregate management^]
+
NOTE: If you are splitting the ownership of a single stack of disk shelves among multiple controllers, you must disable disk autoassignment (`storage disk option modify -autoassign off *` from both nodes in the cluster) before assigning disk ownership; otherwise, when you assign any single disk drive, the remaining disk drives might be automatically assigned to the same controller and pool.
+
NOTE: You must not add disk drives to aggregates or volumes until after the disk drive firmware and disk shelf firmware have been updated and the verification steps in this task have been completed.

. Verify the operation of the MetroCluster configuration in ONTAP:
 .. Check whether the system is multipathed:
+
`node run -node _node-name_ sysconfig -a`
 .. Check for any health alerts on both clusters:
+
`system health alert show`
 .. Confirm the MetroCluster configuration and that the operational mode is normal:
+
`metrocluster show`
 .. Perform a MetroCluster check:
+
`metrocluster check run`
 .. Display the results of the MetroCluster check:
+
`metrocluster check show`
 .. Check for any health alerts on the bridges after adding the new stacks:
+
`storage bridge show`
 .. Run Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[NetApp Downloads: Config Advisor^]

 .. After running Config Advisor, review the tool's output and follow the recommendations in the output to address any issues discovered.
. If applicable, repeat this procedure for the partner site.

// BURT 1498367, 20 Jun 2023
// BURT 1448684, 17 JAN 2022
