---
permalink: maintain/task_replacing_a_shelf_nondisruptively_in_a_stretch_metrocluster_configuration.html
sidebar: sidebar
keywords: 
summary: 'You can replace disk shelves without disruption in a stretch MetroCluster configuration with a fully populated disk shelf or a disk shelf chassis and transfer components from the shelf you are removing.'
---
= Replacing a shelf nondisruptively in a stretch MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
You can replace disk shelves without disruption in a stretch MetroCluster configuration with a fully populated disk shelf or a disk shelf chassis and transfer components from the shelf you are removing.

The disk shelf model you are installing must meet the storage system requirements specified in the _Hardware Universe_, which includes supported shelf models, supported disk drive types, the maximum number of disk shelves in a stack, and supported ONTAP versions.

https://hwu.netapp.com[NetApp Hardware Universe]

. Properly ground yourself.
. Identify all aggregates and volumes that have disks from the loop that contains the shelf you are replacing and make note of the affected plex name.
+
Either node might contain disks from the loop of the affected shelf and host aggregates or host volumes.

. Choose one of the following two options based on the replacement scenario you are planning.
 ** If you are replacing a complete disk shelf, including the shelf chassis, disks, and I/O modules (IOM), take the corresponding action as described in the table below:
|===
| Scenario| Action
a|
*The affected plex contains fewer disks from the affected shelf.*
a|
Replace the disks one-by-one on the affected shelf with spares from another shelf.     *Note:* You can take the plex offline after completing the disk replacement.

a|
*The affected plex contains more disks than are in the affected shelf.*
a|
Move the plex offline and then delete the plex.
a|
*The affected plex has any disk from the affected shelf.*
a|
Move the plex offline but do not delete it.
|===
 ** If you are replacing only the disk shelf chassis and no other components, perform the following steps:

 .. Offline the affected plexes from the controller where they are hosted: `aggregate offline`
 .. Verify that the plexes are offline: `aggregate status -r`
. Identify the controller SAS ports to which the affected shelf loop is connected and disable the SAS ports on both site controllers:``storage port disable -node node_name -port SAS_port``
+
The affected shelf loop is connected to both sites.

. Wait for ONTAP to recognize that the disk is missing. You can use the following commands to verify that the disk is missing:``sysconfig -a`` or `sysconfig -r`.
. Turn off the power switch on the disk shelf.
. Unplug all power cords from the disk shelf.
. Make a record of the ports from which you unplug the cables so that you can cable the new disk shelf in the same way.
. Unplug and remove the cables connecting the disk shelf to the other disk shelves or the storage system.
. Remove the disk shelf from the rack.
+
To make the disk shelf lighter and easier to maneuver, remove the power supplies and IOM. If you will be installing a disk shelf chassis, also remove the disk drives or carriers. Otherwise, avoid removing disk drives or carriers if possible because excessive handling can cause internal drive damage.

. Install and secure the replacement disk shelf onto the support brackets and rack.
. If you installed a disk shelf chassis, reinstall power supplies and IOM.
. Reconfigure the stack of disk shelves by connecting all cables to the replacement disk shelf ports exactly as they were configured on the disk shelf that you removed.
. Turn on the power to the replacement disk shelf and wait for the disk drives to spin up.
. Change the disk shelf ID to a unique ID from 0 through 98.
. Enable any SAS ports that you previously disabled and then wait for ONTAP to recognize that the disks are inserted.
+
You can use the following commands to verify that the disks are inserted: `sysconfig -a` or `sysconfig -r` .

. If you are replacing the complete disk shelf (disk shelf chassis, disks, IOM), perform the following steps:
+
NOTE: If you are replacing only the disk shelf chassis and no other components, go to Step 19.

 .. Use the `storage disk option modify -autoassign` command to determine whether disk auto assignment is enabled (on).
+
Disk assignment will occur automatically.

 .. If disk auto assignment is not enabled, assign disk ownership manually.

. Move the plexes back online: `aggregate online plex name`
. Recreate any plexes that were deleted by mirroring the aggregate.
. Monitor the plexes as they begin resynchronizing: `aggregate status -r <aggregate name>`
. Verify that the storage system is functioning as expected: `system health alert show`
