---
permalink: maintain/task-change-isl-properties-iod-ood-ciso-fc.html
sidebar: sidebar
keywords: metrocluster, maintain, service, change, isl, properties, isl, ports, iod, ood,configuration, cisco, switch
summary: 'You can add Inter-Switch Links (ISLs), change ISL speed, and reconfigure in-order delivery (IOD) or out of-order delivery (OOD) settings on a Cisco FC switch.'
---
= Change ISL properties and the IOD/OOD configuration on a Cisco FC switch
:icons: font
:imagesdir: ../media/

[.lead]
You can add Inter-Switch Links (ISLs), change ISL speed, and reconfigure in-order delivery (IOD) or out of-order delivery (OOD) settings on a Cisco FC switch.

== Add ISLs to a Cisco FC switch

You might need add ISLs to a switch if you are adding or upgrading hardware, for example, adding or upgrading to faster controllers or faster switches.

.About this task

Perform these steps on both switches in the fabric to verify ISL connectivity.

.Steps

. Disable the ISL ports of the ISLs to be added on both switches in the fabric:
+
`FC_switch_A_1#config t`
+
Enter the following configuration commands, one per line. Enter CTRL-Z after you have entered all of the configuration commands.
+
----

	FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----

. Insert SFPs into the ports you are adding as ISL ports, and cable them according to link:..install-fc/task_configure_the_mcc_hardware_components_fabric.html[Cable a fabric-attached MetroCluster configuration].
+
Verify that these ports are listed in the cabling documentation for the switch model that you are adding them to.

. Configure the ISL ports by following the steps in link:../install-fc/task_cable_the_isl_between_the_mcc_sites_fabric_config.html[Cabling the ISLs between MetroCluster sites].
. Enable all ISL ports (if not enabled) on both switches in the fabric:
+
`FC_switch_A_1# config t`
+
Enter the following configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----

. Verify that the ISLs are established between both switches:
+
`show topology isl`

. Repeat the procedure on the second fabric:
+
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

== Change ISL port speeds on a Cisco FC switch

You can change the speed of ISL ports on a switch to improve the quality of the ISL, for example, lowering the speed on ISLs traveling a greater distance.

.About this task 

Perform these steps on both switches in the fabric to verify ISL connectivity.

.Steps 

. Disable the ISL ports for the ISLs that you want to change the speed for on both switches in the fabric:
+
`FC_switch_A_1# config t`
+
Enter the following configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----

. Change the speed of the ISL ports on both switches in the fabric:
+
`FC_switch_A_1# config t`
+
Enter the following configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+
NOTE: Speeds for the ports are 16 = 16,000 Gbps, 8 = 8,000 Gbps, and 4 = 4,000 Gbps.
+
Verify that the ISL ports for your switch are listed in link:../install-fc/index.html[Install a fabric-attached MetroCluster configuration].

. Enable all ISL ports (if not enabled) on both switches in the fabric:
+
`FC_switch_A_1# config t`
+
Enter the following configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----

. Verify that the ISLs are established between both switches:
+
`show topology isl`
+
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

. Repeat the procedure for the second switch fabric.

== Reconfigure the VSAN to guarantee IOD or OOD of frames

The standard IOD settings are recommended. You should only reconfigure OOD if necessary.

=== Reconfigure IOD 

Perform the following step to reconfigure IOD of frames.

.Steps

. Enter configuration mode:
+
`conf t`

. Enable the in-order guarantee of exchanges for the VSAN:
+
`in-order-guarantee vsan <vsan-ID>`
+
IMPORTANT: For FC-VI VSANs (FCVI_1_10 and FCVI_2_30), you must enable in-order guarantee of frames and exchanges only on VSAN 10.


.. Enable load balancing for the VSAN:
+
`vsan <vsan-ID> loadbalancing src-dst-id`

.. Exit configuration mode:
+
`end`

.. Copy the running-config to the startup-config:
+
`copy running-config startup-config`
+
The commands to configure IOD of frames on FC_switch_A_1:
+
----
FC_switch_A_1# config t
FC_switch_A_1(config)# in-order-guarantee vsan 10
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# vsan 10 loadbalancing src-dst-id
FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1# copy running-config startup-config
----
+
The commands to configure IOD of frames on FC_switch_B_1:
+
----
FC_switch_B_1# config t
FC_switch_B_1(config)# in-order-guarantee vsan 10
FC_switch_B_1(config)# vsan database
FC_switch_B_1(config-vsan-db)# vsan 10 loadbalancing src-dst-id
FC_switch_B_1(config-vsan-db)# end
FC_switch_B_1# copy running-config startup-config
----

=== Reconfigure OOD 

The following steps must be performed to reconfigure OOD of frames:

.Steps

. Enter configuration mode:
+
`conf t`

. Disable the in-order guarantee of exchanges for the VSAN:
+
`no in-order-guarantee vsan <vsan-ID>`

. Enable load balancing for the VSAN:
+
`vsan <vsan-ID> loadbalancing src-dst-id`

. Exit configuration mode:
+
`end`

. Copy the running-config to the startup-config:
+
`copy running-config startup-config`
+
The commands to configure OOD of frames on FC_switch_A_1:
+
----
FC_switch_A_1# config t
FC_switch_A_1(config)# no in-order-guarantee vsan 10
FC_switch_A_1(config)# vsan database
FC_switch_A_1(config-vsan-db)# vsan 10 loadbalancing src-dst-id
FC_switch_A_1(config-vsan-db)# end
FC_switch_A_1# copy running-config startup-config
----
+
The commands to configure OOD of frames on FC_switch_B_1:
+
----
FC_switch_B_1# config t
FC_switch_B_1(config)# no in-order-guarantee vsan 10
FC_switch_B_1(config)# vsan database
FC_switch_B_1(config-vsan-db)# vsan 10 loadbalancing src-dst-id
FC_switch_B_1(config-vsan-db)# end
FC_switch_B_1# copy running-config startup-config
----
+
NOTE: When configuring ONTAP on the controller modules, OOD must be explicitly configured on each controller module in the MetroCluster configuration.
+
link:../install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-in-order-delivery-or-out-of-order-delivery-of-frames-on-ontap-software[Learn about configuring IOD or OOD of frames on ONTAP software].

// 2024 May 03, ONTAPDOC-1950