---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html
sidebar: sidebar
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches
summary: 'You might need to upgrade an RCF file on a MetroCluster IP switch. For example, an ONTAP upgrade or a switch firmware upgrade both require a new RCF file.'
---
= Upgrade RCF files on MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade an RCF file on a MetroCluster IP switch. For example, if the RCF file version that you are running on the switches is not supported by the ONTAP version, the switch firmware version, or both.

== Verify that the RCF file is supported

If you are changing the ONTAP version or the switch firmware version, you should verify that you have an RCF file that is supported for that version. If you use the RCF generator, the correct RCF file will be generated for you.

.Steps

. Use the following commands from the switches to verify the version of the RCF file:
+
[cols="30,70"]
|===

h| From this switch...   h| Issue this command...

a| Broadcom switch
a| `(IP_switch_A_1) # show clibanner`

a| Cisco switch
a| `IP_switch_A_1# show banner motd`

|===

+
For either switch, find the line in the output that indicates the version of the RCF file. For example, the following output is from a Cisco switch, which indicates the RCF file version is "`v1.80`".
+
....
Filename : NX3232_v1.80_Switch-A2.txt
....

. To check which files are supported for a specific ONTAP version, switch, and platform, use the RcfFileGenerator.  If you can generate the RCF file for the configuration that you have or that you want to upgrade to, then it is supported.

. To verify that the switch firmware is supported, refer to the following:
+
* https://hwu.netapp.com[Hardware Universe]
* https://imt.netapp.com/matrix/[NetApp Interoperability Matrix^]

== Upgrade RCF files

If you are installing new switch firmware, you must install the switch firmware before upgrading the RCF file.

.About this task

* This procedure disrupts traffic on the switch where the RCF file is upgraded. Traffic will resume once the new RCF file is applied.

* Perform the steps on one switch at a time, in the following order: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.

* link:enable-console-logging-before-maintenance.html[Enable console logging] before performing this task.

// 2024 Aug 13, ONTAPDOC-1988

.Steps
. Verify the health of the configuration.
.. Verify that the MetroCluster components are healthy:
+
`metrocluster check run`
+
----
cluster_A::*> metrocluster check run

----

+
The operation runs in the background.

.. After the `metrocluster check run` operation completes, run `metrocluster check show` to view the results.
+
After approximately five minutes, the following results are displayed:
+
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----

.. Check the status of the running MetroCluster check operation:
+
`metrocluster operation history show -job-id 38`
.. Verify that there are no health alerts:
+
`system health alert show`
. Prepare the IP switches for the application of the new RCF files.
+
Follow the steps for your switch vendor:
+
* link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults[Reset the Broadcom IP switch to factory defaults]
+
* link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults[Reset the Cisco IP switch to factory defaults]
+
* link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults[Reset the NVIDIA IP SN2100 switch to factory defaults]

. Download and install the IP RCF file, depending on your switch vendor.
+
* link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files[Download and install the Broadcom IP RCF files]
+
* link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files[Download and install the Cisco IP RCF files]
+
* link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files[Download and install the NVIDIA IP RCF files]
+
NOTE: If you have an L2 shared or L3 network configuration, you might need to adjust the ISL ports on the intermediate/customer switches. The switchport mode might change from 'access' to 'trunk' mode. Only proceed to upgrade the second switch pair (A_2, B_2) if the network connectivity between switches A_1 and B_1 is fully operational and the network is healthy.

// 2024 Feb 22, GH issue 366
// 2023 Feb 21, GH issue 361
// 2023 Nov 28, ONTAPDOC-1493
// GitHub issue 135, July 4th 2022
// GH issue 213, 2022-Oct-06
