---
permalink: maintain/task_power_off_an_entire_mcc_ip_configuration.html
sidebar: sidebar
keywords: 
summary: 'You must power off the entire MetroCluster IP configuration and all of the equipment before maintenance or relocation can begin.'
---
= Powering off an entire MetroCluster IP configuration
:icons: font
:imagesdir: ../media/

[.lead]
You must power off the entire MetroCluster IP configuration and all of the equipment before maintenance or relocation can begin.

NOTE: Starting with ONTAP 9.8, the `storage switch` command is replaced with `system switch`. The following steps show the `storage switch` command, but if you are running ONTAP 9.8 or later, the `system switch` command is preferred.

. Verify the MetroCluster configuration from both sites in the MetroCluster configuration.
 .. Confirm that the MetroCluster configuration and operational mode are normal.`metrocluster show`
 .. Run the following command: `metrocluster interconnect show`
 .. Confirm connectivity to the disks by entering the following command on any one of the MetroCluster nodes: `run local sysconfig -v`
 .. Run the following command: `storage port show`
 .. Run the following command: `storage switch show`
 .. Run the following command: `network interface show`
 .. Run the following command: `network port show`
 .. Run the following command: `network device-discovery show`
 .. Perform a MetroCluster check: `metrocluster check run`
 .. Display the results of the MetroCluster check: `metrocluster check show`
 .. Run the following command: `metrocluster configuration-settings interface show`
. If necessary, disable AUSO by modifying the AUSO Failure Domain to `auso-disabled`
+
----
cluster_A_site_A::*>metrocluster modify -auto-switchover-failure-domain auso-disabled
----
+
NOTE: In a MetroCluster IP configuration, the AUSO Failure Domain is already set to 'auso-disabled' unless the configuration is configured with ONTAP Mediator.

. Verify the change using the command `metrocluster operation show`
+
----

	cluster_A_site_A::*> metrocluster operation show
       Operation: modify
           State: successful
      Start Time: 4/25/2020 20:20:36
        End Time: 4/25/2020 20:20:36
          Errors: -
----

. Halt the nodes: `halt`
+
----
system node halt -node node1_SiteA -inhibit-takeover true -ignore-quorum-warnings true
----

. Power off the following equipment at the site:
 ** Storage controllers
 ** MetroCluster IP switches
 ** Storage shelves
. Wait for thirty minutes and then power on all the controllers.
. After the controllers are powered on, verify the MetroCluster configuration from both sites.
+
To verify the configuration, repeat step 1.

. Perform power cycle checks.
 .. Verify that all sync-source SVMs are online: `vserver show`
 .. Start any sync-source SVMs that are not online: `vserver start`
