---
permalink: maintain/task_replace_a_brocade_fc_switch_mcc.html
sidebar: sidebar
keywords: metrocluster, maintain, service, replace, brocade, fc, switch
summary: 'You must use this Brocade-specific procedure to replace a failed switch.'
---
= Replacing a Brocade FC switch
:icons: font
:imagesdir: ../media/

[.lead]
You must use this Brocade-specific procedure to replace a failed switch.

.About this task

You need the admin password and access to an FTP or SCP server.

link:enable-console-logging-before-maintenance.html[Enable console logging] before performing this task.

// 2024 Aug 13, ONTAPDOC-1988

In the following examples, FC_switch_A_1 is the healthy switch and FC_switch_B_1 is the impaired switch. The switch port usage in the examples is shown in the following table:

|===

h| Port connections h| Ports

a|
FC-VI connections
a|
0, 3
a|
HBA connections
a|
1, 2, 4, 5
a|
FC-to-SAS bridge connections
a|
6, 7
a|
ISL connections
a|
10, 11
|===

The examples show two FC-to-SAS bridges. If you have more, you must disable and subsequently enable the additional ports.

NOTE: This procedure is nondisruptive and takes approximately two hours to complete.

Your switch port usage should follow the recommended assignments.

* link:concept_port_assignments_for_fc_switches_when_using_ontap_9_1_and_later.html[Port assignments for FC switches when using ONTAP 9.1 and later]

.Steps

. Fence off the switch undergoing replacement by disabling the ISL ports on the healthy switch in the fabric and the FC-VI and HBA ports on the impaired switch (if the impaired switch is still operating):
.. Disable the ISL ports on the healthy switch for each port:
+
`portcfgpersistentdisable _port-number_`
+
----
FC_switch_A_1:admin> portcfgpersistentdisable 10
FC_switch_A_1:admin> portcfgpersistentdisable 11
----

.. If the impaired switch is still operational, disable the FC-VI and HBA ports on that switch for each port:
+
`portcfgpersistentdisable _port-number_`
+
----
FC_switch_B_1:admin> portcfgpersistentdisable 0
FC_switch_B_1:admin> portcfgpersistentdisable 1
FC_switch_B_1:admin> portcfgpersistentdisable 2
FC_switch_B_1:admin> portcfgpersistentdisable 3
FC_switch_B_1:admin> portcfgpersistentdisable 4
FC_switch_B_1:admin> portcfgpersistentdisable 5
----

. If the impaired switch is still operational, gather the output from the `switchshow` command.
+
----
FC_switch_B_1:admin> switchshow
    switchName: FC_switch_B_1
    switchType: 71.2
    switchState:Online
    switchMode: Native
    switchRole: Subordinate
    switchDomain:       2
    switchId:   fffc01
    switchWwn:  10:00:00:05:33:86:89:cb
    zoning:             OFF
    switchBeacon:       OFF
----

. Boot and preconfigure the new switch prior to physically installing it:
.. Power up the new switch and let it boot up.
.. Check the firmware version on the switch to confirm that it matches the version of the other FC switches:
+
`firmwareShow`
.. Configure the new switch by following the Brocade procedures in link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/concept-configure-fc-switches.html[Configure the FC switches].
+
NOTE: At this point, the new switch is not cabled to the MetroCluster configuration.

.. Disable the FC-VI, HBA, and storage ports on the new switch, and the ports connected to the FC-SAS bridges.
+
----
FC_switch_B_1:admin> portcfgpersistentdisable 0
FC_switch_B_1:admin> portcfgpersistentdisable 1
FC_switch_B_1:admin> portcfgpersistentdisable 2
FC_switch_B_1:admin> portcfgpersistentdisable 3
FC_switch_B_1:admin> portcfgpersistentdisable 4
FC_switch_B_1:admin> portcfgpersistentdisable 5

FC_switch_B_1:admin> portcfgpersistentdisable 6
FC_switch_B_1:admin> portcfgpersistentdisable 7
----
. Physically replace the switch:
.. Power off the impaired FC switch.
.. Power off the replacement FC switch.
.. Uncable and remove the impaired switch, carefully noting which cables connected to which ports.
.. Install the replacement switch in the rack.
.. Cable the replacement switch exactly as the old switch was cabled.
.. Power on the new FC switch.
. If you want to enable ISL encryption, complete the applicable tasks in  link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration].
+
If you are enabling ISL encryption, you need to complete the following tasks:

 ** Disable the virtual fabric
 ** Set the payload
 ** Set the authentication policy
 ** Enable ISL encryption on Brocade switches

. Complete the configuration of the new switch:
.. Enable the ISLs:
+
`portcfgpersistentenable _port-number_`
+
----
FC_switch_B_1:admin> portcfgpersistentenable 10
FC_switch_B_1:admin> portcfgpersistentenable 11
----

.. Verify the zoning configuration:
+
`cfg show`
.. On the replacement switch (FC_switch_B_1 in the example), verify that the ISLs are online:
+
`switchshow`
+
----
FC_switch_B_1:admin> switchshow
switchName: FC_switch_B_1
switchType: 71.2
switchState:Online
switchMode: Native
switchRole: Principal
switchDomain:       4
switchId:   fffc03
switchWwn:  10:00:00:05:33:8c:2e:9a
zoning:             OFF
switchBeacon:       OFF

Index Port Address Media Speed State  Proto
==============================================
...
10   10    030A00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1"
11   11    030B00 id   16G     Online  FC E-Port 10:00:00:05:33:86:89:cb "FC_switch_A_1" (downstream)
...
----

.. Enable the storage ports that connect to the FC bridges.
+
----
FC_switch_B_1:admin> portcfgpersistentenable 6
FC_switch_B_1:admin> portcfgpersistentenable 7
----

.. Enable the storage, HBA, and FC-VI ports.
+
The following example shows the commands used to enable the ports connecting HBA adapters:
+
----
FC_switch_B_1:admin> portcfgpersistentenable 1
FC_switch_B_1:admin> portcfgpersistentenable 2
FC_switch_B_1:admin> portcfgpersistentenable 4
FC_switch_B_1:admin> portcfgpersistentenable 5
----
+
The following example shows the commands used to enable the ports connecting the FC-VI adapters:
+
----
FC_switch_B_1:admin> portcfgpersistentenable 0
FC_switch_B_1:admin> portcfgpersistentenable 3
----
. Verify that the ports are online:
+
`switchshow`
. Verify the operation of the MetroCluster configuration in ONTAP:
.. Check whether the system is multipathed:
+
`node run -node _node-name_ sysconfig -a`
.. Check for any health alerts on both clusters:
+
`system health alert show`
.. Confirm the MetroCluster configuration and that the operational mode is normal:
+
`metrocluster show`
.. Perform a MetroCluster check:
+
`metrocluster check run`
.. Display the results of the MetroCluster check:
+
`metrocluster check show`
.. Check for any health alerts on the switches (if present):
+
`storage switch show`
.. Run https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[Config Advisor].

.. After running Config Advisor, review the tool's output and follow the recommendations in the output to address any issues discovered.

// 2025 Jan 29, MCC-2587
// 2023 Feb 14, GH issue 342
//BURT 1448684, 02 FEB 2022
