---
permalink: maintain/task_upgrading_rcf_files_on_mcc_ip_switches.html
sidebar: sidebar
keywords: 
summary: 'You might need to upgrade an RCF file on a MetroCluster IP switch. For example, an ONTAP upgrade or a switch firmware upgrade both require a new RCF file.'
---
= Upgrading RCF files on MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade an RCF file on a MetroCluster IP switch. For example, an ONTAP upgrade or a switch firmware upgrade both require a new RCF file.

If you are installing new switch firmware, you must install the switch firmware before upgrading the RCF file.

This procedure disrupts traffic on the switch where the RCF file is upgraded. Traffic will resume once the new RCF file is applied.

. Verify the health of the configuration.
 .. Verify that the MetroCluster components are healthy: `metrocluster check run`
+
----
dpgqa-mcc-funct-8040-0403_siteA::*> metrocluster check run

----
----
+
The operation runs in the background.

 .. After the `metrocluster check run` operation completes, run `metrocluster check show` to view the results.
+
After approximately five minutes, the following results are displayed:
+
----
-----------
dpgqa-mcc-funct-8040-0403_siteA::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----

 .. To check the status of the running MetroCluster check operation, use the command: `metrocluster operation history show -job-id 38`
 .. Verify that there are no health alerts: `system health alert show`
. Prepare the IP switches for the application of the new RCF files.
+
Follow the steps in the section for your switch vendor from the _MetroCluster IP Installation and Configuration guide_.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html[MetroCluster IP installation and configuration]

 ** _Resetting the Broadcom IP switch to factory defaults_
 ** _Resetting the Cisco IP switch to factory defaults_

. Download and install the IP RCF file depending on your switch vendor.
+
Follow the steps in the section for your switch vendor from the _MetroCluster IP Installation and Configuration guide_.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html[MetroCluster IP installation and configuration]

 ** _Downloading and installing the Broadcom IP RCF files_
 ** _Downloading and installing the Cisco IP RCF files_


 .. Update the switches in the following order: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.
