---
permalink: maintain/task_upgrade_rcf_files_on_mcc_ip_switches.html
sidebar: sidebar
keywords: metrocluster, maintain, service, upgrade, rcf, files, ip, switches
summary: 'You might need to upgrade an RCF file on a MetroCluster IP switch. For example, an ONTAP upgrade or a switch firmware upgrade both require a new RCF file.'
---
= Upgrade RCF files on MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade a reference configuration file (RCF) file on a MetroCluster IP switch. For example, if the RCF version that you are running on the switches is not supported by the ONTAP version, the switch firmware version, or both.

.Before you begin

* If you are installing new switch firmware, you must install the switch firmware before upgrading the RCF file.
* Before you upgrade the RCF, link:task_upgrade_firmware_on_mcc_ip_switches.html[verify that the RCF is supported].
* link:enable-console-logging-before-maintenance.html[Enable console logging] before performing this task.

.About this task

* This procedure disrupts traffic on the switch where the RCF file is upgraded. Traffic resumes when the new RCF file is applied.

* Perform the steps on one switch at a time, in the following order: Switch_A_1, Switch_B_1, Switch_A_2, Switch_B_2.

// 2024 Aug 13, ONTAPDOC-1988

.Steps 

. Verify the health of the configuration.
.. Verify that the MetroCluster components are healthy:
+
`metrocluster check run`
+
----
cluster_A::*> metrocluster check run

----

+
The operation runs in the background.

.. After the `metrocluster check run` operation completes, run `metrocluster check show` to view the results.
+
After approximately five minutes, the following results are displayed:
+
----
-----------
::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok
7 entries were displayed.
----

.. Check the status of the running MetroCluster check operation:
+
`metrocluster operation history show -job-id 38`
.. Verify that there are no health alerts:
+
`system health alert show`
. Prepare the IP switches for the application of the new RCF files.
+
Follow the steps for your switch vendor:
+
* link:../install-ip/task_switch_config_broadcom.html#resetting-the-broadcom-ip-switch-to-factory-defaults[Reset the Broadcom IP switch to factory defaults]
+
* link:../install-ip/task_switch_config_cisco.html#resetting-the-cisco-ip-switch-to-factory-defaults[Reset the Cisco IP switch to factory defaults]
+
* link:../install-ip/task_switch_config_nvidia.html#reset-the-nvidia-ip-sn2100-switch-to-factory-defaults[Reset the NVIDIA IP SN2100 switch to factory defaults]

. Download and install the IP RCF file, depending on your switch vendor.
+
* link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-rcf-files[Download and install the Broadcom IP RCF files]
+
* link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-ip-rcf-files[Download and install the Cisco IP RCF files]
+
* link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-nvidia-rcf-files[Download and install the NVIDIA IP RCF files]
+
NOTE: If you have an L2 shared or L3 network configuration, you might need to adjust the ISL ports on the intermediate/customer switches. The switchport mode might change from 'access' to 'trunk' mode. Only proceed to upgrade the second switch pair (A_2, B_2) if the network connectivity between switches A_1 and B_1 is fully operational and the network is healthy.

// 2025 Mar 05, ONTAPDOC-2286, 1587
// 2025 Jan 17, GH issue 449
// 2024 Feb 22, GH issue 366
// 2023 Feb 21, GH issue 361
// 2023 Nov 28, ONTAPDOC-1493
// GitHub issue 135, July 4th 2022
// GH issue 213, 2022-Oct-06
