---
permalink: maintain/task_hot_add_a_sas_disk_shelf_in_a_direct_attached_mcc_configuration_us_sas_optical_cables.html
sidebar: sidebar
keywords: 
summary: 'You can use SAS optical cables to hot-add a SAS disk shelf to an existing stack of SAS disk shelves in a direct-attached MetroCluster FC configuration, or as a new stack to a SAS HBA or an onboard SAS port on the controller.'
---
= Hot-adding a SAS disk shelf in a direct-attached MetroCluster FC configuration using SAS optical cables
:icons: font
:imagesdir: ../media/

[.lead]
You can use SAS optical cables to hot-add a SAS disk shelf to an existing stack of SAS disk shelves in a direct-attached MetroCluster FC configuration, or as a new stack to a SAS HBA or an onboard SAS port on the controller.

* This procedure is nondisruptive and takes approximately two hours to complete.
* You need the admin password and access to an FTP or SCP server.
* If you are adding an IOM12 shelf to a stack of IOM6 shelves, see _Hot-adding IOM12 shelves to a stack of IOM6 shelves_.
+
https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules]

This task applies to a MetroCluster FC configuration in which the storage is connected directly to the storage controllers with SAS cables. It does not apply to MetroCluster FC configurations using FC-to-SAS bridges or FC switch fabrics.

. Follow the instructions for hot-adding a SAS disk shelf in the _Installation Guide_ for your disk shelf model to perform the following tasks to hot-add a disk shelf:
 .. Install a disk shelf for a hot-add.
 .. Turn on the power supplies and set the shelf ID for a hot-add.
 .. Cable the hot-added disk shelf.
 .. Verify SAS connectivity.
