---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html
sidebar: sidebar
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install
summary: 'Upgrading firmware on MetroCluster IP switches.'
---
= Upgrade firmware on MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade the firmware on a MetroCluster IP switch.

//GH issue #132 31/01/2022
.About this task
You must repeat this task on each of the switches in succession.

link:enable-console-logging-before-maintenance.html[Enable console logging] before performing this task.

// 2024 Aug 13, ONTAPDOC-1988

.Steps

[[step_1_fw_upgrade]]
. Check the health of the configuration.

.. Check that the MetroCluster is configured and in normal mode on each cluster:
+
`metrocluster show`
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----

.. Check that mirroring is enabled on each node:
+
`metrocluster node show`
+
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----

.. Check that the MetroCluster components are healthy:
+
`metrocluster check run`
+
----
cluster_A::*> metrocluster check run
----
+
The operation runs in the background.

.. After the `metrocluster check run` operation completes, run:
+
`metrocluster check show`
+
After approximately five minutes, the following results are displayed:
+
----
cluster_A:::*> metrocluster check show

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----


.. Check that there are no health alerts:
+
`system health alert show`

. Install the software on the first switch.
+
NOTE: You must install the switch software on the switches in the following order: switch_A_1, switch_B_1, switch_A_2, switch_B_2.
+
Follow the steps for installing switch software in the relevant topic depending on whether the switch type is Broadcom, Cisco, or NVIDIA:
+
* link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software[Download and install the Broadcom switch EFOS software]
+
* link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software[Download and install the Cisco switch NX-OS software]
+
* link:../install-ip/task_switch_config_nvidia.html#download-and-install-the-cumulus-software[Download and install the NVIDIA SN2100 switch Cumulus software]

. Repeat the previous step for each of the switches.


. Repeat <<step_1_fw_upgrade,Step 1>> to check the health of the configuration.

// 2024 Dec 12, GH issue 1 (german)
// 2024 May 02, ONTAPDOC-1916, ONTAPDOC-1805
// BURT 1376758, 15 DEC 2021
// BURT 1451283 and GH issue 126 27/01/2022
// BURT 1380522