---
permalink: maintain/task_upgrade_or_downgrad_the_firmware_on_a_brocade_fc_switch_mcc.html
sidebar: sidebar
keywords: metrocluster, maintain, service, upgrade, downgrade, firmware, brocade, fc, switch
summary: 'To upgrade or downgrade the firmware on a Brocade FC switch, you must use the Brocade-specific commands to disable the switch, perform and verify the firmware change, and reboot and reenable the switch.'
---
= Upgrade or downgrade the firmware on a Brocade FC switch
:icons: font
:imagesdir: ../media/

[.lead]
To upgrade or downgrade the firmware on a Brocade FC switch, you must use the Brocade-specific commands to disable the switch, perform and verify the firmware change, and reboot and reenable the switch.

.About this task

Confirm that you have checked and performed the following tasks for your configuration: 

* You have the firmware files.
* The system is properly cabled.
* All paths to the storage shelves are available.
* The disk shelf stacks are stable.
* The FC switch fabric is healthy.
* No failed components are present in the system.
* The system is operating normally.
* You have the admin password and access to an FTP or SCP server.
* Console logging is enabled.
+
link:enable-console-logging-before-maintenance.html[Enable console logging]
 

// 2024 Aug 13, ONTAPDOC-1988

The switch fabric is disabled during a firmware upgrade or downgrade, and the MetroCluster configuration relies on the second fabric to continue operation.

Beginning in Fabric OS 9.0.1, SNMPv2 is not supported on Brocade switches. If you upgrade to Fabric OS 9.0.1 or later, you must use SNMPv3 for health monitoring. For more information, see link:../install-fc/concept_configure_the_mcc_software_in_ontap.html#configuring-snmpv3-in-a-metrocluster-configuration[Configuring SNMPv3 in a MetroCluster configuration]. 

If you are upgrading to Fabric OS v 9.2.x or later, you must have a Brocade TruFOS certificate installed, refer to link:https://techdocs.broadcom.com/us/en/fibre-channel-networking/fabric-os/fabric-os-software-upgrade/9-2-x/Obtaining-Firmware/download-prerequisites-new/brocade-trufos-certificates.html[Brocade Fabric OS Software Upgrade Guide, 9.2.x^] for more information.

This task must be performed on each of the switch fabrics in succession so that all switches are running the same firmware version.

NOTE: This procedure is nondisruptive and takes approximately one hour to complete.

.Steps
. Log in to each of the switches in the fabric.
+
The examples in the following steps use the switch `FC_switch_A_1`.

. Disable each of the switches in the fabric:
+
`*switchCfgPersistentDisable*`
+
If this command is not available, then run the `switchDisable` command.
+
----
FC_switch_A_1:admin> switchCfgPersistentDisable
----

. Download the desired firmware version:
+
`*firmwareDownload*`
+
When prompted for the file name, you must specify the subdirectory or relative path to the firmware file.
+
You can run the `firmwareDownload` command at the same time on both switches, but you must allow the firmware to download and commit properly before moving to the next step.
+
----
FC_switch_A_1:admin> firmwaredownload
Server Name or IP Address: 10.64.203.188
User Name: test
File Name: v7.3.1b
Network Protocol(1-auto-select, 2-FTP, 3-SCP, 4-SFTP, 5-HTTP) [1]: 2
Password:
Server IP: 10.64.203.188, Protocol IPv4
Checking system settings for firmwaredownload...
System settings check passed.
----

. Verify that the firmware was downloaded and committed to both partitions:
+
`*firmwareShow*`
+
The following example shows that the firmware download is complete as both images are updated:
+
----
FC_switch_A_1:admin> firmwareShow
Appl     Primary/Secondary Versions

------------------------------------------

FOS      v7.3.1b

         v7.3.1b
----

. Reboot the switches:
+
`*reboot*`
+
Some firmware versions automatically perform an haReboot operation after the firmware download is finished. The reboot in this step is required even if the haReboot has been performed.
+
----
FC_switch_A_1:admin> reboot
----

. Check whether the new firmware is for an intermediate firmware level or for a final specified release.
+
If the download is for the intermediate firmware level, then perform the previous two steps until the specified release is installed.

. Enable the switches:
+
`*switchCfgPersistentEnable*`
+
If this command is not available, then the switch should be in the `enabled` state after the `reboot` command is executed.
+
----
FC_switch_A_1:admin> switchCfgPersistentEnable
----

. Verify that the switches are online and that all of the devices are properly logged in:
+
`*switchShow*`
+
----
FC_switch_A_1:admin> switchShow
----

. Verify that the buffer usage information for a port group or all of the port groups in the switch is displayed properly:
+
`*portbuffershow*`
+
----
FC_switch_A_1:admin> portbuffershow
----

. Verify that the current configuration of a port is displayed properly:
+
`*portcfgshow*`
+
----
FC_switch_A_1:admin> portcfgshow
----
+
Verify the port settings, such as speed, mode, trunking, encryption, and compression, in the Inter-Switch Link (ISL) output. Verify that the port settings were not affected by the firmware download.

. Verify the operation of the MetroCluster configuration in ONTAP:
 .. Check whether the system is multipathed:
 +
`*node run -node _node-name_ sysconfig -a*`
 .. Check for any health alerts on both clusters:
 +
`*system health alert show*`
 .. Confirm the MetroCluster configuration and that the operational mode is normal:
 +
`*metrocluster show*`
 .. Perform a MetroCluster check:
 +
`*metrocluster check run*`
 .. Display the results of the MetroCluster check:
 +
`*metrocluster check show*`
 .. Check for any health alerts on the switches (if present):
 +
`*storage switch show*`
 .. Run Config Advisor.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[NetApp Downloads: Config Advisor]

 .. After running Config Advisor, review the tool's output and follow the recommendations in the output to address any issues discovered.
. Wait 15 minutes before repeating this procedure for the second switch fabric.

// 2025 Aug 21, ONTAPDOC-2573
// 2025 Mar 13, ONTAPDOC-2668