---
permalink: maintain/task_do_not_use_for_9_8_and_later_reconfigure_the_fc_switch_layout_for_ontap_9_1_or_later.html
sidebar: sidebar
keywords: metrocluster, maintain, service, reconfigure, fc, switch, layout, configured
summary: 'If your existing FC switch layout was configured prior to ONTAP 9.1, you must reconfigure the port layout and apply the latest Reference Configuration Files (RCFs). This procedure applies only to MetroCluster FC configurations.'
---
= Reconfiguring an FC switch layout configured before ONTAP 9.x
:icons: font
:imagesdir: ../media/

[.lead]
If your existing FC switch layout was configured prior to ONTAP 9.1, you must reconfigure the port layout and apply the latest Reference Configuration Files (RCFs). This procedure applies only to MetroCluster FC configurations.

.Before you begin

You must identify the FC switches present in the fabric domain.

You need the admin password and access to an FTP or SCP server.

You must perform this task if your existing FC switch layout was configured prior to ONTAP 9.1. It is _not_ required if you are upgrading from an existing switch layout that was configured for ONTAP 9.1 or later.

.About this task

This procedure is nondisruptive and takes approximately four hours to complete (excluding rack and stack) when disks are zeroed.

== Sending a custom AutoSupport message prior to reconfiguring switches

Before reconfiguring your switches, you should issue an AutoSupport message to notify NetApp technical support that maintenance is underway. Informing technical support that maintenance is underway prevents them from opening a case on the assumption that a disruption has occurred.

This task must be performed on each MetroCluster site.

.Steps
. Log in to the cluster.
. Invoke an AutoSupport message indicating the start of the maintenance:
+
`system node autosupport invoke -node * -type all -message MAINT=__maintenance-window-in-hours__*`
+
maintenance-window-in-hours specifies the length of the maintenance window, with a maximum of 72 hours. If the maintenance is completed before the time has elapsed, you can invoke an AutoSupport message indicating the end of the maintenance period:
+
`system node autosupport invoke -node * -type all -message MAINT=end`

. Repeat these steps on the partner site.

== Verifying the health of the MetroCluster configuration

You should check the health of the MetroCluster configuration to verify proper operation.

.Steps
. Verify that the MetroCluster components are healthy:
+
`metrocluster check run`
+
----
cluster_A::*> metrocluster check run

----

+
The operation runs in the background.

. After the `metrocluster check run` operation completes, run `metrocluster check show` to view the results.
+
After approximately five minutes, the following results are displayed:
+
----
-----------
cluster_A::*> metrocluster check show

Last Checked On: 4/7/2019 21:15:05

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          warning
clusters            ok
connections         not-applicable
volumes             ok
7 entries were displayed.
----

. To check the status of the running MetroCluster check operation, use the command:
+
`metrocluster operation history show -job-id 38`
. Verify that there are no health alerts:
+
`system health alert show`

== Checking for MetroCluster configuration errors

You can use the Config Advisor tool available from the NetApp Support Site to check for common configuration errors.

Config Advisor is a configuration validation and health check tool. You can deploy it at both secure sites and non-secure sites for data collection and system analysis.

NOTE: Support for Config Advisor is limited, and available only online.

. Download the Config Advisor tool.
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor[NetApp Downloads: Config Advisor^]

. Run Config Advisor, reviewing the output and following its recommendations to address any issues.

== Persistently disabling the switches

You must disable the switches in the fabric persistently so that you can modify its configuration.

You disable the switches by running the commands on the switch command line; the commands used for this are not ONTAP commands.

.Steps
. Persistently disable the switch:
+
* Use the following command to disable a Brocade switch persistently:
+
`FC_switch_A_1:admin> switchCfgPersistentDisable`
+
* Use the following command to disable a Cisco switch persistently:
+
`vsan [vsna #] suspend`

== Determining the new cabling layout

You must determine the cabling for the new controller modules and any new disk shelves to the existing FC switches.

This task must be performed at each MetroCluster site.

.Steps

. Use https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration^] to determine the cabling layout for your switch type, using the port usage for an eight-node MetroCluster configuration.
+
The FC switch port usage must match the usage described in the guide so that the Reference Configuration Files (RCFs) can be used.
+
NOTE: If your environment cannot be cabled in a way that RCFs can be used, then contact technical support. Do not use this procedure if the cabling cannot use RCFs.

== Applying RCF files and recabling the switches

You must apply the appropriate reference configuration (RCF) files to reconfigure your switches to accommodate the new nodes. After you apply the RCF files, you can recable the switches.

The FC switch port usage must match the usage described in the https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration^] so that the RCFs can be used.

.Steps

. Locate the RCF files for your configuration.
+
You must use the RCF files that match your switch model.

. Apply the RCF files, following the directions on the Download page and adjusting the ISL settings as needed.
. Verify that the switch configuration is saved.
. Cable both of the FC-to-SAS bridges to the FC switches, using the cabling layout you created in the "`Determining the new cabling layout`" section.
. Verify that the ports are online:
 ** For Brocade switches, use the `switchshow` command.
 ** For Cisco switches, use the `show interface brief` command.
. Cable the FC-VI ports from the controllers to the switches.
. From the existing nodes, verify that the FC-VI ports are online:
+
`metrocluster interconnect adapter show`
+
`metrocluster interconnect mirror show`

== Persistently enable the switches

You must enable the switches in the fabric persistently.

.Steps
. Persistently enable the switch:
 ** For Brocade switches, use the `switchCfgPersistentenable` command.
 ** For Cisco switches, use the no `suspend` command.
The following command persistently enables a Brocade switch:
+
----
FC_switch_A_1:admin> switchCfgPersistentenable
----
+
The following command enables a Cisco switch:
+
----
vsan [vsna #]no suspend
----

== Verifying switchover, healing, and switchback

You should verify the switchover, healing, and switchback operations of the MetroCluster configuration.

. Use the procedures for negotiated switchover, healing, and switchback that are described in https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/index.html[MetroCluster management and disaster recovery^].
