---
permalink: maintain/task_fb_hot_add_shelf_preparing_7500n.html
sidebar: sidebar
keywords: 
summary: 'Preparing to hot-add a SAS disk shelf involves downloading documents as well as the disk drive and disk shelf firmware.'
---
= Preparing to hot-add SAS disk shelves
:icons: font
:imagesdir: ../media/

[.lead]
Preparing to hot-add a SAS disk shelf involves downloading documents as well as the disk drive and disk shelf firmware.

* Your system must be a supported configuration and must be running a supported version of ONTAP.
* All disk drives and disk shelves in the system must be running the latest firmware version.
+
You might want to update the disk and shelf firmware throughout the MetroCluster configuration prior to adding shelves.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html[Upgrade, revert, or downgrade]

NOTE: A mix of IOM12 modules and IOM6 modules is supported within the same stack if your system is running a supported version of ONTAP. To establish whether your version of ONTAP supports shelf mixing, refer to the Interoperability Matrix Tool (IMT).https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability] If your version of ONTAP is not supported and you cannot upgrade or downgrade the IOM modules on the existing stack or the new shelf that is to be added to a supported combination of IOM modules, you need to do one of the following:

* Start a new stack on a new SAS port (if supported by the bridge-pair).
* Start a new stack on an additional bridge-pair.

. Download or view the following documents from the NetApp Support Site:
 ** https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
 ** The _Installation Guide_ for your disk shelf model.
. Verify that the disk shelf you are hot-adding is supported.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

. Download the latest disk and disk shelf firmware:
+
NOTE: In this step, you are only completing the download portion of the instructions provided in the links. You need to follow the steps found in the link:task_fb_hot_adding_a_disk_shelf_installing_7500n.md#[Hot-adding a disk shelf] section for installing the disk shelf.

 .. Download the disk firmware and make a copy of the disk firmware instructions for reference later.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware[NetApp Downloads: Disk Drive Firmware]

 .. Download the disk shelf firmware and make a copy of the disk shelf firmware instructions for reference later.
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware[NetApp Downloads: Disk Shelf Firmware]
