---
permalink: maintain/task_upgrade_firmware_on_mcc_ip_switches.html
sidebar: sidebar
keywords: metrocluster, maintain, service, upgrade, firmware. ip, switches, cisco, broadcom, efos, nxos, nx-os, software, install
summary: 'Upgrading firmware on MetroCluster IP switches.'
---
= Upgrading firmware on MetroCluster IP switches
:icons: font
:imagesdir: ../media/

[.lead]
You might need to upgrade the firmware on a MetroCluster IP switch.

//GH issue #132 31/01/2022

You must repeat this task on each of the switch in succession.

.Steps

. Check the health of the configuration.

.. Check that the MetroCluster is configured and in normal mode on each cluster:
+
`metrocluster show`
+
----
cluster_A::> metrocluster show
Cluster                   Entry Name          State
------------------------- ------------------- -----------
 Local: cluster_A         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
Remote: cluster_B         Configuration state configured
                          Mode                normal
                          AUSO Failure Domain auso-on-cluster-disaster
----

.. Check that mirroring is enabled on each node:
+
`metrocluster node show`
+
----
cluster_A::> metrocluster node show
DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              node_A_1       configured     enabled   normal
      cluster_B
              node_B_1       configured     enabled   normal
2 entries were displayed.
----

.. Check that the MetroCluster components are healthy:
+
`metrocluster check run`
+
----
cluster_A::> metrocluster check run

Last Checked On: 10/1/2014 16:03:37

Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
4 entries were displayed.

Command completed. Use the "metrocluster check show -instance" command or sub-commands in "metrocluster check" directory for detailed results.
To check if the nodes are ready to do a switchover or switchback operation, run "metrocluster switchover -simulate" or "metrocluster switchback -simulate", respectively.
----

.. Check that there are no health alerts:
+
`system health alert show`

. Install the software on the first switch.
+
NOTE: You must install the switch software on the switches in the following order: switch_A_1, switch_B_1, switch_A_2, switch_B_2.
+
// BURT 1451283 and GH issue 126 27/01/2022
+
Follow the steps for installing switch software in the relevant topic of the _MetroCluster IP Installation and Configuration_ information depending on whether the switch type is Broadcom or Cisco:

* link:../install-ip/task_switch_config_broadcom.html#downloading-and-installing-the-broadcom-switch-efos-software[Downloading and installing the Broadcom switch EFOS software]
+
* link:../install-ip/task_switch_config_cisco.html#downloading-and-installing-the-cisco-switch-nx-os-software[Downloading and installing the Cisco switch NX-OS software]
// BURT 1376758, 15 DEC 2021

. Repeat the previous step for each of the switches.
// BURT 1380522

. Repeat Step 1 to check the health of the configuration.
