---
permalink: maintain/task_add_lsls_to_a_cisco_fc_switch.html
sidebar: sidebar
keywords: metrocluster, maintain, service, add, isl, cisco, switch
summary: 'You might need to add ISLs to a switch if you are adding or upgrading hardware such as additional or faster controllers or faster switches.'
---
= Adding lSLs to a Cisco switch
:icons: font
:imagesdir: ../media/

[.lead]
You might need to add ISLs to a switch if you are adding or upgrading hardware such as additional or faster controllers or faster switches.

.About this task
* Steps that are completed on one switch must also be completed on the other to ensure ISL connectivity.
* link:enable-console-logging-before-maintenance.html[Enable console logging] before performing this task.

// 2024 Aug 13, ONTAPDOC-1988

.Steps

. Disable the ISL ports of the ISLs to be added on both switches in the fabric:
+
`*FC_switch_A_1#config t*`
+
Enter the configuration commands, one per line. End with CTRL-Z after all the configuration commands have been entered.
+
----

	FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----

. Insert SFPs into the ports you are adding as ISL ports, and cable them according to the _Installation and Configuration Guide_.
+
Ensure that these ports are listed in the _Installation and Configuration Guide_ for the switch you are adding them to.

. Configure the ISL ports in accordance with the _Installation and Configuration Guide_.
. Enable all ISL ports (if not enabled) on both switches in the fabric:
+
`*FC_switch_A_1# config t*`
+
Enter the configuration commands, one per line. End with CTRL-Z.
+
----

 FC_switch_A_1# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----

. Verify the ISLs are established between both switches:
+
`*show topology isl*`
. Repeat the procedure on the second fabric:
+
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----
