---
permalink: maintain/task_change_speed_of_isl_ports_on_a_cisco_fc_switch.html
sidebar: sidebar
keywords: metrocluster, maintain, service, change, speed, isl, ports, cisco, fc, switch
summary: 'You might need to change the speed of ISL ports on a switch to improve the quality of the ISL. ISLs traveling greater distances might need their speed lowered to improve quality.'
---
= Changing speed of ISL ports on a Cisco FC switch
:icons: font
:imagesdir: ../media/

[.lead]
You might need to change the speed of ISL ports on a switch to improve the quality of the ISL. ISLs traveling greater distances might need their speed lowered to improve quality.

You must complete all the steps on both switches to ensure ISL connectivity.

. Disable the ISL ports of the ISLs that you want to change the speed of on both switches in the fabric:
+
`*FC_switch_A_1# config t*`
+
Enter configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# shut
	FC_switch_A_1(config)# end
----

. Change the speed of the ISL ports on both switches in the fabric:
+
`*FC_switch_A_1# config t*`
+
Enter configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# switchport speed 16000
----
+
NOTE: Speeds for ports are 16 = 16,000 Gbps, 8 = 8,000 Gbps, 4 = 4,000 Gbps.
+
Ensure that these ISL ports for your switch are listed in the _Fabric-attached MetroCluster Installation and Configuration Guide_.

. Enable all ISL ports (if not enabled) on both switches in the fabric:
+
`*FC_switch_A_1# config t*`
+
Enter configuration commands, one per line. End with CTRL-Z after you have entered all of the configuration commands.
+
----

 FC_switch_A_1(config)# interface fc1/36
	FC_switch_A_1(config-if)# no shut
	FC_switch_A_1(config)# end
----

. Verify the ISLs are established between both switches:
+
`*show topology isl*`
+
----
--------------------------------------------------------------------------------
	__________Local_________ _________Remote_________ VSAN Cost I/F  PC    I/F  Band
	 PC Domain SwName   Port  Port   SwName Domain PC          Stat Stat Speed width
	--------------------------------------------------------------------------------
	  1   0x11 cisco9 fc1/36  fc1/36 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/40  fc1/40 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/44  fc1/44 cisco9 0xbc    1    1   15 up   up    16g   64g
	  1   0x11 cisco9 fc1/48  fc1/48 cisco9 0xbc    1    1   15 up   up    16g   64g
----

. Repeat the procedure for the second switch fabric.
