---
permalink: install-stretch/concept_in_band_management_of_the_fc_to_sas_bridges.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, in, band, management, fc, sas, bridges
summary: 'Beginning with ONTAP 9.5 with FibreBridge 7500N or 7600N bridges, in-band management of the bridges is supported as an alternative to IP management of the bridges. Beginning with ONTAP 9.8, out-of-band management is deprecated.'
---
= In-band management of the FC-to-SAS bridges
:icons: font
:imagesdir: ../media/

[.lead]
Beginning with ONTAP 9.5 with FibreBridge 7500N or 7600N bridges, _in-band management_ of the bridges is supported as an alternative to IP management of the bridges. Beginning with ONTAP 9.8, out-of-band management is deprecated.

NOTE: Starting with ONTAP 9.8, the `*storage bridge*` command is replaced with `*system bridge*`. The following steps show the `*storage bridge*` command, but if you are running ONTAP 9.8 or later, the `*system bridge*` command is preferred.

When using in-band management, the bridges can be managed and monitored from the ONTAP CLI via the FC connection to the bridge. Physical access to the bridge via the bridge Ethernet ports is not required, reducing the security vulnerability of the bridge.

The availability of in-band management of the bridges depends on the version of ONTAP:

* Starting with ONTAP 9.8, bridges are managed via in-band connections by default and out-of-band management of the bridges via SNMP is deprecated.
* ONTAP 9.5 through 9.7: Either in-band management or out-of-band SNMP management is supported.
* Prior to ONTAP 9.5, only out-of-band SNMP management is supported.

Bridge CLI commands can be issued from the ONTAP interface `storage bridge run-cli -name _bridge-name_ -command _bridge-command-name_` command at the ONTAP interface.

NOTE: Using in-band management with IP access disabled is recommended to improve security by limiting physical connectivity the bridge.
