---
permalink: install-stretch/concept_required_mcc_components_and_naming_conventions_for_two_node_bridge_attached_stretch_configurations_mcc.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, required, hardware, components, naming, conventions, two, node, stretch, bridge
summary: 'When planning your MetroCluster configuration, you must understand the required and supported hardware and software components. For convenience and clarity, you should also understand the naming conventions used for components in examples throughout the documentation. For example, one site is referred to as Site A and the other site is referred to as Site B.'
---
= Required MetroCluster hardware components and naming conventions for two-node bridge-attached stretch configurations
:icons: font
:imagesdir: ../media/

[.lead]
When planning your MetroCluster configuration, you must understand the required and supported hardware and software components. For convenience and clarity, you should also understand the naming conventions used for components in examples throughout the documentation. For example, one site is referred to as Site A and the other site is referred to as Site B.

== Supported software and hardware

The hardware and software must be supported for the MetroCluster FC configuration.

https://hwu.netapp.com[NetApp Hardware Universe]

When using AFF systems, all controller modules in the MetroCluster configuration must be configured as AFF systems.

== Hardware redundancy in the MetroCluster configuration

Because of the hardware redundancy in the MetroCluster configuration, there are two of each component at each site. The sites are arbitrarily assigned the letters A and B and the individual components are arbitrarily assigned the numbers 1 and 2.

== Requirement for two single-node ONTAP clusters

The bridge-attached stretch MetroCluster configuration requires two single-node ONTAP clusters.

Naming must be unique within the MetroCluster configuration.

Example names:

* Site A: cluster_A
* Site B: cluster_B

== Requirement for two storage controller modules

The bridge-attached stretch MetroCluster configuration requires two storage controller modules.

The controllers must meet the following requirements:

* Naming must be unique within the MetroCluster configuration.
* All controller modules in the MetroCluster configuration must be running the same version of ONTAP.
* All controller modules in a DR group must be of the same model.
* All controller modules in a DR group must use the same FC-VI configuration.
+
Some controller modules support two options for FC-VI connectivity:

 ** Onboard FC-VI ports
 ** An FC-VI card in slot 1
+
A mix of one controller module using onboard FC-VI ports and another using an add-on FC-VI card is not supported. For example, if one node uses onboard FC-VI configuration, then all other nodes in the DR group must use onboard FC-VI configuration as well.

Example names:

* Site A: controller_A_1
* Site B: controller_B_1

== Requirement for FC-to-SAS bridges

The bridge-attached stretch MetroCluster configuration requires two or more FC-to-SAS bridges at each site.

These bridges connect the SAS disk shelves to the controller modules.

NOTE: FibreBridge 6500N bridges are not supported in configurations running ONTAP 9.8 and later.

* FibreBridge 7600N and 7500N bridges support up to four SAS stacks.
* Each stack can use different models of IOM, but all shelves within a stack must use the same model.
+
The supported IOM models depend on the ONTAP version you are running.

* Naming must be unique within the MetroCluster configuration.

The suggested names used as examples in this procedure identify the controller module that the bridge connects to and the port.

Example names:

* Site A:
 ** bridge_A_1_``__port-number__``
 ** bridge_A_2_``__port-number__``
* Site B:
 ** bridge_B_1_``__port-number__``
 ** bridge_B_2_``__port-number__``

== Requirement for at least four SAS shelves (recommended)

The bridge-attached stretch MetroCluster configuration requires at least two SAS shelves. However, two shelves are recommended at each site to allow disk ownership on a per-shelf basis, for a total of four SAS shelves.

A minimum of one shelf at each site is supported.

Example names:

* Site A:
 ** shelf_A_1_1
 ** shelf_A_1_2
* Site B:
 ** shelf_B_1_1
 ** shelf_B_1_2

== Mixing IOM12 and IOM 6 modules in a stack

Your version of ONTAP must support shelf mixing. Refer to the Interoperability Matrix Tool (IMT) to see if your version of ONTAP supports shelf mixing. https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability^]

For further details on shelf mixing, see: https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules^]

// 2024 APR 8, ONTAPDOC-1710