---
permalink: install-stretch/concept_required_mcc_components_and_example_names_for_two_node_sas_attached_stretch_configurations_mcc.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, required, hardware, components, naming, guidelines, two, node, sas, configuration
summary: 'The MetroCluster configuration requires a variety of hardware components. For convenience and clarity, standard names for components are used throughout the MetroCluster documentation. Also, one site is referred to as Site A and the other site is referred to as Site B.'
---
= Required MetroCluster hardware components and naming guidelines for two-node SAS-attached stretch configurations
:icons: font
:imagesdir: ../media/

[.lead]
The MetroCluster configuration requires a variety of hardware components. For convenience and clarity, standard names for components are used throughout the MetroCluster documentation. Also, one site is referred to as Site A and the other site is referred to as Site B.

== Supported software and hardware

The hardware and software must be supported for the MetroCluster FC configuration.

https://hwu.netapp.com[NetApp Hardware Universe]

When using AFF systems, all controller modules in the MetroCluster configuration must be configured as AFF systems.

== Hardware redundancy in the MetroCluster configuration

Because of the hardware redundancy in the MetroCluster configuration, there are two of each component at each site. The sites are arbitrarily assigned the letters A and B and the individual components are arbitrarily assigned the numbers 1 and 2.

== Two single-node ONTAP clusters

The SAS-attached stretch MetroCluster configuration requires two single-node ONTAP clusters.

Naming must be unique within the MetroCluster configuration.

Example names:

* Site A: cluster_A
* Site B: cluster_B

== Two storage controller modules

The SAS-attached stretch MetroCluster configuration requires two storage controller modules.

* Naming must be unique within the MetroCluster configuration.
* All controller modules in the MetroCluster configuration must be running the same version of ONTAP.
* All controller modules in a DR group must be of the same model.
* All controller modules in a DR group must use the same FC-VI configuration.
+
Some controller modules support two options for FC-VI connectivity:

 ** Onboard FC-VI ports
 ** An FC-VI card in slot 1
A mix of one controller module using onboard FC-VI ports and another using an add-on FC-VI card is not supported. For example, if one node uses onboard FC-VI configuration, then all other nodes in the DR group must use onboard FC-VI configuration as well.

Example names:

* Site A: controller_A_1
* Site B: controller_B_1

== At least four SAS disk shelves (recommended)

The SAS-attached stretch MetroCluster configuration requires at least two SAS disk shelves. Four SAS disk shelves is recommended.

Two shelves are recommended at each site to allow disk ownership on a per-shelf basis. A minimum of one shelf at each site is supported.

Example names:

* Site A:
 ** shelf_A_1_1
 ** shelf_A_1_2
* Site B:
 ** shelf_B_1_1
 ** shelf_B_1_2

== Mixing IOM12 and IOM 6 modules in a stack

Your version of ONTAP must support shelf mixing. Refer to the Interoperability Matrix Tool (IMT) to see if your version of ONTAP supports shelf mixing. https://mysupport.netapp.com/NOW/products/interoperability[NetApp Interoperability]

For further details on shelf mixing, see: https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-ds-mix-hotadd/home.html[Hot-adding shelves with IOM12 modules to a stack of shelves with IOM6 modules]
