---
permalink: install-stretch/reference_sas_optical_mc_configuring_a_stretch_metrocluster_system_with_sas_disk_shelves_and_sas_optical_cables.html
sidebar: sidebar
keywords: 
summary: 'The storage controllers must be cabled to the storage and to each other. The storage controllers must also be cabled to the data and management network.'
---
= Installing and cabling MetroCluster components for two-node SAS-attached stretch configurations
:icons: font
:imagesdir: ../media/

[.lead]
The storage controllers must be cabled to the storage and to each other. The storage controllers must also be cabled to the data and management network.

== Before you begin any procedure in this document

The following overall requirements must be met before completing this task:

* You must have familiarized yourself with the considerations and best practices for installing and cabling disk shelves for your disk shelf model.
* All components must be supported.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
+
In the IMT, you can use the Storage Solution field to select your MetroCluster solution. You use the *Component Explorer* to select the components and ONTAP version to refine your search. You can click *Show Results* to display the list of supported configurations that match the criteria.

== About this task

* The terms node and controller are used interchangeably.
