---
permalink: install-stretch/reference_sas_optical_mc_configuring_a_stretch_mcc_system_with_sas_disk_shelves_and_sas_optical_cables.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, install, cable, components, two, node, sas, stretch, attached, configuration
summary: 'The storage controllers must be cabled to the storage media and to each other. The storage controllers must also be cabled to the data and management network.'
---
= Installing and cabling MetroCluster components for two-node SAS-attached stretch configurations
:icons: font
:imagesdir: ../media/

[.lead]
The storage controllers must be cabled to the storage media and to each other. The storage controllers must also be cabled to the data and management network.

== Before you begin any procedure in this document

The following overall requirements must be met before completing this task:

* Prior to installation you must have familiarized yourself with the considerations and best practices for installing and cabling disk shelves for your disk shelf model.
* All MetroCluster components must be supported.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
+
In the IMT, you can use the Storage Solution field to select your MetroCluster solution. Use the *Component Explorer* to select the components and ONTAP version to refine your search. You can click *Show Results* to display the list of supported configurations that match the criteria.

== About this task

* The terms node and controller are used interchangeably.

// 2023 Nov 23, GH issue 345