---
permalink: install-stretch/reference_information_gathering_worksheet_for_fc_to_sas_bridges_2_node_atto.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, worksheet, fc, sas, bridges, information
summary: 'Before beginning to configure the MetroCluster sites, you should gather required configuration information.'
---
= Information gathering worksheet for FC-to-SAS bridges
:icons: font
:imagesdir: ../media/

[.lead]
Before beginning to configure the MetroCluster sites, you should gather required configuration information.

== Site A, FC-to-SAS bridge 1 (FC_bridge_A_1a)

Each SAS stack requires at least two FC-to-SAS bridges.

Each bridge connects to Controller_A_1_``__port-number__`` and Controller_B_1_``__port-number__``.

[options="header"]
|===
| Site A| Your value
a|
Bridge_A_1a IP address
a|

a|
Bridge_A_1a Username
a|

a|
Bridge_A_1a Password
a|

|===

== Site A, FC-to-SAS bridge 2 (FC_bridge_A_1b)

Each SAS stack requires at least two FC-to-SAS bridges.

Each bridge connects to Controller_A_1_``__port-number__`` and Controller_B_1_``__port-number__``.

[options="header"]
|===
| Site A| Your value
a|
Bridge_A_1b IP address
a|

a|
Bridge_A_1b Username
a|

a|
Bridge_A_1b Password
a|

|===

== Site B, FC-to-SAS bridge 1 (FC_bridge_B_1a)

Each SAS stack requires at least two FC-to-SAS bridges.

Each bridge connects to Controller_A_1_``__port-number__`` and Controller_B_1_``__port-number__``.

[options="header"]
|===
| Site B| Your value
a|
Bridge_B_1a IP address
a|

a|
Bridge_B_1a Username
a|

a|
Bridge_B_1a Password
a|

|===

== Site B, FC-to-SAS bridge 2 (FC_bridge_B_1b)

Each SAS stack requires at least two FC-to-SAS bridges.

Each bridge connects to Controller_A_1_``__port-number__`` and Controller_B_1_``__port-number__``.

[options="header"]
|===
| Site B| Your value
a|
Bridge_B_1b IP address
a|

a|
Bridge_B_1b Username
a|

a|
Bridge_B_1b Password
a|


|===
