---
permalink: install-stretch/reference_where_to_find_additional_information_icg.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, additional, information
summary: 'You can learn more about MetroCluster configuration and operation from the NetApp documentation library.'
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about MetroCluster configuration and operation from the NetApp documentation library.

== MetroCluster and miscellaneous guides

|===
| Guide| Content
a|
https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]

a|

* All MetroCluster guides

a|

a|

* A technical overview of the MetroCluster FC configuration and operation.
* Best practices for MetroCluster FC configuration.

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html[MetroCluster IP installation and configuration]
a|

* MetroCluster IP architecture
* Cabling the configuration
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/home.html[MetroCluster management and disaster recovery]
a|

* Understanding the MetroCluster configuration
* Switchover, healing and switchback
* Disaster recovery

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-service/home.html[MetroCluster Service Guide]
a|

* Guidelines for maintenance in a MetroCluster FC configuration
* Hardware replacement or upgrade and firmware upgrade procedures for FC-to-SAS bridges and FC switches
* Hot-adding a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Hot-removing a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Replacing hardware at a disaster site in a fabric-attached or stretch MetroCluster FC configuration
* Expanding a two-node fabric-attached or stretch MetroCluster FC configuration to a four-node MetroCluster configuration.
* Expanding a four-node fabric-attached or stretch MetroCluster FC configuration to an eight-node MetroCluster FC configuration.

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-upgrade/home.html[MetroCluster Upgrade, Transition, and Expansion Guide]

a|

* Upgrading or refreshing a MetroCluster configuration
* Transitioning from a MetroCluster FC configuration to a MetroCluster IP configuration
* Expanding a MetroCluster configuration by adding additional nodes

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[MetroCluster Tiebreaker Software Installation and Configuration Guide]
a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
Active IQ Unified Manager documentation

https://www.netapp.com/support-and-training/documentation/[NetApp Documentation: Product Guides and Resources]

a|

* Monitoring the MetroCluster configuration and performance

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts]
a|

* How mirrored aggregates work

|===
