---
permalink: install-stretch/reference_where_to_find_additional_information_icg.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, additional, information
summary: 'You can learn more about MetroCluster configuration and operation from NetApp documentation.'
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about the MetroCluster configuration and operation.

== MetroCluster and miscellaneous information

|===
| Information | Subject
a|
https://docs.netapp.com/us-en/ontap/index.html[ONTAP 9 Documentation^]

a|

* All MetroCluster guides

a|

a|

* A technical overview of the MetroCluster FC configuration and operation.
* Best practices for MetroCluster FC configuration.

a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_considerations_differences.html[MetroCluster IP installation and configuration: Differences among the ONTAP MetroCluster configurations]
a|

* MetroCluster IP architecture
* Cabling the configuration
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/us-en/ontap-metrocluster/manage/index.html[MetroCluster management and disaster recovery]
a|

* Understanding the MetroCluster configuration
* Switchover, healing and switchback
* Disaster recovery (DR)

a|
link:../maintain/index.html[Maintain MetroCluster Components]
a|

* Guidelines for maintenance in a MetroCluster FC configuration
* Hardware replacement or upgrade. Firmware upgrade procedures for FC-to-SAS bridges and FC switches
* Hot-adding a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Hot-removing a disk shelf in a fabric-attached or stretch MetroCluster FC configuration
* Replacing hardware at a disaster recovery site in a fabric-attached or stretch MetroCluster FC configuration
* Expanding a two-node fabric-attached or stretch MetroCluster FC configuration to a four-node MetroCluster configuration.
* Expanding a four-node fabric-attached or stretch MetroCluster FC configuration to an eight-node MetroCluster FC configuration.

a|
https://docs.netapp.com/us-en/ontap-metrocluster/transition/concept_choosing_your_transition_procedure_mcc_transition.html[Transition from MetroCluster FC to MetroCluster IP]

https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html[MetroCluster Upgrade and Expansion Guide]

a|

* Upgrading or refreshing a MetroCluster configuration
* Transitioning from a MetroCluster FC configuration to a MetroCluster IP configuration
* Expanding a MetroCluster configuration by adding additional nodes

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.hw-metrocluster-tiebreaker/home.html[MetroCluster Tiebreaker Software installation and configuration]
a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
Active IQ Unified Manager documentation

https://www.netapp.com/support-and-training/documentation/[NetApp Documentation: Product Guides and Resources^]

a|

* Monitoring the MetroCluster configuration and performance

a|
https://docs.netapp.com/us-en/ontap-7mode-transition/copy-based/index.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html[ONTAP concepts]
a|

* How mirrored aggregates work

|===

// BURT 1448684, 01 FEB 2022
