---
permalink: install-stretch/task_fb_new_install_prepare.html
sidebar: sidebar
keywords: 
summary: 'When you are preparing to install the bridges as part of your new MetroCluster system, you must ensure that your system meets certain requirements, including meeting setup and configuration requirements for the bridges. Other requirements include downloading the necessary documents, the ATTO QuickNAV utility, and the bridge firmware.'
---
= Preparing for the installation
:icons: font
:imagesdir: ../media/

[.lead]
When you are preparing to install the bridges as part of your new MetroCluster system, you must ensure that your system meets certain requirements, including meeting setup and configuration requirements for the bridges. Other requirements include downloading the necessary documents, the ATTO QuickNAV utility, and the bridge firmware.

* Your system must already be installed in a rack if it was not shipped in a system cabinet.
* Your configuration must be using supported hardware models and software versions.
+
https://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
+
In the IMT, you can use the Storage Solution field to select your MetroCluster solution. You use the *Component Explorer* to select the components and ONTAP version to refine your search. You can click *Show Results* to display the list of supported configurations that match the criteria.

* Each FC switch must have one FC port available for one bridge to connect to it.
* You must have familiarized yourself with how to handle SAS cables and the considerations and best practices for installing and cabling disk shelves.
+
The _Installation and Service Guide_ for your disk shelf model describes the considerations and best practices.

* The computer you are using to set up the bridges must be running an ATTO-supported web browser to use the ATTO ExpressNAV GUI.
+
The _ATTO Product Release Notes_ have an up-to-date list of supported web browsers. You can access this document from the ATTO web site as described in the following steps.

. Download the _Installation and Service Guide_ for your disk shelf model:
. Access the ATTO web site using the link provided for your FibreBridge model and download the manual and the QuickNAV utility.
+
NOTE: The _ATTO FibreBridge Installation and Operation Manual_ for your model bridge has more information about management interfaces.
+
You can access this and other content on the ATTO web site by using the link provided on the ATTO Fibrebridge Description page.

. Gather the hardware and information needed to use the recommended bridge management interfaces, the ATTO ExpressNAV GUI, and the ATTO QuickNAV utility:
 .. Determine a non-default user name and password (for accessing the bridges).
+
You should change the default user name and password.

 .. If configuring for IP management of the bridges, you need the shielded Ethernet cable provided with the bridges (which connects from the bridge Ethernet management 1 port to your network).
 .. If configuring for IP management of the bridges, you need an IP address, subnet mask, and gateway information for the Ethernet management 1 port on each bridge.
 .. Disable VPN clients on the computer you are using for setup.
+
Active VPN clients cause the QuickNAV scan for bridges to fail.
