---
permalink: install-stretch/task_install_the_fc_to_sas_bridge_and_sas_shelves_fb_new_install_parent.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, install, fc, sas, bridge, shelves
summary: 'After ensuring that the system meets all of the requirements in the “Preparing for the installation” section, you can install your new system.'
---
= Installing the FC-to-SAS bridge and SAS shelves
:icons: font
:imagesdir: ../media/

[.lead]
After ensuring that the system meets all of the requirements in the "`Preparing for the installation`" section, you can install your new system.

* The disk and shelf configuration at both sites should be identical.
+
If a non-mirrored aggregate is used, the disk and shelf configuration at each site might be different.
+
NOTE: All disks in the disaster recovery group must use the same type of connection and be visible to all of the nodes within the disaster recovery group, regardless of the disks being used for mirrored or non-mirrored aggregate.

* The system connectivity requirements for maximum distances for disk shelves, FC switches, and backup tape devices using 50-micron, multimode fiber-optic cables, also apply to FibreBridge bridges.
+
https://hwu.netapp.com[NetApp Hardware Universe]

* A mix of IOM12 modules and IOM3 modules is not supported within the same storage stack. A mix of IOM12 modules and IOM6 modules is supported within the same storage stack if your system is running a supported version of ONTAP.

[NOTE]
====
In-band ACP is supported without additional cabling in the following shelves and FibreBridge 7500N or 7600N bridge:

* IOM12 (DS460C) behind a 7500N or 7600N bridge with ONTAP 9.2 and later
* IOM12 (DS212C and DS224C) behind a 7500N or 7600N bridge with ONTAP 9.1 and later
====

NOTE: SAS shelves in MetroCluster configurations do not support ACP cabling.
