---
permalink: install-stretch/task_upgrade_the_configuration_to_fabric_attached_mcc.html
sidebar: sidebar
keywords: metrocluster, stretch, installation, transition, stretch, fabric, attacjed, configuration
summary: 'In a fabric-attached MetroCluster configuration, the nodes are in different locations. This geographical difference increases the disaster protection. To transition from a stretch to a fabric-attached MetroCluster configuration, you must add FC switches and, if necessary, FC-to-SAS bridges to the configuration.'
---
= Transitioning from a stretch to a fabric-attached MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
In a fabric-attached MetroCluster configuration, the nodes are in different locations. This geographical difference increases the disaster protection. To transition from a stretch to a fabric-attached MetroCluster configuration, you must add FC switches and, if necessary, FC-to-SAS bridges to the configuration.

* You must disable automatic switchover on both of the clusters by running the `metrocluster modify -auto-switchover-failure-domain auto-disabled` command.
* You must have shut down the nodes.
+
This procedure is disruptive.

The MetroCluster configuration must be transitioned on both sites. After upgrading the MetroCluster configuration, you must enable automatic switchover on both the clusters. You also must validate the configuration by running the `metrocluster check run` command.

This procedure gives an overview of the required steps. For detailed steps, you must refer to specific sections in the link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration]. You do not need to do a full installation and configuration.

.Steps
. Prepare for the upgrade by carefully reviewing the "Preparing for the MetroCluster installation" section of the link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration].
. Install, cable, and configure the required switches and FC-to-SAS bridges.
+
NOTE: You should use the procedures in the section "Cabling a fabric-attached MetroCluster configuration" of the link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration].

. Refresh the MetroCluster configuration using the following steps.
+
Do not use the procedures in the section "Configuring the MetroCluster software in ONTAP" found in the link: https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration].

 .. Enter advanced privilege mode:
 +
 `*set -privilege advanced*`
 .. Refresh the MetroCluster configuration:
 +
 `*metrocluster configure -refresh true*`
+
The following command refreshes the MetroCluster configuration on all the nodes in the DR group that contains controller_A_1:
+
----
controller_A_1::*> metrocluster configure -refresh true
[Job 009] Job succeeded: Configure is successful.
----

 .. Return to admin privilege mode:
 +
 `*set -privilege admin*`

. Check the MetroCluster configuration for errors and verify that it is operational.
+
You should use the procedures in the following sections of the link:https://docs.netapp.com/us-en/ontap-metrocluster/install-fc/index.html[Fabric-attached MetroCluster installation and configuration]:

 ** Checking for MetroCluster configuration errors with Config Advisor
 ** Verifying local HA operation
 ** Verifying switchover, healing, and switchback
