---
permalink: install-stretch/task_cable_the_cluster_peering_connections.html
sidebar: sidebar
keywords:
summary: 'You must cable the controller module ports used for cluster peering so that they have connectivity with the cluster on the partner site.'
---
= Cabling the cluster peering connections
:icons: font
:imagesdir: ../media/

[.lead]
You must cable the controller module ports used for cluster peering so that they have connectivity with the cluster on the partner site.

This task must be performed on each controller module in the MetroCluster configuration.

At least two ports on each controller module should be used for cluster peering.

The recommended minimum bandwidth for the ports and network connectivity is 1 GbE.

.Steps
. Identify and cable at least two ports for cluster peering and verify they have network connectivity with the partner cluster.
+
Cluster peering can be done on dedicated ports or on data ports. Using dedicated ports provides higher throughput for the cluster peering traffic.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-clus-peer/home.html[Cluster and SVM peering express configuration]
