---
permalink: install-stretch/task_rack_the_hardware_components_2_node_stretch_sas.html
sidebar: sidebar
keywords: 
summary: 'If you have not received the equipment already installed in cabinets, you must rack the components.'
---
= Racking the hardware components
:icons: font
:imagesdir: ../media/

[.lead]
If you have not received the equipment already installed in cabinets, you must rack the components.

This task must be performed on both MetroCluster sites.

. Plan the positioning of the MetroCluster components.
+
The amount of rack space needed depends on the platform model of the storage controllers, the switch types, and the number of disk shelf stacks in your configuration.

. Properly ground yourself.
. Install the storage controllers in the rack or cabinet.
+
https://docs.netapp.com/platstor/index.jsp[AFF and FAS Documentation Center]

. Install the disk shelves, daisy-chain the disk shelves in each stack, power them on, and set the shelf IDs.
+
See the appropriate guide for your disk shelf model for information about daisy-chaining disk shelves and setting shelf IDs.
+
NOTE: Shelf IDs must be unique for each SAS disk shelf within each MetroCluster DR group (including both sites). When manually setting shelf IDs, you must power-cycle the disk shelf.
