---
permalink: install-stretch/task_upgrade_the_configuration_to_fabric_attached_mcc.html
sidebar: sidebar
keywords: 
summary: 'In a fabric-attached MetroCluster configuration, the nodes are in different locations. This geographical difference increases the disaster protection. To transition from a stretch to a fabric-attached MetroCluster configuration, you must add FC switches and, if necessary, FC-to-SAS bridges to the configuration.'
---
= Transitioning from a stretch to a fabric-attached MetroCluster configuration
:icons: font
:imagesdir: ../media/

[.lead]
In a fabric-attached MetroCluster configuration, the nodes are in different locations. This geographical difference increases the disaster protection. To transition from a stretch to a fabric-attached MetroCluster configuration, you must add FC switches and, if necessary, FC-to-SAS bridges to the configuration.

* You must have disabled automatic switchover on both of the clusters by running the metrocluster modify -auto-switchover-failure-domain auto-disabled command.
* You must have shut down the nodes.
+
This procedure is disruptive.

The MetroCluster configuration must be transitioned on both sites. After upgrading the MetroCluster configuration, you must enable automatic switchover on both the clusters. You also must validate the configuration by running the metrocluster check run command.

This procedure gives an overview of the required steps. For detailed steps, you must refer to specific sections in the _Fabric-attached MetroCluster Installation and Configuration Guide._ You do not need to do a full installation and configuration.

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]

. Prepare for the upgrade by carefully reviewing the "Preparing for the MetroCluster installation" section of the _Fabric-attached MetroCluster Installation and Configuration Guide_.
. Install, cable, and configure the required switches and FC-to-SAS bridges.
+
NOTE: You should use the procedures in the section "Cabling a fabric-attached MetroCluster configuration" of the _Fabric-attached MetroCluster Installation and Configuration Guide._.

. Refresh the MetroCluster configuration using the following steps.
+
Do not use the procedures in the section "Configuring the MetroCluster software in ONTAP" found in the _Fabric-attached MetroCluster Installation and Configuration Guide._

 .. Enter advanced privilege mode: `set -privilege advanced`
 .. Refresh the MetroCluster configuration: `metrocluster configure -refresh true`
+
The following command refreshes the MetroCluster configuration on all the nodes in the DR group that contains controller_A_1:
+
----
controller_A_1::*> metrocluster configure -refresh true
[Job 009] Job succeeded: Configure is successful.
----

 .. Return to admin privilege mode: `set -privilege admin`

. Check the MetroCluster configuration for errors and verify that it is operational.
+
You should use the procedures in the following sections of the _Fabric-attached MetroCluster Installation and Configuration Guide_:

 ** Checking for MetroCluster configuration errors with Config Advisor
 ** Verifying local HA operation
 ** Verifying switchover, healing, and switchback
