---
permalink: manage/reference_where_to_find_additional_information_dr_guide.html
sidebar: sidebar
keywords: learn, metrocluster, configuration, operation, netapp, extensive, documentation, library, additional, information, miscellaneous, guide
summary: You can learn more about MetroCluster configuration and operation in NetApp’s extensive documentation library.
---
= Where to find additional information
:icons: font
:imagesdir: ../media/

[.lead]
You can learn more about MetroCluster configuration and operation in NetApp's extensive documentation library.

== MetroCluster and miscellaneous guides

[cols=2*,options="header"]
|===
| Guide| Content
a|
https://docs.netapp.com/ontap-9/index.jsp[ONTAP 9 Documentation Center]

a|

* All MetroCluster guides

a|
http://www.netapp.com/us/media/tr-4375.pdf[NetApp Technical Report 4375: NetApp MetroCluster for ONTAP 9.3]
a|

* A technical overview of the MetroCluster configuration and operation.
* Best practices for MetroCluster configuration.

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-fabric/home.html[Fabric-attached MetroCluster installation and configuration]
a|

* Fabric-attached MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the FC switches
* Configuring the MetroCluster in ONTAP

a|
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-stretch/home.html[Stretch MetroCluster installation and configuration]
a|

* Stretch MetroCluster architecture
* Cabling the configuration
* Configuring the FC-to-SAS bridges
* Configuring the MetroCluster in ONTAP

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-inst-cnfg-ip/home.html[MetroCluster IP installation and configuration]
a|

* MetroCluster IP architecture
* Cabling the configuration
* Configuring the MetroCluster in ONTAP

a|
link:../tiebreaker/concept_overview_of_the_tiebreaker_software.html[MetroCluster Tiebreaker 1.21 software installation and configuration ]
a|

* Monitoring the MetroCluster configuration with the MetroCluster Tiebreaker software

a|
Active IQ Unified Manager documentation https://www.netapp.com/support-and-training/documentation/[NetApp Documentation: Product Guides and Resources]

a|

* Monitoring the MetroCluster configuration and performance

a|
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-dctg/home.html[Copy-based transition]
a|

* Transitioning data from 7-Mode storage systems to clustered storage systems

|===
