---
permalink: manage/switchover-limitations.html
sidebar: sidebar
keywords: switchover, perform, heal, operation, restore, metrocluster, functionality, fc, configuration, ip, limitations, 
summary: During a switchover, certain operations should not be perform
---
= Limitations when the system is in switchover
:icons: font
:imagesdir: ../media/

[.lead]
During a switchover, certain operations should not be performed. You should be aware of the restricted operations and limitations when the system is in switchover. 

.Restricted operations in switchover

The following operations are not supported when the system is in switchover:

* Creating or deleting aggregates and volumes 
* Creating or deleting SVMs
* Creating or deleting LIFs
* Adding or removing disks (only if you are replacing them as part of a recovery procedure)
* Performing configuration changes to SnapMirror SVM DR

.Hardware replacement in switchover

* If you need to replace a controller of the same type, at the site not in switchover, follow the procedure to link:../disaster-recovery/task_recover_from_a_multi_controller_and_or_storage_failure.html[Recover from a multi-controller or storage failure]

* If you need to replace a controller with a different type, follow the procedure for your configuration in link:../upgrade/concept_choosing_controller_upgrade_mcc.html[Choose a controller upgrade procedure]

* If your system is in switchover because of a controller failure or if you experience a controller failure while in switchover, you must first replace the controller hardware, perform a switchback, and then perform a controller upgrade:
+
** To replace the controller hardware and perform the switchback, follow link:../disaster-recovery/task_recover_from_a_multi_controller_and_or_storage_failure.html[Recover from a multi-controller or storage failure]
** After you have replaced the hardware, perform a controller upgrade using the procedures in link:../upgrade/concept_choosing_controller_upgrade_mcc.html[Choose a controller upgrade procedure]


If you are in s/o, and you cannot replace the controller with the same controller, and you need to upgrade, you first need to replace, and then upgrade the controller - You need to first replace the broken hardware - If you are in SO because of controller failure, or , you cannot upgrade until you have replaced hardware, switchback and controller upgrade. Switchover done without upgrade - or fails during the S/o

// 2024 Sep 05, ONTAPDOC-2293