---
permalink: manage/task_heal_the_configuration_in_a_mcc_ip_configuration_ontap_9_4_and_earlier.html
sidebar: sidebar
keywords: heal, aggregate, preparation, switchback, operation, configuration, metrocluster, ip, ontap
summary: You must heal the aggregates in preparation for the switchback operation.
---
= Healing the configuration in a MetroCluster IP configuration (ONTAP 9.4 and earlier)
:icons: font
:imagesdir: ../media/

[.lead]
You must heal the aggregates in preparation for the switchback operation.

The following conditions must exist before performing the healing procedure:

* Switchover must have been performed and the surviving site must be serving data.
* Storage shelves at the disaster site must be powered up, functional, and accessible.
* ISLs must be up and operating.
* Nodes in the surviving site must not be in HA failover state (both nodes must be up and running).

This task applies to MetroCluster IP configurations running ONTAP versions prior to 9.5 only.

This procedure differs from the healing procedure for MetroCluster FC configurations.

. Power up each controller module on the site that was switched over and let them fully boot.
+
If the system displays the LOADER prompt, run the `boot_ontap` command.

. Perform the root aggregate healing phase: `metrocluster heal root-aggregates`
+
----
cluster_A::> metrocluster heal root-aggregates
[Job 137] Job succeeded: Heal Root-Aggregates is successful
----
+
If the healing is vetoed, you have the option of reissuing the metrocluster heal root-aggregates command with the --override-vetoes parameter. If you use this optional parameter, the system overrides any soft vetoes that prevent the healing operation.

. Resynchronize the aggregates: `metrocluster heal aggregates`
+
----
cluster_A::> metrocluster heal aggregates
[Job 137] Job succeeded: Heal Aggregates is successful
----
+
If the healing is vetoed, you have the option of reissuing the metrocluster heal command with the --override-vetoes parameter. If you use this optional parameter, the system overrides any soft vetoes that prevent the healing operation.

. Confirm the heal operation is complete by running the metrocluster operation show command on the healthy cluster:
+
----

cluster_A::> metrocluster operation show
  Operation: heal-aggregates
      State: successful
 Start Time: 7/29/2017 20:54:41
   End Time: 7/29/2017 20:54:42
     Errors: -
----
