---
permalink: manage/task_healing_the_configuration_in_a_mcc_fc_configuration_supertask.html
sidebar: sidebar
keywords: 
summary: 'Following a switchover, you must perform the healing operations in specific order to restore MetroCluster functionality.'
---
= Healing the configuration in a MetroCluster FC configuration
:icons: font
:imagesdir: ../media/

[.lead]
Following a switchover, you must perform the healing operations in specific order to restore MetroCluster functionality.

* Switchover must have been performed and the surviving site must be serving data.
* Nodes on the disaster site must be halted or remain powered off.
+
They must not be fully booted during the healing process.

* Storage at the disaster site must be accessible (shelves are powered up, functional, and accessible).
* In fabric-attached MetroCluster configurations, inter-switch links (ISLs) must be up and operating.
* In four-node MetroCluster configurations, nodes in the surviving site must not be in HA failover state (all nodes must be up and running for each HA pair).

The healing operation must first be performed on the data aggregates, and then on the root aggregates.
