---
permalink: manage/task_verify_a_successful_switchback.html
sidebar: sidebar
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful
summary: After performing the switchback, you want to confirm that all aggregates and storage virtual machines \(SVMs\) are switched back and online.
---
= Verifying a successful switchback
:icons: font
:imagesdir: ../media/

[.lead]
After performing the switchback, you want to confirm that all aggregates and storage virtual machines (SVMs) are switched back and online.

. Verify that the switched-over data aggregates are switched back:
+
`storage aggregate show`
+
In the following example, aggr_b2 on node B2 has switched back:
+
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal
----

. Verify that all sync-destination SVMs on the surviving cluster are dormant (showing an operational state of "`stopped`"):
+
`vserver show -subtype sync-destination`
+
----
node_B_1::> vserver show -subtype sync-destination
                                 Admin    Operational  Root                       
Vserver       Type    Subtype    State    State        Volume    Aggregate       
-----------   ------- ---------- -------- ----------  ---------  ---------- 
...
cluster_A-vs1a-mc data sync-destination
                               running    stopped    vs1a_vol   aggr_b2       
                                                                     
----
+
Sync-destination aggregates in the MetroCluster configuration have the suffix "`-mc`" automatically appended to their name to help identify them.

. Verify the sync-source SVMs on the disaster cluster are up and running:
+
`vserver show -subtype sync-source`
+
----
node_A_1::> vserver show -subtype sync-source
                                  Admin    Operational  Root                        
Vserver        Type    Subtype    State    State        Volume     Aggregate  
-----------    ------- ---------- -------- ----------  ---------   ----------
...
vs1a           data    sync-source
                                  running  running    vs1a_vol  aggr_b2   
                                                                      
----


. Confirm that the switchback operations succeeded by using the `metrocluster operation show` command.
+

|===

h| If the command output shows... h| Then...

a|
That the switchback operation state is successful.
a|
The switchback process is complete and you can proceed with operation of the system.
a|
That the switchback operation or switchback-continuation-agent operation is partially successful.
a|
Perform the suggested fix provided in the output of the `metrocluster operation show` command.
|===

You must repeat the previous sections to perform the switchback in the opposite direction. If site_A did a switchover of site_B, have site_B do a switchover of site_A.

// 2024 Dec 16, ONTAPDOC-2384
// BURT 1448684, 03 FEB 2022
// BURT 1485050, 2022-06-29
