---
permalink: manage/task_verifiy_that_your_system_is_ready_for_a_switchover.html
sidebar: sidebar
keywords: simulate, option, preview, result, switchover, operation, verification, check, precondition, succesful, verify, ready, example
summary: You can use the -simulate option to preview the results of a switchover operation. A verification check gives you a way to verify that most of the preconditions for a successful run are met before you start the operation.
---
= Verifying that your system is ready for a switchover
:icons: font
:imagesdir: ../media/

[.lead]
You can use the -simulate option to preview the results of a switchover operation. A verification check gives you a way to verify that most of the preconditions for a successful run are met before you start the operation. Issue these commands from the site that will remain up and operational:

. Set the privilege level to advanced: `set -privilege advanced`
. Simulate a switchover operation: `metrocluster switchover -simulate`
. Review the output that is returned.
+
The output shows whether any vetoes would prevent a switchover operation. Every time you perform a MetroCluster operation, you must verify a set of criteria for the success of the operation. A "`veto`" is a mechanism to prohibit the operation if one or more of the criteria are not fulfilled. There are two types of veto: a "`soft`" veto and a "`hard`" veto. You can override a soft veto, but not a hard veto. For example, to perform a negotiated switchover in a four-node MetroCluster configuration, one criterion is that all of the nodes are up and healthy. Suppose one node is down and was taken over by its HA partner. The switchover operation will be hard vetoed because it is a hard criterion that all of the nodes must be up and healthy. Because this is a hard veto, you cannot override the veto.
+
IMPORTANT: It is best not to override any veto.

== Example: Verification results

The following example shows the errors that are encountered in a simulation of a switchover operation:

[source,nolinebreak]
----
cluster4::*> metrocluster switchover -simulate

[Job 126] Preparing the cluster for the switchover operation...
[Job 126] Job failed: Failed to prepare the cluster for the switchover
operation. Use the "metrocluster operation show" command to view detailed error
information. Resolve the errors, then try the command again.
----

NOTE: Negotiated switchover and switchback will fail until you replace all of the failed disks. You can perform disaster recovery after you replace the failed disks. If you want to ignore the warning for failed disks, you can add a soft veto for the negotiated switchover and switchback.
