---
permalink: manage/task_verify_SVMs are_running_and_aggregates_are_online.html
sidebar: sidebar
keywords: switchover, dr, partner, ownership, disk, svm, online, confirm
summary: After the switchover is complete, you should verify that the DR partners have taken ownership of the disks and the partner SVMs have come online.
---
= Verify that the SVMs are running and that the aggregates are online
:icons: font
:imagesdir: ../media/

[.lead]
After the switchover is complete, you should verify that the DR partners have taken ownership of the disks and the partner SVMs have come online.

When you run the storage aggregate plex show command after a MetroCluster switchover, the status of plex0 of the switched over root aggregate is indeterminate and is displayed as failed. During this time, the switched over root is not updated. The actual status of this plex can only be determined after the MetroCluster healing phase.

.Steps

. Check that the aggregates were switched over by using the storage aggregate show command.
+
In this example, the aggregates were switched over. The root aggregate (aggr0_b2) is in a degraded state. The data aggregate (b2_aggr2) is in a mirrored, normal state:
+
----
cluster_A::*> storage aggregate show

.
.
.
mcc1-b Switched Over Aggregates:
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr0_b2    227.1GB   45.1GB    80% online       0 node_A_1        raid_dp,
                                                                   mirror
                                                                   degraded
b2_aggr1    227.1GB   200.3GB    20% online       0 node_A_1       raid_dp,
                                                                   mirrored
                                                                   normal
----

. Confirm that the secondary SVMs have come online by using the vserver show command.
+
In this example, the previously dormant sync-destination SVMs on the secondary site have been activated and have an Admin State of running:
+
----
cluster_A::*> vserver show
                                          Admin      Operational  Root                 Name    Name
Vserver           Type  Subtype           State      State        Volume    Aggregate  Service Mapping
-----------       ----- ----------        ---------- -----------  --------- ---------- ------- -------
...
cluster_B-vs1b-mc data   sync-destination  running   running      vs1b_vol   aggr_b1   file    file
----
