---
permalink: manage/task_verify_a_successful_switchback.html
sidebar: sidebar
keywords: perform, switchback, aggregate, storage, virtual, machine, svm, switch, back, online, verify, successful
summary: After performing the switchback, you want to confirm that all aggregates and storage virtual machines \(SVMs\) are switched back and online.
---
= Verifying a successful switchback
:icons: font
:imagesdir: ../media/

[.lead]
After performing the switchback, you want to confirm that all aggregates and storage virtual machines (SVMs) are switched back and online.

. Verify that the switched-over data aggregates are switched back:
+
`storage aggregate show`
+
In the following example, aggr_b2 on node B2 has switched back:
+
----
node_B_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 node_B_2   raid_dp,
                                                                   mirrored,
                                                                   normal
----

. Verify that all sync-destination SVMs on the surviving cluster are dormant (showing an operational state of "`stopped`"):
+
`vserver show -subtype sync-destination`
+
----
node_B_1::> vserver show -subtype sync-destination
                                 Admin    Operational  Root                       
Vserver       Type    Subtype    State    State        Volume    Aggregate       
-----------   ------- ---------- -------- ----------   --------  ---------- 
...
cluster_A-vs1a-mc data sync-destination
                               running    stopped    vs1a_vol   aggr_b2       
                                                                     
----
+
Sync-destination aggregates in the MetroCluster configuration have the suffix "`-mc`" automatically appended to their name to help identify them.

. Verify the sync-source SVMs on the disaster cluster are up and running:
+
`vserver show -subtype sync-source`
+
----
node_A_1::> vserver show -subtype sync-source
                                  Admin    Operational  Root                        
Vserver        Type    Subtype    State    State        Volume     Aggregate  
-----------    ------- ---------- -------- ----------   --------   ----------
...
vs1a           data    sync-source
                                  running  running    vs1a_vol  aggr_b2   
                                                                      
----


. Confirm that the switchback operations succeeded by using the `metrocluster operation show` command.
+

|===

h| If the command output shows... h| Then...

a|
That the switchback operation state is successful.
a|
The switchback process is complete and you can proceed with operation of the system.
a|
That the switchback operation or switchback-continuation-agent operation is partially successful.
a|
Perform the suggested fix provided in the output of the `metrocluster operation show` command.
|===

. Perform the following checks to confirm that switchover is operational between the two clusters:

* From the DR cluster, check if a switchover from the surviving cluster to the DR cluster is possible:
+
`metrocluster switchover -simulate`
+

* From the surviving cluster, check if a switchover from the DR cluster to the surviving cluster is possible:
+
`metrocluster switchover -simulate`
+

* From either side of the metrocluster, confirm that that all outputs are ok: 
+
`metrocluster check show`
+

For a successful switchover, the command output should appear similar to the following: 
+
----
Component           Result
------------------- ---------
nodes               ok
lifs                ok
config-replication  ok
aggregates          ok
clusters            ok
connections         ok
volumes             ok

7 entries were displayed.
----
+

NOTE: In a non-MetroCluster IP environment, 'connections' should show as "not-applicable" in the command output.

// 2026 Feb 12, ONTAPDOC-3583
// 2024 Dec 16, ONTAPDOC-2384
// BURT 1448684, 03 FEB 2022
// BURT 1485050, 2022-06-29
